### ISSUE TITLE
Blank contents in Joplin window

### ISSUE THREAD

**Issue by utmuk** [laurent22/joplin#10017]
### Operating system

Windows

### Joplin version

2.13.15

### Desktop version info

Joplin 2.13.15 (prod, win32)

Client ID: bc1f0973c51c41ee8fb6ab56dd5ffdf4
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: 7d2c1c0

### Current behaviour

Joplin always resides in tray. It's window is usually closed and I occasionally click the tray icon to open the window and use Joplin. Not often, but sometimes, after I click the icon, Joplin's window opens, but white blank inside (screenshot attached). After I see that window I can do nothing - I close it and then click the icon - the same blank window opens. The only way to fix this is to quit the application from tray context menu and then reopen it.
![Clipboard01](https://github.com/laurent22/joplin/assets/28525658/8dc9713d-4119-4933-8677-103ba17811d7)

### Expected behaviour

It should always open a working window, not blank

**Comment by charles7668** [comment]
I'm facing a similar issue here. I'm using Windows 11, and sometimes after I turn off the screen and then turn it back on, Joplin will display blank. It's not just Joplin; some other programs that use Electron may encounter similar issues.

I think the problem may be related to using dual screens.

To resolve this, I need to switch the screen resolution to another setting and then switch it back. After doing this, these programs will display normally.

Did you try changing the resolution setting and then turning it back? If this works, probably your problem is the same as mine.

**Comment by utmuk** [comment]
Ihave only one screen. I didn't try changing the resolution. I wil try it next time this happens.

**Comment by utmuk** [comment]
I have only one screen. Yes, changing the resolution does resolve this without restarting Joplin.
