### ISSUE TITLE
[Possible Bug] Joplin spawns 22 processes, many with over 100mb of memory consumed. Is this normal?

### ISSUE THREAD

**Issue by futuremotiondev** [laurent22/joplin#10054]
### Operating system

Windows

### Joplin version

Joplin 2.14.17

### Desktop version info

Joplin 2.14.17 (prod, win32)

Client ID: 4dab185d885945ac897a0608af59c6f7
Sync Version: 3
Profile Version: 46
Keychain Supported: Yes

Revision: 094175c

Backup: 1.4.0
Better Code Blocks: 1.1.0
CodeMirror Options: 1.1.0
Container with Classes: 1.0.0
Csv Import: 1.0.1
Ez Table: 1.0.2
Favorites: 1.3.2
Headings 4 to 6: 1.0.1
Insert Date: 1.0.1
Markdown Table: Sortable: 1.2.2
Paste Special: 1.1.2
Pseudocode Support: 0.1.0
Quick HTML tags: 0.2.0
Simple Highlighter: 1.0.0
Slash Commands: Datetime & More: 1.3.2
Suitcase: 0.3.2
Table Formatter Plugin: 1.2.1
Whitespacer: 1.0.0

### Current behaviour

Joplin, on open, spawns a total of 22 processes. I have 18 plugins installed, so I'm wondering if this is because of my plugins. The RAM consumed is enormous, so I'm going to cut down on the plugin installs if this is the case.

Image:

![Taskmgr_oN2GPC5Swk](https://github.com/laurent22/joplin/assets/33441569/3c0757d1-5a40-4bc2-a0a5-8756ec079b2a)

Is this normal?

### Expected behaviour

I would expect Joplin to consume much less RAM, even with a medium amount of plugins installed.

**Comment by tomasz1986** [comment]
This is because of the number of plugins, which you seem to have installed around 20, which matches the number of processes. This is how Electron works, I don't think you will be able to reduce the number. What you could do is to try finding out which plugins use the most memory and then inquiring the author about its RAM usage and possible optimisations to reduce it.

High RAM usage is one of the main reason why I personally use a very little number of plugins, especially on devices that have less RAM (e.g. just 2 plugins on the device where I'm writing this post right now, which only has 8 GB of RAM).

**Comment by futuremotiondev** [comment]
Thanks, That's kind of what I figured. I'll have to really whittle down the number of plugins I use.
