### ISSUE TITLE
Desktop: "New note" and "new to-do" buttons too small on startup when the first notebook is the trash notebook

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#10060]
### Operating system

Linux

### Joplin version

3.0.0

### Desktop version info

Joplin 3.0.0 (dev, linux)

Client ID: 44da07c87ebf4662aa0e0f97f77f7f38
Sync Version: 3
Profile Version: 46
Keychain Supported: No

Revision: 1ab891723 (pr/user-action-log)

Backup: 1.4.0
CodeMirror 6 snippets: 0.0.5

### Current behaviour

1. Open Joplin
2. Delete a note.
3. Permanently delete the note from the trash.
4. Quit Joplin
5. Start Joplin
6. Inspect the "new note" and "new to-do" buttons in the sidebar
![screenshot: new note and new to-do buttons overflow their borders.](https://github.com/laurent22/joplin/assets/46334387/10c7e8cb-08d4-4d79-a7a8-36317c7d0615)
7. Resize the sidebar

### Expected behaviour

The "new note" and "new to-do" buttons should not have text that overflows their borders.

**Comment by Praveen03AJJARAPU** [comment]
I checked it several times in my Windows, but it didn't show me the bug.
![Screenshot 2024-03-06 200034](https://github.com/laurent22/joplin/assets/97183004/119452bf-f674-47bc-9e1e-b3b0ff59e94d)
![Screenshot 2024-03-06 200045](https://github.com/laurent22/joplin/assets/97183004/719a511c-892c-42e5-901e-2778a3b619ed)

**Comment by khuongduy354** [comment]
Sorry, but where is the Trash Can feature? I'm in 2.14.17 version

**Comment by roman-r-m** [comment]
> Sorry, but where is the Trash Can feature? I'm in 2.14.17 version

You need version 3, so build from dev

**Comment by roman-r-m** [comment]
> I checked it several times in my Windows, but it didn't show me the bug.
> ![Screenshot 2024-03-06 200034](https://github.com/laurent22/joplin/assets/97183004/119452bf-f674-47bc-9e1e-b3b0ff59e94d)
> ![Screenshot 2024-03-06 200045](https://github.com/laurent22/joplin/assets/97183004/719a511c-892c-42e5-901e-2778a3b619ed)
> 

Because your starting notebook isn't the trash notebook. Read the description again

**Comment by khuongduy354** [comment]
Okay, I nailed the bug, the bug have nothing to do with trashcan. It's the switching of search bar to add note. Steps to reproduce: 
1. Open a brand new joplin (or new profile)
2. Click on trash can, so that the add note is hidden
![image](https://github.com/laurent22/joplin/assets/42113313/8c128e36-6627-443e-85f7-67a8225ee4f7)
3. close app and reopen, add notebook and shall see bug

I'm on Linux (debian). 
Can you leave this bug for me to fix? I know we don't assign on Joplin, who fix first get first pr, but I'd appreciate if this is spared for tomorrow, trying to get my first bug :D

**Comment by shivansh193** [comment]
Is this specific to Linux? I am unable to recreate it on windows

**Comment by khuongduy354** [comment]
I haven't tested on Windows, but I believe it's all desktop platforms, because it's a React state update bug. #10076
