### ISSUE TITLE
Pasting text in WYSIWYG editor starts a new line

### ISSUE THREAD

**Issue by sneira** [laurent22/joplin#10061]
### Operating system

Windows

### Joplin version

2.14.17

### Desktop version info

Joplin 2.14.17 (prod, win32)

Client ID: 58cd36faae7c406392acfa9c838fe434
Sync Version: 3
Profile Version: 46
Keychain Supported: Yes

Revision: 094175c

Backup: 1.4.0
Combine notes: 1.2.2
Cursor Sync: 2.1.0
Markdown Prettier: 0.1.0
Note overview: 1.7.1
Note Tabs: 1.4.0
Quick Links: 1.3.0
Search & Replace: 2.2.0
Suitcase: 0.3.2
Templates: 2.4.0

### Current behaviour

In the WYSIWYG editor, when pasting text with Ctrl + V, it always starts a new line. For example, if I have a note with this text:
```
Lorem ipsum dolor sit amet
```
and I copy the word "ipsum" and paste if after "dolor", I get this:
```
Lorem ipsum dolor
ipsum
sit amet
```
This happens when the text is copied from other applications too. Paste as text (Ctrl + Shift + V) works fine.

### Expected behaviour

I expect Joplin to not add line breaks if the pasted text doesn't have them. So the above example should have this result:
```
Lorem ipsum dolor ipsum sit amet
```
This was working fine in previous versions of the application.

**Comment by personalizedrefrigerator** [comment]
This seems to be a regression from v2.13 (comparing with v2.13.8) and related to plugins.

**Edit**: In version 2.14, I can reproduce this if I have [the reveal.js slides plugin](https://joplinapp.org/plugins/plugin/io.github.personalizedrefrigerator.revealjs-integration/) installed, but not if it's uninstalled. I'm not experiencing the issue with the same plugin in version 2.13.

**Comment by khuongduy354** [comment]
Is this an intended feature? I'm able to reproduce this on 2.14.17 no plugin (Debian). Just copy ipsum code block and paste it to joplin note, it will start newline with wrapped ``

**Comment by laurent22** [comment]
I cannot replicate this on macOS with or without plugins.

**Comment by personalizedrefrigerator** [comment]
> **Edit:** In version 2.14, I can reproduce this if I have [the reveal.js slides plugin](https://joplinapp.org/plugins/plugin/io.github.personalizedrefrigerator.revealjs-integration/) installed, but not if it's uninstalled. I'm not experiencing the issue with the same plugin in version 2.13.

This issue seems to be related to adding a `<style onload="some-code-here"></style>` to the end of rendered markdown. Since [this commit (v0.8.0)](https://github.com/personalizedrefrigerator/joplin-plugin-revealjs-slides/commit/fee235ee64976da22e9043d21788e0f7b5b180cd), the `reveal.js` slides plugin no longer does this.

I think the backlinks plugin still causes this issue.

**Comment by personalizedrefrigerator** [comment]
This issue seems related to HTML added by certain plugins when rendering.

For example, with the backlinks plugin, if I 1) open the Rich Text Editor, then 2) type and copy `test`, and finally 3) paste, [processPastedHtml creates](https://github.com/laurent22/joplin/blob/59989d2735ede2ced363f0c448fb5b4cfe0e1bf8/packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx#L1209),

```html
<p>test</p>

                    <div id="backs"></div>
                    <style>
```
from the pasted HTML `test`.

The Rich Text Editor surrounds the pasted content with newlines.

These newlines seem to be coming from the `<p>` that wraps `text` and/or the `<div id="backlinks"></div>`. The [trailing opening `<style>` tag is related to a known issue with the backlinks plugin](https://github.com/ambrt/joplin-plugin-referencing-notes/pull/15). Without `backlinks` installed, there is no wrapping `<p>` in the generated HTML.

One option could be to exclude plugins when removing unsupported HTML. However, this would mean that plugin-generated blocks (e.g. those created by the example [content script plugin](https://github.com/laurent22/joplin/tree/dev/packages/app-cli/tests/support/plugins/content_script/src)) would lose information on paste.

**Edit**:
1. Check whether the original markdown is one line.
2. If one line, remove the wrapping paragraph & simplify.
