### ISSUE TITLE
Android: Table breaks when entering numbered list

### ISSUE THREAD

**Issue by samarlyka** [laurent22/joplin#10106]
### Operating system

Android

### Joplin version

2.14.9

### Current behaviour

Using numbered list in a Markdown table breaks the table. This issue occurs in Android version of Joplin, but not the desktop version.

![Screenshot_20240312-114014_Joplin](https://github.com/laurent22/joplin/assets/93555329/e64a7c17-5553-4589-b60c-976cca7bc5a0)

To replicate this issue, create a Markdown note in Joplin for Android with numbered list, for instance:

```
|No.|Rank|Metacode|Identity|
|:-:|:-:|:-:|:-|
1. |`00001`|**D**|Discoveries|
2. |`00002`|**E**|Experiences|
3. |`00003`|**TT**|The Truths|
4. |`00004`|**KIR**|Kindness' I Received|
5. |`00005`|**CIE**|Challenges I Encountered|
```

### Expected behaviour

I want to be able to synchronize my Joplin notes in desktop and Android, and get the same visual output. Here's how the table in the above markdown note in Joplin for Android is rendered on **Joplin 2.8.8 (dev, linux) revision c2a6a13**

![20240312_114509](https://github.com/laurent22/joplin/assets/93555329/0fa2be70-afbc-4654-abde-361f601acf6b)

**Comment by YadavBinay** [comment]
The issue is with markdown text and not in **Android  App:  v 2.14.9**
issue with this markdown is that the alignment specifier (`:-:`) should be placed after the dashes in the header row, not before.
The pipes **( | )** also must align vertically and there shouldn't be any additional characters before and after pipes ( | )

fixes issue #10106

I already Tested This in specified Version of App

here is revised MD With output


```
| No. | Rank | Metacode | Identity |
|:---:|:----:|:--------:|:--------|
| 1.  | `00001` | **D** | Discoveries |
| 2.  | `00002` | **E** | Experiences |
| 3.  | `00003` | **TT** | The Truths |
| 4.  | `00004` | **KIR** | Kindness' I Received |
| 5.  | `00005` | **CIE** | Challenges I Encountered |

```

| No. | Rank | Metacode | Identity |
|:---:|:----:|:--------:|:--------|
| 1.  | `00001` | **D** | Discoveries |
| 2.  | `00002` | **E** | Experiences |
| 3.  | `00003` | **TT** | The Truths |
| 4.  | `00004` | **KIR** | Kindness' I Received |
| 5.  | `00005` | **CIE** | Challenges I Encountered |

**Comment by roman-r-m** [comment]
This is due to the multimarkdown plugin which you have enabled on desktop but disabled on Android.

![image](https://github.com/laurent22/joplin/assets/995612/a7f2d6b1-ccd7-482b-905c-89a59e241352)

**Comment by samarlyka** [comment]
> This is due to the multimarkdown plugin which you have enabled on desktop but disabled on Android.

The desktop version which I am using (and synchronizing with) does not have **"Multimarkdown Support"** enabled, but the following MD table can be rendered out-of-the-box (even without specifying "\|" at the beginning of each line, before the ordered list):

```
|No.|Rank|Metacode|Identity|
|:-:|:-:|:-:|:-|
1. |`00001`|**D**|Discoveries|
2. |`00002`|**E**|Experiences|
3. |`00003`|**TT**|The Truths|
4. |`00004`|**KIR**|Kindness' I Received|
5. |`00005`|**CIE**|Challenges I Encountered|
```

Then I attempted to enable **"Multimarkdown Support"** in the Joplin for Android I am currently using. It worked!

This is how it looks like on Joplin for Android after the multi-MD feature has been enabled:

![Screenshot_20240314-143634_Joplin](https://github.com/laurent22/joplin/assets/93555329/f3a23b22-9f65-49b2-a425-d467f4df3fc0)

The table rows no longer break.

Thanks [roman-r-m](https://github.com/roman-r-m), much appreciated!
