### ISSUE TITLE
Unable to uninstall successfully in Windows

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#10183]
### Operating system

Windows

### Joplin version

2.13.9

### Desktop version info

Windows 10

### Current behaviour

When Joplin is uninstalled from the settings, the following files remain undeleted

- `C:\Program Files\Joplin\`
- `C:\Users\USERNAME\AppData\Roaming\Joplin\`
- `"C:\Users\USERNAME\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Tombstones\Joplin (2).lnk"`

**Comment by mimeyn** [comment]
Hi dear [elvis-hrvat](https://github.com/elvis-hrvat),

This is definitely not a problem with the joplin windows app.
Joplin uses ElectronJS to implement its functionality in Windows, and electron.

Electron is a node-based ecosystem that has the task of installing and removing on target platforms; At the time of installation, it creates some folders to maintain proper functionality, which does not delete these folders when uninstalling.

If you want the programs (and not just joplin) to be completely deleted in Windows, instead of deleting them from the settings or control panel, use the complete uninstaller programs like: Revo uninstaller, Ashampoo UnInstaller and etc.

**Comment by roman-r-m** [comment]
The installer can be customized. I suspect setting `deleteAppDataOnUninstall` (https://www.electron.build/configuration/nsis) may help.

Or, if not, a custom NSIS script with additional uninstall steps can be added.

**Comment by ghost** [comment]
Don't close Issues

**Comment by ghost** [comment]
Don't close Issues

**Comment by ghost** [comment]
Don't close issue
