### ISSUE TITLE
User should not be invited to create a note from the trash folder

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#10191]
- Open the trash folder when it's empty

=> It displays the message "This notebook is empty, create one by clicking on the + button..."

Instead it should say "The trash folder is empty".

**Comment by Sidd-R** [comment]
I have implemented the mentioned change, but I have a doubt. Let's say the trash folder is empty and I create a folder then delete it without adding any note/todo. In that case what should be displayed when the trash folder is opened? It's not empty since it has a folder in it, but it doesn't have any note/todo to display. As of now I'm showing the "The trash folder is empty" message in this case.

**Comment by laurent22** [comment]
You're right, we should add a more generic message that would apply to both these cases. Maybe just "There is no notes here"?

**Comment by Sidd-R** [comment]
That sounds good.

**Comment by personalizedrefrigerator** [comment]
Related: https://github.com/laurent22/joplin/issues/10259
