### ISSUE TITLE
BibTex plugin shows an error on starting the desktop application

### ISSUE THREAD

**Issue by ab-elhaddad** [laurent22/joplin#10232]
### Operating system

Windows

### Joplin version

2.14.20

### Desktop version info

Joplin 2.14.20 (prod, win32)

Client ID: 661464843b9c4f28bae33231432440c4
Sync Version: 3
Profile Version: 46
Keychain Supported: Yes

Revision: cfd98e3

Backup: 1.4.0
BibTeX: 0.5.0
Calendar: 1.1.0
Delete notes without confirmation: 1.0.0

### Current behaviour

Each time I start the Joplin desktop application, I get this error from `BibTex` plugin

![BibTex](https://github.com/laurent22/joplin/assets/113056556/7bfbf369-5021-415b-a6db-ecff371f77d1)

### Expected behaviour

the application should run normally without showing errors.

**Comment by DarkFalc0n** [comment]
This is because BibTex expects a bibliography source file, in other words, a `.bib` file where numerous citation sources are stored for quickly inserting into the editor. If you do not want to see this warning, create an empty sample.bib file somewhere in your Documents folder, then paste the full path in the BibTex plugin config menu.

### Directions
First press `Ctrl + ,`

Then paste the full path of the file as shown


![image](https://github.com/laurent22/joplin/assets/59203815/d78d8eeb-2bb3-4d58-be85-994baf39eb18)
