### ISSUE TITLE
Notebook selection blocked in note editor

### ISSUE THREAD

**Issue by PaulS-26** [laurent22/joplin#10252]
### Operating system

Android

### Joplin version

2.14.9

### Current behaviour

1. Close Joplin app using Android app drawer (in case it has already been opened)
2. Press Joplin shortcut "New note" on home screen
3. Enter content of the new note (title, body)
4. Return to the note list by pressing back arrow twice (on top left)
5. Switch to different notebook using hamburger menu
6. Return to home screen using Android home button (not Android back button)
7. Press Joplin shortcut "New note" on home screen again
8. Notebook selector is blocked (grayed out), therefore the new note can't be assigned to a different notebook

### Expected behaviour

Notebook selector is not blocked and can be used.

**Comment by pedr** [comment]
I think there is a race condition happening here:

- For the folder selector not to be disabled `selectedNotesIds` must not be an empty array (I'm not sure why this is a rule)

1. When user press "New note" a new note is created (Note A)
2. User is redirected to the editor
3. `NotesScreenComponent/Notes` component calls `refreshNotes` because `selectedFolderId` changed (couldn't understand why yet)
4. `Notes.previews` (inside `refreshNotes`) won't return the newly created note (race condition??)
5. `NOTE_UPDATE_ALL` event is called without the newly created note
6. Inside `updateSelectedNotesFromExistingNotes` selectedNoteIds is set to an empty array since the previously selected note is not present in the `draft.notes` array
7. Since now `selectedNoteIds` is an empty array the folder selector is disabled

I'm documenting what I discovered so far. I'm trying to understand why the `selectedFolderId`, I think it might be related to `NOTE_UPDATE_ONE`

I think it might there be a race condition happening there because if I add a delay between creating a note and redirecting to the note editor inside the `setupQuickActions` "solves the bug"

**Comment by pedr** [comment]
The problem was much simpler, the issue was that quick actions function was using a old value of `selectedFolderId`. I refactored to use the newest value and the issue related here is fixed.

But by fixing it I might have introduced another bug: 

1. Close Joplin app using Android app drawer (in case it has already been opened)
2. Press Joplin shortcut "New note" on home screen
3. Try to change notebook with the dropdown
4. App will show the selected notebook for one second and change the notebook to the original again

I'm going to take a look tomorrow to see if I can fix it
