### ISSUE TITLE
Website: Wrong github link in changelog

### ISSUE THREAD

**Issue by marph91** [laurent22/joplin#10279]
### Operating system

Linux

### Joplin version

3.0.2

### Current behaviour

For example at https://github.com/laurent22/joplin/blob/dev/readme/about/changelog/desktop.md?plain=1#L11, the link points to https://github.com/Marph. This is wrong. My correct github account is https://github.com/marph91.

### Expected behaviour

Use the correct link.

Please let me know if the page is generated or edited manually. In the latter case, I could create a PR.

**Comment by laurent22** [comment]
I know I looked into this at some point and I believe that's because:

- Your git email address is not associated with your GitHub account
- And there's a valid GitHub account that has the same username as your git username (this is the fallback when we can't find the GitHub account from the email)

Because this is a rare occurrence we leave it as it is for now. I think what you could do to have your account detected is add your email to your GitHub account, or rename your git username to "marph91", same as your GitHub account

**Comment by marph91** [comment]
Thanks for checking. My commit email is associated to my github account, but it's not public. I just changed my username. Let's see if it works at the next update.
