### ISSUE TITLE
iOS mobile app  background sync

### ISSUE THREAD

**Issue by casasfernando** [laurent22/joplin#1029]
### Operating system

- iOS

### Application

- Mobile

I noticed that the Joplin mobile app is only synchronizing while running in the foreground. As soon as you switch to any other app, the home screen or if the device screen is locked/off sync will pause and it will only resume when the application is back in the foreground.
This is kind of a problem on a first sync or if you have many items to sync to the device, since while it's running the sync process you can't switch to any other app or lock the device.

**Comment by deciacco** [comment]
Background sync in an app like this is a must. Its unreasonable to have to keep the app open and wait while it syncs. It takes a long time on initial setup if you have many items which if you use the app as intended you will. Every time you get a new device you have to repeat the process as it doesn't transfer when you initialize from backup.

It's also a problem having to sync before closing the app in order to make sure your latest changes will show up on your other devices/desktop. I've often forgotten to sync  and ended up missing that note when I  needed it on my Desktop.

I find myself all too often not making changes in iOS and only using Joplin in "read only" mode because I don't want to have wait for syncs.  Its also hard to create much content on an iOS device since you cant clip to Joplin from any other app, but thats for another issue/feature request.

**Comment by alexj-m** [comment]
I'd really like this fixed as well. I also find myself using Joplin as a "read-only" app on iOS as I always miss the sync.

**Comment by merida132** [comment]
I agree, this is a critical feature for me also and the last step to abandon Evernote entirely.

**Comment by squidrpi** [comment]
This is mandatory to enable me to switch from the built in Notes app.

**Comment by squidrpi** [comment]
Issue still hasn't been resolved.

**Comment by casasfernando** [comment]
Issue still hasn't been resolved.

**Comment by yadayadaydadaa** [comment]
What is it with no response at all? As stated in another censored posting, background sync is mandatory to be able to make the switch from the built-in Notes app. (That and ironing out a few glitches in the interface.)

**Comment by alexj-m** [comment]
Still an issue for me too

**Comment by altosaar** [comment]
Still an issue.
