### ISSUE TITLE
Joplin can not use fcitx ime when I use wayland

### ISSUE THREAD

**Issue by wugh** [laurent22/joplin#10345]
### Operating system

Linux

### Joplin version

Joplin 2.14.20 (prod, linux)

### Desktop version info

Joplin 2.14.20 (prod, linux)

Client ID: b86f5a85e27540668b4973abc4831569
Sync Version: 3
Profile Version: 46
Keychain Supported: No

Revision: cfd98e3

Backup: 1.4.0

### Current behaviour

I want to use joplin wayland native use following command 
```
joplin-desktop --enable-features=UseOzonePlatform --ozone-platform=wayland 
```
This  can work. but I can not input Chinese to the notes.

Then I search the `fcitx5` wiki
https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland
They said I need to start with `--enable-wayland-ime` option. for e.g.
I can start chromium with following command
```
chromium --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime 
```
I also can start vscode with command
```
code --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime
```

But when I start joplin with
```
 joplin-desktop --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime
```
I got error message
```
Unknow flag: --enable-wayland-ime
```

How to fix this error

**Comment by personalizedrefrigerator** [comment]
Thank you for reporting this!

b69bf84ab6476627b168006b379f78c3c250d21c should allow passing `--enable-wayland-ime` as a startup option. It may take some time for it to be in a stable release, however (see [the release cycle](https://joplinapp.org/help/about/release_cycle)).

**Comment by wugh** [comment]
Thank you

**Comment by wugh** [comment]
> Thank you for reporting this!
> 
> [b69bf84](https://github.com/laurent22/joplin/commit/b69bf84ab6476627b168006b379f78c3c250d21c) should allow passing `--enable-wayland-ime` as a startup option. It may take some time for it to be in a stable release, however (see [the release cycle](https://joplinapp.org/help/about/release_cycle)).

Thank you for fix this case.
I want to know how to trigger a prerelease version. I can not typing chinese in joplin now, queit urgent issue.
Or How to build the app locally, so I can use the version can typing chinese.

**Comment by personalizedrefrigerator** [comment]
It might take a week or so for the next prerelease build to be ready (the last one was [5 days ago](https://github.com/laurent22/joplin/releases)).

Build instructions [can be found here](https://joplinapp.org/help/dev/BUILD#building).

To summarize:
1. [Install the required dependencies](https://joplinapp.org/help/dev/BUILD/#required-dependencies)
   - The documentation says "Node 16+", but I think it needs Node 18+ (see https://github.com/laurent22/joplin/issues/10234).
2. Run `yarn install` from the root of the repository.
   - It may be necessary to run `corepack enable` first (or alternatively, `corepack yarn install` instead of `yarn install`).
3. `cd packages/app-desktop`, then run `yarn dist --publish=never`.
4. The built AppImage should be in `packages/app-desktop/dist/` (e.g. as `Joplin-3.0.3.AppImage`).

**Comment by personalizedrefrigerator** [comment]
The relevant change should now be in the [v3.0.6 pre-release](https://github.com/laurent22/joplin/releases/tag/v3.0.6).
