### ISSUE TITLE
web clipper often fails with joplin v3

### ISSUE THREAD

**Issue by jotech** [laurent22/joplin#10365]
### Operating system

Linux

### Joplin version

v3.0.3

### Desktop version info

Joplin 3.0.3 (prod, linux)

Client ID: 5f8d4a874f9949668307282cf47708ff
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: e84ea8a

Backup: 1.4.1
Bidirectional Links: 0.1.2
Favorites: 1.3.2
Inline tags: 1.3.0
Link Graph UI: 1.5.0
Note list (Preview): 0.4.1
Note Tabs: 1.4.0
Outline: 1.5.13
Quick Links: 1.3.2
Rich Markdown: 0.14.1

### Current behaviour

Lately, I encountered problems when using Joplin's web clipper. Many pages like this [1] cannot be saved to Joplin. Using 'Clip simplified page' from the web clipper results in an error `Internal Server Error: Cannot create property 'httpCode' on string`

[1] https://doi.org/10.1111/mmi.15236

### Expected behaviour

Web clipping works fine with older joplin versions like v2.14.20Joplin

### Logs

detailed web clipper error message
```
There was some error creating the note: {"error":"Internal Server Error: Cannot create property 'httpCode' on string 'Image at /home/jo/.config/joplin-desktop/tmp/mmi15236-fig-0002-m_c63645e2d93648a6a8e01c5a9b4549b2.png failed to load.': \n\nTypeError: Cannot create property 'httpCode' on string 'Image at /home/jo/.config/joplin-desktop/tmp/mmi15236-fig-0002-m_c63645e2d93648a6a8e01c5a9b4549b2.png failed to load.'\n at Api.<anonymous> (/tmp/.mount_joplingk4zD7/resources/app.asar/node_modules/@joplin/lib/services/rest/Api.js:162:36)\n at Generator.throw (<anonymous>)\n at rejected (/tmp/.mount_joplingk4zD7/resources/app.asar/node_modules/@joplin/lib/services/rest/Api.js:6:65)"}
```

**Comment by laurent22** [comment]
Dev info: It happens on `packages/lib/services/rest/Api.ts` line 247 which means something somewhere is throwing a string instead of an error object

Edit: @personalizedrefrigerator, it's probably this commit: a0f003f9d563e1c8945707b247312bfbc546583e When we call `reject` we should pass an error object instead of a string whenever possible (Actually I saw there's a [prefer-promise-reject-errors](https://eslint.org/docs/latest/rules/prefer-promise-reject-errors) rule which we should implement to more easily detect those)

**Comment by personalizedrefrigerator** [comment]
> it's probably this commit: https://github.com/laurent22/joplin/commit/a0f003f9d563e1c8945707b247312bfbc546583e When we call reject we should pass an error object instead of a string whenever possible

I've created a pull request that should cause the correct error message to be displayed (https://github.com/laurent22/joplin/pull/10368). While it improves the error message, it doesn't seem to fix the issue.

I'm in the process of doing a `git bisect`.

**Edit**: 

<details><summary>Error messages when building from #10308</summary>

Clipping https://onlinelibrary.wiley.com/doi/10.1111/mmi.15236 from #10368:

```
There was some error creating the note: {"error":"Internal Server Error: Image at /home/builder/.config/joplindev-desktop/profile-0fof4zei/tmp/mmi15236-fig-0001-m_4abcf3d737f8408dac637304ea39a532.png failed to load.: \n\nError: Image at /home/builder/.config/joplindev-desktop/profile-0fof4zei/tmp/mmi15236-fig-0001-m_4abcf3d737f8408dac637304ea39a532.png failed to load.\n at image.onerror (/home/builder/Documents/joplin/packages/lib/shim-init-node.js:180:50)"}
```

If I reset `handleResizeImage_` to 0e6b5b338ce86828ac48844bffe5f8467cd382f1 (a commit before it was updated to use an `Image` rather than `native-image`), I get

```
There was some error creating the note: {"error":"Internal Server Error: Image is invalid or does not exist: /home/builder/.config/joplindev-desktop/profile-0fof4zei/tmp/mmi15236-fig-0001-m_cf904fa17b0946f9a12c55e2000a300c.png: \n\nError: Image is invalid or does not exist: /home/builder/.config/joplindev-desktop/profile-0fof4zei/tmp/mmi15236-fig-0001-m_cf904fa17b0946f9a12c55e2000a300c.png\n at /home/builder/Documents/joplin/packages/lib/shim-init-node.js:173:27\n at Generator.next (<anonymous>)\n at /home/builder/Documents/joplin/packages/lib/shim-init-node.js:8:71\n at new Promise (<anonymous>)\n at __awaiter (/home/builder/Documents/joplin/packages/lib/shim-init-node.js:4:12)\n at handleResizeImage_ (/home/builder/Documents/joplin/packages/lib/shim-init-node.js:166:16)\n at Object.<anonymous> (/home/builder/Documents/joplin/packages/lib/shim-init-node.js:278:34)\n at Generator.next (<anonymous>)\n at fulfilled (/home/builder/Documents/joplin/packages/lib/shim-init-node.js:5:58)"}
```

</details>

A `git bisect` points to 9e0a0468b29d0bec391bd483bcb7f2c56b0ba795 as being the first commit where this issue happens.

**Comment by jotech** [comment]
solved in https://github.com/laurent22/joplin/releases/tag/v3.0.6
