### ISSUE TITLE
Note diseappear when selected for edit from a TAG list (Works OK when selected from a Notebook)

### ISSUE THREAD

**Issue by Pierrep56** [laurent22/joplin#10388]
### Operating system

Linux

### Joplin version

3.0.6

### Desktop version info

Joplin 3.0.6 (prod, linux)

Client ID: 2fde79a23a8646c180bbcd3ac47249d5
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: 18b9f5c

Backup: 1.4.1
Conflict Resolution: 1.2.3
Convert Text To New Note: 1.5.1
Delete unlinked resources: 1.0.0
Emoji: 1.0.4
Enhancement: 1.2.1
Ez Table: 1.0.2
Menu items, Shortcuts, Toolbar icons: 1.1.0
MultiMarkdown Table Tools: 1.2.0
Search & Replace: 2.2.0
Table Formatter Plugin: 1.2.1

### Current behaviour

1. Joplin opens normally
2. I select a file from the TAGS list
3. The file opens as it should in the editor (internal editor)
4. As soon as I begin to edit it, it just "vanish"
5. If I return to the notes list, change my selection, then return to the previous tag I can see it again.
6. And again, re-opening it FROM THE TAG LIST reproduce the same vanishing effect.
7. Now, If I open the SAME FILE from a NOTEBOOK or ALL FILES (Not from a Tag list), I can edit it normally. No apparent bug.
8. I have deleted and recreated my tags. No change. The issue appears ONLY when the file is open FROM the Tags list.

### Expected behaviour

No vashing file when editing it, after opening it from the Tags list

### Logs

Well, I did create the flags.txt file and the console opens in Joplin but the flag.txt stays empty even after the bug occurs.

**Comment by personalizedrefrigerator** [comment]
Related: https://github.com/laurent22/joplin/issues/10236.

**Comment by Marain888** [comment]
I am also experiencing this issue. When I try to edit a file in a list generated from a Tag, the file disappears. If I click on the Tag name again, the file reappears in the list. 

Joplin 3.0.6 (prod, win32)
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes
Revision: 18b9f5c
Backup: 1.4.1

Marian
[-1714928945851.log](https://github.com/laurent22/joplin/files/15213827/-1714928945851.log)

**Comment by Marain888** [comment]
This issue also occurs when I try to edit a Note in a List generated from a Search - I type one character and the note disappears from the List. 

Joplin 3.0.6 (prod, win32)
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes
Revision: 18b9f5c
Backup: 1.4.1

[-1715152028961.log](https://github.com/laurent22/joplin/files/15245068/-1715152028961.log)

**Comment by nonobio** [comment]
Hi,

Same issue:
![tvnviewer_2024-05-16_11-34-28](https://github.com/laurent22/joplin/assets/7425799/eadce36a-fa16-449b-85ab-0f0ed2ceff05)

I found a workaround, just click on the "in notebook" button before clicking in the note:
![image](https://github.com/laurent22/joplin/assets/7425799/d3d92343-f277-432c-986f-4898925dd60f)

![tvnviewer_2024-05-16_11-43-49](https://github.com/laurent22/joplin/assets/7425799/e426173b-5ba9-4ba9-8cc1-112af1979900)

Joplin 3.0.6 (prod, win32)

ID client : bc23d8d35e3d469eb21243f774c7ff1e
Version de Synchro : 3
Version du profil : 47
Trousseau supporté : Oui

Révision : 18b9f5c

Backup: 1.4.1
Note overview: 1.7.1
Note Tabs: 1.4.0
Outline: 1.5.13
Rich Markdown: 0.15.0
Search & Replace: 2.2.0

I tried on two different PCs and after deactivating all plugins, same problem.
I have the impression that the problem is not present if I do the same search again 🤔

Seems related:
https://github.com/laurent22/joplin/issues/10236
https://github.com/laurent22/joplin/issues/10219

**Comment by Marain888** [comment]
@nonobio Yes, this works, but the downside is that the List generated from the Search or Tag must be regenerated by Search/Tag for, e.g., the case that you want to edit more or all of the Notes in the List than only the one that disappears when you try to edit it from the List. I hope they will fix this soon. It's just a bit annoying. It seems to be an error introduced with one of the Beta 3.nn versions (not for normal users who are still on version 2.nn).

**Comment by Dricc123** [comment]
Could we put the priority level on 'high' please? It makes the desktop app pretty inconvenient.

**Comment by Julrob199** [comment]
Hope this gets fixed soon! This bug still exists in 3.0.7, it makes the app barely usable since weeks. Hope this i prioritized in the next update. I have the problem on the work windows computer and also here on my private linux. Thank you!!

There are duplicates of many different types, which somehow all refer to the same problem: 
#10219 
#10236 
#10194

**Comment by Dricc123** [comment]
I'm surpised this issue doesn't get more attention

**Comment by Julrob199** [comment]
@Dricc123 me as well 😂 or if actually everyone is experiencing this (I have at least the problem on two different machines, linux and windows). Unfortunately my programming skills are quite limited to fix this :(

**Comment by Dricc123** [comment]
Can I support in any way?

**Comment by Julrob199** [comment]
If you found the reason for this problem this would be amazing. Is it something you would use this developer view window use for?

**Comment by nonobio** [comment]
A huge thank you, it works :)

On the other hand, the list still changes after editing, is this normal?

I have the impression that during a search the list is sorted by relevance, and that as soon as I edit a note, the list is sorted by the defined sorting (descending modification date in my case):
![tvnviewer_2024-06-13_08-24-21](https://github.com/laurent22/joplin/assets/7425799/523e55a7-ae88-4787-952a-9975e19451fa)

I would prefer if she didn't change, what do you think?

**Comment by personalizedrefrigerator** [comment]
> On the other hand, the list still changes after editing, is this normal?

That didn't happen in Joplin 2.14.22 (**edit**: This is because of different sort settings in the 2.14 client. See below)! I've opened an issue: https://github.com/laurent22/joplin/issues/10586

**Comment by Marain888** [comment]
I'm pretty sure that it was normal in the past that a note would pop to the top of whatever list had been generated as soon as it was edited, assuming the list is sorted by most recently updated. If you sort it alphabetically, this won't happen. 

My Joplin was updated today and included the fixes announced by Laurent. I am very happy that everything seems to be back to normal. Thank you, Laurent!

Marian
