### ISSUE TITLE
[feature] Add written hashtags in a note as Joplin-tags

### ISSUE THREAD

**Issue by BengaloBongali** [laurent22/joplin#1040]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

It would be extremely convenient to have #hastags that are written in a note ("Read an interesting article about synchronization #software today.") added to the note as Joplin-tags automatically.

**Comment by Baba-Samika** [comment]
I also think this would be very useful. Or an extra keywords funktion, where you could highlight words in text so that they are easily searchable and so that you can list all notes that relate to the keyword. 

Maybe the @ symbol could be used, since the # symbol is markdown for a header.

**Comment by foxmask** [comment]
# for keyword, and @ for folder / tag

**Comment by BengaloBongali** [comment]
@Baba-Samika 
Markdown header is `# header`, no? So that's not a problem, since you'd use `#tag`.
`@Person` is standard for linking to profiles online. So please don't implement this for tags.

@foxmask 
Why would you differentiate between keywords and tags?

**Comment by laurent22** [comment]
This kind of automation won't be built-in but you could create your own script that parses the notes and auto create tags.

**Comment by pqrth** [comment]
Thanks a ton, @laurent22 for creating and maintaining one of my essential apps.

I couldn't understand your rationale behind not supporting "this kind of automation". Personally, I think it's a good productivity improvement and it would be really helpful if it's supported natively, instead of using some script. I request you to keep this issue open, so one of us can think about implementing it, maybe controlled by a toggle in _General Options_.

**Comment by cable729** [comment]
Something to think about: GitHub supports this (type # and a drop-down will come up to reference issues, or type @ and a drop-down will come up to reference people). I personally think those two features are very useful on GitHub.

**Comment by colmsjo** [comment]
+1
