### ISSUE TITLE
Joplin  updated from 12.14.6 to 12.14.8 in IOS17.5 , Webdav sync failed :Network request faild 

### ISSUE THREAD

**Issue by suntingbo** [laurent22/joplin#10437]
### Operating system

iOS

### Joplin version

12.14.8

### Current behaviour

In IOS 17.5 , after updated Joplin to 12.14.8 , webdav cannot be used；but  12.14.6  works fine . 

### Logs

![cfab9f5de58c6c2240dd1881b6d5342](https://github.com/laurent22/joplin/assets/23579851/0541b410-836d-4499-a602-73edbdfdccf2)

**Comment by suntingbo** [comment]
this is my webdav address , works fine before Joplin 12.14.6

![image](https://github.com/laurent22/joplin/assets/23579851/61b1ee83-6a17-4dfe-a9a1-bdcb29b2d3ff)

**Comment by wljince007** [comment]
# The reason is: [nsapptransportsecurity](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity)
I found a feasible method by compiling the dev version of 12.14.8.

# Here is a flexible solution:
1. In Joplin Setting, configure the WebDav Url address to http://api.joplincloud.local:12345
2. `api.joplincloud.local` has been set to enable HTTP requests by Joplin IOS version.
3. Add nginx forwarding before WebDav service, example configure:
```
server {
  listen 12345;
  location / {
    proxy_set_header Host 101.35.198.14:51234;
    proxy_pass  http://101.35.198.14:51234;
  }
}
```
4. Change IOS Hosts, or use Stash proxys or other methods to transfer http://api.joplincloud.local:12345 lead to your nginx monitoring http://101.35.198.14:12345

**Comment by suntingbo** [comment]
It works, thanks a lot!

> # The reason is: [nsapptransportsecurity](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity)
> I found a feasible method by compiling the dev version of 12.14.8.
> 
> # Here is a flexible solution:
> 1. In Joplin Setting, configure the WebDav Url address to http://api.joplincloud.local:12345
> 2. `api.joplincloud.local` has been set to enable HTTP requests by Joplin IOS version.
> 3. Add nginx forwarding before WebDav service, example configure:
> 
> ```
> server {
>   listen 12345;
>   location / {
>     proxy_set_header Host 101.35.198.14:51234;
>     proxy_pass  http://101.35.198.14:51234;
>   }
> }
> ```
> 
> 4. Change IOS Hosts, or use Stach proxys or other methods to transfer http://api.joplincloud.local:54321 lead to your nginx monitoring http://101.35.198.14:12345
