### ISSUE TITLE
Documents seem lost in latest release on mac (intel)

### ISSUE THREAD

**Issue by snorky22** [laurent22/joplin#10455]
### Operating system

macOS

### Joplin version

2.14.21

### Current behaviour

When opening Joplin 2.14.21, a blank window opens with minimal menus.
The notes do not appear. The quit menu does not work.
My wife has had the same problem on her Mac
My system version is MacOS Sonoma 14.5 on an intel machine. My wife's machine rune the latest patch of Monterey.

When reverting to version 2.14.20, the app's behavior becomes normal.

Both version are release versions. The buggy version was downloaded from the update prompt of the preceding version.

### Expected behaviour

Notes should appear with functional menus.

**Comment by laurent22** [comment]
Please see here: https://discourse.joplinapp.org/t/joplin-2-14-21-serious-bug/38191/14?u=laurent

**Comment by personalizedrefrigerator** [comment]
This should be fixed in [v2.14.22](https://github.com/laurent22/joplin/releases/tag/v2.14.22)!

**Explanation**: The release CI was running on `macos-latest`, [which switched from x86 to ARM](https://github.com/actions/runner-images/issues/9741). This caused the ARM version of some libraries to be bundled with the application, which broke the MacOS x86 `.dmg` file.

See also https://github.com/laurent22/joplin/commit/36aaf5a10ce609c1928d23e9d8ec00cf53c3f1dd.

Thank you for reporting this!
