### ISSUE TITLE
Desktop: No MacOs Intel pre lease version for 3.0.8

### ISSUE THREAD

**Issue by bsavant** [laurent22/joplin#10481]
### Operating system

macOS

### Joplin version

3.0.8

### Current behaviour

There is no MacOS intel dmg for the 3.0.8 prerelease.

**Comment by swofford** [comment]
Any updates on this?

I tried to install the "M1" version because it was all I saw and I thought it might be universal. When it wasn't, I downloaded the standard 2.x version and launched it, only to discover that my 3.x profile version is incompatible with version 2.x. I have customized my profile quite a bit so I'd prefer not to start all over.

I will build from source if necessary, but I was hoping to not need to.  Thanks.

**Comment by swofford** [comment]
I just now figured out how to download 3.0.6, so I'm back in business and there is no longer any urgency. Sorry.

> Any updates on this?
> ...
