### ISSUE TITLE
Table properties are not readable in dark mode

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#10561]
### Operating system

Windows

### Joplin version

3.0.0

### Desktop version info

Table properties in the RTE are not readable in dark mode:

<img width="504" alt="image" src="https://github.com/laurent22/joplin/assets/1285584/741c3fde-f478-4fbb-a09c-b626db2dcd25">

**Comment by X1Vi** [comment]
can u explain what RTE is ?

**Comment by laurent22** [comment]
ChatGPT is your friend here:

<img width="799" alt="image" src="https://github.com/laurent22/joplin/assets/1285584/7e786565-d10d-4133-967f-c2d226a60ecb">

**Comment by skushagra** [comment]
Hello @laurent22, is someone working on this issue? I would like to work on this!

**Comment by Aarya01Patil** [comment]
I would like to fix this issue @laurent22

**Comment by CodeMaverick2** [comment]
Hey @laurent22  I would like to solve this issue

**Comment by Aarya01Patil** [comment]
Hey @personalizedrefrigerator / @laurent22  can you exactly let me know which table property is not readable in dark mode in RTE , because as for the screenshot i can see the properties , did you mean the general tab greys out when we select advanced section and a vice versa 
Do you want me to fix that?
It would be helpful for me to know so I can work towards fixing it

**Comment by laurent22** [comment]
> Hey @personalizedrefrigerator / @laurent22 can you exactly let me know which table property is not readable in dark mode in RTE , because as for the screenshot i can see the properties , did you mean the general tab greys out when we select advanced section and a vice versa

Just try?

**Comment by laurent22** [comment]
**IMPORTANT**: the next person who `@-mention` someone will be blocked from this repository. If you want to participate in GSoC, start by reading the rule please and one thing you shouldn't do is ping people left and right.

**Comment by personalizedrefrigerator** [comment]
> did you mean the general tab greys out when we select advanced section and a vice versa

I'm including light and dark mode screenshots for comparison.

![light mode screenshot of the table properties dialog](https://github.com/user-attachments/assets/73141141-b8de-43fc-89b6-e85b8eb1c78e)
![dark mode screenshot of the table properties dialog -- advanced link in the sidebar and show caption checkbox still have the same color as in the light mode screenshot, which is almost invisible.](https://github.com/user-attachments/assets/b5027a06-40b6-4ce2-bbd3-beacbc80b20c)

Based on these, I suspect that the issue is referring to the "show caption" checkbox and "advanced" link.
