### ISSUE TITLE
Keyboard Shortcuts do not work in Markdown Viewer 

### ISSUE THREAD

**Issue by bsavant** [laurent22/joplin#10578]
### Operating system

Linux

### Joplin version

3.0.6

### Desktop version info

Joplin 3.0.6 (prod, linux)

Client ID: b2bc7fbd98864f42af824c2361a1a1bb
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: 18b9f5c

Backup: 1.4.1

### Current behaviour

1. Set keyboard shortcuts for Back and Forward actions in preferences
2. Enter a few different sample notes
3. Click between them to build navigation history
4. In Markdown Editor, use keyboard shortcuts to move back and forth between notes
5. Switch to Markdown Viewer, try to use keyboard shortcuts to move back and forth - nothing happens
6. Switch to Split Editor/Viewer, using the shortcuts works.

### Expected behaviour

I would expect the keyboard shortcuts to consistently work across the different modes, the same as the physical forward and back buttons.

**Comment by personalizedrefrigerator** [comment]
In Joplin 2.14.22, it seems to work (Ubuntu 24.04), but only after I restarted Joplin. I think this is because the markdown editor [registers Joplin commands as CodeMirror shortcuts](https://github.com/laurent22/joplin/blob/dev/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v6/utils/useKeymap.ts), while the viewer and other parts of the app rely on the shortcut being updated in Joplin's menubar.

**Comment by bsavant** [comment]
Got it.  You're right, this is working ok after a restart.  I will close.
