### ISSUE TITLE
Android application weight is too high

### ISSUE THREAD

**Issue by BigPebble123** [laurent22/joplin#10655]
### Operating system

Android

### Joplin version

3.0.4

### Desktop version info

n/a

### Current behaviour

Why is the size of the Android app so large? According to F-Droid, it is over 97 MiB, which is not appropriate for the features the app offers. Could you please look into this?

### Expected behaviour

n/a

### Logs

n/a

**Comment by personalizedrefrigerator** [comment]
See https://github.com/laurent22/joplin/commit/a0e3e4fefb4beb7830d34b65ba47f327edbd8c70#commitcomment-143068881

**Comment by dkbg** [comment]
I found this issue since I noticed that the newest version in F-Droid (3.2.1) is now more than 2x as large (204.6MB!) as the previous version in F-Droid 3.1.8 (97.5MB). Is this expected?

EDIT: nevermind, this is already addressed in #15 , https://github.com/laurent22/joplin/issues/15#issuecomment-2475879394
