### ISSUE TITLE
Android 14 tab jopplin app not sync via dropbox

### ISSUE THREAD

**Issue by parduspanteri** [laurent22/joplin#10681]
### Operating system

Android

### Joplin version

3.0.7

### Current behaviour

![photo_2024-07-03_17-49-32](https://github.com/laurent22/joplin/assets/105588014/38b866f3-8e98-464b-8ae5-c5805836222d)

### Expected behaviour

I expected Joplin to synchronize notes via Dropbox.

### Logs

[syncReport-1720077376871.txt](https://github.com/user-attachments/files/16094869/syncReport-1720077376871.txt)

**Comment by personalizedrefrigerator** [comment]
<details><summary>I haven't been able to reproduce this. However, I've only tested with <strong>the English (UK)</strong> and <strong>Español (España)</strong> locales selected (in Joplin).</summary>

Here's what I've tried:
- [x] Set up Dropbox sync with encryption disabled on Android 13.
    - Joplin 3.0.8, built from the `dev` branch (development mode).
- [x] Created a small number of notes and verified that these notes can be successfully synced with Dropbox.
- [x] Connected and synced a desktop client.
- [x] Attached a large file from the Android device (174 MiB) and verified that it syncs successfully.

Things that could still be tested:
- [ ] Sync with a larger note collection.
- [ ] Sync with encryption enabled.
- [ ] Test on an Android 14 emulator.
- [ ] Test with a release version of Joplin.

</details>

The attached log contains `Error: RNFetchBlob request error: Unexpected char 0x131 at 10 in header name: dropbox-apı-argnull`, where the `ı` in `dropbox-apı-argnull` is a [dotless i](https://en.wikipedia.org/wiki/Dotless_I) character. I suspect that this should be an ASCII `i`. As such, I think that this issue is related to localization-related logic.

A GitHub [code search for `/dropbox-apı/`](https://github.com/search?q=repo%3Alaurent22%2Fjoplin%20%2Fdropbox-ap%C4%B1%2F&type=code) in Joplin's code, however, returns zero results.

Follow-up questions:
- What display language is the Android device set to globally?
- What display language is Joplin set to (if different)?

**Comment by parduspanteri** [comment]
Tablet and joplin app in turkish language.

**Comment by personalizedrefrigerator** [comment]
Upstream issue: https://github.com/joltup/rn-fetch-blob/issues/573.

We likely need to either switch to a fork of `rn-fetch-blob` or patch `rn-fetch-blob` to work around the issue. The upstream issue recommends switching to [`react-native-blob-util`](https://github.com/RonRadtke/react-native-blob-util).

Joplin previously migrated to [`react-native-blob-util` in this commit](https://github.com/laurent22/joplin/commit/b023f58497b7ab94516b0c66293e3fbb794409c1), but was [migrated back to `rn-fetch-blob` in this commit](https://github.com/laurent22/joplin/commit/e149e4b5fd6267acc82020a486631bc6db371422) to fix the sync issues [reported in this forum post](https://discourse.joplinapp.org/t/the-latest-ios-version-of-joplin-12-11-2-works-weird/31045). 

**Edit 1**: Reworded for clarity.
**Edit 2**: The upstream commit in the `react-native-blob-util` fork that fixes the issue seems to be https://github.com/RonRadtke/react-native-blob-util/commit/46876cb9c10a111631f4a6c497867af16a0d1e82.

**Comment by parduspanteri** [comment]
> Upstream issue: [joltup/rn-fetch-blob#573](https://github.com/joltup/rn-fetch-blob/issues/573).
> 
> We likely need to either switch to a fork of `rn-fetch-blob` or patch `rn-fetch-blob` to work around the issue. The upstream issue recommends switching to [`react-native-blob-util`](https://github.com/RonRadtke/react-native-blob-util).
> 
> Joplin previously migrated to [`react-native-blob-util` in this commit](https://github.com/laurent22/joplin/commit/b023f58497b7ab94516b0c66293e3fbb794409c1), but was [migrated back to `rn-fetch-blob` in this commit](https://github.com/laurent22/joplin/commit/e149e4b5fd6267acc82020a486631bc6db371422) to fix the sync issues [reported in this forum post](https://discourse.joplinapp.org/t/the-latest-ios-version-of-joplin-12-11-2-works-weird/31045).
> 
> **Edit 1**: Reworded for clarity. **Edit 2**: The upstream commit in the `react-native-blob-util` fork that fixes the issue seems to be [RonRadtke/react-native-blob-util@46876cb](https://github.com/RonRadtke/react-native-blob-util/commit/46876cb9c10a111631f4a6c497867af16a0d1e82).

Based on what is described here, when I changed the language of the tablet to English and entered the joplin app, the synchronization worked. Then when I switched back to Turkish, the synchronization continued to work. The problem was temporarily solved. But this bug from 2020 still seems to continuing.Thank you for your help.
