### ISSUE TITLE
[Feature Request] Note Sharing

### ISSUE THREAD

**Issue by trymeouteh** [laurent22/joplin#1085]
The encryption option is great which allows notes to be secure when stored on a cloud but it Joplin lacks note sharing which is a handy feature in apps such as Google Keep, Evernote and Turtl. Joplin is a self hosted note app and a way to share notes would be to use Syncthing or cloud storage with a shared folder. I think Joplin should add the following to make this a reality.

1. Encrypted Notes and Notebooks - Keep the default encryption setting but have excluded notes use a separate password which can be shared with friends to access the notes. Consider it to kinda work like PGP keys in encrypted emails.

2. Note Permissions. If you want to share a note to friends but not have the note deleted, edited, encryption changed have a admin password that is required to make such changes.

**Comment by mbiebl** [comment]
This would be a really neat feature, but I guess this will be tricky, unless sharing happens via the same backend. E.g. notes are stored on dropbox and userA and userB both have joplin configured with dropbox as backend.
Or userA and userB use the same nextcloud instance. In this case sharing seems doable.

**Comment by trymeouteh** [comment]
I will be tricky when it comes to sharing the notes with others but Joplin doesn't have to worry about that. All Joplin needs to do is allow certain notes and notebooks to be encrypted with separate passwords. This way you can encrypted a single note or a notebook and share that password with other users.

Also what will be needed is a way to ensure that there is a admin to the note who can change the note password so other peers cannot change the password making it unable to decrypt by others.

**Comment by trymeouteh** [comment]
A suggestion for having a admin to have the ability to modify the note permissions would be to have a admin password. This password will not decrypt the note but only this password will determine who can change the note password itself. Essentially if you want to change the note password a special password is required to do so.

**Comment by ReekyMarko** [comment]
I've also thought about this. But more in the context of shared notebooks that can be edited by multiple individuals. In my workflow it would just mean sharing the folder on Syncthing but I can imagine it might be a problem if people are using different backends

**Comment by bernd-wechner** [comment]
This is the one feature missing from Joplin that would make it replace almost every similar tool me and my family use. At the moment only I use it. The minute I want to keep a note that I share with my wife, I'm on Wunderlist right now. But to be really useful in a broader context an app like Joplin needs good sharing options. 

Most apps that support this do it with accounts and a single central repo for the notes and such. Joplin of course support numerous synchronization backends, NextCloud, and others.  I guess one solution is configure our clients to use the same backend. The draw back is that ALL the notes would be shared. 

Correct me if I'm wrong.

If so, there could be a number of approaches to sharing. The simplest which would work for regular sharing partners is perhaps of under General options/Synchronisation where I currently specify one service that we configure the same one but that notes in that repo have owners and permissions based on a Joplin security layer on top of the webdav one. That would need sharing users to be using the same synchronization service (and is how I suspect most apps do this).

Any shared note needs to be shared with "someone" and they need to be identified. Common method is email. So they'd get an email I guess (Wunderlist works this way) and in it a link to get the shared note synched to their instance).  But the mechanics of that would be open (note specific sync services?).

I guess the challenge of doing this across diverse backends is what's kept it unimplemented. Alas until it happens Jolpin loses a large market of prospective users, those that have sharing needs. I love the rest of it! And that I can host my back end privately.  But I need to share with family and so they are stuck using Wunderlist with me for now.

**Comment by lord-aerion** [comment]
For me too this is the one missing feature from Joplin.

I use Syncthing to sync Joplin notes between 3 devices. Would it be possible to configure a separate sync path per notebook/note that is to be shared? I could then create a separate sync task in Syncthing. This approach could in theory also work for those using Dropbox or other sync solutions.

**Comment by foxmask** [comment]
> For me too this is the one missing feature from Joplin.
> 
> I use Syncthing to sync Joplin notes between 3 devices. Would it be possible to configure a separate sync path per notebook/note that is to be shared? I could then create a separate sync task in Syncthing. This approach could in theory also work for those using Dropbox or other sync solutions.

if I had to share I will export the note to Dropbox (for example) then share the file from here.

**Comment by SteveHolle** [comment]
I have been using syncthing to sync three devices, two PC's and one Android phone.  Everything started out great and the two PC's are remaining in sync perfectly.  My problem is the Android notebook and note structure has slowly disintegrated so that notes wind up in the wrong notebook and the structure is becoming more random as time goes by.  Is there any way to get the Android Joplin back in sync without starting from scratch?  It seems that when a note is moved on the PC's Android doesn't track that change.

Any ideas?  Not a fan of Dropbox since they changed their device policy.

Thanks

**Comment by bernd-wechner** [comment]
> if I had to share I will export the note to Dropbox (for example) then share the file from here.

This is a workaround not a solution. I am hoping some day to replace Wunderlist with Jolin. But no can do until my family members can and I can all look at one TODO list and add items, check them off etc. so we need to be able to share a notebook, so that when an item is added, others can see it, when an item is checked done, others can see it.  This is a central feature for apps like Wunderlist and Evernote to be honest. Joplin is by far the most hopeful replacement for them all just needs this kind of sharing.

Non trivial to implement but not the end of the world. As I see it would need account management somehow that Joplin lacks at the moment.

It needs for Joplin instances to be able to find one another. So I can right click on a notebook and click Share ... and enter an email address and they get an email with instructions on how to install Joplin on their phone or PC and when they do in their Joplin instance they see an incoming share request which they can accept and then it syncs with their client. 

So the shared notebook has to have a cloud address (and Joplin supports numerous options there so this may only be available for a subset of them) and that cloud system needs support for sharing that Joplin can configure if it has a login to that cloud system configured under Tools>Options>Synchronisation.

It needs a little thought and design basically.

And a new Joplin instance newly installed or preexisting needs somehow to receive the share request.  Which also needs some thought an design given the diversity of clients back end cloud systems they support. And again this may in the first instance only work with with some backends, and if they provide a share link, then the email the recipient has might have that link in it for them to click which NextCloud, DropBox or OneDrive manage and gives someone shared access to the file or folder that represents the notebook etc ... 

There seem at least two layers there and it may not work with Filesystem or WebDav, don't know.

What I do know is, Sharing would take Joplin to the next level of world dominance.

**Comment by lord-aerion** [comment]
> > if I had to share I will export the note to Dropbox (for example) then share the file from here.
> 
> This is a workaround not a solution. I am hoping some day to replace Wunderlist with Jolin. But no can do until my family members can and I can all look at one TODO list and add items, check them off etc.

Speaking of workarounds, have you thought about using Etesync together with OpenTasks (confusingly just called Tasks on F-Droid)? Fully end-to-end encrypted synchronisation of both contacts, calendar, and tasks.

**Comment by HannesOberreiter** [comment]
My workaround is atm. a "group" Account on nextcloud,  which is used by all group members for syncing of Joplin.

Now I face the problem, that I also want to use it private. Therefore, I would need two instances of the app. 

A way would be to allow multiple sync accounts, this don't solve easy sharing but would allow multiple shared instances.

Cheers
Hannes

**Comment by darkdebo** [comment]
Can I get chance to work on it...

**Comment by lord-aerion** [comment]
Note sharing is still a much desired feature, please keep this open.

**Comment by Rustymage** [comment]
I'd love to see this - one of the main reasons I haven't moved fully across.

**Comment by bernd-wechner** [comment]
Not fixed and highly desired.

**Comment by alexpovel** [comment]
Also expressing interest in this.

Joplin is great and I love using it.

I had moved my WebDAV destination to a Nextcloud instance now and in the process removed encryption. I thought this was the reason sharing via [Rightclick on Note -> Share note... -> Get Shareable Link](https://discourse.joplinapp.org/t/share-note-feature/8511) fails (also fails for me with `Unsupported WebDAV URL format:`).

Nextcloud can render Markdown. So if that sharing functionality gave a URL to a Markdown file based on the WebDAV URL (if that is a Nextcloud destination), that could work neatly?

**Comment by frankhommers** [comment]
I am missing this too in order to make a full switch.

**Comment by betsythefc** [comment]
I think note sharing would be best accomplished by setting a different save path for notebooks, including different encryption settings, and that location would be shared among those you want to share it with. Say a separate syncthing folder, or a dropbox folder or something.

**Comment by heurihermilab** [comment]
I have a not-dissimilar use case where I would like to sync/encrypt some but not all notebooks across multiple devices (including desktop).

The aim would be to share only some notebooks with resource-constrained mobile devices while enabling the full collection of notebooks to be accessible on a desktop.

**Comment by rangulicon** [comment]
This is the one feature I need to make the switch to Joplin. Is there a plan to get this feature implemented? I understand security and reliability are imperative for this feature, but it would be great to know if this is actually a feature under development.

I can think of 3 ways to make this work.

1.  Integrate with Cloud Storage APIs to share notes natively on the platform they are stored
- Doesn't seem feasible, but is definitely doable
- Subject to availability of APIs
- Could break if Cloud Provider APIs are changed

2. Native Joplin Sync/Share Server that handles the encryption, sync, edits, and other mechanisms required
- Would take a significant amount of work
- Ability to maintain security and performance inhouse
- No reliance on a 3rd party

3. Interface with a 3rd party solution for Sync, Share, Encryption, and other mechanisms required
- Requires reliance on 3rd party software integration for security and reliability
- Possibility for 3rd party to abandon development
- Changes to 3rd party solution could break the integration


It would be ideal to have both public and private notes.

**Public Notes**
- Public notes would be readable and/or writeable by anyone with a link
- You could set an expiration date on these to easily remove them as shared after the specified time

**Private Notes**
- Private Notes would allow for multiple mechanisms to secure them
- PGP Encryption seems like an obvious way to go as this is the defacto Encryption

**Comment by mc0e** [comment]
This is still a highly desirable feature - keep this open

**Comment by mc0e** [comment]
I think @rangulicon is on the right track here in identifying the sort of options available.

Being independent of the storage engine is a significant feature of Joplin, which would be lost if we base synchronisation on smart server-side processes.

Basing synchronisation on shared access to the underlying storage would mean that sharing one note requires giving the other party the ability to mess up everything that is stored.

Clients could perhaps handle synchronisation themselves given some sort of client-to-client messaging system.  
 * Messages would pass update data, and either locking messages, or conflict resolution ones.
 * The messaging system would presumably have to be asynchronous, so messages would go via some sort of server, but the requirement of that server could be quite generic.  It's probably necessary to know that all messages are delivered and processed in order, but otherwise this could be pretty independent of implementation layers.

**Comment by lord-aerion** [comment]
Would it not be possible to leverage Syncthing for this, in the same way that DecSync does for RSS, contacts, and calendars? 

Even a simple folder share achieves this, a suggestion I've made before. Due to other frustrations with Joplin (cough…. auto save… cough) I've (hopefully temporarily) switched over to Markor, which stores notes in a simple folder structure. Any note or collection of notes I wish to share I save in a different folder, set up a new Syncthing share, and job done.

Private, secure, serverless, no reliance on third party integration efforts and/or ongoing support. Also no risk of breakage as a result of upstream changes as it's filesystem based synchronization. Unless Syncthing as a whole gets abandoned, of course.

The only downside is that Syncthing doesn't work on iOS, but that doesn't affect me personally.

**Comment by betsythefc** [comment]
Although it would be nice to have Joplin store notes using the filesystem for structure, I think if we can define secondary sync locations for a notebook, and set default encryption settings for that secondary sync location, then it can be up to us to organize, and share that out as we want.

In Settings > Synchronize, click a button that says "Add directory to sync", and enter the absolute path. Under Settings > Encryption > Master Keys, use check boxes or something to select which directories to use which encryption keys, including one call "All" that would be the default master key.

**Comment by betsythefc** [comment]
I think the way I've thought it up would be the least work for developers to implement, and give basic notebook level sharing to the application. It can later be hashed up to do note level sharing.

**Comment by alexanderadam** [comment]
Hi Stalebot 👋

**Comment by flier268** [comment]
Or, could i publish notes to github, just like Gitnote?

**Comment by Rustymage** [comment]
Bad bot.

**Comment by tasn** [comment]
I think this (and more) can be solved by adding an [Etebase](https://www.etebase.com) backend to Joplin. Etebase is an open-source SDK and backend for building end-to-end encrypted applications. It supports sharing and a lot of other things and has an easy to use TypeScript library.

Etebase is also used in [EteSync](https://www.etesync.com), Tasks.org, GNOME, KDE and a few other apps, so it's battle-tested and cross-platform, so should be a great fit for Joplin. Also, a lot of users already reached out to us about using Etebase in Joplin (which is how I got here), so I think users will like the change. :)

Website: https://www.etebase.com
Docs: https://docs.etebase.com

Note: I'm the developer behind Etebase and EteSync

**Comment by rangulicon** [comment]
It looks like the work for this is already underway, per the post [here](https://www.patreon.com/posts/joplin-server-is-45843886) on the maintainer's Patreon page and in the forums [here](https://discourse.joplinapp.org/t/joplin-server-pre-release-is-now-available/13605). 

@laurent22 is there any way progress can be tracked in Github to reflect the actual status of the features planned for the newest versions of Joplin/Server 1.6? There are so many open issues that have little to no indication of progress it's hard to know what is happening with them all. Thank you, your hard work is greatly appreciated.

**Comment by szul** [comment]
The other option would be to simply allow specified synchronization where you can add multiple external synchronization accounts (e.g., Dropbox, OneDrive), but specify which notes are synced to which service. Then the sharing becomes a matter of sharing the file on the cloud service instead of inside Joplin.

**Comment by Rustymage** [comment]
Bad bot - go to the corner and think about what you've done!

**Comment by bernd-wechner** [comment]
Yeah stale bot, you should got to the naughty corner and not flag it as stale but flag it with drums and whistles to attract attention, it needs someone to develop it! it's the one thing that prevents Joplin from ruling the roost of all note takers I've ever seen. If only I could roll it out in my family with shared notes like shopping lists and such the way w can with MS-Todo (which was Wunderlist until MS bought them out) or Evernote.

**Comment by bernd-wechner** [comment]
The server looks awesome: https://github.com/laurent22/joplin/tree/dev/packages/server

But some notes on its status (stability and safety) and how to install and run it with and without docker would be nice. It looks like the awesomest of Joplin improvements imaginable! When done this will propel Joplin from a geeks favourite notetaker to broad community use I predict. I can finally drop MS Todo and ask my family to install Joplin (presuming that it runs on their iPhones and Macs, I as the family geek use Android and Linux of course and Windows perforce professionally and Joplin rocks on those last three I know!)

**Comment by dangerfish96** [comment]
Hi, I just wanted to say that this project is awesome!!
Particularly this feature would make it even better. 
Thank you very much!

**Comment by betsythefc** [comment]
What is the current implementation idea for this? It's been suggested that specifying different sync paths for different notebooks (my preference), and various syncing protocols (etebase, big fan here). Is there work towards one going on?

**Comment by rangulicon** [comment]
> What is the current implementation idea for this? It's been suggested that specifying different sync paths for different notebooks (my preference), and various syncing protocols (etebase, big fan here). Is there work towards one going on?

This is being implemented within the context of Joplin Server. Details can be found in my comment from a few months ago here: https://github.com/laurent22/joplin/issues/1085#issuecomment-755109197

**Comment by betsythefc** [comment]
Awesome, thank you!

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by bernd-wechner** [comment]
Importantly the Server is here: https://github.com/laurent22/joplin/blob/dev/packages/server/README.md

And I'm still hoping to see instructions for installing it without docker at some point. I don't mind docker per se, but I don't like it as the only option. On a dedicated server say, like a Rpi dedicated to the job, I wouldn't want that extra layer per se, but that aside it's very nice to have the dependencies listed and understood as well not behind smoke and mirrors (docker, which is an awesome way of keeping the dependencies contained and up to date).

**Comment by roman-r-m** [comment]
> And I'm still hoping to see instructions for installing it without docker at some point.

I think you can do it by manually executing steps from Dockerfile; skipping some of them like creating new users, etc.

**Comment by solar-core** [comment]
Yes, it would be nice to have this feature

**Comment by vith** [comment]
.

**Comment by laurent22** [comment]
This is now implemented in Joplin Server. The doc for now is not quite up to date but it will be soon.

**Comment by lestephane** [comment]
I'm a bit late to the party here, but I wonder if there is a Joplin way to do what I want (sharing a subset of notes with myself in a different context, with a different encryption key)

- There is one Joplin Cloud billing user, me (joplin-cloud-user).

- There is one linux user account 'personal' with joplin app synced to joplin-cloud-user account, using a Joplin notebook / note namespace for personal notes with one encryption key (pk)

- There is one other user linux account 'work-customer1' with joplin app synced to joplin-cloud-user account, using a Joplin notebook / note namespace for customer work notes with another encryption key (cust1k).
- When I use the joplin app in 'personal' all notes from 'work-customer1' look garbled/locked or don't show up at all (If I open/sync only the personal notebook / note namespace).
- When I use the joplin app in 'work-customer1' all notes from 'personal' look garbled/locked or don't show up at all (If I open/sync only the work-customer1 notebook / note namespace).

Keep in mind I'm not a Joplin user at all, just asking whether this use case is at all on the radar.
There is only one user, but multiple encryption keys, and multiple subviews of the same note tree, one for each encryption key.
Segregate all the things on a need to know basis.
