### ISSUE TITLE
Blank screen when searching for a note and switching phone off and on again

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#11197]
- Search for a note
- Open the note
- Switch off your phone
- Switch it on again

=> The app is just a blank screen with a blank header and a "Back" arrow. Clicking on the Back arrow brings back to the Search screen

**Also:**

- Search for a note
- Open the note
- Edit it
- Attach an image

=> Back to the blank screen and the image has not been attached

On Android, v3.1.6

**Comment by laurent22** [comment]
@personalizedrefrigerator, I suspect it's related to this bug: https://github.com/laurent22/joplin/issues/11195 Not critical but would be good to check if there's an easy fix

**Comment by personalizedrefrigerator** [comment]
I haven't been able to reproduce this locally, though I'm testing with the Joplin build currently on my device (a custom branch based slightly before 3.1.5). Could this be related to the biometric lock/unlock feature?

**Edit**: I've also tested on  iOS, Joplin 13.1.5  and haven't been able to reproduce this.

**Comment by laurent22** [comment]
It does it without biometric lock too. When I switch the phone back on, the note is displayed for a short time then it disappear and this blank screen + header is displayed instead. It's just a massive issue though, since it's possible to go back to the note by pressing the back arrow and selecting the note again

**Comment by laurent22** [comment]
> I haven't been able to reproduce this locally, though I'm testing with the Joplin build currently on my device (a custom branch based slightly before 3.1.5). Could this be related to the biometric lock/unlock feature?
> 
> **Edit**: I've also tested on iOS 13.1.5 and haven't been able to reproduce this.

I can still reproduce it in 3.1.6 Android. More annoying is that it also does this when attaching an image to a note, and in that case it doesn't actually attach anything (which makes it impossible to attach an image on a searched note). I've updated the issue with this info.

**Comment by personalizedrefrigerator** [comment]
I can now reproduce this on an Android API 35 emulator. Steps to reproduce:
1. Ensure that there are at least two folders.
2. Create a note, "Test note" in one of the folders.
3. Switch to a different folder. (Important!)
4. Search for "Test note".
5. Open the note created in step 2.
6. Turn off the phone.
7. Turn on the phone.

**Comment by personalizedrefrigerator** [comment]
Here's what seems to be happening:
1. As the user turns off the device, `Notes.tsx` [recomputes the set of available notes.](https://github.com/laurent22/joplin/blob/a62e35c123d7e6be517d51895ffdb97f2743bc2e/packages/app-mobile/components/screens/Notes.tsx#L151)
   - `notesParentType` is `Folder` (possible bug?), so `Notes.tsx` [fetches all notes in `selectedFolderId`](https://github.com/laurent22/joplin/blob/a62e35c123d7e6be517d51895ffdb97f2743bc2e/packages/app-mobile/components/screens/Notes.tsx#L173).
3. `Notes.tsx` [dispatches `NOTE_UPDATE_ALL`](https://github.com/laurent22/joplin/blob/a62e35c123d7e6be517d51895ffdb97f2743bc2e/packages/app-mobile/components/screens/Notes.tsx#L181) with the selected notes.
4. `reducer.tsx` [updates `draft.notes`](https://github.com/laurent22/joplin/blob/a62e35c123d7e6be517d51895ffdb97f2743bc2e/packages/lib/reducer.ts#L944) and calls [`updateSelectedNotesFromExistingNotes`](https://github.com/laurent22/joplin/blob/a62e35c123d7e6be517d51895ffdb97f2743bc2e/packages/lib/reducer.ts#L511).
5. `updateSelectedNotesFromExistingNotes` observes that no `selectedNoteIds` are in `draft.notes` and sets `selectedNoteIds` to `[]`.
6. This causes Redux to recompute the props for `NoteScreenWrapper`. In this case, because `selectedNoteIds` is `[]`, the [`noteId` prop is `null`](https://github.com/laurent22/joplin/blob/a62e35c123d7e6be517d51895ffdb97f2743bc2e/packages/app-mobile/components/screens/Note.tsx#L1659).
7. This causes the `Note` screen to render an empty title/body.
