### ISSUE TITLE
"Open with" is broken when opening a note from search

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#11195]
- Search for a note that contains an image
- Open the note
- Long press on the image and select "Open with"

=> The screen is now empty with just the heading bar at the top

Not sure if it's a regression. If it is we should try to fix it for 3.1

**Comment by personalizedrefrigerator** [comment]
More information might be helpful. From a quick test on the current build on my Android device (from a custom branch, 0fafec5e3), I haven't been able to reproduce the issue.

- Is this on Android?
- Is this with v3.1.4 or a build from the latest `dev`? (v3.1.4 had a search screen bug which has since been fixed).
- Is the note long (has scroll)?
   - I was testing with a note that isn't long enough to scroll.

**Comment by laurent22** [comment]
It's on Android, 3.1.4. I'm going to build a new version so I'll test then. Maybe it's indeed been fixed by that other fix you mention. And the note was long enough to scroll

**Comment by laurent22** [comment]
Yes it is fixed in 3.1.5, thank you!
