### ISSUE TITLE
Problem with appimage on Ubuntu 24.04

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#11251]
### Operating system

Linux

### Joplin version

3.*

### Current behaviour

[50232:1024/134236.818463:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_JoplinLrPHrP/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
![Screenshot_20241024_134625](https://github.com/user-attachments/assets/d9f05173-143d-4a1a-aa3f-f057d2133ec0)

It's not work on every version of Joplin AppImage.
Another programms as Telegram, Obsidian and others are opened and works fine without that bug with SUID

### Expected behaviour

Opened it in window.

**Comment by LFd3v** [comment]
Hi, there. This is a [known problem with Electron AppImages](https://authmane512.medium.com/solve-the-suid-sandbox-helper-binary-was-found-but-is-not-configured-correctly-3-solutions-4f1425a9a76c), one solution is to run it with `--no-sandbox` flag. As far as I know, Telegram does not use Electron, that is why there is no error.

**Comment by ghost** [comment]
> Hi, there. This is a [known problem with Electron AppImages](https://authmane512.medium.com/solve-the-suid-sandbox-helper-binary-was-found-but-is-not-configured-correctly-3-solutions-4f1425a9a76c), one solution is to run it with `--no-sandbox` flag. As far as I know, Telegram does not use Electron, that is why there is no error.

Hey, but before 24.04 ubuntu, it was working fine. What happened now?

**Comment by LFd3v** [comment]
@alexander-lamdan I cannot answer this since I was not using the Joplin AppImage on Ubuntu before 24.04 and then upgraded to 24.04. Some possible explanations:

- the .desktop file used to have `--no-sandbox` parameter (see [install script](https://github.com/laurent22/joplin/blob/84d0b1f080f010ebd57c38b4f74d66eaa37726cf/Joplin_install_and_update.sh#L210C4-L235C3)) but not anymore;
- different kernel with settings that would make `--no-sandbox` not necessary (see below);
- you had `kernel.unprivileged_userns_clone=1` configured because you had `docker` installed or some other reason (this makes `--no-sandbox` not necessary).

**Comment by JGCarroll** [comment]
Debian had always disabled this functionality by default and Ubuntu has followed suite since 23.10 but uses AppArmor to allow some apps to bypass have exceptions. When an app is installed as a native package, the app can add an AppArmor exception for itself. The AppImage cannot do this and thus requires the functionality to be disabled or for the app to avoid using it. Some apps have some special bypasses for being commonly known even if they're not necessarily designed to set this up themselves.

You can turn off the security policy permamently, but the position from the community, even outside of Ubuntu, and paraphrasing from Linus himself, is that unprivileged user namespaces are a mistake that we now have to deal with, and cause more security problems than they fix.

Of course, that's from a general ecosystem POV. If you know and trust the apps on your computer, you can turn this security off. However, the opinions of people smarter than me is it's off for good reason, and that from a good practise POV, AppImages can't be trusted to have it because only admin installed software can.

**Comment by robwestwood** [comment]
I had this problem on KDE Neon (an ubuntu-derived distribution). I manually added --no-sandbox to the parameters in the application .desktop file.

The installation script doesn't pick it up as being an-ubuntu derived distribution because of the output of lsb_release on Neon:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Neon
Description:    KDE neon 6.2
Release:        24.04
Codename:       noble
```

Would suggest using the ID or ID_LIKE fields on /etc/os-release (if present) or /usr/lib/os-release files, before falling back to lsb_release to enable derived distributions to be identified more robustly. In particular, this would identify Linux Mint as being debian-derived (`ID_LIKE=debian`).

Happy to write a PR if this approach is considered goof.

**Comment by brlin-tw** [comment]
I want to share my solution that should be somewhat safer than simply disabling the entire security feature:

1. Create a `/etc/apparmor.d/appimage.joplin` file _as root_, with the following content:

    ```apparmor
    # Allow Joplin AppImages to run without AppArmor unprivileged user namespace restrictions
    abi <abi/4.0>,
    include <tunables/global>

    profile appimage.cursor /**/Joplin-*.AppImage  flags=(unconfined) {
    userns,

    # Site-specific additions and overrides. See local/README for details.
    include if exists <local/appimage.joplin>
    }
    ```

1. Run the following command _as root_ to load the `appimage.joplin` AppArmor profile:

    ```bash
    apparmor_parser -r /etc/apparmor.d/appimage.joplin
    ```

1. Verify the result.

**Comment by ghost** [comment]
Thanks friends for answering, I close this issue. It's not relevant, because I switch to deb package.
