### ISSUE TITLE
Plus Icon disappeared

### ISSUE THREAD

**Issue by ErwinH1** [laurent22/joplin#11276]
### Operating system

Android

### Joplin version

3.0.8

### Current behaviour

GrapheneOS, based on Android 15
Joplin 3.0.8

Note: I installed Joplin from Aurora-store, which caused no problem for the app to work fine for more than a year. 

Recently the Plus Icon (to create new notes) has disappeared. I do not know exactly how long ago the icon was still there, but it must have been not more than two weeks ago. 

I tried switching to another notebook, then closing the app and restarting it, but it didn't help. 

### Expected behaviour

To display the icon

**Comment by Garbulix** [comment]
I have the same issue for version 3.1.6 installed from Droid-ify (so from F-Droid repo). Also GrapheneOS based on Android 15. Exploit protection compatibility mode is enabled. Wiping app storage nor reinstalling the app doesn't solve the issue.

**Comment by Garbulix** [comment]
Because we have other Joplin versions, I guess this problem is related with Android and its upgrade to 15.

It looks like this plus button is somehow hidden "below" the screen as when I switch from navigating using 3 buttons (which I used until now) to navigating using gestures, I found its small fragment. It's hard to touch it but its possible and then submenu appears as expected. When I close this plus submenu, the button comes back to its initial place (still shows incorrectly).

![ResizedImage_2024-10-30_14-41-59_1380.png](https://github.com/user-attachments/assets/d4133356-97ad-4eff-a0f9-673749d9828f)

![ResizedImage_2024-10-30_14-41-15_6049.png](https://github.com/user-attachments/assets/103ba40c-4fbb-48e9-af6d-6ae7c2b7c9a2)

**Comment by tomasz1986** [comment]
Probably related: https://developer.android.com/reference/android/R.attr#windowOptOutEdgeToEdgeEnforcement

**Comment by Garbulix** [comment]
What's also interesting to me is that the icon to edit content of the note when you are in note view is displayed correctly.

![Screenshot_20241101-195056.png](https://github.com/user-attachments/assets/919bbe66-4981-43b3-8d2c-ddadfe7e317a)
