### ISSUE TITLE
iOS: Crash while opening new note or task

### ISSUE THREAD

**Issue by boumboumboum** [laurent22/joplin#11338]
### Operating system

iOS

### Joplin version

13.1.6

### Current behaviour

1. Open new note
2. Screen all white/black, no response
![IMG_3239](https://github.com/user-attachments/assets/aebcb73b-80ce-47fb-8c2a-51732cc4e867)
![IMG_3240](https://github.com/user-attachments/assets/ad756cc3-0e00-4fad-911f-0f2361145148)

### Expected behaviour

maybe fix the bug or tell me what to do?

### Logs

[mobile-log.log](https://github.com/user-attachments/files/17669783/mobile-log.log)

**Comment by personalizedrefrigerator** [comment]
Thank you for reporting this!

I'm linking to a similar issue: https://github.com/laurent22/joplin/issues/11325. If the issues have the same cause, this may be fixed by [this pull request](https://github.com/laurent22/joplin/pull/11326).

Additional information:
- Does duplicating notes by long-pressing, then clicking "duplicate" still work?
- Is this with Joplin Cloud as the sync target?

**Comment by boumboumboum** [comment]
thanks for your response!

Does duplicating notes by long-pressing, then clicking "duplicate" still work?

yes.

Is this with Joplin Cloud as the sync target?

yes.

**Comment by personalizedrefrigerator** [comment]
Thank you for the information! Based on it, this issue seems likely to be the same as https://github.com/laurent22/joplin/issues/11325.

A [fix](https://github.com/laurent22/joplin/pull/11326) for #11325 has just been merged. Note that, as of the time of this writing, the fix hasn't yet been included in a release of Joplin for iOS.
