### ISSUE TITLE
Inaccessible Backward Navigation in Note List Using Shift+Tab

### ISSUE THREAD

**Issue by RafaelFernandesBR** [laurent22/joplin#11443]
### Operating system

Windows

### Joplin version

3.1.24

### Desktop version info

Joplin 3.1.24 (prod, win32)

ID do cliente: ecdb6b3128d549d29e46c9f0743a3b09
Versão Sync: 3
Versão do Perfil: 47
Keychain Suportada: Sim

Revisão: d581264

Backup: 1.4.2
Describe image: 1.7.0

### Current behaviour

When focusing on the list of notes, either using the Ctrl+Shift+L command or manually with a screen reader, it is not possible to return to the interface using Shift+Tab.

Steps to reproduce:

1. Focus on the list of notes using the shortcut or manually.  
2. Press Shift+Tab to exit the note list and navigate to the "Reverse sort order" button.  
3. Observe that it is not possible to return to the interface from the list. Navigation is only possible by moving forward with the Tab key.

### Expected behaviour

Make it possible to exit the notes list normally, without blocking the interface. Both forward and backward (tab and shift+tab).

**Comment by personalizedrefrigerator** [comment]
Thank you for reporting this!

I've opened a [pull request](https://github.com/laurent22/joplin/pull/11446) that removes these focus overrides. Prior to the pull request:
- <kbd>shift</kbd>-<kbd>tab</kbd> from the **note list** maps to jump to the **notebook list** (even if the notebook list was hidden).
- <kbd>tab</kbd> from the **notebook list** maps to "jump to the **note list**" (even if the note list was hidden). 

The linked pull request removes these mappings and replaces them with <kbd>shift</kbd>-<kbd>enter</kbd> and <kbd>enter</kbd>, respectively. <kbd>Enter</kbd> was selected in part because it's similar to the keybindings in Visual Studio Code &mdash; in that application, pressing <kbd>enter</kbd> moves focus from the folder list to the editor. However, VSCode doesn't seem to have an equivalent binding for <kbd>shift</kbd>-<kbd>enter</kbd>.

I'm not certain that <kbd>enter</kbd> and <kbd>shift</kbd>-<kbd>enter</kbd> are the best replacements for the old navigation behavior (or if a replacement is even necessary). Feedback on this would be welcome.
