### ISSUE TITLE
[Feature Request] Automatically download external pictures

### ISSUE THREAD

**Issue by gorgobacka** [laurent22/joplin#1205]
Story: I really like the Web Clipper. However, sometime a images can not be downloaded correctly and I need to replace/adjust the urls by myself in the note.

Therefore, it would be great, if there would be a function to automatically download external images and replace them in the note. It would also be useful while manually entering a note without using the Web Clipper.

**Comment by dayfuaim** [comment]
I'll add my 5 cents. ;)
IMHO it could be very usable that Web Clipper would insert "normal" image URLs, i.e. `![](https://cdn-images-1.medium.com/max/1600/1*JyVlvqwsCBYl2FuvPFVRZQ.png)` instead of `![](:/9f277d16821c40098206e3ee72292a62)`.
It _will_ make notes more portable. Because if I'd like to share it I'll just copy-paste it – that's it.

**Comment by laurent22** [comment]
Closing as the way images are imported have been improved since then. If it doesn't work on a page, please post the URL.
