### ISSUE TITLE
GNU/Linux Desktop Changelog Dialog Too Long

### ISSUE THREAD

**Issue by lehitoskin** [laurent22/joplin#1222]
### Operating system

- GNU/Linux

### Application

- Desktop

Clicking "Check for updates" on GNU/Linux Desktop brought up a changelog dialog box that is way too long and goes off the edge of the screen. The Changelog needs to be a proper size and if there's too much text, either be able to scroll or truncate after a certain number of lines and say something like "View the full change log on GitHub".

Screenshot:
![2019-02-15-092646_779x2099_scrot](https://user-images.githubusercontent.com/2506703/52873771-a9ce2380-3104-11e9-97e3-24b01d117808.png)

* * *

To solve this, for now we'll just truncate the changelog to x characters. The log should be truncated somewhere in `checkForUpdate.js`

**Comment by virtadpt** [comment]
This.  I can't even find the button anywhere in there to download the update.

**Comment by mgrandi** [comment]
this is actually a problem on mac too, but it seems that macOS handles it nicely by cutting off the text so the buttons are visible

![screenshot_1146](https://user-images.githubusercontent.com/802786/52888388-be2c1380-3138-11e9-8819-889feccadb26.png)


the solution is probably to make it so the update notes are within a little HTML page instead of just an Alert, like things using Sparkle on mac:

![screenshot_1147](https://user-images.githubusercontent.com/802786/52888402-c5ebb800-3138-11e9-984e-d7018822b51e.png)

**Comment by mgrandi** [comment]
this is still an issue yes
