### ISSUE TITLE
Not syncing with mac & dropbox

### ISSUE THREAD

**Issue by krambra** [laurent22/joplin#1263]
### Operating system
- macOS
- iOS

### Application
- Desktop
- Mobile

I'm syncing with a dropbox folder.
Mobile works, no issue.
Desktop will not sync. 

Under the sync button, it reads:

_Created remote items: 1
Completed: 26/02//2019 16:30
Last error: FetchError: request to https://content.dropboxapi.com/2/files/upload failed, reason: self signed certificate in certificate chain"_

It looks like plenty of people have has this issue with OneDrive and Windows, but I'm not seeing anything for mac and dropbox.

**Comment by aschuhl** [comment]
I can confirm that I also cannot sync Mac and Joplin. I am using 10.13.6 and get
 
```

Could not authorise application:
 
request to https://api.dropboxapi.com/oauth2/token failed, reason: unable to get local issuer certificate
 
Please try again.
```

**Comment by Bangarang143** [comment]
I'm running 10.14.5 and I'm also unable to complete a Dropbox sync. Same error as aschuhl.

**Comment by hckrgod** [comment]
ya i read just bout all ur post on your issue here n reading your logcat now im about to try ABD ON THIS i have had alot of success with it i will reply asap thnks  Extract the contents of this ZIP file into an easily accessible folder (such as C:\adOpen Windows explorer and browse to where you extracted the contents of this ZIP fThen open up a Command Prompt from the same directory as this ADB binary. This can be done by holding Shift and Right-clicking within the folder then click the “open command prompt here” option. (Some Windows 10 users may see “PowerShell” instead of “command prompt”.)Connect your smartphone or tablet to your computer with a USB cable. Change the USB mode to “file transfer (MTP)” mode. Some OEMs may or may not require this, but it’s best to just leave it in this mode for general compatibility.In the Command Prompt window, enter the following command to launch the ADB daemon: adb devices On your phone’s screen, you should see a prompt to allow or deny USB Debugging access      this isfor linux                                      . Naturally, you will want to grant USB Debugging access when prompted (and tap the always allow check box if you never want to see that prompt again)Extract the ZIP to an easily-accessible location (like the Desktop for example).Open a Terminal window.Enter the following command: cd /path/to/extracted/foldeThis will change the directory to where you extracted the ADB files.So for example:cd /Users/Your/Desktop/platform-tools/Connect your device to your Linux machine with your USB cable. Change the connection mode to “file transfer (MTP)” mode. This is not always necessary for every device, but it’s recommended so you don’t run into any issues.Once the Terminal is in the same folder your ADB tools are in, you can execute the following command to launch the ADB daemon: adb devi Back on your smartphone or tablet device, you’ll see a prompt asking you to allow USB debugging. Go ahead and grant it     IM CONFIGUING ABD NOW I SENT U BOTH COMMANSD FOR WINDOWW AND LINUX I IDNT KNOW HOW MUCHU KNOW ABOUT ADB BUT IF U DO JUST SCRAP IT I HAVE SOLVED ALOT OF ISSUES WITH ADB AN THE ANDROID SDK AND TOOLKIT OHH AND IN WINDOWSSOMTIMES YOU HAVE TO USE NOT ONLY QUTES IF USING POWERSHELL U HAVE TO PUT THIS  ".\adb.exe devices"  if uare using linux this lil scriot here will do it ll in seconds
wget https://dl.google.com/android/repository/platform-tools-latest-linux.zip
unzip \platform-tools-latest-linux.zip
sudo cp platform-tools/adb /usr/bin/adb
sudo cp platform-tools/fastboot /usr/bin/fastboot    ok hope it helps and 2 brains or more better than one

Sent with [ProtonMail](https://protonmail.com) Secure Email.
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
