### ISSUE TITLE
[Bug] Restart After Update

### ISSUE THREAD

**Issue by zero77** [laurent22/joplin#1270]
### Operating system

- Linux: ubuntu 18.04

### Application

- Desktop

At the moment joplin does seem to automatically update successfully but, it doesn't restart the application to use the new one.
So, although you have the new one installed the old one is still running.

Can you please restart joplin after each update so that the newest install is runing.
Thanks

**Comment by tessus** [comment]
You are supposed to stop an application before you upgrade it.

**Comment by zero77** [comment]
@tessus 
So just to clarify, what's recommended when updating is to first stop Joplin then run  `Joplin_install_and_update.sh` and then start it again.

**Comment by tessus** [comment]
Yes, or do you change your tires while you are driving?

As far as I know it's only possible to update Erlang programs while they are actually running (and it's only possible, if it has been incorporated into the program from the beginning).

On POSIX systems it could be possible to update the binary on disk while the program is running in memory. However, this might not always work, because the binary on disk could be locked.

Anyway, to answer your question: Yes, you should stop Joplin, upgrade it and the start it again.
If you want to automate this, you would have to check for a running Joplin process and kill it. What do you do, if you have more than one Joplin process running? (Different instances with different profiles.)
There's no problem with automating this, but it would take a lot more than just starting Joplin after the script has been run. Also, you should give people a choice and not do this by default.

**Comment by zero77** [comment]
> Yes, or do you change your tires while you are driving?

> As far as I know it's only possible to update Erlang programs while they are actually running (and it's only possible, if it has been incorporated into the program from the beginning).

> On POSIX systems it could be possible to update the binary on disk while the program is running in memory. However, this might not always work, because the binary on disk could be locked.

Yes, this makes sense, i just didn't think it through.

> What do you do, if you have more than one Joplin process running? (Different instances with different profiles.)

Other than perhaps using PID files, what do you think would be the most stable way to kill then update Joplin.

> There's no problem with automating this, but it would take a lot more than just starting Joplin after the script has been run.

What would be missing from Kill, update and then start the new Appimage.

**Comment by tessus** [comment]
> Other than perhaps using PID files, what do you think would be the most stable way to kill then update Joplin.

Joplin uses a main process and 3 or 4 helper processes. You should only kill the main process with the default signal (usually SIGTERM).

You could do something like `ps -ef |grep -e "Joplin$" |awk '{print $2}'` to get the PID. Although this command will not work for getting the PID for the main process of a Joplin instance started with additional parameters like `--profile`. In that case something like this should do the trick:
`ps -ef |grep -e "Joplin" |grep -v "Helper" |grep -v grep |awk '{print $2}'`
as in:
```
for PID in `ps -ef |grep -e "Joplin" |grep -v "Helper" |grep -v grep |awk '{print $2}'`
do
  kill $PID
done
```
It's rather the problem with restarting the Joplin processes. It won't be an issue, if only one process was running without any paramters. But if there were several processes you would have to retrieve the start parameters somehow and store them, so that you can start all the instances with the correct parameters.

> What would be missing from Kill, update and then start the new Appimage.

The kill, upgrade, and restart are the main steps, but you have to figure out all the possibilities and edge cases. (e.g. that several Joplin instances are running). Because if you want to kill all Joplin instances, you also have to restart all of them - otherwise where's the point?
Then you have to make sure that all commands you are using like `grep`, `awk`, `ps` are available and work the same way on the target platforms (which should be the case on Linux boxes).

While the idea is a simple one, the implementation can become tiresome. (If you have ever done system programming, you know that the real program might only be a few lines but will be huge at the end just to take care of all eventualities, like signal processing, cleaning up (child processes or threads), stdin and stdout filtering, ...)
