### ISSUE TITLE
[Linux, Desktop, 1.0.134] Dragging to expand notes list pane frequently pauses

### ISSUE THREAD

**Issue by cable729** [laurent22/joplin#1273]
### Operating system
* Linux

### Application
* Desktop (1.0.134 prod)

### Steps to Reproduce
1. Put mouse on divider between note list/note content or notebooks/note list
2. Click and drag, then go to the right to make the pane wider

### Expected
Pane will expand as expected

### Actual
Pane expands a little, then pauses. One must release the mouse, then restart the click and drag to expand process.

*Note:* this does not happen when resizing the pane to be smaller, and does not happen for the notebooks pane. However, resizing the notebooks pane is not smooth (read: choppy) on my computer.

**Comment by gerroon** [comment]
I am actually hating this, now I am stuck with a tiny note list pane :( It is not just glitchy (as the OP noted) but it is impossible to make with work properly on Windows 10.

**Comment by laurent22** [comment]
@gerroon, on v134?

**Comment by laurent22** [comment]
Note for dev: Use Electron `screen.getCursorScreenPoint()` to get cursor position instead of glitchy HTML drag events.

**Comment by gerroon** [comment]
Sorry I did not provide better details, I seem to be on v132

**Comment by gerroon** [comment]
Ok jus ttested v134, it is slightly better but still super glitchy.

**Comment by innocuo** [comment]
This issue is already closed, but I think it can be improved. I don't think event.nativeEvent.clientX are glitchy (at least not on MacOS).

I think the problem is that the OnDrag events don't completely catch up when you move the mouse "too fast". 

Something that works better is:
- on drag start: store initial sidebar width + initial x position
- on drag: new width =  (initial sidebar width) + (current cursor x position - initial cursor x position)

I did some testing, and the sidebar always seem to catch up to the mouse. 

Do you mind if I create a new PR for this?

**Comment by laurent22** [comment]
@innocuo, sure, if you can improve this feel free to open a PR for it.
