### ISSUE TITLE
Failed localization after update

### ISSUE THREAD

**Issue by lutz** [laurent22/joplin#1283]
### Operating system

- Windows

### Application

- Desktop

### Errors
No errors displayed in the console

After changing from version 1.0.127 to version 1.0.135, the main bar is no longer displayed in the set language.

![grafik](https://user-images.githubusercontent.com/26437097/53558959-64204a80-3b49-11e9-87d0-7b7b7fa54170.png)

**Comment by tessus** [comment]
Due to a bug in Electron (see https://github.com/electron/electron/issues/11106), the top level menu items had to prefixed with a `&`. Therefore the translations are missing and have to be adjusted.

@laurent: I updated the German translation in db1dab9293909c893b9eff91b0575844c745d174, before 1.0.135 was released. Why isn't this reflected in the build? Or is there another bug with localization and electron?

**Comment by laurent22** [comment]
Yes that PR wasn't well thought out since it affects such a visible place of the application. Next time I'll ask to batch process the po files and add a reasonable default to all the translations. @tessus, I didn't build the translations recently as I just wanted to get the last release bugs fixed. It will be in the next release.

**Comment by 772b** [comment]
> Yes that PR wasn't well thought out since it affects such a visible place of the application. Next time I'll ask to batch process the po files and add a reasonable default to all the translations. @tessus, I didn't build the translations recently as I just wanted to get the last release bugs fixed. It will be in the next release.

thank you for the v1.0.137 fixed #1282 , it's OK now,thank very much. ^_^

**Comment by tessus** [comment]
This has been fixed already. Closing.

For future reference: there a certain situations where a translation has to be re-translated. This is not a bug, but requires someone to change/improve the `.po` file.
