### ISSUE TITLE
High CPU usage - Firefox crash

### ISSUE THREAD

**Issue by N3tFX** [laurent22/joplin#1284]
### Operating system

- Linux

### Application

- Desktop

When I start Joplin with Firefox already running, Firefox freezes and CPU usage goes to 100%. I have to close Firefox to fix it.
If Joplin is already running and I open Firefox after Joplin, everything is fine.
Something is conflicting with Firefox in Linux at Joplin startup.

**Comment by N3tFX** [comment]
I just tried v1.0.140 and the problem still remains.

**Comment by N3tFX** [comment]
I tried testing it under wayland and it seems to work OK. Something is wrong in Gnome with X.

**Comment by N3tFX** [comment]
Same thing with version 1.0.142. I don't know why Joplin clashes with Firefox, but as it is Joplin desktop is unusable. It all started about three or so version before. By the way, I don't have Web Clipper extension installed in Firefox. So, technically, there shouldn't be any way for the two apps to communicate.

**Comment by laurent22** [comment]
When Firefox crashes, it should produce an error report, so I would suggest sending this to the Firefox issue tracker, and maybe also add an issue on the Electron tracker (and link to the Firefox issue).

I had a similar problem with a Qt app that was making Firefox crash before. I've opened a bug report at that time although I don't know if it's been acted on.

On Joplin side, there's nothing we can do since we don't deal with low level things like process access, shared memory, and so on.
