### ISSUE TITLE
[FEATURE REQUEST] Import .JSON notes from Vivaldi(browser)

### ISSUE THREAD

**Issue by RealDrJester** [laurent22/joplin#1308]
I believe there is no way to actually export any of Vivaldi's notes, anywhere... Even to .ENEX format. So, unfortunately I can not export all my notes to Joplin(which amounts to around 60MB). 
So, I humbly request, a feature so I can import the notes from Vivaldi. 

Thank you in advance for considering this.

**Comment by laurent22** [comment]
You could try to convert them to text files and use the "import Markdown directory" functionality in Joplin. There's a Python example there on how to convert the notes: https://forum.vivaldi.net/topic/26173/exporting-notes

**Comment by drmagnumwolf** [comment]
I did a test, both for directory and file import. It didn't work, since it creates and exports in text format(renaming it to .md) also did not work. Importing as directory, imports the folders I have set up with backups my PC creates every 2 days from my browser, but no notes, nor the directory/folder structures inside the notes. 

Thanks for the suggestion though. 

Here's a screenshot from Joplin showing the directories separating which part of the browser it gets backed up: https://i.imgur.com/BNKd8OZ.png

The following screenshots should give you a general idea of the folder structure I have, which Joplin imported, but no notes. Maybe it will be helpful, maybe not. But just in case... 
https://i.imgur.com/r6LpD2H.png
https://i.imgur.com/fVIzMX5.png
https://i.imgur.com/NYgucix.png
