### ISSUE TITLE
Corrupt data? Hung in rendering loop?

### ISSUE THREAD

**Issue by jpmv27** [laurent22/joplin#1312]
### Operating system

- Windows 10 Pro 64-bit

### Application

- Desktop 1.0.135 (Also seen earlier in 1.0.127)

### Description

This is the second time this has happened. I was simply typing some text into a note.

The application seems to be "hung" in a rendering loop. I have a video clip but can't seem to attach it here.

If I exit and re-enter the application, it goes right back into the rendering loop.

Need a way to recover.

**Comment by laurent22** [comment]
Video could be useful, could you upload it on some website like sendspace.com?

Also if you could share the actual note that is causing the loop it would really help fix that bug, which unfortunately I've never managed to replicate.

**Comment by laurent22** [comment]
If you want to fix it, you'll need to open the file database.sqlite, open the "settings" table and delete the key "activeFolderId" (or set it to a notebook ID that you know to be safe).

**Comment by jpmv27** [comment]
So, I tried something like that (deleting the offending record) the first time it happened and was unable to update the database because sqlite3 (on Linux) kept complaining the database was locked.
Will give it another try and advise.

**Comment by laurent22** [comment]
Yes that would certainly help figure out this bug. In that case, please send it directly to this address: https://raw.githubusercontent.com/laurent22/joplin/master/Assets/Adresse.png

**Comment by jpmv27** [comment]
Unfortunately (in a way), this time, after killing and restarting Joplin the problem did not recur.
Is there something I can do next time to capture the state of the application?

**Comment by laurent22** [comment]
No, other than trying to remember what you were doing that might have caused this freeze.

**Comment by jpmv27** [comment]
OK. Feel free to close and I can reopen if I run into this again

**Comment by 13s5lp** [comment]
I recently updated to v1.0.140 (Windows 7) and I'm having a similar issue. I was reluctant to create a new issue because I cant find any obvious trigger, it seems to happen pretty randomly, but I have triggered it 3 times in the past half hour or so by just randomly navigating to different notes, toggling the layout mode, etc. When it freezes, I get the following message logged hundreds of times a second in the console:

![console](https://user-images.githubusercontent.com/48759575/54686489-54c16b00-4b11-11e9-9033-4769e401e78f.png)

**Comment by 13s5lp** [comment]
I am still running into this issue daily. It seems to be related to one note in particular - most often when I click on that note straight after deleting any other note, but I can't reproduce it reliably. That note uses a lot of `[x]` / `[ ]` checkboxes, `---` horizontal rules and `<br/>` elements, although I have other notes like that which aren't causing any problems. It only happens when the layout mode is showing the editor.

It looks like this is the infinite loop that is being triggered in NoteText.jsx:
componentWillReceiveProps
scheduleReloadNote
reloadNote
AceEditor onScroll
editor_scroll
setViewerPercentScroll (dispatches "EDITOR_SCROLL_PERCENT_SET")

**Comment by jpmv27** [comment]
@laurent22 
Since at least one other person is seeing this, it seems like a legitimate issue. Should it be re-opened?

**Comment by 13s5lp** [comment]
I am still coming across this issue regularly when switching between notes. It's happening on multiple notes, so it's probably not related to any note content in particular. Usually when it happens the interface is completely frozen except for the console messages I mentioned before, but this time I noticed the viewer pane very quickly switching the scroll position between the top and the bottom of the note, over and over.
