### ISSUE TITLE
long code lines don't wrap when notes are printed

### ISSUE THREAD

**Issue by raddessi** [laurent22/joplin#1343]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop

Hi, maybe I have missed a method to do this but if I have some very long lines of

```
multi line
code syntax highlighted content
```

Is there a way to have those lines wrap when they render so that I don't have to scroll each area?

**Comment by tessus** [comment]
No, and usually one does not want to wrap code blocks.

The code block shows code as is, thus you can use pre-formatted text. Otherwise who sets the rules?
As you might have noticed, code blocks never wrap. e.g. look at Stackoverflow, github, discourse, or any other web site that allows you to use code blocks.

**Comment by tessus** [comment]
However, there's one exception. Wrapping should be enabled when printing.

Currently text is just cut off when printing code blocks. This can be a problem, because the same happens when exporting to PDF. I've been meaning to open a issue about this. Let's see if @laurent22  has some input on this.

**Comment by raddessi** [comment]
Fair enough on principle. Unfortunately I use code blocks to put bash reference commands or output, and most terminals wrap automatically so there is a lot of long output from some terminal commands, and some command strings are just plain huge :) I'll have to look for another way to store this as I don't see a good way to do it in joplin at the moment. Thanks for the feedback :)

**Comment by mmahmoudian** [comment]
@tessus in Slack it shows few first lines of a long code block and one should expand it to see the whole thing.

I personally think that it might be a good option to have as a button on the top bar of the note to toggle this collapse. In Rmarkdown they have addressed this by putting a button that can hide all the code blocks, which imho is not the best way to address this need.

**Comment by tessus** [comment]
I think @laurent22 mentioned that he added some code to wrap long code lines when printing.

This should stay open.

**Comment by bforland** [comment]
I would like to reopen this. I read through the arguments against wrapping, but I really disagree. I'm not sure exactly how everyone uses this app, but I use it for note taking and keeping track of progress with projects that I have that often require coping large bits of code or errors into a note in order to document them. I used to use Quiver, and other app but macOS exclusive before I found Joplin. I much prefer joplin, but there is a clear advantage to how Quiver handles code. Here are examples: [Quiver](https://drive.google.com/file/d/1gy5w7rPgpWLucFfxMtbgHTODraAxvHTq/view?usp=sharing); [Joplin](https://drive.google.com/file/d/1Onv26MWtTzSmMDc6xMvTUYxYLTt2oWkD/view?usp=sharing). As you can see from the Joplin example, everything isn't even visible. I have a 4k monitor and even in Viewer only full screen, I can't view it all. At least having an option in the settings to turn it on/off would be nice for the people that clearly view wrapping differently.

**Comment by tessus** [comment]
It is still open. But please note that this issue is only for printing.

**Comment by tessus** [comment]
I can't reproduce this anymore. This seems to be fixed.
