### ISSUE TITLE
[Feature Request] -make it possible to maintian the notes structure inner a notebook

### ISSUE THREAD

**Issue by alexlavigne** [laurent22/joplin#1344]
### Operating system

- Windows
- Linux
- Android

### Application

- Desktop
- Mobile
- Terminal

## Feature description
I wish to maintain my notes like a tree inner a notebook.
It means the notes inner a notebook has relationship with others .
It is something like that:

Notebooks
└── parent_notebook1
├── son_notebook1
│   └── parent_note1(with some content)
│   ├── son_note1(with some content relate to parent_note1)
│   │   ├── grandson_note1(with some content relate to son_note1)
│   │   └── grandson_note2(with some content relate to son_note1)
│   └── son_note2(with another content relate to parent_note1 )
└── son_notebook2

## Feature motivation
That is what my notes look like now.
It is a normal structure of knowleges .

**Comment by dayfuaim** [comment]
Yes, it would be very usable.

**Comment by i-need-to-tell-you-something** [comment]
Sorry, I don't understand. Do you mind explaining?
1. Do you mean you want there to be these lines indicating where a notebook belongs to? A UI request then. (I like this idea very much).
2. Do you mean that it should be possible to organize notebooks in some way that isn't possible yet? (In this case I request more explanation, since it was left unclear to me).
3. Something else I didn't think of?
