### ISSUE TITLE
Synchronization fails with PROPFIND error

### ISSUE THREAD

**Issue by jpmv27** [laurent22/joplin#1346]
### Operating system

- Windows 10 Pro 64-bit

### Application

- Desktop 1.0.140

### Description

Getting a sync failure per attached error message.

![Capture](https://user-images.githubusercontent.com/1688977/54451071-57dee480-4728-11e9-855f-e12a55f4bb75.PNG)

Error started happening on next sync after I used Web Clipper.
Deleted the note created with Web Clipper, still see the issue.
Exited Joplin completely and restarted, still see the issue.
Not seeing the issue when syncing from a different desktop (but also don't see latest changes.)

This is the same error I reported earlier in #1311.

**Comment by jpmv27** [comment]
And now the issue seems to have resolved itself of its own accord.

**Comment by CalebJohn** [comment]
It looks like there was some code in the file that was scraped from the webclipper that was throwing an error, but joplin didn't really know how to handle it so this happened. This seems like a very challenging fix because it would involve searching through clipped files for bits of code that could potentially fail.

**Comment by jpmv27** [comment]
However, when I ran into this and created #1311 all I had done was create a new empty Notebook.
