### ISSUE TITLE
[Help] nvim in termite as external editor

### ISSUE THREAD

**Issue by ReekyMarko** [laurent22/joplin#1357]
If I set `/usr/bin/termite` and arguments `-e nvim` as my external editor, it just opens an empty nvim. The same works with `st` so I don't know what could be the cause.

**Comment by CalebJohn** [comment]
I had a similar issue where I couldn't get vim to open at all. One thing I saw suggested was to wrap nvim in quotes like so
```termite -e "nvim %F"```
This might work for you (but it didn't for me).

My solution was to edit the usr/share/applications/vim.desktop so that it opened in my prefered terminal, and then I set vim as my default editor for markdown files. After that I could leave the external editor in Joplin blank and everything just worked!

**Comment by ReekyMarko** [comment]
Thanks for the suggestion, but it did not work for me also :disappointed:

**Comment by CalebJohn** [comment]
Here is the exec term of my desktop file

```
Exec=xfce4-terminal -e "vim %F"
```

maybe you're needs to be something similar?

**Comment by ReekyMarko** [comment]
yeah my desktop file looks identical, instead it's nvim, not vim. It works with other terminals than termite though, so it might be a termite issue. Then again, launching a file in nvim in termite works outside of Joplin.

**Comment by ReekyMarko** [comment]
Solved this by creating a new file in `/usr/local/bin/gnome-terminal` with the contents
```
#!/bin/bash
if [ $# -eq 1 ]; then
	/usr/bin/termite -e "nvim $1"
else
	/usr/bin/termite -e "$2 $3"
fi
```
And making the editor command just /usr/local/bin/gnome-terminal

The if blocks are there to solve another problem, gio is hardcoded to open everything in gnome-terminal so I just used the same file to solve two problems.
