### ISSUE TITLE
Impossible to remove tag

### ISSUE THREAD

**Issue by The33Coder** [laurent22/joplin#1370]
### Operating system
- macOS

### Application
- Terminal

I have a little bug with the tag. In my iOS I don't have any tag  but in cli interface I have.  And I don't know how to delete it because I have  
```
> tag remove search
Cannot find "undefined".
```

<img width="800" alt="Screenshot 2019-03-27 at 20 46 17" src="https://user-images.githubusercontent.com/12548652/55107430-93d35b80-50d1-11e9-924f-6d669426f801.png">

**Comment by foxmask** [comment]
```
joplin tag list
```
Should list them and then you could see the I'd of the tag to delete

**Comment by The33Coder** [comment]
I don't have any id

<img width="327" alt="Screenshot 2019-04-02 at 16 08 06" src="https://user-images.githubusercontent.com/12548652/55409065-96b2ce00-5561-11e9-8739-523004819128.png">

**Comment by foxmask** [comment]
as the help show us, tag list --long should show us the ID and others details ; but it's no more the case today o_O
otherwise, if curl is familiar for you ; you can use ` curl -XGET http://localhost:41184/tags for example`

**Comment by kamilko** [comment]
I can confirm that _tags_ are not properly synced with terminal app.
Steps to get this problem:
- install desktop version
- point synchronisation to webdav/nextcloud
- leave default notes and tags
- install terminal version (I did everything on the same mac)
- point synchronisation to webdav/nextcloud the same as desktop ver.
- leave default notes and tags
- you can also install here mobile version, point sync as in desktop and leave default notes/tags

After this steps you will have notebooks:
- Welcome
- Welcome (desktop)
- Welcome (mobile)
- all tags duplicated by the three types of install

Now I just cleaned up my desktop application (terminal off, mobile off). Removed all notes and tags, add new notes, notebooks, etc. Fortunately I didn't add new tags here but anyway I played a lot with Import/Export from Evernote and MD files. After full synchronisation with Nextcloud - I just left the application in background.
Then I opened terminal version and waited for full sync. It took a moment but with notebooks and notes everything was synced.
Except tags.
And there is no way to delete tags from commandline because Notes for those tags doesn't exists anymore. Every attempt of `:tag remove <name-some-default-tag>` ends with _Cannot find undefined_.
The **only** option to cleanup those tags is by delete them from table _note_tags_ and _tags_ in sqlite database. Here is the my _fortunate_ "I didn't add own tags", because you can just wipe all data from those tables, not bother with ID or name. Just run:
`DELETE FROM tags; DELETE FROM note_tags;`
If you already have own tags, then you must delete only the orphaned ones, first checking with some `SELECT...LEFT JOIN` from tables _note_tags_, _notes_ and _tags_.
This problem is only with terminal version, mobile app synchronised tags in proper way. Except this, where they were duplicated between app version. So I think tag named "markdown" created on desktop app is not the same as tag named "markdown" created in terminal app.
I think in this case, tags should be identified by **title** not by _id_ or _tag_id_, because this is probably duplication issue.
