### ISSUE TITLE
Poor Formating of To-Do Alarm Notification

### ISSUE THREAD

**Issue by phillc73** [laurent22/joplin#1390]
### Operating system

- Windows 7

### Application

- Desktop

The pop-up notification for To-Do alarms is poorly formatted with line breaks visible. Please see attached image

![joplin_alarm](https://user-images.githubusercontent.com/815126/55566527-64cd7300-56eb-11e9-9367-195bcd94846d.png)

**Comment by mickmattes** [comment]
### Operating system
- Linux (Gentoo)
### Application
- Desktop

Hi,
I have similar issues. 
On Linux I can see the notification pop up, but instead of the application name (Joplin) and the notification title, it shows only the notification body (i.e. ToDo title and body).

This makes it impossible to catch the notification and play a sound or something like that, as the ToDo title changes for every new ToDo item...

It should look like this:

---
### Joplin 
#### 26.07.2019
__Do your ToDo item!__
- foo
- bar
---

Instead it looks like this:

---
### Do your ToDo item!
26.07.2019
- foo
- bar
---

I might be wrong, but I guess it is due to the fact, that the `AlarmServieDriverNode.js` is instantiated incorrectly in `root.js`. The constructor expects an object (`options`) but is instantiated without any parameter, i.e.: 
__`AlarmService.setDriver(new AlarmServiceDriver())`__
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;__`^`__

Greetz
