### ISSUE TITLE
Beautify Joplin

### ISSUE THREAD

**Issue by inimitablemind** [laurent22/joplin#1396]
### Application
- Desktop
- Mobile

### Specification

For Good First Issue:

- Add a new `icon` property to the `Folder` object - it will be a string that will take any of the [Fork Awesome](https://forkaweso.me/Fork-Awesome/icons/) icon names.
- Make sure Fork Awesome is loaded in the app (it should already be) so that its icons can be displayed
- When right-clicking a notebook, change "Rename" to "Properties"
- Change the Rename dialog to a more generic Notebook Properties dialog
- Add the option to set the icon there. Initially it can be a simple text input where the user inputs the name of the icon directly. We can link to the Fork Awesome page to give the list of possible icons.
- When the user click Save, save the icon to the database
- In the sidebar, display the icon next to the notebook name.

Please note that there's a lot more info in this issue but the only thing that needs to be done at this point is the feature as described above.

Ideally both desktop and mobile should be supported, but it's ok to only support one of them at first.

* * *

1. Assign an icon to a Notebook
2. Assign an icon to a Note Name
3. Have a Trashcan
4. Two to Three Line preview of note in the Note List under the Note Name

**Bear Note Picture below**
![image](https://user-images.githubusercontent.com/48426607/55658635-32874880-57b3-11e9-97fd-387b0b7654e8.png)

1. Assign a color to a Tag
2. Have at-least two to four Tags be visible in the Note List section
3. Implement Tag Groups, Just like we have nested Notebooks.
    1. I will use tag groups to create groups with names like Favorites, Pinned, Status

**InkDrop Picture below**

![image](https://user-images.githubusercontent.com/48426607/55658643-39ae5680-57b3-11e9-87b3-9f37139a9505.png)

**Comment by starstuff** [comment]
good suggestion! I

**Comment by N3tFX** [comment]
Very good suggestions

I would really want to see this: "Two to Three Line preview of note in the Note List under the Note Name".

I have many notes with the same Title but not the same content. Currently the only way to see what note I want to read is to open them one by one. With two-line preview it would be so much easier and quicker.

Also, can the tags in the Desktop version also get selected as check boxes? Typing tag names should only be required for new tags. This will also minimize the chance of creating a new tag, due to mistyping, instead of assigning an old tag name.

**Comment by foxmask** [comment]
It still possible to set icon to folder with unicode characters

**Comment by tessus** [comment]
> Two to Three Line preview of note in the Note List under the Note Name

As long as it is optional. I definitely don't want this as the default behavior, let alone not being able to turn this preview off.

**Comment by N3tFX** [comment]
I agree that there should be an option, so everyone can choose what works best for them. I, for example, would like to have it as my default behavior in my copy of Joplin. Many note taking apps have this. Even the most basic ones, like Samsung Note:

![Screenshot_Two-line_preview](https://user-images.githubusercontent.com/48089992/55791191-a46ad500-5ac6-11e9-899c-93d42dfb115d.jpg)

**Comment by Dasymi** [comment]
It would also be useful to be able to see the created and updated times in the preview or list of notes.

**Comment by Stele77** [comment]
I would like to add, that "beautifying" the UI would be very very important for Joplins wider adoption.
One may not like this, but UI and therefore UX are as important as features and quality of code itself for most non-technical people.
I remember quite a long time ago when this was already proposed, Laurent said that UI design is not his strong suit, and he would be glad for input and help on this.
So maybe some of the designers here could make some mockups? Something more concrete?

PS: The UI design of Inkdrop and bear would also be the positive examples that i would have proposed. They look modern, clean, not distracting, comfortable and not intimitading for the non-techy users.

**Comment by inimitablemind** [comment]
The interface needs some love.

**Comment by pbaesse** [comment]
I would be great to have the name of the notebook besides the note title when listing all notes. Just like the example below with the tags!

> **InkDrop Picture below**
> 
> ![image](https://user-images.githubusercontent.com/48426607/55658643-39ae5680-57b3-11e9-87b3-9f37139a9505.png)

**Comment by mgrandi** [comment]
various parts of this should probably be split up into separate tickets. Things like "having a color associated with a tag' is an example of one

**Comment by tessus** [comment]
@mgrandi we can create a new issue when somebody decides to work on an item.

**Comment by etho201** [comment]
I do think that the notebooks at least need some sort of stylized icon to the left and/or a change to the the color (especially for the top level notebooks). I'll try to work up some mock designs around that to figure out what exactly is missing.

**Comment by etho201** [comment]
Just messing around with some potential design concepts. I really love Joplin so far, but the thing that bugs me is the way the notebooks are formatted on the left. Sometimes it isn't immediately obvious which notebook is selected and/or that a top-level notebook has pages. With that being said, I tried some designs to help make that a little more obvious. I'm using the [Nord color pallet](https://github.com/arcticicestudio/nord) in this concept. Only the Notebooks bar and the pages bar has been themed so far because that's my main target at the moment.

If a notebook has a sub-notebook, it will have the arrow/chevron symbol. If there are sub-notebooks, it will have a circle. Selected notebooks/pages are highlighted in yellow. Obviously all the colors could be changed depending on the theme.

Let me know what you think of this (very early) design concept:
![Joplin Design Concept 1](https://user-images.githubusercontent.com/15069703/67555955-2c14db80-f6c7-11e9-87ef-4bbf3a60f6e5.png)

**Comment by bronson** [comment]
@etho201, explaining my thumbs-down: OneNote's forcing everything into a three-level hierarchy is why I'm getting off it. Not only is it a big waste of space, it takes an unreasonable amount of time to force my note taking to fit this arbitrary structure. After using OneNote, I'm going to avoid note taking apps that force the user to create no-op sections/pages just to write something. Also, having more than 3 levels of hierarchy in OneNote feels like a glued-on hack.

**Comment by laurent22** [comment]
For general discussion about Joplin design please use the forum. I've now added a spec to this issue to narrow down the scope a bit, in case someone wants to have a go at it as a "good first issue".

**Comment by devonzuegel** [comment]
Good call @laurent22! Also I'm excited for this feature.

Suggestion: It might be useful to close this and create a separate issue to minimize confusion for anyone who might take this task. `Good first issue`s are meant to be as un-intimidating as possible, and seeing a long nuanced conversation attached to a task has the opposite effect.

**Comment by laurent22** [comment]
Good point @devonzuegel - I've moved the issue there: https://github.com/laurent22/joplin/issues/2268

**Comment by laurent22** [comment]
@inimitablemind, although there are good ideas in this issue, it became more of a general discussion about Joplin's design. If additional self-contained issues can be extracted from these ideas, please go ahead and create new issues, or you may also move the discussion to the forum. In the meantime I will close this one.
