### ISSUE TITLE
[BUG] Numbering inconsistency between edit and rendered list items

### ISSUE THREAD

**Issue by CollinChaffin** [laurent22/joplin#1398]
### Operating system

Windows 7x64

- Windows (have not confirmed if others are affected)

### Application

- Desktop

Have only experienced and subsequently reproduced on Windows 7 x64 desktop version I have not confirmed whether also present in other builds.

See screenshot below.  This page was initially webclipped and as you can see, the rendered final shown despite being correct in every other way, in the render does not properly reflect the actual numbered list item counter/numbers.  In fact, below what is shown, two more times the list is restarted in numbering as a new list, but continues as shown here to continue to increment as one large list instead.

![SNAG_4-6-2019_18-53-00](https://user-images.githubusercontent.com/9301483/55676694-b10ce480-589e-11e9-97f4-84db8298ccf2.png)

**Comment by innocuo** [comment]
I don't think this is a bug, but an annoying behavior in the markdown spec.

The 2 specific definitions:

> The start number of an ordered list is determined by the list number of its initial list item. **The numbers of subsequent list items are disregarded.**

> A list is loose if any of its constituent list items are separated by blank lines, [...] paragraphs in a loose list are wrapped in <p> tags

([you can see the spec for lists here](https://spec.commonmark.org/0.29/#lists)).

#### What this means:
1. markdown ignores whatever numbers you have in each list item, it only cares about the first number in a list
2. line breaks aren't used to divide lists, whether you use 1 or a 100 linebreaks, the markdown is still parsed as a single list.

So, annoyingly, this:

```
1. item 1
1. item 2
20. item 3

3. item 4

1. item 5
```

renders as:

1. item 1
1. item 2
20. item 3

3. item 4

1. item 5

This is clearly dumb. But Joplin uses [markdown-it.](https://github.com/markdown-it/markdown-it) to parse markdown. And Markdown-it follows the [CommonMark](http://spec.commonmark.org/) spec, which specifies this behavior. So for this to change, CommonMark needs to improve its spec. I'm guessing it's unlikely to change, because [they've known about this since at least 2014](https://github.com/commonmark/commonmark-spec/issues/82).

### Solution 

You have to add 
`<!-- -->`, `<br>`, or `&nbsp;` (or any other visible character, or a divider like `____`) between lists for the parser to understand it's 2 lists ([found on stackoverflow](https://stackoverflow.com/questions/23821014/markdown-having-multiple-lists))

I don't know how the webclipper works, but maybe someone can change it so that it  adds one of this "list dividers" before each list by default?

**Comment by innocuo** [comment]
As a sidenote, I found the same behavior in the github comments editor, Atom's markdown preview, BoostNote, and [markdown-it demo](https://markdown-it.github.io/)  so this isn't unique to Joplin. I bet almost all standard markdown editors will have the same behavior.

**Comment by CollinChaffin** [comment]
Hey sorry to not get back to this one.  I agree I admittedly had not done my due diligence on this nearly as much as I normally do so I apologize.  You are absolutely correct this issue 100% lies not in Joplin, but in the spec/parser so I'll close this.  It however is absolutely not only just an annoyance but a real productivity-killing issue if you use MD commonly for serious list/ULs so I really hope someday in the next spec drafts is actually addressed and in the meantime perhaps the engines can implement some better workarounds.

I'll begin trying to use the `<br>` workaround for the time being.  Thanks!
