### ISSUE TITLE
Proxychains do not work > 1.0.126 (prod, linux)

### ISSUE THREAD

**Issue by michalterbert** [laurent22/joplin#1431]
### Operating system
- Linux (Fedora 29)

### Application
- Desktop

Hi,
I'm using proxychains with Joplin, last working version was Joplin 1.0.126 (prod, linux).
Any other version don't work any more - problem with rendering GUI, screenshot below:
![image](https://user-images.githubusercontent.com/15417117/56425313-00e2a700-62b4-11e9-897f-f2e02c7ec5ab.png)

**Comment by tessus** [comment]
I don't want to be insensitive towards your problem, but what does this have to do with Joplin?

proxychains is preloading dynamic libraries to hijack network calls. You have no idea how much stuff can go wrong when doing things like that.
There's a ticket open _[doesn't work with atom](https://github.com/haad/proxychains/issues/48)_ since 2015, which was basically ignored. Atom is an Electron app, so I think this issue is related.
I suggest to open a ticket with proxychains and ask why Electron apps may or may not work with proxychains.

This is really not an issue the Joplin dev can solve. I mean you don't buy a car, convert it to a boat, and go back to the dealership, when it stops swimming at a certain point, or do you?

**Comment by laurent22** [comment]
Indeed there's probably not much we can do but just in case could you start the app in debug mode to see if there's any error in the console? https://joplinapp.org/debugging/

**Comment by michalterbert** [comment]
Ok, thanks for info - I will address this issue to proxychains team.

BTW. No errors in console - console is not running by joplin via proxychains.
