### ISSUE TITLE
Garbage Collection Seems Missing

### ISSUE THREAD

**Issue by boramalper** [laurent22/joplin#1452]
### Operating system

- Linux

### Application

- Desktop

I've removed an attachment (using the Desktop client on Linux) and successfully synchronised using Dropbox, but the attachment seems not to be removed from my Dropbox folder (neither the `HASH.md` nor the `.resource/HASH` file).

Is this by design, or do you encounter some sort of bug?

**Comment by CalebJohn** [comment]
A bit of both probably, the resource cleanup doesn't run on every sync (by design it only runs at some specific interval). So if you wait a little while (perhaps a couple of days) the resource should disappear on it's own. But there is currently a bug where these resources aren't always (or at all?) deleted see issue #932 for reference.
btw this issue is likely a duplicate of #932 so I recommend closing it and commenting there if you need to add anything to the conversation.

**Comment by boramalper** [comment]
I am closing this as I have nothing further to add. =)
