### ISSUE TITLE
[Feature request] html note-storage format and configurable backend 

### ISSUE THREAD

**Issue by hgkamath** [laurent22/joplin#1454]
Operating system: all
Application: all
Thank you: for the hard work

I understand that a design decision was made to use markdown as a note-storage and rendering format.

Q) How about a configurable option and support to allow for choice of note-storage format? ex html. Why get tied down to only one note-storage format? Perhaps other backends also ex: plant-txt and so on.
This is different from import/export to html.

This would open possibilities for having MathML and SVG directly linked or embedded into the note. 
For example wordpress uses html backend, and uses tinyMCE as the editing front end. 

The advantage of a markdown format, is that it is a very simple format, modestly meant for simple purposes. It is user readable, easy to start editing. For developers perhaps easy to code, plenty of community code, and easy to search. 

The advantage of the html format is that the html, mathml, svg have more tooling and can be copy pasted in and out of several apps/software, without losing anything in interconversions, since, other than cleaning for sanity, the note-body will mostly stay the same. Usually, software frameworks like electron have HTML renderers as part of the browser framework, so no additional code is needed to instruct how to render html. So html itself brings a lot of goodies with it, control, color, styles, css, perhaps optionally also a javascript engine, and ability to access data from json files.

Others  have also expressed a need for more advanced note format (issue #1080 , #891 )
nb. Latex isn't always preferred, but latex users will also prefer embedding latex-equations into markdown, so this is not to downplay the need/feature request of latex users to embed latex in markdown, which is always a desirable feature (issue #11  ). Perhaps also a markdown embeddable mathml along the same lines. 

#### References
- Add support for maths input #11  https://github.com/laurent22/joplin/issues/11
- Enhanced Note Format #1080 https://github.com/laurent22/joplin/issues/1080
- Featured Notes #891 https://github.com/laurent22/joplin/issues/891

**Comment by laurent22** [comment]
HTML should already mostly work in Joplin.

**Comment by CalebJohn** [comment]
Just to add to this I tried adding some svg taken from [w3 schools](https://www.w3schools.com/html/html5_svg.asp) and it works perfectly in joplin

![image](https://user-images.githubusercontent.com/2179547/56754184-a0d38100-6749-11e9-9287-4af71b01b48b.png)

You should take a look at the joplin readme sections on [HTML](https://github.com/laurent22/joplin#html-support) and [css](https://github.com/laurent22/joplin#custom-css). 

Joplin actually uses an html renderer to display your notes, under the hood markdown is converted to html and then displayed. One of the advantages of a format like markdown is that it is just plain text, so you are free to put as much html into your notes as you want (and not put any markdown) and they should render correctly (this isn't always the case because of bugs with joplin or electron). 

The only thing that Joplin seems to be missing that you've requested is MathML support. Joplin is built on electron which is build on the chrome. According to [this wikipedia page](https://en.wikipedia.org/wiki/MathML) google removed native MathML support a number of years ago meaning some plugin will be necessary for it to work in joplin. Which leads me to suggest that you give katex a try. I know you mentioned that you don't necessarily like it, but it is the new standard for rendering math expressions and has robust tooling available.

**Comment by hgkamath** [comment]
thanks for the quick response and for the info: just thinking and making some notes in this comment

- joplin uses the github-flavored markdown https://github.github.com/gfm/ (or adamp-p github flavored markdown https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet )
  It recognizes html tags as long as it meets a start condition 
  One disadvantage perhaps is one had to edit the html tags directly and does not have the html/editor-UI,  which s perhaps the whole first selling point of markdown.
  
- Until some 3rd party effort like https://mathml.igalia.com/ add mathml support to the chrome/ chromium engine, which probably sounds like mathml is going to be on the back burner, as it may or may never happen.

- another advantage of markdown, is that maybe has minimum cognitive overhead while coding and using git , which is the second selling point of markdown.

- one thought perhaps implicit here, is to consider just moving to markdown entirely and pandoc backwards if ever needed ... which is something to mull over.

- will be investigating katex https://en.wikipedia.org/wiki/KaTeX
