### ISSUE TITLE
Lack of mobile sync reverted everything to weeks ago

### ISSUE THREAD

**Issue by NginUS** [laurent22/joplin#1501]
### Operating system

- Linux
- Android

### Application

- Desktop
- Mobile

While I was out shopping today I made a quick edit to my shopping list on Joplin Android & when I was done it sync'd and reverted everything on both mobile & desktop to the time/date the Android Joplin was last used. In this case that was several weeks ago & all recent work was lost.

Hopefully I have a backup, but in the meantime I'm posting here so maybe someone can fix it to not happen again.

**Comment by donaldtone** [comment]
In order to prevent lost of notes, I have a idea how to improve the sync logic.

1. During sync, if a note is not been **deleted clearly** in one of the client app, it will not be deleted just because of one of the client app does not have this note.
when a note has been clearly deleted by client app, this action will have a record of its id and deleted date in the Joplin system.

2. Have a system folder named "**Trash**", the deleted note will be move to this folder automatically. 
 Leave another chance to recover.

3. Have a **backup function** to reserve all the history notes. This backup will be restrict to access and modify only by authorized app, for example, just windows app.

**Comment by guy-rouillier** [comment]
Not sure what "Lack of mobile sync" refers to, but I encountered lack of sync with Android app today.  Using Dropbox for syncing.  I originally created a note on Joplin Windows desktop, then installed Joplin on Android phone and told it to sync.  It retrieved the note entered on Windows.

Today, I updated that note on Android phone.  Several hours later, I got on Windows and told Joplin to sync.  No updates.  Told phone to sync, then Windows, still no updates on Windows. Did this a couple more times, and eventually got the updates on Windows.  Syncing from Android doesn't seem to be very reliable.

**Comment by tessus** [comment]
Joplin on Android does not sync in the background.

**Comment by guy-rouillier** [comment]
@tessus Ok, thanks, that it explains it.

**Comment by laurent22** [comment]
Not enough info to replace this. But are you sure the note version you were looking for was not in the Conflict notebook?

**Comment by NginUS** [comment]
There wasn't a 'conflict' notebook, or any indicator to that extent anywhere.
