### ISSUE TITLE
[Bug] syntax highlight automatic language detector pick

### ISSUE THREAD

**Issue by noraj** [laurent22/joplin#1514]
### Issue

It seems there is a syntax highlight automatic language detector.

But in Markdown when a code block has no language specified it means it must be highlighted as plaintext (not highlighted so).

Here for my nmap scans I'm not giving any language but there is still some syntax highlight: 

![image](https://user-images.githubusercontent.com/16578570/57573300-e8cef500-7425-11e9-8c0c-f5097a99ab85.png)

The core/root cause may be the same as for #1513.

### Operating system

Linux: ArchLinux (installed via the AUR package).

### Application

- Desktop

### Version

Joplin 1.0.145

**Comment by CastedConst** [comment]
There should be an automated language detection (like in github).

I had a quick look in the code, and it appears to use `highlight.js`. If thats the case you can try to specify the code block as plaintext (` ```plaintext`)

**Comment by noraj** [comment]
I tried `none` that was added in version 9.15.1 of highlight.js (2019-02-24) but it was not working. Anyway; default should be none/plaintext but not javascript. `plaintext` is working but is quite a big overhead. I'm using Boostnote right now.

**Comment by innocuo** [comment]
A few things:
1. I think there's some confusion about the `none` language. If you look at [highlight.js' changelog](https://github.com/highlightjs/highlight.js/blob/master/CHANGES.md), they have _"new language: none"_ in multiple versions, newer and older than 9.15.1. It doesn't mean that they added the `none` language, but that they haven't added any new language for that version.  You can also see [the list of available languages for highlight.js](https://github.com/highlightjs/highlight.js/tree/master/src/languages), you won't find `none` there. So, `none` is not an option, `plaintext` is, and `plaintext` works.

2. Default language is not `javascript`.There's automated language detection. If you don't specify a language, Joplin uses [highlightAuto()](https://highlightjs.readthedocs.io/en/latest/api.html#highlightauto-value-languagesubset). In fact, if I type some of the _code_ from your screenshot, it detected multiple languages: `cs`, `stata`, `angelscript`, `vim`.

3. There's another way to not highlight code in Github Flavored Markdown other than setting it as `plaintext`: you can indent your code by four spaces (1 tab also seems to work) instead of using the backticks. See the [syntax highlight section here](https://guides.github.com/features/mastering-markdown/). The issue here is that Joplin won't add a background color to this block. If this doesn't get added to the css, you can add it yourself to userstyle.css or to the note itself with a style tag; something like pre{ background:#666666;} might be enough.

4. Making `plaintext` the default language could be a valid option. Auto-detecting the code language (as it does now) also seems to me like a valid option. Maybe the solution could be to add a setting so users can decide, but in the meantime, it looks like there's already 2 valid alternatives to type code without formatting.

5. A third option is to use html, something like this also works in Joplin:
```
<pre style="background:#666;">
code that is not javascript goes here
</pre>
```

**Comment by noraj** [comment]
>     1. I think there's some confusion about the `none` language. If you look at [highlight.js' changelog](https://github.com/highlightjs/highlight.js/blob/master/CHANGES.md), they have _"new language: none"_ in multiple versions, newer and older than 9.15.1. It doesn't mean that they added the `none` language, but that they haven't added any new language for that version.  You can also see [the list of available languages for highlight.js](https://github.com/highlightjs/highlight.js/tree/master/src/languages), you won't find `none` there. So, `none` is not an option, `plaintext` is, and `plaintext` works.

Right, it was confusing, I was wrong about `none`.

>     2\. Default language is not `javascript`.There's automated language detection. If you don't specify a language, Joplin uses [highlightAuto()](https://highlightjs.readthedocs.io/en/latest/api.html#highlightauto-value-languagesubset). In fact, if I type some of the _code_ from your screenshot, it detected multiple languages: `cs`, `stata`, `angelscript`, `vim`.

Ok, so default should be plaintext and not automatic detection.

>     3\. There's another way to not highlight code in Github Flavored Markdown other than setting it as `plaintext`: you can indent your code by four spaces (1 tab also seems to work) instead of using the backticks.

What you say here is a workaround and using indentation is not as reliable and handy as backticks.

> * If this doesn't get added to the css, you can add it yourself to userstyle.css or to the note itself with a style tag; something like pre{ background:#666666;} might be enough.

That's a very unpractical and it is not working by default.

>     4\. Making `plaintext` the default language could be a valid option. Auto-detecting the code language (as it does now) also seems to me like a valid option. Maybe the solution could be to add a setting so users can decide, 

Yeah should be plaintext as default and add an option to enable auto-detect as default. Would be the best way.

> but in the meantime, it looks like there's already 2 valid alternatives to type code without formatting.

Workaround more than valid alternatives, hacking a custom css stylesheet can't be counted as a solution.

>     5\. A third option is to use html, something like this also works in Joplin:

The goal of markdown is not to write HTML, so writing HTML kill markdown interest.

**Comment by CastedConst** [comment]
Hi All,
glad that the `none` is clarified. I didn't had the time to analyze this, therefore I didn't wrote an answer...
Summarizing your two posts the remaining Question is what the default should be and whether it should be customizable or not.

According to the CommonMark specification of Markdown the triple backticks are described as "Fenced Code Block" (see https://spec.commonmark.org/0.29/#fenced-code-block). Therefore describing the intended purpose of this Element as "contains coding". The specification of John Gruber does not specify the triple backticks as code-blocks (only indentation based), but it describes any number of backticks as wrapper for code, so "contains coding" does apply here as well (see here https://daringfireball.net/projects/markdown/syntax#code).

Following the specifications my suggestion is to keep the default on "try syntax highlighting".
A global setting for this may be a good Idea, but I think there are several issues that have a higher priority.

**Comment by Nebucatnetzer** [comment]
> A few things:
> 
>     1. I think there's some confusion about the `none` language. If you look at [highlight.js' changelog](https://github.com/highlightjs/highlight.js/blob/master/CHANGES.md), they have _"new language: none"_ in multiple versions, newer and older than 9.15.1. It doesn't mean that they added the `none` language, but that they haven't added any new language for that version.  You can also see [the list of available languages for highlight.js](https://github.com/highlightjs/highlight.js/tree/master/src/languages), you won't find `none` there. So, `none` is not an option, `plaintext` is, and `plaintext` works.
> 
>     2. Default language is not `javascript`.There's automated language detection. If you don't specify a language, Joplin uses [highlightAuto()](https://highlightjs.readthedocs.io/en/latest/api.html#highlightauto-value-languagesubset). In fact, if I type some of the _code_ from your screenshot, it detected multiple languages: `cs`, `stata`, `angelscript`, `vim`.
> 
>     3. There's another way to not highlight code in Github Flavored Markdown other than setting it as `plaintext`: you can indent your code by four spaces (1 tab also seems to work) instead of using the backticks. See the [syntax highlight section here](https://guides.github.com/features/mastering-markdown/). The issue here is that Joplin won't add a background color to this block. If this doesn't get added to the css, you can add it yourself to userstyle.css or to the note itself with a style tag; something like pre{ background:#666666;} might be enough.
> 
>     4. Making `plaintext` the default language could be a valid option. Auto-detecting the code language (as it does now) also seems to me like a valid option. Maybe the solution could be to add a setting so users can decide, but in the meantime, it looks like there's already 2 valid alternatives to type code without formatting.
> 
>     5. A third option is to use html, something like this also works in Joplin:
> 
> 
> ```
> <pre style="background:#666;">
> code that is not javascript goes here
> </pre>
> ```

For me number 3 is quite an annoying bug. I started to copy websites with the clipper and it saves all code examples as indented code blocks. Since they don't get the background  set they are very hard to read and I have to go through the file and add back ticks around all the code blocks.

**Comment by noraj** [comment]
bump

**Comment by noraj** [comment]
Yeah let's close that I'm just using [VSCode](https://code.visualstudio.com/) + [Nested Tags](https://marketplace.visualstudio.com/items?itemName=vscode-nested-tags.vscode-nested-tags) now which has far better support for all of that and is not limited to note taking.
