### ISSUE TITLE
Synchronization with File System not work

### ISSUE THREAD

**Issue by leetschau** [laurent22/joplin#1542]
Operating system: Ubuntu 18.04
Application: Desktop (App Image)
Joplin version: 1.0.152

Sync with *file system*, I've checked the note file (89b0xxx.md) has been updated with `cat` in console.
But in Joplin, the contents of the note do not change after click the *Synchronise* button.
This problem only appears after updating to 1.0.152.

**Comment by tessus** [comment]
You are not supposed to change notes manually outside of Joplin.

The reason for that is that the metadata needs to be updated as well. So, if you only change the note, but not the metadata, the sync algorithm does not know that the note has changed.

As far as I know this is not officially supported. This topic also would have been better in the forum so that people who are not on github can chime in - and for this topic to be available as a reference for future questions in that area.
