### ISSUE TITLE
Hover highlight for notebooks

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [laurent22/joplin#1549]
### Operating system

- Linux

### Application

- Desktop

---

Notebooks are not highlighted when hovering over them in the notebook list.

This is a common feature in many applications and is present in the note list in Joplin. Not super important though.

**Comment by tessus** [comment]
Seriously? 30 issues? I mean you could have created a few topics in the forum, but 30 github issues? Really?

**Comment by innocuo** [comment]
@i-need-to-tell-you-something so it's clear: each reported issue needs to be reviewed. Depending into its priority, it might get fixed, or some discussion might get started about it with other users. That takes time, on top of the time that is spent on other existing issues. Meaning: the more issues you report, even if they're valid, the less likely you're making it for yourself for those issues to get resolved, because you're taking away time that could be used on developing a better app.

Even if you plan to create a bunch of pull requests for your own issues, they also have to go through review and testing.

I suggest you stop reporting issues for now. Keep them on a private list (hey, why not even use Joplin for that!), follow the issue tracker, and keep reporting them once other issues are solved. Actual bugs take the top priority. Feature requests and enhancements usually need discussion by the community.

I'm sure you're also spending a ton of time when testing, reviewing, and writing detailed descriptions of the issues, and while appreciated, flooding the issue tracker with issues will mean a bunch of them might get ignored for a while. I'm guessing you want to help, but this isn't quite the best way.

**Comment by i-need-to-tell-you-something** [comment]
I appreciate the explanation a lot, thanks.
