### ISSUE TITLE
No shortcut key for new notebook

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [laurent22/joplin#1560]
### Operating system

- Linux

### Application

- Desktop

---
Niche feature.
New notebook function/button is missing a shortcut key. Now I don't have a good suggestion either what it should be. A web search turned up that apparently CTRL+SHIFT+N was used once upon a time maybe. So this is more of a feature waiting for #1557 so it can be listed as a function to optionally get a shortcut key, but not necessarily by default.
Also creating new notebooks is not that common of a need and those users who insist on doing everything by keyboard are more likely to use the terminal version anyway.

**Comment by tessus** [comment]
I wanted to use `Cmd+Shift+N` at one time, but it's already used for setting the focus on the note title. `Ctrl+Shift+N` is used on Windows and Linux.
Laurent mentioned at that time that creating a notebook is not a very common action anyway.

If Laurent changes his mind, I can definitely create a PR for that. The problem is that shortcuts are used differently on Windows and Mac, thus we have to find combinations other than `Cmd+Shift+N` or `Ctrl+Shift+N` (since they are already used).
