### ISSUE TITLE
Poor synchronization UX that leads to potential data loss.

### ISSUE THREAD

**Issue by al3xand3r-K** [laurent22/joplin#1588]
### Operating system

- Linux
- Android

### Application

Here's a case of an extremely poor UX joplin has. I've made a note on my mobile (spent about 1.5h on it, thinking and typing). Then, I hit sync - first on my mobile, then on desktop - and the note seems to be deleted.

Two questions:
1. Why would I want to explicitly save something I've just made before syncing? This makes no sense to me in any possible way. I've already spent time making a note, so if I'll ever want to delete it - I'll do that. Making the deletion process implicit in any way is a great way to mess user's data. You don't even use your own servers for synchronization to somewhat justify this kind of UX!
2. Why wouldn't the app notify me about the potential loss of unsaved data?

**Comment by tessus** [comment]
This works as designed. Joplin is a react native app thus has to make due with the UI and workflows available to it. Maybe there's a way to fix this and create an auto save. On the othe hand, I believe it is logically to save a document. Auto save and these things are features - not a given.
Please head over to the [forum](https://discourse.joplinapp.org/) to discuss this.

**Comment by CalebJohn** [comment]
I agree with @al3xand3r-K to an extent. Of course you should always save your work, but it's not unreasonable to think triggering a sync would save. 

A simple hack would be to auto save when the menu is opened, I can look into doing that later and see how it impacts performance.

**Comment by Thomashighbaugh** [comment]
I just had a sync issue after installing on Linux (make a deb/rpm file btw, AppImages have launching issues I couldn't get it to even launch last time I installed my OS) and bam nothing comes up. So I import my DropBox files directly and now the title are unreadable strings of gibberish (database entries I know) its not unreasonable to have it autosave on sync nor to not want to spend hours reorganizing everything because a hiccup in the application. Awful UX

Also come on, everything autosaves these days and most people are moving away from checking the "did I save" box mentally especially with things integrated so heavily into the web. As the OP said, if people wanted it deleted they would do so and you aren't using your own servers. Sure they aren't a given, but neither is using this app instead of the plethora of alternatives. You have to have the expected features of the apps you compete with or people will go elsewhere. 

 But what do on the ground users know, amirite

**Comment by mgrandi** [comment]
so is the OP saying that he typed a note on mobile, didn't hit the save button (but hit back) , and then hit the sync button and that didn't actually save and sync the note and deleted it? that def seems like a bug

and i have sorta been bitten by the auto save / revision system not applying for mobile notes unless you hit the save button, i agree that should be improved as well.

**Comment by tessus** [comment]
autosave added in a1e8e71359000d782874f28b1a3e3c3a2adee43a

it will be available in the next release.

**Comment by xuhcc** [comment]
@tessus Is there any way to disable it (see #310)?

**Comment by tessus** [comment]
@xuhcc no, but this is a different issue. this issue is aboout autosave for mobile.
The issue you referenced is for desktop.

**Comment by xuhcc** [comment]
I understand, but the point is that auto-save should be configurable. I like the current workflow in android app (with manual saving).

**Comment by tessus** [comment]
Ah, I see what you are saying. I also like pressing 'save' manually, but apparently people lost data, because of not clicking the save icon. I guess it is expected on Android not having to save to actually retain data.

It shoud be fairly easy to make an option available. If @laurent22 is ok with it, I can add it.

Yea, the other issue talks about making auto-save optional, but the commit I referenced actually removes manual save completely (the opposite of what is requested in the ticket for desktop).
Somehow this will be inconsistent, shoud auto-save ever be an option on desktop (which Laurent was contemplating about anyway), unless there's an option for mobile as well.

**Comment by mgrandi** [comment]
On mobile apps, you can't expect that your app will ever exit in a normal fashion, the phone could crash, run out of battery, or get killed by the operating system or something, so i think having a backup save is a good idea even if people don't prefer it

also , doesn't desktop have auto save anyway? i thought the 'sync interval` option basically implied a auto save when it syncs

**Comment by tessus** [comment]
> also , doesn't desktop have auto save anyway?

Yes, but people want an option to disable this. It's one of the longest open issues and feature requests.
So now the people who were happy to not have auto-save on mobile are irked that it will now be the default without the chance to turn it off.

**Comment by laurent22** [comment]
I'm curious what the use case for not having auto save? (Or for making it optional) I'd rather not make it optional but instead understand what issue is, and maybe try to fix that.

**Comment by xuhcc** [comment]
@laurent22 For me manual saving just feels more 'natural', because most text editors work this way.

There is also a bug which probably associated with auto-save, when recent change disappears from the note (reported here https://github.com/laurent22/joplin/issues/310#issuecomment-381419932 and here https://github.com/laurent22/joplin/issues/1352).

**Comment by xuhcc** [comment]
One use case is undoing changes. For example, I have made few edits in different parts of the note and then changed my mind. On desktop I usually use Ctrl-Z (which has its own problems), but how to do that on mobile?
