### ISSUE TITLE
typing a backtick seems to auto insert a closing backtick

### ISSUE THREAD

**Issue by mgrandi** [laurent22/joplin#1604]
### Operating system
- macOS

### Application
- Desktop - version `Joplin 1.0.158 (prod, darwin)`

I don't know if this is joplin per se, but it seems that after upgrading to version 1.0.158, when i insert a backtick, it now inserts a closing backtick, and then if you insert another backtick, it seems to instead move the cursor to the right of the backtick instead of inserting a new one.

This seems like behavior used by a lot of programming IDEs, the problem is that at least with github flavored markdown, inserting a codeblock requires 3 backticks, ` ```  `, but what happens is if you hit the backtick key 3 times, you end up with 4 backticks:

* first key press: create first backtick and second to close it
* second key press: move cursor past the second backtick that it  auto created
* third key press: create third backtick and a fourth to close it

I actually just realized that typing up this bug report that it seems that any number of backticks >= 3 works to create a code block, but I am at least used to using 3 of them as that is what github uses

Anyway, i didn't see any release notes about  adding this feature, was this unintended? 

video: 

https://www.dropbox.com/s/met7c0ycclm1uk7/joplin_backtick.mov?dl=0

**Comment by CalebJohn** [comment]
This was already reported in #1534 you can follow the fix in #1599

**Comment by tessus** [comment]
Unfortunately we had to revert #1534. The fix in #1599 turned out to be too akward.

However, I've added a shortcut, so you can select a text and press ``` Cmd+` ``` (macOS) or  ``` Ctrl+` ``` (Linux, Windows) to enclose it with a backtick.
I've also opened a ticket with the Ace editor and they have fixed this (the original issue and the side-effect) in their code. But it will take a while before these changes will make it to `react-ace` and `brace`, which are the packages we are using as the glue for the Ace editor. So until all upstream packages include the fix, you will have to use the shortcut.

You can test how it will work, when all packages will have been updated upstream, in the Ace editor [kitchen sink](https://raw.githack.com/ajaxorg/ace/master/kitchen-sink.html?doc=Markdown).
