### ISSUE TITLE
why google analytics?

### ISSUE THREAD

**Issue by catastrop** [laurent22/joplin#1621]
why does Joplin's web use *google analytics*? **It shouldn't use it.**

**Comment by laurent22** [comment]
If you know a better alternative that GA, please let me know. In the meantime there are plenty of extension you can use to block GA.

**Comment by Shamp0o** [comment]
If self-hosting is an option, you should take a look at [Matomo](https://github.com/matomo-org/).

**Comment by laurent22** [comment]
It's currently not an option as maintaining a server for this is more work than I'd want to do, and I don't even need analytics that much (it's just now and then to see what article might be linking to the website).

I would think that if someone doesn't like GA they'd simply block it with an extension instead of asking each site to remove it.
