### ISSUE TITLE
Shortcut for tags

### ISSUE THREAD

**Issue by mikelu92** [laurent22/joplin#1626]
### Operating system

- macOS

### Application

- Desktop

Is there a shortcut for adding tags to notes? haven't been able to find it anywhere and I tried the ones that would seem intuitive (like <kbd>cmd</kbd> + <kbd>T</kbd>)

**Comment by tessus** [comment]
`cmd+T` is already used.

**Comment by mikelu92** [comment]
sorry I guess I wasn't clear, I know that's already used. I was just trying to see if there were any intuitive shortcuts that would bring up the tags menu but I couldn't find one.

**Comment by tessus** [comment]
Nope, there isn't a shortcut for tags. I guess Laurent ran into the same problem: finding a suitable shortcut. If you can come up with one, maybe we can add it. I think the forum is a good place to ask others what they think, because I believe more users are reading the forum than the gh tracker.
You can either leave this one open or open a new one, when you have found a good shortcut.
Sounds good?

**Comment by laurent22** [comment]
Maybe Alt+Ctrl+T (Option+Cmd+T)?
