### ISSUE TITLE
Notes and Notebooks Disappearing

### ISSUE THREAD

**Issue by xthursdayx** [laurent22/joplin#1673]
### Operating system

- macOS
- iOS

### Application

- Desktop
- Mobile

For some background: I switched to Joplin from Evernote with over 100,000 notes, so it took me a long time to get it all to sync (I'm syncing to my own Nextcloud server). I finally finished that sync a couple of weeks ago, and since then have been running a sync in the Joplin iOS app on my phone in order to sync all the notes there as well. I also just updated Joplin to the most recent version a couple of days ago (yesterday?). 

The problem: Today while looking through my notes for some information, I found that two of my notebooks had disappeared, along with all of the notes they contained. Some of these notes, along with others, now appear in a notebook called "Conflicts", however not all of the missing notes have been recognized as "conflicts", rest are just missing entirely. 

Any ideas? It would really suck if all of those notes were just lost forever.

**Comment by tessus** [comment]
It might be better to use the forum, since more people are likely to read topics there than on the gh tracker.

Anyway, here are a few questions:

Where have your notebooks/notes disappeared from: desktop, mobile, both?
What does the log say? Without a log, we have no idea what's going on.

Conflcts happen, if one changes the same note on different devices without synchronizing. The Conflicts folder contains the "local" copy of the note. The other ("old") note should still be available in your original notebook.

Nextcloud allows you to recover deleted files, so you should be able to get your data back.

However, to figure out what happened, we need a log file.

@laurent22 is it possible that 100,000 notes hit the limit of sqlite? Although I rather doubt that.

**Comment by xthursdayx** [comment]
Yes, sorry about that, I couldn't remember how to create a debugging log, but I've got it now. 

First, to answer your questions: 
The notes/notebooks were disappearing from both, however notes and notebooks were only created in the desktop app on my Macbook. That is one reason that the conflicts seem strange. The notes being shown in the desktop app as conflicts were also "local" - created on the desktop app and no "old" versions are appearing in any other notebooks (I believe because they were in the notebook that has disappeared). However, I can't search for them because searching does not appear to be working (as per issues #1674 ).

In terms of a 100,000 limit in sqlite, I don't think that's it either, because I've been able to create other new notes without them disappearing. 

I can't share any debug errors since this has all already happened and I don't know how to reproduce it, but I've attached my general log file here. 

[log.txt](https://github.com/laurent22/joplin/files/3304439/log.txt)

**Comment by tessus** [comment]
Yea, in this case conflicts are indeed strange. Let's see what Laurent has to say.

**Comment by laurent22** [comment]
> @laurent22 is it possible that 100,000 notes hit the limit of sqlite? Although I rather doubt that.

I don't remember the exact limit but it's in the billions rows so 100,000 shouldn't be a problem.

It's going to be difficult to find the reason for this bug without a clear way to replicate it. The log indicates that there's a permission issue though, which could be part of the reason:

    2019-03-30 12:58:14: "Error: Error: EACCES: permission denied, mkdir '/.sync'. Path: .sync
Code: EACCES

Does Joplin has all the permissions set? Is there still some space left on your device?

Otherwise do you have a backup of your notes? If so, you could try deleting the local data on all devices and on the sync target, then import your backup and resync everything. On mobile, set "Attachment download behaviour" to "Auto" so that it won't download all the resources immediately which should make the sync process a bit faster.

**Comment by xthursdayx** [comment]
Yep, Joplin syncs just fine normally, and there are is 11Tb of unused space available on my server, so that should be the problem. Some of the errors I saw in the log were from times when my Nextcloud instance was inaccessible for whatever reason (e.g. server was offline, Nextcloud was updating, etc). 

In terms of a backup of my notes, is this something that Joplin makes automatically. If not, then no, I don't just the normal database on my Nextcloud. 

Thanks for the advice for the mobile app, I'd missed that option.

**Comment by laurent22** [comment]
Closing for now as it's not possible to replicate the bug if there is one.
