### ISSUE TITLE
Clipping github issues or PRs produces strange results

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#1682]
Clipper 1.0.16

The output of `Clip simplified page` seems as if all text elements were clipped (even the ones hidden by divs). The output of `Clip complete page` is not much better.
When it comes to PRs, the result is even worse.

I am not sure if this issue is just with gh or an indication of an underlying problem.

It partly reminds me of #1379, which resolution does not seem to work anymore. (But maybe they are different issues.)

**Comment by tessus** [comment]
Hmm, it's not working.

I just tied to clip #1678 and this was the result: 
[test.jex.zip](https://github.com/laurent22/joplin/files/3319430/test.jex.zip)

(remove .zip extension - I had to add it to upload it - it is not zipped!)

**Comment by laurent22** [comment]
Was that "Clip selection"? Because at the moment the fix only applies to "Clip complete page". Not sure how it can be done for Clip Selection at the moment.

**Comment by tessus** [comment]
Nope, it was `Clip simplified page`. If you use `Clip complete page` with github issues, the result is bad. The icons are all over the place and it's legibility is down the drain. The simplified approach gave a better result, except that hidden elements are shown, which doesn't help legibility either.

**Comment by laurent22** [comment]
Clipping complete is better with GitHub now since the hidden elements are actually hidden, but there's indeed a lot of elements that are left. I've just realised that the same fix can probably be applied to simplified page too so I'll take a look.

**Comment by tessus** [comment]
Thanks Laurent for looking into this. It's not so much that I clip gh issues every day, but I think people could encounter similar issues on other sites as well.

**Comment by laurent22** [comment]
No problem, the clipper is quite important since few other open source apps have one so it's good to keep improving it.

Regarding simplified mode in GitHub, for me it either doesn't work at all if I'm not logged in or, if I'm logged in, it imports the first message in the thread and the other messages it's just random hidden text. I guess Readability is already supposed to cleaned up the HTML including removing hidden elements, which it doesn't for GitHub (and indeed there's warning for issue pages that they are not supported).

Do you have an example of page that works in Simplified Mode but shows hidden elements?

**Comment by tessus** [comment]
Not currently, but I will post it as soon as I come across one. I will browse different pages and use the clipper....

**Comment by laurent22** [comment]
Closing this for now as I'm not sure if that can be fixed. Let's open another issue if you find a way to replicate this bug.
