### ISSUE TITLE
WEBDav sync in Android version cannot be performed.

### ISSUE THREAD

**Issue by topxeq** [laurent22/joplin#1686]
The recent Android version of Joplin(from Google Play Store) now has an synchronizing issue. The WEBDav target cannot start even if the URL and auth info are correct. Although the PC version does it well. Please have a look, thanks.

**Comment by foxmask** [comment]
which version exaclty ?

**Comment by topxeq** [comment]
1.0.271

**Comment by hcdeeken** [comment]
Same problem and version here.

**Comment by laurent22** [comment]
http or https?

**Comment by hcdeeken** [comment]
In my case: http

Which worked in the past and still works with the linux and windows desktop clients

**Comment by tessus** [comment]
As Laurent mentioned in the forum:

_There are quite a few recent reports about Network Request Failed on the React Native repo and at least some of them seems to be related to using http, because latest Android SDK blocks these by default: https://github.com/facebook/react-native/search?q=network+request+failed&type=Issues_

While I understand this is inconvenient, macOS Objective-C has been disallowing and blocking http for over a year now. The same is true for other APIs. This will get only worse in the future.
Apparently the big players have finally decided to abolish http for good.

Maybe we can create a fix for now, but I am afraid it will be rather problematic in the future when no API allows http anymore. Therefore I really suggest to switch to https. As developers we can only use the tools that are given to us and soon http will be a thing of the past. I'm pretty sure you don't use a rotary dial phone or an acoustic coupler anymore, or do you?

**Comment by topxeq** [comment]
I use http, too. BTW, The restriction of HTTPS in iOS is not actually put into practice yet. HTTP is more convenient than https for us, and Joplin is my favorite Note App now(and important to keep personal info). Please help, thanks.

**Comment by tessus** [comment]
You got it right: _The restriction of HTTPS in iOS is not actually put into practice yet._ The operative words here are **iOS** and **YET**. What do you do, when it is?

I'm sure, Laurent will try to find a workaround and fix, but it might be too complex or not feasible. 

All I am saying is that people should start moving away from http now. You know that it will be gone at one point. Please note that I really do understand that using http is more convenient in certain circumstances, I'm not denying that fact.

It's the same as it was with openssl 0.9.8. People knew years ahead of time that it would be EOL, and what happened? Some are still using it thinking that they are safe.
Wait until the next macOS. No more 32-bit apps. Period. No ifs, ands, or buts.

**Comment by hcdeeken** [comment]
I have no problem switching to HTTPS (had planned it anyway), but I think it should not fail silently.
Some kind of error message would be helpful in these cases.

**Comment by xnedas** [comment]
Same problem with own Seafile server (http).

**Comment by tessus** [comment]
@hcdeeken 

>I think it should not fail silently.

I agree, but this depends on upstream. If we don't get any information why the network request failed (Android blocking http, react-native not getting that info or not makeing it available via an error code), there's not much we can do on Joplin's side.

**Comment by topxeq** [comment]
I spent several days to setup a https server. But the Android version still gives "Network request failed" error, while PC version works well on ssl connection(with WEBDAV). The https URL is accessible from browsers(after entering username and password), too.

**Comment by hcdeeken** [comment]
@topxeq did you use a self-signed certificate?

I just set up HTTPS on my Nextcloud instance using a certificate from LetsEncrypt and since then syncing Joplin on Android is working again.

@tessus sure, you would not be able to give a sensible error message if a transfer fails, but you could put up a warning if someone enters a HTTP URL for syncing. That would have been a lot of help, at least for me.

**Comment by topxeq** [comment]
No, I use a certificate issued by Symantec. And use caddy as https & WebDAV server.

**Comment by xnedas** [comment]
From yesterday no problems with sync. Just configured https (Let's Encrypt) connection to Seafile server.
