### ISSUE TITLE
tooling issue: “git branch --show-current” fails for me

### ISSUE THREAD

**Issue by charles-e** [laurent22/joplin#1695]
The file compile-package-info.js does an exec of ‘git branch --show-current’.  This fails.  Googling shows me that an extant way to get the current branch is: ‘git rev-parse --abbrev-ref HEAD’.

**Comment by laurent22** [comment]
@tessus, any idea about this? From the code, it seems it should handle failure and still allow the app to build? @charles-e, what error message do you have?

**Comment by tessus** [comment]
@laurent22 no, I've never heard of `git branch --show-current` not working, unless someone is using an ancient git version that might not have that option?

@charles-e which git version are you using and what is the error message? 

Even if the command fails, Joplin will still build, but it won't show the git hash and branch in the About dialog. This is not an error. This works as designed. If someonw is using an old version of git or does not have git installed, or builds from a zip file instead of using git clone, this will just be ignored.

**Comment by tessus** [comment]
Just did some checking. The option `--show-current` was introduced in git 2.22.0. If we wanted this to work with previous versions, we should indeed use `git rev-parse --abbrev-ref HEAD`.

**Comment by laurent22** [comment]
Thanks for the quick fix @tessus.

**Comment by tessus** [comment]
You are welcome.
