### ISSUE TITLE
FeatureRequest: Focus Mode / Zen Mode 

### ISSUE THREAD

**Issue by adityakeyal** [laurent22/joplin#1713]
### Operating system

 - [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- Desktop

It would be great if we can have a focus mode /  zen mode which removes all noise eg. Note List, Toolbar, etc. (Currently only Notebook/Sidebar can be toggled) and preferably an option to move to Full Screen mode. 

This feature is useful in desktop models (I use windows)

This would enable to concentrate on just writing the note.

**Comment by CalebJohn** [comment]
I know you must have seen this already by checking the forum, but have you considered using an external editor for focus mode? Many editors support it (and many editors have a much better writing experience than Joplin) and since you're changing focus anyways, using an external editor shouldn't be a burden.

Some recommendations:
1. [Mark Text](https://github.com/marktext/marktext)
2. [Typora](https://typora.io/)
3. [ghostwriter](https://wereturtle.github.io/ghostwriter/) 

All support some form of focus mode.

**Comment by adityakeyal** [comment]
I tried a couple
  - VS Code (too bulky)
 - ghostwriter (doesn't have smart paste)
Will try out mark text / typora (looks promising)
however an option to toggle notes bar at the minimum would be great. 
Since when I am working on a small screen (11 inch laptop) its a problem.
I felt having an in-built option would be nice , however I am open to other ideas. Thanks.

**Comment by CalebJohn** [comment]
@adityakeyal did one of those options work for you?

**Comment by adityakeyal** [comment]
@calebjohn - Yes for the time being I am working with Typora. For now it is free so serves my purpose.
