### ISSUE TITLE
"Advices" Typo on Encryption Options Screen (English UK) 

### ISSUE THREAD

**Issue by soyouonly** [laurent22/joplin#1798]
## Environment

Joplin version: 1.0.161
Platform: Windows 10
Language: English (UK)

## Steps To Reproduce

1. Tools > Encryption Options
2. Banner appears across Encryption Options screen stating "For more information about End-To-End Encryption (E2EE) and **advices** on how to enable it please check the documentation: https://joplinapp.org/e2ee/"
3. "Advices" is typo,

![image](https://user-images.githubusercontent.com/54069111/62944599-4d12a380-bddd-11e9-83f3-f6898fea626d.png)

Describe what you expected to happen:

Change "advices" to ["advice"](https://dictionary.cambridge.org/dictionary/english/advice) - an uncountable noun

**Comment by tessus** [comment]
Yes, there are other typos or wrong terms as well.

The problem is that English UK is the source for all other languages, which means changing it will break all translations for that entry. We'll have to change it in all translations. This is a painful process because it is not automated.
I'm thinking about writing a script that will do this automatically, but I haven't had the time yet.
