### ISSUE TITLE
An easy way to scroll to the beginning of the note

### ISSUE THREAD

**Issue by joaoreis81** [laurent22/joplin#1838]
When editing a long note, it would be nice to have a way to scroll to the beginnig of the note.

**Comment by genneko** [comment]
It's really nice to have such a way as a workaround for slow scrolling on Android app (#202 #899).

I know the problem comes from React Native as indicated in #202 but it's also true that adding text at the beginning of a long note is quite painful and sometimes almost impossible on Android.

Something like "Go To Top", "Go To Bottom" in editor mode would help to relieve the pain.

Thank you so much for the great application.
