### ISSUE TITLE
When syncing unable to verify the first certificate

### ISSUE THREAD

**Issue by griggy** [laurent22/joplin#1846]
I have configured Joplin with dropbox. Syncing used to work between mac, ubuntu and android but now I get this error on the mac and ubuntu:

request to https://content.dropboxapi.com/2/files/upload failed, reason: unable to verify the first certificate

I uninstalled Joplin and specified no encryption but the error persists.

## Environment 

Joplin version: 1.0.165
Platform: Mac (sierra) /Ubuntu (18)
OS specifcs: 

## Steps To Reproduce

1.
2.

Describe what you expected to happen:

**Comment by tessus** [comment]
@griggy the log file is missing. (For iissues like these, a log file is the only way to figure out what the problem is) Also, it worked before. So all of a sudden it doesn't and you think it's Joplin's fault? Or did you update from one version to another? If so, this information is also missing.
This is a usability question and should go in the forum. This bug tracker is for rproducible bugs.

Most likely you are in a public WLAN that hijacks your connection or you got hacked and it was a MITM attack.

In either case, please direct usability questions to the forum. I can't reproduce this, but if during the discussion on the forum we come to a point where it is, we can always re-open the issue or create a new one.
