### ISSUE TITLE
All data gone

### ISSUE THREAD

**Issue by cr1st1p** [laurent22/joplin#1895]
Yesterday, coming back home, I found my Joplin instance (running on linux) without any notes and notebooks.

## Environment

Joplin version: 1.0.161-1
Platform:Linux
OS specifcs:
Linux , Manjaro distro (Arch based).

Joplin is set up to be synchronized with a Nextcloud server to which another laptop and a mobile client are also syncing.

## Steps To Reproduce
Don't know how to reproduce.

Additional info:
- During items removal, computer was running, with no one at the keyboard.
- laptop was closed (i.e. the 2nd Joplin instance). But it had not run any sync lately. Double checked today, there is data in it.
- mobile (android): it does not appear to have synced, seems to be a manual process. Shows (probably) all  my notes.
- nextcloud shows a lot of files though. I would have expected a delete to really remove files
- nextcloud shows the last file to be changed 4 days ago (so *not* yesterday, when things went havoc)

sqlite db:
- has no records into 'notes', 'folder' , note_resources, note_tags, resources,  revisions tables
- no records into sync_items, tags tables
- has 405 records into item_changes. Most of them seem to be dated, as per created_time field around the moment the issue popped up. Field 'type' is '3' - maybe meaning a delete?

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/3647753/log.txt)
These are the log lines around the moment items seems to have been deleted.

I started joplin with debug logging enabled but it does not show anything relevant. Attached last lines from log.txt:
[log2.txt](https://github.com/laurent22/joplin/files/3647760/log2.txt)

I would appreciate, first, some advice on recovering the data.

**Comment by laurent22** [comment]
What happened is that Joplin checked the items you had locally (you had 3666 items), then checked the items on Nextcloud. On Nextcloud it found 0 item, as if everything had been wiped out, so it proceeded to delete all your local items too.

Did you change the Nextcloud directory recently?

If not could you find the log on Nextcloud from around 2019-09-23 20:27:16? It seems Nextcloud responded that you had no item on the sync target, which you say is not true so it would be good to understand why it did that.

To recover the items, you can either take them from the sync target if they are still there, or from another device. If they are all on one of your desktop devices, the best is to export to JEX and start over from this archive.

**Comment by cr1st1p** [comment]
I'll search for nextcloud logs later - I doubt they are relevant, see below.

Meanwhile:
- I remind you that I saw a lot of files in nextcloud directory. Based on this observation I did next test.
- No, I did not change Nextcloud directory 

And here's a test I did:
- ran a sync from my laptop. It got all the last changes added
  Nothing removed!
- ran a sync from my phone. It got also notes *added*
- ran a sync from my desktop - nothing appeared, all notes are still removed.

So, I see 2 issues in here:
a) what happened that desktop instance removed all notes
b) why further syncs, on different programs, are behaving differently

**Comment by laurent22** [comment]
> I'll search for nextcloud logs later - I doubt they are relevant, see below.

What could be very useful is to see the request that was made (it should be a PROPFIND call) and the response.

I'm wondering if there has been a change on Nextcloud and it returns some strange error that makes it look like an empty list instead of an error. If it's an error, Joplin would detect that and stop. If it's an empty list however it will assume there's nothing on the target and start deleting locally.

**Comment by Perkolator** [comment]
It seems to a constant problem that sync removes all notes (not taking a side who's to blame). Would it help to add a safe-guard to Joplin, that would prompt the user if Joplin is about to remove ALL notes at once? Also, implementing a trash can/folder could be used as a safe-guard for situations like this.

**Comment by laurent22** [comment]
@Perkolator, I'm thinking of just skipping sync if it finds an empty dir. Adding warnings with user confirmation on all three clients for something that happens in the background is tricky.

But I think if it's about to delete everything, just don't do it. Maybe I'll add an option in the config to override the bevahiour in the rare cases where this is what the user wants.

**Comment by Perkolator** [comment]
If the notification is hard to implement, I understand, but the problem is that the user should be notified that something is probably not right, right? The situation might not change for the better for the next sync attempt. The user is then left in the dark.

What about the trash can/folder? Would it solve this problem (too)? The trash can should be implemented so that the user **instantly** knows/sees if something is put there; for example, implementing a feature that shows the number of notes in each folder, or just in the trash can/folder? Some kind of indication of state change (maybe not notification) of the trash can/folder should implemented that would be instantly visible.

**Comment by cr1st1p** [comment]
Attached, the logs from nextcloud. Note that its time is in UTC, so a diff of 3hours vs Joplin's logs.
[nextcloud.log.gz](https://github.com/laurent22/joplin/files/3656584/nextcloud.log.gz)

To me, they look normal.
My opinion:
- deny removing all items in a single go - that is a bandaid. probably good to implement. But in its simplest form, no Trash stuff. Just mark somewhere that it happened (from the sync code), and in the UI, whenever it can, check that flag and show a popup (i.e. so that they are separate things)

- not sure if you read what I wrote, that there are 2(!) problems. i.e. next syncs did NOT bring back items, even though they were not deleted on server.

- did another test - from my laptop, I added a new note, then sync'ed the desktop version. The desktop(where all my notes are gone) said it sync'ed 1 item, but nothing appears!

Instead of doing a lot of work with the trash thing, wouldn't it be better to analyze what could have happened and *fix the actual bug*? Did I not bring enough details?

**Comment by laurent22** [comment]
> Instead of doing a lot of work with the trash thing, wouldn't it be better to analyze what could have happened and fix the actual bug? Did I not bring enough details?

So far every time the data got wiped out we found it was either a user mistake or server problem:

- User deletes their data on their server - can't fix
- User moves their data somewhere else on their server - can't fix
- Network drive gets disconnected but instead of reporting an error it reports an empty one - can't fix

So the fail-safe is designed to protect from this.

Your case seems to be different but my only guess is that Nextcloud either wrongly reported an empty dir, or exceptionally sent back a strange response format that's not understood by Joplin (but that wouldn't make sense that it does it once and never again afterwards). Unfortunately whatever was that response, it is not in the log so I don't think we'll get to the bottom of it. I'm going to make a tweak to the Joplin log so that next time I can know what happened.

> not sure if you read what I wrote, that there are 2(!) problems. i.e. next syncs did NOT bring back items, even though they were not deleted on server.

Presumably the item timestamps are before the client "last sync" state so they won't be synced. Joplin skips old items since normally it already have them.

> did another test - from my laptop, I added a new note, then sync'ed the desktop version. The desktop(where all my notes are gone) said it sync'ed 1 item, but nothing appears!

It might have synced but since the notebook doesn't exist it doesn't show up.

**Comment by laurent22** [comment]
Actually there's one clue in your log:

All PROPFIND calls return about 900KB data:

> 10.244.0.0 - cristi [23/Sep/2019:17:18:47 +0000] "PROPFIND /remote.php/webdav/Joplin/ HTTP/1.1" 207 982638 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"

But when you had this issue, the PROPFIND call exceptionally returned only 1712 bytes:

> 10.244.0.0 - cristi [23/Sep/2019:17:23:48 +0000] "PROPFIND /remote.php/webdav/Joplin/ HTTP/1.1" 207 1712 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"

So it's this 1712 that's faulty - the app requested to list the /Joplin folder and Nextcloud responded with something else, with what looks like an empty dir. It's most likely a bug in Nextcloud, but how to replicate it is the question.

**Comment by laurent22** [comment]
In fact, you can maybe report this on Nextcloud bug tracker, although I'm not sure they can do something about it without a way to replicate it or without seeing what exact response was sent back.

**Comment by cr1st1p** [comment]
previous logs were from the http part of nextcloud.
checking for what you mention, in nextcloud.log, I find this:

`{"reqId":"PSZPIqK5odQvRwmGMdve","level":3,"time":"2019-09-23T17:23:48+00:00","remoteAddr":"10.244.0.0","user":"cristi","app":"PHP","method":"PROPFIND","url":"\/remote.php\/webdav\/Joplin\/","message":"Empty row packet body at \/var\/www\/html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"node-fetch\/1.0 (+https:\/\/github.com\/bitinn\/node-fetch)","version":"13.0.5.2"}
`

I do hope that Joplin doesn't interpret ill format responses (even with 20x http ret code) as 'empty' list.
I'll see what I can do next.

**Comment by laurent22** [comment]
> I do hope that Joplin doesn't interpret ill format responses (even with 20x http ret code) as 'empty' list.

Something plainly dumb like that, no I hope not, but thanks. The WebDAV format is horribly messy though, so it's possible there's something subtle, like the error is wrapped inside a multi-response and the whole thing somehow has the properties of a resource list (which is what Joplin expects).

I don't like that Nextcloud returns 207 for what's obviously an error though. For other errors, it returns a 4xx or 5xx code.

**Comment by cr1st1p** [comment]
Digging through the rfc + nextcloud code + Joplin code. Indeed, webdav rfc seems convoluted...
I am wondering if these can be true:
a) giving back a 207 multistatus http code is ok from webdav's spec perspective, regardless of what error code bumps into as long as the error is reported somehow.
b) instead of giving a multistatus + response entries, because of the mysql exception, nextcloud returned  either an xml document  with an 'error' xml entry or a  'multistatus' + one 'error' entry.
  I do see inside Sabre (the webdav part of Nextcloud) a catch Exception block that creates an 'error' xml document, but at first look it seems it should have returned http 500.

Again, I just read for some minutes here and there, I do not know the webdav protocol, as  you do, but so far, that kind of http response seems plausible to me.
If that's the case, after a quick code check, Joplin's code though does not check for either case. It seems to just take multistatus-> response entries. To be on the safer side, I would change code to check for these 2 situations.
I'll try to also ask on nextcloud's side about this type of error.

**Comment by laurent22** [comment]
Thanks for looking into it. The fact that WebDAV can randomly return either a single response or a multi-response, even though it only got a single request is annoying, but normally shouldn't be an issue.

The code expects a `d:multistatus / d:response` structure in the XML. If that's missing or if d:response is not an array it would fail and stop syncing. The only case it would be an issue is if Nextcloud somehow returns a d:response (empty) array even in case of an error (and maybe put the error somewhere in a node or attribute). That behaviour in my opinion would be a bug as it shouldn't return a valid array if, as seems to be the case, the database query failed.

I could add additional checks for sure, but we'd need to figure out what response they send, to see what to look for in the XML. As mentioned I've added additional logging capabilities so that next time we can see the request and response directly in the Joplin log, but if you can also get info from Nextcloud that would be great.

**Comment by cr1st1p** [comment]
Just a FYI: I recovered my data (by removing everything + sync).

Unfortunately, I probably will not have time to dig into this deeper - my idea was to do another nextcloud install (a test one), and fiddle with its code to throw that db exception and check what it is sending back as a response..
So..feel free to close the bug.

And, it looks like I missed this: thank you for the Joplin program!!

**Comment by tessus** [comment]
Thanks. Please open another issue should you run into this again!
