### ISSUE TITLE
Android App Protection

### ISSUE THREAD

**Issue by bobleeSwagger2** [laurent22/joplin#1942]
Joplin NEEDS a protection measure to prevent someone from opening and seeing a blevy of private notes...this may not be due to intentionally letting someone you don't trust access your device but rather could result from malicious intent. Or, simply a child, etc.
This has been neglected long enough- it's time for action. Discussion has taken place (https://discourse.joplinapp.org/t/is-it-possible-to-password-lock-the-application-upon-opening/122). The Android OS makes this EXTREMELY simple but way of the "Biometricprompt API." This would effectively solve the issue and prevent unnecessary coding, creating a pin/password wall when one is already present at the system level. 
I am a financial supporter of this app's development and I need this matter addressed. Once it is, I will consider additional funding in the future.
Thank you

**Comment by tessus** [comment]
The feature request was never accepted on the forum. This is not going to happen.

If you have read the discussion, you'd know why this will never be implemented.
But if you really want such a useless feature, please install an app that protects other apps with a password.

**Comment by bobleeSwagger2** [comment]
Wow, you guys are arrogant. Asking paying users to install other apps that provide "useless" features is ignorant. I'm sad to see that Laurent has rude mods like you helping out. SMH 😑

**Comment by bobleeSwagger2** [comment]
Furthermore, the "so called" reasons for not implementing this make no sense. I suggested a solution that requires very little on the dev's part and solves a very important problem. Good thing there are a lot of other projects out there that actually care about suggestions- especially smart ones.

**Comment by tessus** [comment]
"paying customers"? This is an open source project and the software is free.

My phone is encrypted and secured by a passphrase, so please explain to me how setting an app password helps. Please do not forget that the data on the phone is NOT encrypted, other than by the OS encryption. Thus if someone hacks your phone, no app password will secure your data.

Let me ask you something else: so a child has your passphrase or your fingerprint to open your phone? Hmm, I gueess this child will also have your app password then. 

Name calling, very mature. Here's one for you:

How would you call a person who's using accusatory phrases in their comment (e.g. _This has been neglected long enough- it's time for action.)_ and ignores the first very clear statement at the beginning of the template?
⚠🚨⛔⛔⛔⛔⛔ ⬇ STOP & READ THIS ⬇ ⛔⛔⛔⛔⛔🚨⚠
A feature request that has not been accepted on the forum will be closed!
⚠🚨⛔⛔⛔⛔⛔ ⬆ STOP & READ THIS ⬆ ⛔⛔⛔⛔⛔🚨⚠

**Comment by bobleeSwagger2** [comment]
Wow. You almost leave me for a loss of words...
I will address your inaccuracies, then I'm done.
First, I never called you a name. A name is a noun (jerk, a$$hole, etc) of which I did not do. I did, however, use verbs to describe your comment (rude, arrogant.) 
2. Yes, paying customers. That means consumers who contribute monetary support for a product or project. I have contributed to Joplin's development several times but no more because of YOU. 
3. Adults who have children (which I hope you don't) often allow them to play appropriate games at times. If a child who is in possession of the device decides to open Joplin, they could inadvertently modify or erase notes/contents. That is one of dozens of examples I could provide to educate you on possible scenarios.
4. Have a nice life and I do hope you obtain some manners at some point. 
✌🏼

**Comment by tessus** [comment]
> First, I never called you a name. A name is a noun (jerk, a$$hole, etc) of which I did not do. I did, however, use verbs to describe your comment (rude, arrogant.)

Name calling is not limited to nouns. A common misconception. I'm too busy to explaining this, but maybe you want to have a look at https://en.wikipedia.org/wiki/Name_calling which states right at the beginning: Name calling is a form of verbal abuse in which insulting or demeaning labels are directed at an individual or group.
Yes, it is a wikipedia article, but you can also talk to a university prof, if you don't believe it.

> 2. Yes, paying customers. That means consumers who contribute monetary support for a product or project. I have contributed to Joplin's development several times but no more because of YOU.

I do not speak for Laurent, but I have only repeated what was said in that topic and in countless other topics on the forum and github.

> 3. Adults who have children (which I hope you don't) often allow them to play appropriate games at times. If a child who is in possession of the device decides to open Joplin, they could inadvertently modify or erase notes/contents. That is one of dozens of examples I could provide to educate you on possible scenarios.

I get that, but this is why there are profiles on Android and/or a guest profile. A friend of mine sets his tablet in a certain mode (via an app), where his kids can only access specific apps. So profiles are not even needed should one use an older Android OS. 
Giving a full functioning device to a child is probably not the best idea. Otherwise they might install a game which is not appropriate.
Other parents lock channels on their TV, so that kids can't watch them.

Btw, you are mean by saying something like _Adults who have children (which I hope you don't)_ . You can have a technical argument with me any time, but assuming something about my fitness to raise a child is not only mean, but inappropriate.

**Comment by bobleeSwagger2** [comment]
Look, it's this simple: my solution/suggestion was completely different than what had been discussed in the forum. In the time you have spent explaining why it shouldn't be added, it could have been added. 
I've been an app enthusiast & beta tester for years but I have never encountered someone with your attitude. If you hadn't responded in such a negative way, I probably wouldn't have replied to you like I did. If you think I'M mean or offensive, here's 3 words for you - get over it. Enjoy reading your Wiki articles and talking to professors ya snowflake
