### ISSUE TITLE
"Supprimer cette note" when selecting just ONE note

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#1951]
## Environment

Joplin version: 1.0.307
Platform: Mobile
OS specifcs: Android

## Steps To Reproduce

1. select just ONE note
2. press on the trashcan

In the confirm popup, I would like to see ""Supprimer cette note" and not "Supprimer ces notes"

**Comment by tessus** [comment]
Ok, this should be easy to fix. This looks like a good first issue. I'll add it to hacktoberfest.

Here's an explanation for people who want to work on this:

When you long press an item, the id(s) is/are available to the context menu and to the called functions. So the function that throws the popup has to check how many ids there are. If it's just one, a different message should be shown.

**Comment by laurent22** [comment]
I believe that gettext, which we use for translation has the concept of singular/plural. Don't know if would make sense to use this.

**Comment by laurent22** [comment]
Also by the way, the reason there's not two messages is that I want to keep the number of translations low. If we need to duplicate many messages like this, it can increase the translation work by quite a lot. That's why there are often tricks like "Delete note(s)?".

I think we should think how to handle this because it's not just this message but many of them.

**Comment by tessus** [comment]
That's a good point. I'm ok with using the single sentence approach, because everything else might be very tiresome.

However, for some reason in this special case only the plural is used. Thus we should change it to something like you mentioned.

Which makes it an even easier good first issue. :-)

On October 5, 2019 6:30:27 PM EDT, Laurent Cozic <notifications@github.com> wrote:
>Also by the way, the reason there's not two messages is that I want to
>keep the number of translations low. If we need to duplicate many
>messages like this, it can increase the translation work by quite a
>lot. That's why there are often tricks like "Delete note(s)?".
>
>I think we should think how to handle this because it's not just this
>message but many of them.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/laurent22/joplin/issues/1951#issuecomment-538694371

-- 
regards Helmut K. C. Tessarek

(sent from a mobile device)

**Comment by laurent22** [comment]
Plural translation is now supported 🙂
