### ISSUE TITLE
incomplete sync across joplin instances (nextcloud/owncloud)

### ISSUE THREAD

**Issue by dominikwelke** [laurent22/joplin#1959]
## Environment

Joplin version: Desktop, currently 1.0.169 (macOS) and 1.0.165 (linux). previous versions as well.
Platform: MacOS, Linux
OS specifcs: 

## bug report

hi all, thanks for the great program!

I am accessing joplin on 2 different machines (one running macOS, one running Ubuntu) with a "nextcloud"-sync set up via the settings, that actually links to an owncloud server.

**my problem is, that the sync is incomplete** (see attached screenshots, logs). 
- one machine does not download (some?) notes from the server that were created on the other machine. this seems to be the case for both macos and linux instances.
- updating existing notes (meaning those that were present when second device was added) usually works, but not 100% reliable. sometimes there are sync-conflicts (observed on linux instance) even though instances do not run at the same time. sometimes changes were not synced at all but stay local.

- newly created notes and changes from macos-instance are transferred to the owncloud server (md-files are present). changes are usually synced with linux instance, new notes usually not.
- changes from the linux instance are usally transferred and synced to owncloud and macos instance. new notes are sometimes not even uploaded to owncloud, and obviously not synced with macos joplin.

so ONE problem has to be related to the sync/indexing with the owncloud server. new notes  (and some changes) *which are present on the server* are not synced to the local instance.
a potentially separate problem could be that the linux version doesnt sync to owncloud reliably. syncing is also quite slow, some minutes.

possibly related to more general linux syncing problems? (#1023)

note that owncloud sync was set up from the macOS version, which is my primary device regarding joplin.

sorry for the messy bug report without proper testing and steps to reproduce. 

### macOS
![grafik](https://user-images.githubusercontent.com/33089761/66303354-219ec780-e8fb-11e9-8e6f-78aa7ee908ad.png)
[sync report](https://owncloud.gwdg.de/index.php/s/kSfkHcPhhXmDJf9)

### ubuntu
![grafik](https://user-images.githubusercontent.com/33089761/66303266-f87e3700-e8fa-11e9-9fe6-9ef97eb57560.png)
[sync report](https://owncloud.gwdg.de/index.php/s/5OLAiWF936AoSx4)

**Comment by laurent22** [comment]
Not much been be done without detailed steps to replicate the issue.

**Comment by fsbox666** [comment]
Hello, sorry if this post is not up to the normal level of discussion you might have, I am new to GitHub and Linux (and not a developer) but I thought that the difficulties I experiences with the sync process might still be relevant in the present thread.
I successfully set up Joplin on iOS and Mac and Sync works fine. Setting it up on Linux (Ubuntu/Budgie), I ran into a similar issue to the one described above. Actually, I first made a setup mistake and gave a webdav address without the (already existing) /Joplin folder (so simply .../remote.php/webdav) and synced from Linux. The upload of the various files went well. The I realised that I had put it the "root" folder of my University's OwnCloud without /Joplin and corrected that, thinking that this way, the local content would be erased and replaced by the content from the /Joplin folder on the cloud. This is not the case and the notes from the cloud /Joplin folder do not download.
On both iOS and MacOS on several devices the notes are still there and sync without problem. They are also still apparent in the web environment of my OwnCloud space.
I have tried several times to re-enter the webdav information, turn on and off encryption just in case, ... (and now Joplin does tell me there is a password to enter but I see this: "Missing Master Keys
The master keys with these IDs are used to encrypt some of your items, however the application does not currently have access to them. It is likely they will eventually be downloaded via synchronisation." Nothing happening, though, and not all keys are requested for the previous setups on the other devices).
Obviously, I would simply like to know how I could resolve this for myself (e.g. "reset" the sync settings? remove the saved settings in Linux and remove Joplin then "reinstall" it? ...?), but since I read the similar problem above I thought I'd also submit it to you in case there was a more general interest in this issue. If there is anything I can do to make it clearer or give more precise information, let me know. I would be glad to hear from you since the cross-platform-compatibility including Linux was one of the reasons for me to switch to Joplin. 
Other than that, in any case, congratulations and thanks for this great independent app.
