### ISSUE TITLE
Remove duplicate notes

### ISSUE THREAD

**Issue by breisfeld** [laurent22/joplin#197]
### Operating system

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [X] Desktop
- [ ] Mobile
- [ ] Terminal

First, let me say that Joplin is a great application. 

I am forced to continue to use Evernote, so my workflow involves exporting from Evernote and then importing the enex files into Joplin. It is sometimes painful to have to track which notes are already in Joplin, but a bulk move from the import folder to my target folders in Joplin creates many duplicates.

**Would it be possible to add functionality to remove notes that are identical and keep a single copy?**

Thanks.

**Comment by laurent22** [comment]
That cannot be done as Evernote export format (enex) doesn't include IDs so it's not possible to match the Evernote notes with those in Joplin.

I've tried some fuzzy matching based on title and created date at some point but it cannot be fully reliable so I dropped it.

So unfortunately the only way is to manually track the data. Evernote also does the same - if you import an enex file twice it will create duplicate notes.

**Comment by laurent22** [comment]
Sorry, no that wouldn't work as two notes with the same content (for example two reminders with the same title) would be mistaken as the same note. Also a note that had its content slightly changed since last time it was imported would be mistaken as two different notes. There are many edge cases like this that makes this solution impracticable.

**Comment by foxmask** [comment]
Could be added as a trick on the forum
