### ISSUE TITLE
Create sub-notebook by right-clicking on notebook

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#1978]
When right-clicking on a notebook, there should be a new option in the context menu:

> Create sub-notebook

That will show the regular "New notebook" dialog and associate the newly created notebook with the notebook that was clicked on.

Have a look at the `newNotebook` command for ideas on how to implement this.

**Comment by tessus** [comment]
I'm already working on this. However, I'm also adding a new menu item and toolbar icon called `New sub-notebook`.

We can't use the same menu item, because it is not possible to unselect a folder) or better said to select the root folder. Thus, if one were to use only one menu item, it would always create the folder in the selected folder.

**Comment by tessus** [comment]
see also #1629

**Comment by laurent22** [comment]
> We can't use the same menu item, because it is not possible to unselect a folder) or better said to select the root folder. Thus, if one were to use only one menu item, it would always create the folder in the selected folder.

Hmm I'm not following you. The point is to create a sub notebook so indeed it should create a notebook inside the selected notebook.

To create notebooks at the root we have the regular "New notebook" button.

**Comment by tessus** [comment]
> Hmm I'm not following you.

When I was working on this, I also wanted to use the code for the menu item, but came to the conclusion that this is not possible, because of the reason I wrote. The reason why I wanted a  menu item is to use keyboard, otherwise a mouse is needed to get the context menu.

Thus I am working on 2 things:

- the context menu item
- menu item and btoolbar button that creates a sub-notebook in the current folder

**Comment by laurent22** [comment]
Ok that makes sense. I don't think however we should have a toolbar button for this, but a menu item and shortcut would be great.

**Comment by tessus** [comment]
Ok, no toolbar button then.

About the shortcut. We do not even have one for `Create notebook`. But I'm more than happy to add a shortcut(s).

If someone can come up with a shortcut or even 2 shortcuts (one for notebook and one for sub-notebook) that would be swell.

**Comment by rallek** [comment]
I am pretty new to Joplin (and love it already :-) )
My thought about this topic:
When I added my first sub-notebook I went to the main notebook (focus on that one) and clicked on ``Create notebook``. My expectation was to have the new notebook inside my selected one. Unfortunately it was created in the root.
To create a new notebook inside the root the selection of ``notebook``s (the headline to fold an unfold the notebooks) should be possible.
Just the idea of a noncoding user :-)
