### ISSUE TITLE
Feature request: Drag&Drop, insert picture from clipboard

### ISSUE THREAD

**Issue by zelvik** [laurent22/joplin#200]
Firstly thank you for development very useful application. It could be very useful support of Drag&Drop operation for inserting files and mainly pictures, instead only attaching via attach file button. Also it could be good inserting picture from clipboard :).

### Operating system

- [ ] Windows
- [X] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

**Comment by Bellaz** [comment]
Me too! I'm making a patch to add the support for drag and drop because I think it's a very useful feature. Also the code I'm preparing allows to drop images dragged for example from a web browser (so the download -> attach file phase can be avoided).

I plan also to work on inserting images from the clipboard when I will be finished with drag-drop support.
