### ISSUE TITLE
Viewport jumps around randomly as typing

### ISSUE THREAD

**Issue by Tycholiz** [laurent22/joplin#2127]
Randomly when I am typing on the desktop app, the main text container jumps around at seemingly random times. 

As the logfile below suggests, I suspect it has something to do with syncing, though I can't be certain. At it's worst, the file jumps around more than once every second. (obviously more often than the sync is scheduled for)

## Environment

Joplin version: 1.0.170
Platform: Linux
OS specifcs: Ubuntu

## Logfile
2019-11-27 07:53:37: "SearchEngine: Updating FTS table..."
2019-11-27 07:53:38: "SearchEngine: Updated FTS table in 118ms. Inserted: 1. Deleted: 0"
2019-11-27 07:53:40: "Scheduling sync operation..."
2019-11-27 07:53:41: "Scheduling sync operation..."

**Comment by coffeejoshua** [comment]
I wanted to share this also happens on Mac + Dropbox.

Joplin 1.0.168 (prod, darwin)
Platform: MacOS
OS specifics: 10.14.16

I tried it with the console open and every time it jumps it says:
`/Applications/Joplin.app/Contents/Resources/app/gui/NoteText.min.js:707 Got ipc-message: setMarkerCount`.

It has this value:
`[0]0: 0length: 1__proto__: Array(0)concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()flat: ƒ flat()flatMap: ƒ flatMap()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toString: ƒ toString()unshift: ƒ unshift()values: ƒ values()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {copyWithin: true, entries: true, fill: true, find: true, findIndex: true, …}__proto__: Object`

I tailed the log and like @Tycholiz says it correlates exactly with:
`2019-12-20 19:46:39: "Scheduling sync operation..."`

I have sync set to every 5 minutes, and strangely, it still happens when I disable automatic sync.

**Comment by coffeejoshua** [comment]
I am suspecting it here:
https://github.com/laurent22/joplin/blob/b16dd051f1e5d7ccb2c9140c66a1ed2672787fb8/ElectronClient/app/gui/NoteText.jsx#L761-L764

I think it was changed in this commit "Desktop: Search within current note" by you @laurent22 :
https://github.com/laurent22/joplin/commit/3e313399c269598d7ad1e18d7f03ec3795827cb8

Please let me know if any additional detail is needed.

**Comment by coffeejoshua** [comment]
I've been using it extensively the last few days.  I didn't realize I was on an older version (I forgot brew cask update in my script). I updated to Joplin 1.0.176 (prod, darwin) and it's significantly better than 1.0.168.

It will only jump down occasionally now, especially if there is content or empty newlines below the current content and I press enter.  But i'll take that over the random jumping in the previous version. 
 Much better!
