### ISSUE TITLE
Pressing Ctrl + P doesn't go to previous line in Mac

### ISSUE THREAD

**Issue by junjizhi** [laurent22/joplin#2133]
## Environment

Joplin version: 1.0.174 (prod, darwin)
Platform: macOS
OS specifcs: macOS Catalina, 10.15.1

## Steps To Reproduce

1. Open Joplin app. 
2. Create a note. 
3. Pressing Ctrl + P doesn't go to previous line.

I could use Ctrl + N to go to next line, but Ctrl + P doesn't work. 

I use Emacs keybindings a lot, without Ctrl + P working, it impacts my workflow.

## Logfile
N/A

**Comment by laurent22** [comment]
@ShaneKilkelly, do you have any idea what might be the issue? I think we disable some shortcuts like ctrl+p in the editor, so that it can be processed by the app. Perhaps we should disable this part of the code when a keyboard mode is active?

**Comment by laurent22** [comment]
I might remove this feature as it's incomplete and we have noone to maintain it

**Comment by ShaneKilkelly** [comment]
Hi! Sorry it's taken a while to get around to this. 

Anyway, on the original question: nothing springs to mind immediately, and I can't test because I don't have access to a mac. I wonder if it's a collision between the pervasive emacs-style shortcuts on the MacOS platform, vs the specific key-handling code of electron/joplin/ace ?

I note that @junjizhi says that they "use emacs keybindings a lot", which could refer to either of two things:

- They use the MacOS emacs-style keybindings (which are supposed to work everywhere in the system)
- They actually use the new emacs-mode in Joplin

We'd need to clarify where exactly the problem lies. Just now (on Ubuntu), I've tried CTRL-P and it pops open the print menu, so I suspect "go to previous line" is just not something Joplin does on the CTRL-P binding anyway, regardless of keyboard mode.

Actually, scratch that, I just tried the same with the Emacs mode in joplin, and it does "go to previous line" perfectly.

So, perhaps our advice to the user should be to explicitely turn on Emacs keybindings in the Joplin options?

**Comment by laurent22** [comment]
Thanks for clarifying @ShaneKilkelly. We'll indeed need more details from you @junjizhi then, in case it's something to your setup.

**Comment by ShaneKilkelly** [comment]
I do take the wider point about the maintenance burden of supporting these new keyboard modes. I'll try to make time to look at these kind of issues :+1:

**Comment by laurent22** [comment]
Thanks @ShaneKilkelly, much appreciated.

**Comment by junjizhi** [comment]
> They use the MacOS emacs-style keybindings (which are supposed to work everywhere in the system)

@ShaneKilkelly ^This is what I meant. 

> So, perhaps our advice to the user should be to explicitely turn on Emacs keybindings in the Joplin options?

Can you advise where the option is? There wasn't anything like that in the settings in the Joplin version (1.0.174) I used. For my environment details, please see the ticket.

**Comment by ShaneKilkelly** [comment]
The option should be under the "General" section of the Options screen. See screenshot:

![image](https://user-images.githubusercontent.com/1540054/71162500-3ffe3900-2243-11ea-8dcd-2161615e5d45.png)

You can get there by selecting Tools -> Options in the menu.

**Comment by junjizhi** [comment]
@ShaneKilkelly Hah, switching to Emacs mode actually fixes the problem. Thanks!
