### ISSUE TITLE
english not move next column

### ISSUE THREAD

**Issue by 2jaeyeol** [laurent22/joplin#2170]
## Environment

Joplin version: 1.0.174
Platform:
OS specifcs: window10 64
![bug](https://user-images.githubusercontent.com/45535789/70539522-2d329700-1ba7-11ea-91fc-311f569d015e.PNG)

## Steps To Reproduce

1.
2.

Describe what you expected to happen:
english is not move next column when I not use spacebar or enter 
when I write korean , there are move next column but not english 
is that bug? if it is bug i want modify

**Comment by laurent22** [comment]
Yes that's a big I guess. Long lines should be wrapped in viewer too.

**Comment by amitsin6h** [comment]
@2jaeyeol @laurent22 I would like to work on it

**Comment by laurent22** [comment]
Thanks good @amitsin6h, if you need any help let me know.

**Comment by amitsin6h** [comment]
@laurent22 sorry for being late, I have fixed the issue. It was the webview loader that was causing the issue so I edited the index.html so that it wrap the content inside the view.

![Screenshot from 2019-12-23 00-20-17](https://user-images.githubusercontent.com/12906090/71325999-b5575b80-251a-11ea-9125-df8577768ea2.png)

**Comment by amitsin6h** [comment]
@laurent22 also I think both have different font styles and the reason both views are not similar. Let me know if I can change the font and then or I will resize the font for the preview screen so it has similar display. Or else I will send the PR.

Please let me know what to do next

**Comment by amitsin6h** [comment]
@laurent22 I am waiting for your reply so that we can close this issue

**Comment by laurent22** [comment]
Thanks for looking into it @amitsin6h. Please go ahead and create a pull request with the wrapping fix, but don't change font size as that should be discussed more in depth, possibly as part of a redesign of the app.

**Comment by amitsin6h** [comment]
@laurent22 please review my PR and also help me in resolving the conflict https://github.com/laurent22/joplin/pull/2442

**Comment by amitsin6h** [comment]
@laurent22 please review the updated PR https://github.com/laurent22/joplin/pull/2447

**Comment by laurent22** [comment]
@amitsin6h, I got three notifications to ask me to review this PR (2 from your comments, and 1 from review request). You don't need to send even one because I already get one when you create the PR, so please just don't send any notification. Your PR will be reviewed eventually when those involved have time.

**Comment by amitsin6h** [comment]
sorry for this will make sure I don't do such things again
