### ISSUE TITLE
When scrolling, the two sides are out of sync

### ISSUE THREAD

**Issue by taliove** [laurent22/joplin#2242]
## Environment

Joplin version: 1.0.175
Platform: Windows
OS specifcs: windows 10

## Steps To Reproduce

1. Create a new markdown note
2. Paste the written markdown notes
3. As you scroll through your notes, the left and right sides of the text do not correspond to each other in the title

Problem tracing:

The possible reason is that the directory was generated.
Because my notes generate a very long directory, the right side ignores that the directory takes up a lot of length when calculating the scroll interval.

**Comment by Liuhaai** [comment]
Hi, tailiove. Is this problem you describe?
<img src="https://s5.gifyu.com/images/sync_gif.gif">

**Comment by taliove** [comment]
> Hi, tailiove. Is this problem you describe?
> ![](https://camo.githubusercontent.com/d8fade96039345e3d21530f8e9716a67080c0dcf/68747470733a2f2f73352e67696679752e636f6d2f696d616765732f73796e635f6769662e676966)

Yes.
 you can use toc mark, it is easier to see this issue.

 using google translation.

---

是的。
您可以使用toc标记，可以更容易看到这个问题。

使用谷歌翻译。

**Comment by nathmo** [comment]
![image](https://user-images.githubusercontent.com/15912256/137189840-8fe71172-6943-4bb6-a991-b984826b2bcb.png)

I just updated to 
Joplin 2.4.12 (prod, win32)

Client ID: 575b4052c50746d3ac72005437976fff
Sync Version: 3
Profile Version: 39
Keychain Supported: Yes

Revision: b45585d

and the problem seems to be gone. thanks to the people who helped fixing the issue.
