### ISSUE TITLE
Add support for notebook icons

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#2268]
### Application

- Desktop
- Mobile

### Description

We would like to support notebook icons in the sidebar, as is done for example in Bear. See screenshot below:

![image](https://user-images.githubusercontent.com/48426607/55658635-32874880-57b3-11e9-97fd-387b0b7654e8.png)

### Specification

- Add a new `icon` property to the `Folder` object - it will be a string that will take any of the [Fork Awesome](https://forkaweso.me/Fork-Awesome/icons/) icon names.
- Make sure Fork Awesome is loaded in the app (it should already be) so that its icons can be displayed
- When right-clicking a notebook, change "Rename" to "Properties"
- Change the Rename dialog to a more generic Notebook Properties dialog
- Add the option to set the icon there. Initially it can be a simple text input where the user inputs the name of the icon directly. We can link to the Fork Awesome page to give the list of possible icons.
- When the user click Save, save the icon to the database
- In the sidebar, display the icon next to the notebook name.

Ideally both desktop and mobile should be supported, but it's ok to only support one of them at first.

**Comment by bedwardly-down** [comment]
I'm trying to work some on this and added a new method only to have the linter throw an error when I tried committing the addition to my branch. How do I get around that?

> 22 error joplin@1.0.0 linter: `eslint --fix --ext .js --ext .jsx --ext .ts     --ext .tsx "/home/justa/Source/git/joplin/ReactNativeClient/lib/models/Fo    lder.js"`
> 22 error Exit status 1
> 23 error Failed at the joplin@1.0.0 linter script.

**Comment by bedwardly-down** [comment]
This doesn't do anything fancy or really useful yet, but I've got a start so far on this.
![2020-01-25-014928_1920x1080_scrot](https://user-images.githubusercontent.com/59133880/73118114-35efea00-3f15-11ea-8be1-81aff7491850.png)
![2020-01-25-014944_1920x1080_scrot](https://user-images.githubusercontent.com/59133880/73118115-3be5cb00-3f15-11ea-998a-316b46ae8376.png)

**Comment by plibither8** [comment]
Hey @laurent22 and @bedwardly-down, I'd like to help out on this issue. Is there a discussion thread regarding this on Discourse?

**Comment by laurent22** [comment]
@plibither8, no, only the spec above but if you need more info feel free to ask here.

@bedwardly-down, thanks but please check the spec carefully - I do not want to clutter context menus with items like "Set icon", that's why I've put it under "Properties".

**Comment by bedwardly-down** [comment]
@plibither8 it doesn't look like it, but if you want to assist with what I've done so far, I'd gladly take it as long as you know how to use git and are willing to stay pretty consistent with how the devs have already written the code.

These steps apply to anyone regardless of proficiency that want to help out so that everything stays consistent:

1. Fork my joplin fork
2. `git clone <insert the full line that begins with git@ on your repo>` 
in a terminal or Git for Bash/Powershell if you're on Windows
![2020-01-25-075001_1920x1080_scrot](https://user-images.githubusercontent.com/59133880/73122191-ae6f9e80-3f47-11ea-80da-2579565fd7c1.png)
3. `cd joplin`
4. `npm install`
5. `git remote add upstream https://github.com/bedwardly-down/joplin.git`
this way you have access to my changes and can pull updates on the fly
6. `git fetch upstream`
to pull my branches to your repo (might not be necessary)
7. `git checkout upstream/Notebook-Icons`
the branch I'm working on for this task
8. Optional: I'd highly recommend creating your own branch (like Notebook-Icons-local) so you can test out things without messing up what I or anyone else has done. When you feel confident, send a pull request and I'll check it out.

I want to keep this completely separate from the main joplin repo until everything gets ironed out and is working. Thanks. :D

**Comment by bedwardly-down** [comment]
@laurent22 I definitely did check that out and should have been clear, but I'm trying to get the setIcon functionality set up first and then move on to the Properties part of the spec. I'm honestly having trouble getting multiple promptOptions to show when switching Rename to Properties. The options are just overriding each other with the last option being the only one showing.

**Comment by plibither8** [comment]
Thanks @bedwardly-down. I've got sufficient experience with Git so I'm pretty sure I'll be able to handle that aspect of the issue - thanks for the instructions! :)

I'll hopefully start work on this tomorrow.

**Comment by bedwardly-down** [comment]
@plibither8 you're quite welcome. My instructions definitely weren't for anyone in particular, just me laying out how I want people to go about helping me. :D

**Comment by bedwardly-down** [comment]
@plibither8 I have a NotebookPropertiesDialog class started in ElectronClient/app/gui. I'm not 100% sure how to implement everything yet but am going to mainly doing everything there with some code added where needed to get the app to register the new additions. MainScreen looks like the main area for just that.

**Comment by bedwardly-down** [comment]
@laurent22 i would live to be assigned this issue. I don't have a massive amount of experience with nodejs or reactjs but I'm great at learning on the fly and have quite a bit of experience with Java and a small handful of other languages.

**Comment by laurent22** [comment]
That's done @bedwardly-down 👍

**Comment by bedwardly-down** [comment]
@laurent22 what's your policy on progress updates for assignments? I didn't see anything about that in the Contributing Code section of the docs.

**Comment by laurent22** [comment]
No policy as of yet

**Comment by bedwardly-down** [comment]
Thanks for getting back to me. I can't sleep, so I'm working on the task as we speak.

**Comment by bedwardly-down** [comment]
Update: This isn't functional beyond the NotebookPropertiesDialog box showing up, but I have cracked how commands are linked to action so far.

![2020-01-27-100250_1920x1080_scrot](https://user-images.githubusercontent.com/59133880/73191200-b9afff00-40ec-11ea-8864-e5fa84c3e115.png)
![2020-01-27-100402_1920x1080_scrot](https://user-images.githubusercontent.com/59133880/73191210-bd438600-40ec-11ea-9e2d-a4258be10217.png)

**Comment by bedwardly-down** [comment]
I have hit a roadblock that I'm not quite sure how to get around just yet. I used the new NotePropertiesDialog class as a base for my NotebookPropertiesDialog class, altering parts of it to apply to what is relevant to Notebooks only. I also found that much of the code was a bit hacked together when I first built it, so I rebuilt the entire class from the ground up to attempt to solve some bugs I ran into. The thing is, those bugs are still prevalent and I'm still figuring things out with it.

I'll keep working at it for the next couple of days, but I may need some assistance, @laurent22. I want to keep working on it solo for a little bit longer because I'm almost certain I can figure, and if I do get through it, I'd love to work on future assignments that are related to Dialog and User Interaction. This is very much up my alley for challenge and whatnot, so thanks for assigning this to me.

**Comment by bedwardly-down** [comment]
Quite a bit of code reworking on my part. What do you think so far, @laurent22?

![2020-01-31-044517_1920x1080_scrot](https://user-images.githubusercontent.com/59133880/73533502-a189f980-43e4-11ea-8be2-54af7fa91eb2.png)

**Comment by bedwardly-down** [comment]
https://github.com/laurent22/joplin/pull/2427

**Comment by bedwardly-down** [comment]
https://github.com/laurent22/joplin/pull/2427

**Comment by idl99** [comment]
Hi @laurent22 , i'd like to work on this issue for the React Native Mobile app. Should i create a draft PR and reference it here before starting work work on it, or should i create the PR and reference it here once i've completed it?

**Comment by rabeehrz** [comment]
Working on this.
