### ISSUE TITLE
Add a scrollbar in note editor and viewer

### ISSUE THREAD

**Issue by gitoss** [laurent22/joplin#2286]
Due to the lack of (draggable) scoll bars, extensive swiping is necessary to to navigate though longer documents.

1. In Edit mode, there is no scroll bar at all

2. In View mode, the is a scroll bar when swiping, but it just indicates the position in the document and is not draggable

Please implement a working right-side, permanent scrollbar like in Android apps like QuickEdit.  The scrollbar should have a minimum width and height to make it draggable - the current View scrollbar is nearly a dot in longer documents.

Note: for the purpose of the "good first issue", it's ok to implement the scrollbar only in Edit mode or only in View mode.

## Environment

Platform: Android, iOS

**Comment by gitoss** [comment]
I just discovered the features forum, and there already is a partial thread about this:

https://discourse.joplinapp.org/t/scroll-while-editing-note-on-mobile-android-app/4587

... feel free to close this bug if this is the wrong way to track this.

**Comment by bedwardly-down** [comment]
@gitoss on iOS, I haven't noticed a major scrolling issue. My main issue is all iOS keyboards I've used hide the bottom text, making it difficult to type beyond a certain point without using an external keyboard [(here)](https://discourse.joplinapp.org/t/ios-keyboard-covering-bottom-line-while-android-version-doesnt-have-this-issue/5167/2).

Do you also have a problem with the keyboard always being on the screen when in Edit mode? I can't turn it off or hide it at all and it's a bit off putting and annoying to say the least.

**Comment by axq** [comment]
Related to https://github.com/laurent22/joplin/issues/1992

**Comment by gitoss** [comment]
Thanks, I've seen #1992, but I don't understand why "Can't be fixed as of now" results in the ticket being closed.

I hope @laurent22 tracks this problem and upcoming framework versions make a fix possible - Joplin is absolutely terific, but nearly broken scrolling in conjunction with static cursor positioning in view->edit mode make it nearly unusablle for longer documents right now. Having said that, this is the app I was looking forward for for ages!

**Comment by laurent22** [comment]
It's related to #1992 because if scrolling could accelerate it would be easier to get to the bottom of a document, but that part can't be implemented by us. We need to wait for it to be done in React Native.

I've converted this issue to a "good first issue" to give it more attention (note that I've also tweaked a bit your text and title as a result).

**Comment by rohit645** [comment]
@laurent22 Can I work on this issue?

**Comment by antreev-brar** [comment]
@laurent22 i would like to work on this issue .

**Comment by axq** [comment]
Unless the change is very complicated or controversial (code-wise), I don't think you need to wait for permission.  You can just submit a pull request that follows the guidelines.

**Comment by ishammahajan** [comment]
Doesn't seem like this is solvable in a reasonable time & complexity. Tried multiple methods, and in case anyone else wants to try this :-
1. [`react-native-webview`](https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md) does not specify any interface in order to customise the scrollbar. The scrollbar isn't by default draggable on the plugins it uses on both platforms (iOS and Android).
2. If we try to customise the webview's content itself in order to customise the scrollbar that way, that isn't possible as well. [MDN](https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md)'s page specifies that the compatibility is with WebKit webviews only, and that is disabled in our iOS app due to a bug f6688a65ae0a9bb4b7e99a749bbe7e8d76ffac4c. Regardless, changing this doesn't resolve the issue in Android either, which is curious in itself -- we do use WebKit for rendering the android webview.

W.r.t. the second point, I noticed that the CSS we send to the webview does contain the `::-webkit-scrollbar` element's customisation, which I'm not sure if it is redundant, since changing those values doesn't seem to cause any effect.
![image](https://user-images.githubusercontent.com/33200024/75315899-f73dae80-5889-11ea-9baf-6bfae2d61132.png)

@laurent22 is this redundant?

**Comment by ishammahajan** [comment]
Possible methods to solve this right now include digging into what `react-native-webview` uses to render the web pages, and perhaps changing their code (possibly requesting a feature in their repo -- although since they are only 2 developers I'm not sure if they'll be able to do it), and switching to a different renderer.
