### ISSUE TITLE
[android cleint bug] Cann't connect to webdav server!

### ISSUE THREAD

**Issue by doubletops** [laurent22/joplin#2299]
## Environment

Joplin version:1.0.312
Platform:android
OS specifcs:android 9

## Steps To Reproduce

1.Configuration--> Synchronization-->WebDAV
2.input my WEBDAV URL
3."CHECK SYNCHRONIZATION CONFIGURATION"

"Net work request filed"
But PC was no problem

**Comment by qijianjun** [comment]
Same here.
I issued an acme ssl cert for the domain `myip.xip.io`, with the url+username+password, it performs well on Windows client, but got "network request failed" error on Android client.

**Comment by zhliang119** [comment]
the same problem with you

**Comment by MercuryhgJiang** [comment]
same problem.
apk version: joplin v 1.0.316
only use http:// , can not use the tsl.

**Comment by xenogenesi** [comment]
For me it works with http but not with https, I'm using a self-signed certificate that works with the same device and url using chrome (with the certificate shown as valid) but not with the joplin android client (1.0.316), same error as above: network request failed

btw... thanks for joplin

**Comment by zhliang119** [comment]
using a self-signed certificate on windows has no problem, but it's not work on android,  error message: "Net work request filed"

**Comment by hualong1009** [comment]
Same with your problem. Client in PC work well, but Android client not. Same configure method. Android client feedback "Network request failed". Joplin is actually a good tool.
***
Joplin APP. version 1.0.316
sync by Nextcloud webDAV URL

**Comment by qijianjun** [comment]
Hi, the problem stays unresolved until the latest version.

**Comment by char32** [comment]
Just wanted to update and give some information. Seems to still exist in the latest Android version.
I use a self-signed SSL certificate (server redirects over nginx).
I pretty much cannot use a Let's encrypt cert since the server is just on my local LAN and not accessible from the outside.

I could import the CA into Android, but then it gives me a constant warning icon about "unsecure" connections in Android 10.
So application support for self-signed SSL certs would be great!

Besides that Joplin is really great! Thank you for that!
