### ISSUE TITLE
Linux Appimage does not ask for integration with OS

### ISSUE THREAD

**Issue by dpoulton-github** [laurent22/joplin#2332]
As reported in the forum for:
[1.0.178](https://discourse.joplinapp.org/t/joplin-version-1-0-178/5276/15) and 
[1.0.177](https://discourse.joplinapp.org/t/the-new-appimage-joplin-1-0-177-appimage-installation-issues/4966)

Rasied at the request of @laurent22 and on behalf of another without a GitHub account.

# Environment

Version: Joplin v1.0.178
Version: Joplin v1.0.177
OS: Linux

# Steps to reproduce

1. Download, chmod+x and run Joplin-1.0.178.Appimage.
2. No request is made by Joplin to integrate the application with the operating system

## Describe what you expected to happen:

Expected behaviour would be that Joplin asks if the user wishes to integrate Joplin with the OS.

**Comment by bedwardly-down** [comment]
I'm not sure how to fix the issue, but I did find out what changed between both AppImages. When running v1.0.175 from the command line, it throws an interesting error on Artix Linux:

![Dialog-AppImage-Joplin-175](https://user-images.githubusercontent.com/59133880/72846140-9822c380-3c65-11ea-98cf-849762911a59.png)

Artix Linux is an off shoot of Arch Linux that has some slightly different packages and a totally different configuration for running programs when booting up. Because I don't use any of the standard desktop environments (I opt for just a keyboard ran, lightweight tiling manager with almost no software installed), I'm missing what most apps look for when they need to throw a dialogue for the user. After extracting both 1.0.175's and 1.0.178's AppImages (using the `--appimage-extract` argument) and running a diff on both image's AppRun script, it looks like the above error message and information was changed:

[diffs.txt](https://github.com/laurent22/joplin/files/4093903/diffs.txt)

After running a diff between 1.0.177's and 1.0.178's AppRun scripts, there is no change between the two scripts, so I won't be providing a diff for them.

I hope that this information is helpful with squashing this bug. :D

**Comment by bedwardly-down** [comment]
Patching the AppRun script using this patch (basically, diffs.txt from the previous post, but reversed) fixed the issue on my end. 

[diffs2.txt](https://github.com/laurent22/joplin/files/4093971/diffs2.txt)


### Steps to Reproduce

1. Download, chmod +x Joplin-1.0.178.AppImage, and execute with the `--appimage-extract` argument.
2. `cd squashfs-root`
3. `patch -p1 AppRun diffs2.txt`
4. Execute `./AppRun`
5. Profit

**Comment by evilSwanson** [comment]
This problem is still present in v1.0.179

**Comment by bedwardly-down** [comment]
It looks like this is an issue that may need to be sent upstream to the AppImage devs. I thought it was something that was specific to this project and something the devs here changed but it doesn't look it.

**Comment by bedwardly-down** [comment]
@dpoulton-github you think this is an Appimage / Electron-builder upstream bug?
