### ISSUE TITLE
Clicking "yes" on update window doesn't open download link

### ISSUE THREAD

**Issue by mgrandi** [laurent22/joplin#2363]
I noticed when trying to download the latest joplin update (1.0.179) after i restarted my computer, is that the download link when you click "yes" on the auto update window doesn't actually open the download link

## Environment

Joplin version: 1.0.178
Platform: win32
OS specifcs: windows 10
browser: firefox 72.0.2 (64-bit)

## Steps To Reproduce

1. make sure browser is open
2. open joplin, or if it is already running go to help -> check for update
3. click "yes" to update
4. the browser does not open to go to the joplin download link 

Describe what you expected to happen:

the browser should go to the joplin download link

## Logfile

the log file doesn't have anything relevant 

EDIT: i thought this was because the browser was closed, but then i tried it with the browser being open, it also doesn't work

**Comment by bedwardly-down** [comment]
It would still be a good idea to have a logfile, even if it doesn't seem relevant. There maybe something the devs know that you don't about what the logs say that could be affecting you.

Also, do you have an antivirus / firewall installed that could be blocking Joplin from working? Have you tried launching Joplin from Powershell / Cmd Prompt so that you can get an idea of what's happening when you click that button? If you can paste what is said there here, that could definitely be useful for finding out what's up with Joplin on your end.

I'm not on Windows, so I can't directly try out any fixes but can definitely steer you in the right direction.

**Comment by dpoulton-github** [comment]
Joplin version: 1.0.178
Platform: Windows 10 x64 (1909)

Same here. Had to go to the Joplin web-site to download the package.

**Comment by ssnellings** [comment]
Joplin version: 1.0.178
Platform: Windows 7 x64

Same issue with it not working through the app. When I go to the joplinapp.org website manually the windows link points to the following link so I didn't download it since it's the version I'm currently on:
https://github.com/laurent22/joplin/releases/download/v1.0.178/Joplin-Setup-1.0.178.exe

I can see 1.0.179 in the releases section of github, it just isn't working through the app itself and the joplinapp.org link is a version behind. No big deal, I'll just grab it from the releases section.

Great program, thanks for all the hard work!

**Comment by mgrandi** [comment]
here are all of my logs, i moved all my old logs to a new folder, set the flags.txt to have --logLevel debug and then started the app, and clicked 'yes' on the update request

[log.txt](https://github.com/laurent22/joplin/files/4113216/log.txt)
[log-autoupdater.txt](https://github.com/laurent22/joplin/files/4113217/log-autoupdater.txt)
[log-clipper.txt](https://github.com/laurent22/joplin/files/4113218/log-clipper.txt)
[log-database.txt](https://github.com/laurent22/joplin/files/4113219/log-database.txt)

**Comment by mgrandi** [comment]
here are my logs, i edited flags.txt to have --logLevel debug and then moved my old logs to a different folder, then restarted joplin, and clicked 'yes' to to the auto update prompt

[log-clipper.txt](https://github.com/laurent22/joplin/files/4113222/log-clipper.txt)
[log.txt](https://github.com/laurent22/joplin/files/4113225/log.txt)
[log-autoupdater.txt](https://github.com/laurent22/joplin/files/4113224/log-autoupdater.txt)

**Comment by bedwardly-down** [comment]
@mgrandi This issue appears on Artix Linux, too, with nothing showing in the terminal or in my logs about it, either. It's not just a Windows issue.

**Comment by bedwardly-down** [comment]
Looks like this bug's been fixed in v1.0.179. The update message box fix in its [changelog](https://github.com/laurent22/joplin/releases/tag/v1.0.179) is just this

**Comment by tessus** [comment]
yep, fixed via 5c54b8310897694078b0a5e6dd929246aa7e71de
