### ISSUE TITLE
Incorrect KaTeX rendering

### ISSUE THREAD

**Issue by lbo34** [laurent22/joplin#2374]
As a follow up of: https://github.com/laurent22/joplin/issues/2357

Some KaTex command like '\mathbb{}' or '\mathcal{}' used to work correctly and are now rendered incorrectly. I attached a pdf exported in the past with the correct rendering and a pdf with the current rendering.

The "E" corresponds to KaTeX command '\mathbb{E}' and the D: '\mathcal{D}'

[KaTeX rendering problem - Old and Good rendering.pdf](https://github.com/laurent22/joplin/files/4114153/KaTeX.rendering.problem.-.Old.and.Good.rendering.pdf)

[KaTeX rendering - New and incorrect rendering .pdf](https://github.com/laurent22/joplin/files/4114152/KaTeX.rendering.-.New.and.incorrect.rendering.pdf)

**Comment by laurent22** [comment]
Hmm yes that's not right. I wonder if it's because the Katex fonts aren't being loaded properly.

**Comment by eh8** [comment]
The problem is that KaTeX is defaulting to a normal symbol since it could not locate a AMSMATH font file.

This can be solved by adding `KaTeX_AMS-Regular.ttf`, `KaTeX_AMS-Regular.woff`, and `KaTeX_AMS-Regular.woff2` to the katex plugin's font directory.

This should correct the appearance of these problematic characters in markdown, but I am not able to find out why I cannot see these in a exported PDF.

https://github.com/KaTeX/katex-fonts

**Comment by lbo34** [comment]
Ok.. but it used to work well...

**Comment by eh8** [comment]
For sure, this is not a full solution and it does not solve the issue of the exporting pdf.
