### ISSUE TITLE
Joplin 1.01.316 Android Samsung S9+: Joplin randomly opens a calendar popup when clicking in text, lags constantly, the cursor jumps around randomly constantly, edits are applied to the wrong parts of the text constantly, etc.

### ISSUE THREAD

**Issue by WraithGlade** [laurent22/joplin#2375]
I just started trying to migrate away from EverNote yesterday, because I've been very tired of how extraordinarily buggy and unreliable it has been for years despite how simple it should be (I only store plain text). I was trying Joplin, and initially it seemed like maybe a good system for my notes and at first I didn't see bugs, but today it is becoming clear that the program is actually extremely unstable and unreliable in a multitude of ways. I've uploaded several thousand of my EverNote notes to it and now as of today it constantly behaves extremely unpredictably and bizarrely.

Here's some of the things its been doing to me:

1. Every time I click on the screen while editing a note, if I click roughly in the middle of the screen then Joplin will sometimes randomly open a strange calendar popup (perhaps built into Joplin, perhaps from some other system app entirely, don't know). There's no apparent reason why it does this. It makes no sense.

2. Joplin constantly fails to register clicks at all, with great frequency. It's not unusual for me to have to click the back button up to 5 or 6 times in order to back out of a note.

3. The editor is generally extremely slow and laggy for anything other than very tiny notes.

4. The editor exhibits many of the same kinds of very bad editing user interface behaviors that EverNote does, such as delays when opening notes despite the fact that they are available offline, jumping the cursor always down to the bottom of a note whenever I start editing, despite this seldom ever being what I want to do, unreliable scrolling even when only working with plain text (have to grab and drag the editor cursor to scroll reliably... normal scrolling with fingers in contrast often fails and stalls and I have to keep repeatedly picking up my finger again and again), etc.

5. The cursor sometimes randomly decides to jump somewhere else in the note when I'm editing, entirely on its own accord and for no apparent reason. It can do it even when I'm not touching the screen in any way, including not even touching the edges of the screen.

6. Even when I successfully get the cursor to stay where click, sometimes the edits I subsequently make will instead be applied to a different part of the text, causing action at a distance and hence frequently damaging the text. For example, if I delete 3 characters at one point in the text it will instead go to, for example, a nearby hyperlink (or any other block of text) and delete 3 characters there instead of where the cursor was, thereby destroying content e.g. rendering a hyperlink now unusable.

7. Very slow upload speeds to Dropbox despite me having the paid version and little to no other data traffic besides Joplin to it and less than 3% storage use of 2 TB. I also have Dropbox set to not limit upload speeds currently too, but it makes no difference.

8. The complete lack of any undo function on the Android version of the app, making it hard to e.g. fix the random incoherent deletions it sometimes likes to make to my note text. It makes no sense that there's no undo available. That is a crippling limitation.

9. When the notes constantly auto save, each auto-save is often accompanied by the editor blocking until the save is done, causing all note editing to be constantly subject to random intermittent very brief moments where the entire app blocks and hence not allowing anything.

10. Random freezes besides these.

11. Copy pasting from websites into the plain text of the markdown text sometimes still picks up formatting such as bold font and temporarily applies it even while in the plain text markdown text editing page, but then it later disappears once the markdown text is exited and re-entered. This makes me suspect that even the plain text copy pasting actually grabs HTML tags and and inserts them into the markdown in invisible and potentially damaging ways.

12. Oh look, and I just found yet another problem: Joplin imported some of my notes as todo lists even though they weren't in any way todo lists and as far as I can tell don't even contain any text that corresponds to what's used in a todo list in the markdown. 

There could of course also be a bunch more issues besides this. Wherever there's some especially incoherent behavior in a program there's often a whole lot more of it hidden away. It's a very bad sign for the health of a codebase when very unrelated components of the system somehow manage to interact with each other regardless. It's the kind of thing that unstructured hacky code (code that doesn't actually model what it is supposed to in any kind of conceptually correct way) often causes. I haven't looked at the code base yet though. Just sharing that thought. Anyway though:

100% of my notes are plain text. There's no multi-media content at all.

Besides Android S9+, I also have Joplin on Windows 7 64 bit.

Note that all other apps on my entire phone are behaving perfectly normally and that I periodically scan my phone for viruses and am very careful.

**I am at my wits end with trying to find any kind of reasonable note storing/taking app.**

**It's starting to seem like there's no such thing as a well-designed reliable note app, not even for plain text apparently**. It seems ridiculous to me.

I am seriously considering that from now on I should only ever take notes as plain text documents and store them on Dropbox directly, and then text search over them with 3rd party apps (e.g. grep) or write my own code to process them. I also have considered perhaps using an Sqlite database directly to store my notes, but I can't find a good frontend for that workflow on Android.

Why is it apparently nearly impossible to find a decent plain text note storage sync system? This is absurd. There's no reason all of these kinds of bizarre bugs (listed here and also elsewhere on this GitHub account, and associated with other apps like EverNote etc) should even exist at all in such a conceptually simple app. All I want is a reliable way to store plain text notes and to append tags and organize them and search them easily and have it be reliable etc.

Oh, and there's also the fact that none of the apps for notes seem to offer any system for forming arbitrary logical expressions for combining tags together, even though that's basically the most useful and blatantly obvious way to set up a tag system to be truly useful e.g. so that you can say "give me all notes that have both tag A and tag B but not tag C" etc. That's why I was considering just literally directly using an Sqlite database instead of any kind of special "note taking" app, but I can't find any good frontend interfaces for that on Android.

I'm a hairs breadth away from forever giving up on ever having a sane note taking app and just degenerating to only ever using plain text and/or Sqlite directly.

My patience is at almost zero at this point.

I felt obligated to send in an error report. Giving precise reproduction steps is impossible though, since the app is too unreliable to even do that much. It just does all this stuff randomly for no apparent reason. It smells like memory corruption (e.g. parts of Joplin may be writing into memory they don't own) to me perhaps.

**Comment by bedwardly-down** [comment]
Ok, first of all, I completely understand your frustrations. I have a Samsung Galaxy S9+ and luckily, Joplin hasn't exhibited most of these problems, but of course, my Galaxy is my work phone and my secondary phone. I primarily run Joplin on Artix Linux and my iPhone XR with it being a backup on my Galaxy in case my iPhone messes up and also because I put some of my work related information in my notes.

1. I haven't ran into this issue yet but I have noticed that the latest updates to One UI (the launcher for Galaxy phones) is really buggy at times and my screen becomes unresponsive at random times with or without a screen protector.

2. This rarely happens on Joplin specifically, but does happen randomly with all of my work apps and even my lock screen sometimes. This seems to be a Samsung bug that is not app specific but something inherently wrong with its own software. It is definitely annoying and does sometimes make my job quite a bit harder. I am a courier and some of the apps I use require timely and precise tapping of buttons on the screen to accept or reject orders or even complete the orders.

3. Others are having similar issues across various different Android phones. #2359 and [Android Slow Search](https://discourse.joplinapp.org/search?q=android%20slow) on the forums here. I'm still digging through the code, so I'm not sure if the issue here is a Joplin one, Android one, or even possibly a bug with Reactjs, the language used heavily in the mobile ports of Joplin. I know some people have been suggesting that it may be due to how plugins are implemented and even possibly cached, but, again, I'd have to really dig into the code to get a better idea about that.

4. Joplin's User Interface on mobile definitely needs quite a bit of work. It's definitely something that is getting looked at and will hopefully be worked on during #2139 (GSoC). Now, one thing I have found to be of great use is not using the default Samsung Keyboard and replacing it with something like Fleksy or Swiftkey. I know Fleksy has the ability to hold the space bar and use it to fully navigate documents like a joystick, so you might want to check that out.

5. See 4. Also, if you have a screen protector and you get little bits of dust under it, this can definitely happen quite a bit. The Galaxy's solution for their screens not responding to touch when a screen protector is on is a bit wonky, and, IMPO, a little too sensitive at times.

6. This is where an Undo or Scratch feature would be so nice. The latter would cause all edits to be made on a copy of the original note and then, upon saving, would be integrated directly into the original. It's what Vim and a few other text editors do and is such a beautiful feature.

7. It's possible that your ISP or Phone provider may have started throttling DropBox connections if enough traffic is going through in your region. It sucks, but at least here in the US, that's a semi common thing depending on location and how many users are on at certain times. It's also not illegal for Internet Service Providers to do almost whatever they want to your connection as long as it doesn't cause you any direct harm (like internet is throttled causing the death of someone who is on life support and has a remote physician or some weird edge case).

8. I completely agree here.

9. If you set Syncing intervals to a slower rate under Configuration (like say 30 minutes to an hour or longer, or even fully disabling them altogether), this should theoretically mitigate that issue. Then you can sync as you go.

10. This could be a Samsung / Android issue since it seems to happen across multiple phones and doesn't just affect this app for me. There are other ones that have pretty bad freezing too.

11. There is a Preformatted Option available in Joplin that should help mitigate this issue, if I'm reading you correctly. Although, it's not exactly easy to use on mobile since not all keyboards have the ``` key. The devs here recommend [this keyboard](https://play.google.com/store/apps/details?id=kl.ime.oh&hl=en) for Android Phones due to it having full Markdown Support built in. I haven't used it, so I can't vouch for it.

12. If Joplin imports a note as a Todo List, it is a bit annoying. If you open the note, you'll see 3 dots on the top right. Tap that and it'll open a small menu that has an option called `Convert to note`. That should solve this problem. I haven't directly used the Importing features here much yet, so I can't relate, but I do know, it's definitely a work in progress that has some issues according to the forums and several bug reports here.

I would highly recommend browsing the [FAQ](https://joplinapp.org/faq/) and joining the [Forums](https://discourse.joplinapp.org), especially if you need help learning how to use Joplin and get around some of its quirks.

I hope me taking the time to write this all out has mitigated some of your frustration and that you may decide to stick around and use Joplin for cool things (like my [Budgeting System](https://discourse.joplinapp.org/t/simple-budget-system-setup/5205)). And, if all else fails, there's plenty of other options for note taking. If you do stick around and am active, your feedback long term may help make the app better. 

I'm definitely not one of the devs. Just a user that loves seeing software with high potential get used by people and always get better. :D

**Comment by laurent22** [comment]
Guys you don't have to write a Tolstoy novel for each bug report. Please keep it concise and actionable, or else noone will be able to work on it.

**Comment by bedwardly-down** [comment]
Sorry. 😅

**Comment by WraithGlade** [comment]
Well, Joplin looked like a good alternative initially, especially on desktop (e.g. with the nice partial Vim mode support, among other things), but I just can't keep tolerating these kinds of very buggy apps for what should be very basic foolproof bookkeeping and organization tasks.

**I've officially uninstalled the app and disconnected it from my Dropbox.** 

It was also constantly spamming Dropbox with lots of needless synchronizations. Even when there was nothing real left to sync it'd still often go through and start syncing thousands of notes again for no reason. It's been doing that all day even though I've only made like 5 new notes today. My entire note database is only ~20 MB of 100% plain text, yet it takes literally all day long to sync. 

(Why does it even do that? **Storing this stuff as tons of separate tiny files is insane**. Doing syncs in bulk as just a few files would be far faster and more reliable. The same amount of data spread over many files is often vastly slower to process on many computers than a single file of the same amount of data, because of how many file systems work. **Maybe that effect is much bigger on Windows than Linux?** A thought.)

**So anyway, don't worry**. If you don't want me to take time out of my day to send in any more of my error reports for the benefit of your app then I certainly won't anymore. I know I'm verbose and some people say overly detailed sometimes, but I'm glad to only give my reports to developers who actually want them. As such, I will bid you farewell now.

Good luck on your app. **Maybe I'll check back in more than a year and see if its stabilized**, but my experience so far is that note taking apps never fix their fundamental issues, no matter how much time passes and no matter how basic the issues seem. I've tried multiple such apps. They always either have poor features or are utterly unreliable. It's truly a testament to overengineering. Maybe one day someone will make one of these apps and have it actually be simple and stable for once. I hope. 

Anyway, that concludes my new sequel to my original "Tolstoy novel". I hope you enjoyed it. You sound like maybe more of a Twitter kind of person though, based on that comment. To each their own though, of course. Best of luck. Hopefully one day a stable note app will exist somewhere. I did have high hopes for Joplin initially.

**Comment by bedwardly-down** [comment]
@WraithGlade, if you know how to code, you could of course do what @laurent22 did and just start writing your own app to solve your issues. That's how this project started. Best of luck.

Can we get this issue closed please since it's no longer really useful?
