### ISSUE TITLE
[Request] Add homebrew installation support for Mac

### ISSUE THREAD

**Issue by benswinburne** [laurent22/joplin#25]

**Comment by laurent22** [comment]
I've submitted a pull request for it a while ago but for some reasons it hasn't been approved yet - https://github.com/Homebrew/homebrew-core/pull/20153

**Comment by benswinburne** [comment]
Ah fantastic thanks I'll keep an eye on that

**Comment by BenjaminHCCarr** [comment]
@laurent22 it likely got overlooked as applicationss are really `Casks` and not `Formulas`, `-core` is for things compiled from source, so Homebrew/homebrew-core#20153 doesn't really fit as well as `Hombrew Cask` would.

That said there is a `PR` submitted by @OranShuster for the `cask` likely approved tonight once the build passes `Travis CI`: caskroom/homebrew-cask#41482. It's being monitored by @commitay who is amazing at keeping things moving.

**Comment by laurent22** [comment]
@BenjaminHCCarr, the formula I've submitted was actually for the CLI app so it was actually fine, they've now accepted it. npm in general is not great to install binaries due to all kind of permission issues, and Homebrew is very good at solving these so it makes sense to release a formula there.

I see they've also accepted the cask formula, which is great, so I will close his issue.
