### ISSUE TITLE
Toggling formatting elements from Toolbar doesn't work.

### ISSUE THREAD

**Issue by rabeehrz** [laurent22/joplin#2560]
Styling the notes using the toolbar is buggy. When clicked elements on the toolbar, it attempts to insert new elements rather than toggle the current one. 

#### Problem
- Highlight a text
- Click on Italics. * gets added before and after the selected 
- Click on Italics again. * gets added again. But two * equals and bold text.

![Bold and Italics Error](https://s5.gifyu.com/images/boldit.gif)

#### Expected Behaviour
The italic property from the highlighted text should be removed.
Alternatively, I think it would be a good idea to change italic from * to _ (Same as the markdown in Github)

#### Problem
- Highlight a text
- Click on either Numbered, Bullet or Checkbox list. 
- Click multiple times. 

![List Error](https://s5.gifyu.com/images/listsc1f72b2ce9a630f1.gif)](https://gifyu.com/image/7Fs0)

#### Expected Behaviour
The newly created list item should be empty, or the addition and removal of the list item should be toggled. 

## Environment

Joplin version: 1.0.185 (dev, darwin)
Platform: macOS Desktop (Electron)
OS specifcs: macOS Catalina 10.15.2

**Comment by rabeehrz** [comment]
@laurent22 I would like to work on this if this is a bug.

**Comment by PackElend** [comment]
I would say yes, but let us ask @tessus as well as GH is more up to @tessus and @laurent22

**Comment by tessus** [comment]
This was never a bug. It worked like this since the beginning.

However, I do understand that a function to toggle the action would be nice. Altho8ugh it's not only Bold and Iralics, but also the code button. Although the code button is more complicated, because it creates a code block, if the selection contains at least one newline.

I would like to see this implemented, because it has a more natural feeling than the current behaviour. But these decisions lie with Laurent. Let's see what he thinks.

**Comment by PackElend** [comment]
@rabeehrz so you know what to do, looking forward to your PR

**Comment by tessus** [comment]
Well, I'd wait for @laurent22's ok first. I don't want anyone to code something that is then not merged.

**Comment by rabeehrz** [comment]
@tessus What do you think about replacing * with _ for italics? I've tested it out and it works fine in the editor.

**Comment by tessus** [comment]
Unfortunately these kind of decisions are not mine to make. It's Laurent's project. I cannot make any architectural descisions or anything that impacts everyone.
I myself use the underscore for italics, but maybe there's a reason why Laurent uses `*`. He also uses `* * *` for a hline, while I use `---`.

Theoreticlly the change should be ok, because it won't break anything, but as I said, this is not my decision. Laurent will have to decide.

**Comment by laurent22** [comment]
That would be a big change (we'd also need to update the turndown package) and not really necessary. I guess I've used stars because that's what they use in their editors on GitHub and SO.

**Comment by rabeehrz** [comment]
@laurent22 So how do you want me to proceed with this?

**Comment by tessus** [comment]
Why the turndown package? Underscores are currently supported. But this is not erally neceesary. The main reason for this discussion was about the toggling.

You have a text `bla`, select it and click `Bold`. Then you get `**bla**`, you select `**bla**`, click `Bold` and get `bla`.

**Comment by laurent22** [comment]
> Why the turndown package? 

The turndown package generates Markdown from HTML and currently uses "*" for bold/italic if I'm not mistaken.

**Comment by rabeehrz** [comment]
> You have a text `bla`, select it and click `Bold`. Then you get `**bla**`, you select `**bla**`, click `Bold` and get `bla`.
 
I will implement this and open a PR.

**Comment by rabeehrz** [comment]
@PackElend label me please.

**Comment by meyash** [comment]
Can i also contribute to this issue?

**Comment by tessus** [comment]
The person who created the PR will be the one in the commit log, since we squash the commits at merge.
But you can always help, this is up to you. If somebody gets stuck or asks for help, you decide if you want to pitch in.
