### ISSUE TITLE
iOS icon has black border - can be polished

### ISSUE THREAD

**Issue by duarteocarmo** [laurent22/joplin#2604]
The iOS icon shows a weird black border as you can see in the following screenshot:

![image](https://user-images.githubusercontent.com/26342344/75546809-bc727c80-5a29-11ea-8509-f21d2a523be6.png)

## Environment

Joplin version: 10.0.43
Platform: iOS 
OS specifics: iPhone 11 pro max on iOS 13.3.1

## Steps to reproduce

Not applicable.

## Describe what you expected to happen

Expect to not see black borders. 

## Appreciation Note

Great work guys! Keep it up!

**Comment by duarteocarmo** [comment]
I’m gonna go ahead and say it’s probably because of some icon asset having transparency.

Reference: https://stackoverflow.com/questions/26014461/black-border-on-my-ios-icon

**Comment by duarteocarmo** [comment]
Yeah, definitely has https://fotoforensics.com/analysis.php?id=2633261c933e7934408991413711802323184780.11938&show=ela

**Comment by duarteocarmo** [comment]
Would love to pull request if someone can confirm issue!

**Comment by vernvandamn** [comment]
I don’t know if you're looking for confirmation from another user but I do see the same issue on my phone.  
![PNG image](https://user-images.githubusercontent.com/8076221/75940487-32784880-5e5b-11ea-9667-812e44d87547.png)

**Comment by duarteocarmo** [comment]
@laurent22 should I upload new icons?

**Comment by amandamcg** [comment]
I noticed this also plus on Mac I also noticed that the app icon is larger than normal and doesn't have all the sizes in the .icns file.

If someone can point me to the original icon file, I can provide the assets in all the various sizes.

**Comment by amandamcg** [comment]
In digging in further, I was able to find the icons in the assets folder. I am not able to build / test the iOS and Mac apps, so I don't feel confident creating a pull request, but I used the same naming convention that was already in use to create the following: 

## iOS icons
- Changed to be square instead of roundrect, which was getting cut off
- I also noticed was that "29x3.png" is currently 96px x 96px. My version resizes it to 87px since I think the other was an oversight. 
Example: 
![60x3](https://user-images.githubusercontent.com/8716226/76284378-5fad6800-625a-11ea-849e-95b3240fa8da.png)

##Mac icons
- Changed to be slightly smaller with less corner radius, modeled off of the Finder icon
Example: 
![icon_128x128](https://user-images.githubusercontent.com/8716226/76284510-bfa40e80-625a-11ea-8039-4363e21de879.png)


##Zip of icons: [MacAndiOSIcons.zip](https://github.com/laurent22/joplin/files/4310545/MacAndiOSIcons.zip)

Hope this is helpful, I'm a very happy recent Joplin convert. Thanks for the hard work!

**Comment by duarteocarmo** [comment]
@amandamcg  nice find, thanks for the update. Same here, also not able to build source here. 

The maintainer has marked this as high priority so it hopefully should be solved soon!

**Comment by duarteocarmo** [comment]
## Issue follow up
Icons are still not completely there in mainly two places. 

## iOS
- Still shows black borders
- iPhone 11 pro max 
- Running 13.3.1
- Joplin Version 10.0.46
- Database v28

Example Screenshot:
![IMG_02FB6AD48910-1](https://user-images.githubusercontent.com/26342344/78533971-0fd6a800-77ea-11ea-9516-9512ba06c017.jpeg)

## MacOS
Icon is large compared to other icons. 
- MacOS version: Catalina 10.15.3
- Joplin Version: 1.0.197 (prod, darwin)
Example Screenshot:
![Screen Shot 2020-04-06 at 09 30 16](https://user-images.githubusercontent.com/26342344/78534486-cb97d780-77ea-11ea-80e6-d840c4736f6a.png)
