### ISSUE TITLE
External File Button Not Working Properly

### ISSUE THREAD

**Issue by mhimanshu712** [laurent22/joplin#2617]
### An ElectronClient Issue:

After clicking on "_Edit Text In External Editor_" button, the button text changes to "_watching..._" , but after closing the external editor, the text doesn't change back to "_Edit Text In External Editor_".

Here is a screenshot:<br><br>
![watch](https://user-images.githubusercontent.com/41316051/75603635-40923600-5af6-11ea-8627-7b3306810f77.gif)

**Comment by mhimanshu712** [comment]
Also I would like to work on it.
@PackElend

**Comment by PackElend** [comment]
please go ahead

**Comment by laurent22** [comment]
It works as expected as we can tell when a file has been closed in an editor (they aren't all modal editors).

**Comment by PackElend** [comment]
can't you watch local processes and listen to the one called by Joplin?

**Comment by laurent22** [comment]
No, there are too many edge cases:

- Most editors aren't modal, so even if the file is closed, the process might still be open

- Some editors (like Sublime) starts a process to open the file, then open a second process and close the first one, so we wouldn't know what the second process is. And it doesn't matter what it is anyway because it won't tell you whether the file is still open or not.

I've tried and other contributors tried to solve the problem too, but it can't be solved reliably, so now the app only reports what it can - that it is watching a file and that's all we know. Maybe the file is still being edited, maybe not.
