### ISSUE TITLE
[Feature Request] Show all notes 

### ISSUE THREAD

**Issue by travelkaefer** [laurent22/joplin#262]
### Operating system

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [X] Desktop
- [ ] Mobile
- [ ] Terminal

All notes should be shown if you click on Notebooks (like in Evernote).

**Comment by foxmask** [comment]
+1 also for mobile version / android - i'd like that :)

**Comment by msbentley** [comment]
This would be great! I often want to see the most recent notes, across all projects and folders that I am working on. I think it would also be nice to have a toggle in the settings to either have notes in subfolders shown at the parent level, or not. For example, in Evernote I have a structure like:

Project1
Project2
--- sub-topic1
--- sub-topic2

And often want to see all the notes at the Project2 level without clicking through the hierarchy. I realised I could also do this with tags... But some people may prefer the current behaviour!

**Comment by mtballday** [comment]
+1 for this on all platforms. Personally, I'd skip the checkbox and just make it behave as it does in Evernote to keep the interface simple, but I'd be happy with either.

msbentley described it pretty well -- see all the notes in a subfolders when clicking on the parent.

Also that way, if you have a top-level folder called "All" (or whatever), then you can click that to see all your notes.

(loving Joplin, BTW)

**Comment by hfccgit** [comment]
+1 I think it should be useful to have a “Show all notes” part in the notebooks section (as in evernote) so we can easily access the most recent edited notes while having them correctly categorized in the different notebooks.

In my case, I usually used this view in evernote instead of navigating through the notebooks.

**Comment by Dasymi** [comment]
Great idea. I miss this feature from Evernote.

**Comment by msbentley** [comment]
I've just installed the Android app after a break, and see that the "All notes" function is already there - yay - but not yet on desktop. It doesn't yet handle "all notes in sub-folders" but it's already a great start, especially on mobile. Is there a plan to bring the All Notes function at least to the desktop in the near future?

**Comment by macariojames** [comment]
I wonder if there's any movement on this, as they created this issue over a year and a half ago. It's annoying to have Joplin open on my phone to see a list of All Notes while typing a note on the macOS Joplin app.

**Comment by TosKam** [comment]
All notes feature is available in iPadOS. It is very useful! I hope the other platforms are also equipped with this feature.

**Comment by weippl** [comment]
Yes, it's available. Would be really useful on the desktopversion (Linux). It should be easy to implement, I would assume

**Comment by nokoa77** [comment]
Hi, I confirm that IMHO it would be a very useful feature for Desktop versions as well,
Best Regards and thanks for this beautiful app,
Bruno

**Comment by Paragon1970** [comment]
+1 This would be very usefull in the desktop enviroments.
All notes works great in the Android app.

**Comment by chumariesco** [comment]
Indeed, I was looking for this function right now in the desktop (linux) version. It would be very much appreciated!

Thanks for all the efforts teams! <33 Joplin

**Comment by mic704b** [comment]
@laurent22 how would this look on the desktop?

Like this: **Option A**
Rename `Notebooks` in the sidebar to `All Notes` and show all notes when selected?
Not sure how rolling and unrolling the Notebooks would work then.

Or perhaps: **Option B**
A new selectable item in the sidebar named `All Notes` (between `Notebooks` and `Tags`)?

Or simply like this: **Option C**
Each notebook shows notes contained in it and all it's sub-notebooks.

If option A or B, would we disable creating new notes while viewing `All Notes`?

**Comment by weippl** [comment]
I would suggest keeping it similar to the mobile version; if you use joplin on different platforms it's nice to have the same or at least a similar UI on all devices.

which is option B but the sidebar item is a the top. Would also be similar to Evernote.

**Comment by mic704b** [comment]
Thanks @wippl, I agree.

Could you confirm the behaviour wrt creating new notes?  Is it disabled when in the "All Notes" view?

**Comment by weippl** [comment]
No, you can create a new note in the "all" view. It seems to go to the first notebook in the list.

**Comment by msbentley** [comment]
The solution to this problem in Evernote is to allow one notebook to be the "default", in which notes are created in the "All Notes" view. We already have right-click actions on the notebooks, so adding a "Set as default" would be one option?

**Comment by tatoosh** [comment]
Here s screenshot that shows, no subnotes can be shown at the moment:
![image](https://user-images.githubusercontent.com/3670907/74085255-70aa6400-4a77-11ea-98a4-c6e7c766a286.png)

**Comment by tessus** [comment]
Since `All notes` is a virtual folder, it should not be possible to create a note or folder.
It should also not be possible to drag notes/folders (or copy and move) into that virtual folder.

If people want the possibilitty to create a note/folder in the `All notes` virtual folder, we would have to either 
- create a default folder (e.g.: `Default Notebook`) automatically (if it doesn't exist)
- let the user choose a default folder
- use the folder, which is the topmost one (will change depending on the sort settings of folders)

(for me in that order)

**Comment by laurent22** [comment]
Note that internally there's already a concept of default notebook, which is used in various places when the active notebook is not known. I guess we would just need to make that visible in the UI and allow the user to set it. A good place for this could be the Notebook Properties dialog that @bedwardly-down is creating.

And I agree with Weippl that option B would be best, as it would be consistent with the mobile app.

**Comment by bedwardly-down** [comment]
I like option B too and do agree but the current All Notes implementation on mobile bugs the hell out of me because it lacks one useful piece of information: it doesn't include any direct indication of which folder that note is in. If someone were to have multiple notes of the same name for whatever reason, figuring out which note is where in the current layout is a nightmare.

I propose that once my current task is fully completed and the icons are fully functional (like they are currently in my test build as we speak), I think that the notes in an All Notes should be shown with their respective Notebook's icon. If multiple Notebooks use the same icon, there should be a number indication similar to how duplicate Notes and Notebooks handle it so the user has further information about where that note is in the fold.

**Comment by mic704b** [comment]
Thanks all.  Ok, so how about to start with, we use the last used notebook (which is the current concept of default notebook).  When the notebook options dialog is available, we can later add an option for the user to override this and select a default notebook if they desire.

In any case, the notebook is shown on the note toolbar, so it is clear to the user where the note has been assigned.

**Comment by bedwardly-down** [comment]
Yeah, but it's definitely not clear on mobile, so I at least propose that the icon suggestion be implemented there, since that makes quite a bit of sense for that platform. I can definitely agree with the rest though.
