### ISSUE TITLE
Mobile: Add note count based on tags on Tags screen

### ISSUE THREAD

**Issue by amitsin6h** [laurent22/joplin#2759]
It will be a great user experience practice to show total notes counts based on tags. 

![image](https://user-images.githubusercontent.com/12906090/76687118-e8574a00-6646-11ea-90e9-d0b9f29f028d.png)

## Environment
Joplin version: 1.0.320
Platform: Mobile
OS specifics: No

## Describe what you expected to happen
I expect to show all the notes counts to the right side of the tags so that it can give a clear view of how many notes are marked with the following tags.

I will work on this change

**Comment by amitsin6h** [comment]
laurent22 let me know your thoughts on this. So, that I can start to work

**Comment by tessus** [comment]
Hmm, I can't say anything about it, because we haven't even established a good note count yet. 

IMO it would be better to fix the current count algorithm. See #2006 especially https://github.com/laurent22/joplin/pull/2006#issuecomment-552319524

Also, please do not open gh issues for ideas. We have the forum for that.
