### ISSUE TITLE
(mobile) red herring of a message: Press to set the decryption password.

### ISSUE THREAD

**Issue by taw00** [laurent22/joplin#2788]
I upgrade my desktop to 1.0.194 and it requested to upgrade the encryption type.  
I did as it asked.  
Then I edited a file.  
Then I thought, "Hmm.... I better ensure the mobile phone works before I do something out of order."

I open Joplin mobile. I see "Press to set the decryption password."  
I do as it asks.  
I verify the password is set fine for mobile.  
Still the message.  
I see there are a number of notes in "Conflicts". I delete the conflicting files on desktop and resync on both: Same message on Joplin mobile.  
I delete the note I edited on the desktop and sync both the desktop and mobile.  
With that, the message goes away.

Morale of the story: That message is baffling and identifying the actual problem needs to be improved.

**Comment by laurent22** [comment]
Not clear to me what the issue is. We'd need clear steps to replicate it.

**Comment by htyeim** [comment]
I have the same problem.

After upgraded Joplin (Macos, through `brew upgrade`), it said need reencrypt, clicked yes. After sync to nextcloud server completed in macos, I tried to sync in ios. it said "press to set the decryption password". I entered the exact password I used, but the ios app says it is wrong.
I tried to figure out what's going on. I exported all notes, deleted all files in `~/.config/joplin-desktop`,  uninstall ios app, and deleted all files in nextcloud server.
Then I imported the notes in macos, encrypted, synced, installed ios app, synced in ios.
After the master key synced, "press to set the decryption password" appeared. Then I inputted the exact password I had just set, but ios Joplin app still said the password is wrong and cann't decrypt the notes.

I think it might need to upgrade ios app?  or there are some problems with the "Reencrypt data"? or the problem is in nextcloud webdav?

**Comment by laurent22** [comment]
Right I see, the desktop pre-release version includes a way to upgrade a master key encryption, however the iOS app has not be updated yet, so it cannot decrypt this master key. I'll try to release an iOS update quickly.

**Comment by htyeim** [comment]
Thank you for the update and this great software!

**Comment by mbode** [comment]
@laurent22 Sorry to bother you – could you give any indication when an iOS release will be ready? I upgraded the master key encryption on macOS without anticipating that it would break sync to my phone. Thank you very much for everything you are doing here!

**Comment by mbode** [comment]
Ah, it is already available. Thank you so much! Imho this issue can be closed.
