### ISSUE TITLE
clipper creates first headings as second headings

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#2817]
##  Environment

Joplin version: 1.0.194 (happens with previous versions too)
Platform: macOS, clipper
OS specifics: clipper 1.0.25 (happens with previous versions too)

## Steps to reproduce

1. clip (simplified) `https://www.addictivetips.com/media-streaming/kodi/update-kodi-library/`
2. check the resulting markdown file
3. The headings do not start with `# `, but with `## `

## Describe what you expected to happen

The headings should start with `# `. The problem is that there are no headings with `# ` in the entire resulting file.
Headings should start at the first heading, not at the second level.

Not really related to that issue either but the `heading` toolbar button also creates a second heading instead of a first heading.

## Logfile

No errors. No usefule info.

**Comment by Ashray123** [comment]
I want to work on this issue could anyone guide me a little more how to reproduce it .

**Comment by tessus** [comment]
I don't understand the question. The steps to reproduce are in the description above.

**Comment by Ashray123** [comment]
@tessus  actually I am new, I don't understand the first step mentioning clip(simplified) .. any hint or suggestion would be sufficient so that I could start working on it.  Thanks!

**Comment by coderrsid** [comment]
I understand the issue. I'll work on this. Thanks @tessus for finding it out.

**Comment by dpoulton-github** [comment]
Just a view. Not based on knowledge of the clipper's workings, but could it be that the clipper considers the note **title** as the H1 / `#` and so all subsequent headers are `##` and below?

If I clip the above page my note title is "How to Update Kodi Library Both Automatically and Manually"

**Comment by tessus** [comment]
Using a title as `#` is stupid. This means that all headings are basically sub headings of the title. Imagine a book:

```
1. TITLE
1.1 Chaper one
1.2 Chapter two
...
 ```

This makes no sense. Either way, there wasn't even a H1 heading in my result. But that's not the point. The title is not a heading. It's a title.

**Comment by dpoulton-github** [comment]
I see your point but rather imagine a chapter of a book, such as a text book. Whilst the book may be titled "The History of Warrington" the chapters may be:

1 History
1.1 Early history
1.2 English Civil War
1.2.1 Notable Naughty Civil War People
1.3 Industrial history
1.4 Second World War
1.5 Post-war expansion

So, for your example URL, the site or "book" title is "Addictive Tips" and you are clipping the chapter titled "How to Update Kodi Library Both Automatically and Manually", the equivalent of "History" above. Any headings within the page become "sub-headings". Using that analogy the numbering works!

Also could it be that you did not see an H1 anywhere in your note, not because the clipper did not identify one, but because when presented with one Joplin itself treated it as the note title?

With rendered Markdown the default behaviour for # tends to be large and underlined text, which normally you would expect to see once at the top of the first page. When printed Joplin used to do just that, presenting the note title as large underlined text, just like H1. It's no longer underlined but a printed note looks like this.

![current](https://user-images.githubusercontent.com/60117449/77276294-2e995280-6cb2-11ea-9bd7-aa3cea364a9f.png)

If Joplin is changed to start headings within the note body at H1, a **default** Joplin note it will look like this and I am just not sure that that is right.

![proposed](https://user-images.githubusercontent.com/60117449/77276313-3a851480-6cb2-11ea-85e0-2e6d1ce59331.png)

**Comment by tessus** [comment]
Just because the default css sucks, doesn't mean that we can skip a heading just for the fun of it.

A title is a title. A heading is a heading. If the title looks too similar to a title, then we'll have to fix that.
Using heading 2 instead of heading one (because it's too big/ugly/whatever) is not the correct approach.

**Comment by coderrsid** [comment]
>Not really related to that issue either but the heading toolbar button also creates a second heading instead of a first heading.

I can verify this issue too. So, it should add `#` to the note right?

**Comment by tessus** [comment]
No, the solution is to start with h1 headings and not with h2 heading. Follow the replication steps above and look at the result.

You will see no heading with `#` only headings with `##`. The headings should be h1 headings instead (starting with `#`).

**Comment by coderrsid** [comment]
> You will see no heading with # only headings with ##.

Yeah i saw that too.

But after pressing Heading button in toolbar of ElectronClient, it should add `#` too instead of `##`. So we can count this as another issue too?

**Comment by tessus** [comment]
This is a separate issue and depends on Laurent. This issue is for the clipper.

I'll be off for a while. It's 5 o'clock in the morning...

**Comment by dpoulton-github** [comment]
> A title is a title. A heading is a heading.

I suppose I am saying that I can see the logic of what the clipper / Joplin is currently doing. Semantics creeps in here because if one thinks of what we have been calling the note's **title** as the note's **main heading** the logic that is currently being applied works.

I know I am not going to convince you :) Let's see what happens.

**Comment by laurent22** [comment]
Hmm, yes what happens is that Readability converts the H1 heading to the title of the page, and leave the H2 heading as-is (they are H2 in the original page too). It's not really a bug, it's just that they take out the H1 heading, which may or may not be a good idea, but something that should be discussed on the Readability repository. Joplin doesn't do anything special with heading, if they are H2 in the original page, they'll be H2 in the note.

**Comment by tessus** [comment]
Unfortunately this means that one always has to edit clipped notes, otherwise the headings are wrong.
I will try to start a discussion in the Readability repository as soon as I find the time.

**Comment by dpoulton-github** [comment]
> Unfortunately this means that one always has to edit clipped notes...

I don't (_see above_)

😉

**Comment by laurent22** [comment]
@tessus, you don't need to edit all the headings as they are actually already correct, but what you can do is copy the title of the note and put it inside the note as h1. Then the headings below will be h2 as expected.

**Comment by tessus** [comment]
@laurent22 As mentioned before, adding the title as H1 is really a no-go for me, since most clipped pages have a lot of headings, in which case I use a TOC.

Having only one first level, especially if it is the same name as the title of the note looks just stupid/weird/off. Especially if I export it to PDF.
