### ISSUE TITLE
Phrase search highlights individual words

### ISSUE THREAD

**Issue by naviji** [laurent22/joplin#2834]
When searching for "abc xyz" (with quotes) only "abc xyz" should be highlighted, not "abc" and "xyz" individually.

## Environment

Joplin version: 1.0.193
Platform: linux
OS specifics: Ubuntu 19.10

## Steps to reproduce

1. Search for "and free"
![issue1](https://user-images.githubusercontent.com/30305957/77242677-db2df280-6c26-11ea-94cd-b7aa9d2de23c.png)
![issue2](https://user-images.githubusercontent.com/30305957/77242680-e1bc6a00-6c26-11ea-988e-b36b188219c6.png)

2. The result has "and" and "free" highlighted. 

## Describe what you expected to happen

Only "and free" should be highlighted.

**Comment by coderrsid** [comment]
Thanks for pointing it out @naviji . Although, i don't consider this as a bug because it is working like a utility of multiple-word search for now. But as i looked into the issue in some cases it can be considered as a bug as when you search three words together and if any one of them is not present in the note tand the other two are present whether together or not, it shows gray screen (not found behaviour) as shown in the GIF below. But instead it should show either of two words only as highlighted. Even i am a little bit confused. @PackElend @tessus , please show some insights.

![Screen-Recording-2020-03-22-at-6](https://user-images.githubusercontent.com/35633575/77250603-1fdd7c00-6c6f-11ea-9cb1-a6753542ec0b.gif)

**Comment by PackElend** [comment]
I'm used to the way described in the bug report when using Outlook due to my work that is the tool I use most 😭, plus google. 
So I would expect that "" is taken account as described, you can also have an option, "match full text" as in Notepad++
![image](https://user-images.githubusercontent.com/3542031/77253746-945aef80-6c5c-11ea-9966-9bd2a6e45639.png)

**Comment by coderrsid** [comment]
>you can also have an option, "match full text" as in Notepad++

That would be another great way to solve this..
You agree @laurent22 ??

**Comment by Paragon1970** [comment]
In any event it would be useful (in its current form) for the returned result list to be graduated with respect to phrase query (""). Currently this does not seem to be the case.
For example: I have a note that has the phrase `Running docker non root` when searching `"Running docker"` phrase,  the returned list does not prioritise the note that has the exact match. Instead it returns notes that match docker || running || both words in any position within the document while the exact match, though found, is listed further down in the results, when ideally it should be either the first result if a single document full match or at least in the top results by hierarchical order. This in my opinion would greatly improve searching experience.
