### ISSUE TITLE
Markdown Code Syntax Highlighting

### ISSUE THREAD

**Issue by snakyjake1** [laurent22/joplin#3001]
Markdown for syntax/code is changing the color when it shouldn't

Actual Results (code syntax color changed to a green):
![image](https://user-images.githubusercontent.com/8312560/78700801-c73aef80-78ba-11ea-83f7-be96cac7cd84.png)

Expected Results (no code syntax color change):
![image](https://user-images.githubusercontent.com/8312560/78700922-fb161500-78ba-11ea-8d51-198013a25a96.png)

## Environment

Joplin 1.0.197 (prod, win32)
Profile Version: 28
Revision: 719afba0 (master)

**Comment by coderrsid** [comment]
Thanks for reporting. I'll quickly have a look into this issue.

**Comment by coderrsid** [comment]
I see that it's kind of necessary to the specified feature of `code` markdown syntax: 
![image](https://user-images.githubusercontent.com/35633575/78777252-d7d09000-79b6-11ea-8f04-281e30c4f536.png)

As you see in the above picture that it takes. it as a string type and color it `green`. But i see we have an issue here to address too.  So let's see a mentor insight.

**Comment by Rishgod** [comment]
you can use bash language preset, it will give you the desired result.

![image](https://user-images.githubusercontent.com/54576074/78898973-53ebd600-7a92-11ea-992e-c6e88163393d.png)

**Comment by dpoulton-github** [comment]
@snakyjake1 

I believe that what you are seeing is expected behaviour.

Three backticks for a fenced code block **without** a "qualifier" causes to Joplin to try to auto-detect the code within the fenced code block.

If you want a fenced clode block without any code highlighting use:

\`\`\`plaintext

There is a post on the forum that also covers this.

https://discourse.joplinapp.org/t/code-block-syntax-highlighting-text/2085/8

**Comment by snakyjake1** [comment]
I would prefer to have an option to NOT autodetect syntax highlighting.
