### ISSUE TITLE
Use quilljs for WYSIWYG editor

### ISSUE THREAD

**Issue by kaushalyap** [laurent22/joplin#3056]
It seems that [WYSIWYG editor feature](https://github.com/laurent22/joplin/issues/176) is not using [Quill](https://github.com/quilljs/quill)

Please use Quill to 

- speed up the development (no need to reinvent the wheel)
- improve reliability of the editor (Quill is matured library)

**Comment by kaushalyap** [comment]
@laurent22 May I ask why do not you use Quill?

**Comment by laurent22** [comment]
There are dozens of editors. If you think Quill is good, the best is to integrate it to Joplin, provide a proof of concept, and show how it is better than other editors. 

Otherwise we can all say editor x or y is better, they all have nice looking demos, but that means nothing if you don't look at how it can be integrated, what API they provide, what's user support like, how well maintained it is, etc.

**Comment by kaushalyap** [comment]
@laurent22 May I know which WYSIWYG editor library Joplin uses?
