### ISSUE TITLE
The input cursor leaves the text when writing cyrillic

### ISSUE THREAD

**Issue by foozzi** [laurent22/joplin#3125]
The input cursor leaves the text when writing cyrillic
<img width="246" alt="Снимок экрана 2020-04-25 в 14 29 18" src="https://user-images.githubusercontent.com/1178208/80278706-314bf500-8701-11ea-8c28-6a780ae468b7.png">

## Environment

Joplin version: 1.0.201 (prod, darwin)
Platform: macos 
OS specifics: catalina 10.15.4

## Steps to reproduce

1. create new note
2. try typing text for cyrillic

**Comment by coderrsid** [comment]
Can you also paste the cyrillic text you're trying to write in image?

**Comment by roman-r-m** [comment]
Can't reproduce on 1.0.201 on Windows

**Comment by tessus** [comment]
The default cyrillic font on macOS is not a monospace font. This has been reported several times on the forum and on github. Please search before you open a "bug".

As mentioned in the settings screen, the editor font MUST BE monospace.

**Comment by vendornet** [comment]
It's a good idea to improve the font selection window from the settings menu. Before posting this bug, I've tried to change the fonts several times. It did not work as the fonts weren't monospace. I've tried with "Courier New" and the issue was resolved. A better font suggestion for MacOS can be implemented.

Solution: Go to Preferences -> Appearance -> Editor font family -> "Courier New".
