### ISSUE TITLE
Display error when inserting korean on the text editor

### ISSUE THREAD

**Issue by PHJJJJ** [laurent22/joplin#3158]
## Environment

Joplin version: 1.0.201
Platform: Win 10
OS specifics: 

## Steps to reproduce
this error is only occurred on the text editor. the title is okay.

![ezgif com](https://user-images.githubusercontent.com/17069231/80859604-2cf18000-8c9d-11ea-93dc-73dfee9a8d29.gif)

**Comment by AllFunThing** [comment]
i have same situation in **1.0.211**

i think that problem is comming because textarea width css property changed.

![cursor](https://user-images.githubusercontent.com/50653394/82518844-3747c100-9b5b-11ea-8d79-e02871574528.gif)

<img width="816" alt="common_space 7" src="https://user-images.githubusercontent.com/50653394/82518862-3f076580-9b5b-11ea-90f7-9817164008ef.png">
noraml

<img width="816" alt="large_space 9" src="https://user-images.githubusercontent.com/50653394/82518875-462e7380-9b5b-11ea-9828-4375d739be0e.png">
overlapped

**Comment by roman-r-m** [comment]
Is your font monospace? The editor won't function correctly if it's not.

**Comment by AllFunThing** [comment]
yes, i used the monospace font that can get form [here](https://fonts.google.com/specimen/Nanum+Gothic+Coding?category=Monospace&subset=korean)(nanum gothic coding font).
