### ISSUE TITLE
Evernote Import - issue with link

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#318]
### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

### Application

- [ ] Desktop
- [x] Mobile
- [ ] Terminal

After having imported my notes, the link are not well named.

Instead of having the original content of the anchor, we a link named "link"

**Comment by laurent22** [comment]
It normally does that for empty links. Again if you have an example ENEX please post it here.

**Comment by foxmask** [comment]
to avoid to flood the issue I pasted one note here https://gist.github.com/foxmask/35e0c4bdebdafdfed5d7774b1c8bef95

**Comment by petrz12** [comment]
Hi,
I can confirm that. It happens when the href and description are the same, when ENEX file contains e.g.: `<a href="http://www.w3c.org">http://www.w3c.org</a>`.

I tracked the problem to this line: https://github.com/laurent22/joplin/blob/72fd77812e943b8a73cf2bc79aa79d5759bead21/ReactNativeClient/lib/import-enex-md-gen.js#L560

Removing the part `|| previous == url` should solve the problem.

Hope this helps.

**Comment by laurent22** [comment]
I've improved this on the Markdown side, but the rendered HTML will always display "(Link)" I'm afraid for URLs on their own, due to this: https://github.com/laurent22/joplin/blob/master/ReactNativeClient/lib/MdToHtml.js#L340

**Comment by foxmask** [comment]
It's not a big deal. Thank you

**Comment by petrz12** [comment]
Hi,
I just tried your latest fixes (commit 28dce0f) and I believe the link import or/and Markdown rendering is still not optimal yet. Since I use plain URLs almost exclusively in Evernote I started to investigate a bit. (Btw, what you have achieved with Joplin so far is an excellent job!)

Here is my Evernote x Joplin import comparison screenshot, I use ElectronClient on Mac:

<img width="1250" alt="links_evernote_x_joplin" src="https://user-images.githubusercontent.com/37639389/37856981-cd4c1ad4-2ef7-11e8-94bf-c2e4d7472345.png">

Having (Link) instead of the real URL after import is very annoying here. Surprisingly, some text that is not supposed to be a link is rendered as link. That may suggest, that there is a problem with Markdown rendering. 

Testing it further here on GitHub with handcrafted Markdown test:

---
Link Tests:

Links:
- www.google.com
- http://www.google.com
- www.apple.com
- http://www.apple.com

Not links:
- some.test
- some.text.com
- filename
- filename.link.is

Links:
- http://www.w3c.org
- http://www.google.com
- http://www.amazon.com
---

And comparing the same with Joplin Markdown rendering:

<img width="694" alt="links_joplin" src="https://user-images.githubusercontent.com/37639389/37857240-cadcda66-2ef9-11e8-99ce-3e765e568007.png">

Reveals differences between URL starting with "www" and with "http://" where the latter is rendered as "(Link)". Also e.g. "some.text.com" is rendered as a link even it should not be.

I would prefer if we can get close to GitHub Markup rendering since it is much more consistent and intuitive.

What do you think?

Thank you

**Comment by bayang** [comment]
this is very annoying for me as my daily use case is to consult list of plain links like this : 
* <www.myfirstlink.com>
* <www.secondlink.com>

which displayed nice before as underlined 'www.secondlink.com' so at first glance I could see where I was clicking, now I see tens of '(Link)' and I need to always be in dual pane view 
![screen7](https://user-images.githubusercontent.com/11558944/37861836-4db19a10-2f42-11e8-8442-573c8d151c33.png)

**Comment by laurent22** [comment]
Right, when used to store many urls like this, the (Link) thing is not a good idea. I'm going to change it back to display regular URLs.

**Comment by bayang** [comment]
Thanks Laurent I appreciate that.

**Comment by petrz12** [comment]
Laurent, it works for me as well. Many thanks!
