### ISSUE TITLE
Bugs (2) v. 1.0.214 (prod, darwin) 

### ISSUE THREAD

**Issue by ReadyResearch** [laurent22/joplin#3251]
New Joplin user, it's been absolutely great! 
Initially this was to report only one bug but I encountered a 2nd as well. 
---
Joplin 1.0.214 (prod, darwin)
Revision: ee6325e (master)
Mac 10.15.4

**STEPS:**
**#1 In WYSIWYG**
I added a new note as follows:
<img width="500" alt="2020-05-22_10-33-40" src="https://user-images.githubusercontent.com/61383653/82681134-56a62300-9c1b-11ea-80ec-bd4e7ecc1551.png">
I went to another note, when returned to this note … the result was:
<img width="500" alt="2020-05-22_10-30-51" src="https://user-images.githubusercontent.com/61383653/82681191-6d4c7a00-9c1b-11ea-8ad8-caf0026f627b.png">
NOTE: This is only occuring (so far) only on NEW notes created (since update), not on existing notes (prior this update.
In each case, I was only using WYSIWYG ‘mode’ and had not changed back/forth from WYSISYG to MD.
**#2 While in WYSIWYG … (writing this out /to report)**
**STEPS**
I placed the cursor immediately after image No. 2, (I wanted a line above text I'd already entered to add another comment ... ) and hit carriage return.
Result: When I hit the 'carriage' return, it just deleted all of the text that I had been written below.
To see if this was just a one-time thing, I added some new text and repeated the same as above. 
The text again was completely deleted.  
**DEBUG LOG:**
In order to attach the debug log, I followed the instructions and then tried to recreate the same behavior again ... (the first one). I've repeated the same steps as above several times ... but so far that same behavior hasn't happened. (It probably will after I've posted this ;-) In the console there are 6 Warnings - I can copy them if that would help?
Thanks! 
Karen

**Comment by laurent22** [comment]
> I placed the cursor immediately after image No. 2, (I wanted a line above text I'd already entered to add another comment ... ) and hit carriage return.
Result: When I hit the 'carriage' return, it just deleted all of the text that I had been written below. To see if this was just a one-time thing, I added some new text and repeated the same as above. The text again was completely deleted.

Could you export the note you used as a JEX file, so that I can replicate the bug? It doesn't happen for me.

>  I went to another note, when returned to this note … the result was:

I also can't replicate this. The text of the note "Go to this URL: .....", is that something you copied and pasted from a web page? If so, please could you give me the link of that page so that I can try the copy and paste operation?
