### ISSUE TITLE
Link displayed as text when immediately after "<br>\n"

### ISSUE THREAD

**Issue by renesugar** [laurent22/joplin#3274]
The following markdown displays as text `[Google](https://www.google.com)`:

```markdown
<br>
[Google](https://www.google.com)
```

The following markdown displays as a link:

```markdown
<br>[Google](https://www.google.com)
```

**Comment by laurent22** [comment]
You need to add a line between the `<br>` and the link, otherwise it's treated as a single HTML block - https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Cbr%3E%5Cn%5BGoogle%5D%28https%3A%2F%2Fwww.google.com%29%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D
