### ISSUE TITLE
cant unencrypt notes on android

### ISSUE THREAD

**Issue by nr458h** [laurent22/joplin#329]
### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

After I reset up my Nextcloud synchronization and activated encryption on linux I'm not able to unencrypt my notes. I tried to put a new masterkey  in the app but that only adds a new key and sync this new key but does not unencrypt my notes.

If more information are required, please tell me.

Kind regards Michael

**Comment by laurent22** [comment]
Did you let the initial synchronisation finish? Normally after a while you'll receive the master key that was initially used, and then you'll need to provide the password to unencrypt the notes. How many master keys do you have in the Encryption Config page?

**Comment by nr458h** [comment]
I think the initial sync finished. And the yellow notification came up but I was only able ro add a new masterkey (this one was added twice) So now I have three keys but I'm not able to enter the passwort for the existing masterkey. See the screenshot of the encryption-config page attached

![screenshot_20180325-133049](https://user-images.githubusercontent.com/34851898/37874512-ce89e144-3030-11e8-8bdc-063039502a3b.png)

**Comment by laurent22** [comment]
The master key you need is efa46... Did it get sync to Nextcloud? Can you check if you can find a file named "efa46.......md"? If not, it means the client on Linux didn't send the master key yet, so you'll need to wait or do a manual sync.

Basically when enabling E2EE it's better to wait for everything to get synced. If you enable manually E2EE on another client, it will create a *new* master key, but that won't allow you to decrypt the old items because they need the original master key.

See also here for more info: https://github.com/laurent22/joplin/blob/master/readme/debugging.md

**Comment by nr458h** [comment]
Thanks for support, after I deleted the other keys I was asked for the masterkey as expected.
I forgot to read the documentation, propably it would be helpful to show the link or the steps for activate encryption in rhe right way. 

Sorry for any inconvenience.

Thanks a lot for your app and your fast support! Have a nice day

- I would feel fine with closing the issue or I can chance the topic if you want to work on the UI topic

**Comment by laurent22** [comment]
There used to be a message an link to this page but I've removed. I'm going to put it back to avoid any confusion.
