### ISSUE TITLE
How to set Joplin Terminal to get the notes available from Joplin desktop ?

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#332]
### Operating system

- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [x] Terminal

I've installed the Joplin Terminal to be able (or at least try) to import notes like in #305
But when I start joplin terminal, I cant see any notes I'vz already synced with the Joplin desktop app

What's the settings we have to put with joplin terminal to point on the same place a the desktop version ?

**Comment by laurent22** [comment]
The terminal app is a separate one, so you need to sync it like the others, even if there's already a desktop one running on the same computer.

**Comment by foxmask** [comment]
Ok

**Comment by foxmask** [comment]
it's not possible even with a 
```
ln -s ~/.config/joplin-desktop/ ~/somwhere/joplin-terminal 
```
?

**Comment by laurent22** [comment]
In theory you can point the CLI client to the desktop app profile with the `--profile` flag:

    joplin --profile ~/.config/joplin-desktop/

That should work but I didn't do any tests with this, so there could be issues with two clients connecting to the same local db.

**Comment by foxmask** [comment]
ok. I'll try.

**Comment by jshum** [comment]
@foxmask , did this work for you?

**Comment by theUncanny** [comment]
I know this issue is closed, but this information may be useful for other Joplin users:

@jshum I can confirm that it worked for me to use the `--profile` flag suggest by @laurent22:

```sh
joplin --profile ~/.config/joplin-desktop/
```

Thanks @laurent22 !! :+1: 

> **Question**: I have not found this option flag in the official documentation, is it documented elsewhere?

- https://joplinapp.org/terminal/
- https://github.com/laurent22/joplin/blob/master/readme/terminal.md

It has also worked for me to use the profile option as the option suggested by @foxmask  to create a symbolic link to the directory that contains the desktop app database:

```sh
mv \
~/.config/joplin \
~/.config/joplin-terminal-bak \
&& ln -sfn \
~/.config/joplin-desktop/ \
~/.config/joplin
```
