### ISSUE TITLE
Tags that are not added to any notes are invisible

### ISSUE THREAD

**Issue by SebastianSeltmann** [laurent22/joplin#3339]
It is possible for tags to exist that are not added to any notes.
These tags do not show up in the list of tags.

## Environment

Joplin version: 1.0.216
Platform: Windows
OS specifics: Windows 10 Pro

## Steps to reproduce

1. Create a new note
2. Add a new Tag to it
3. Delete the note
4. Notice that the tag disappears from the list of Tags.
5. Notice that the tag is still present in the tags database table

## Describe what you expected to happen

I would expect the tags to still be visible, with a note count of 0.

It might be possible to fix this by removing the "WHERE notes.id IS NOT NULL" condition from the tags_with_note_count view.

**Comment by tessus** [comment]
No, this is on purpose, because tags can not be deleted.

However, you can open a feature request on the forum that not used tags are shown when you select `Add or remove tags`. Maybe in a different color (greyed out).

**Comment by SebastianSeltmann** [comment]
As a workaround, I created a new note "tagholder", which holds literally every tag I made. Now all my tags are always visible.

**Comment by tessus** [comment]
I think to remember that at one point the add tags dialog actually showed unused tags, but I could be wrong. In case I am not wrong, the current behavior is a regression. But I don't know for sure, since there've been a lot of commits and I don't have all of them in my head.

Either way, not showing unused tags in the sidebar was on purpose and this won't change.
