### ISSUE TITLE
Android: note created from share can only be saved to the default folder

### ISSUE THREAD

**Issue by roman-r-m** [laurent22/joplin#3343]
Quote from https://github.com/laurent22/joplin/pull/2870#issuecomment-640241806

> I just tried the new "share to joplin" feature under Android 9 and this is what i got:
>     Share to Joplin ---> Accetpt default name/location <---- WORKS
>     Share to Joplin ---> Change note location <---- DOESN'T WORK.
> When it doesn't work, Joplin just creates an empty note in the choosed destination named "Untitled"

**Comment by roman-r-m** [comment]
The issue is not limited to notes created by sharing to Joplin. Another way to reproduce:
* click (+) to add a new note
* before typing anything change folder
* type some text in the body and save -- the title will not be set automatically and the note will be saved as "Untitled"

**Comment by roman-r-m** [comment]
The issue in fact has nothing to do with sharing.
Seems like a leftover from when provisional notes have been introduced.

**Comment by graphixillusion** [comment]
I just tried the updated version but the issue is still here. After share, you are in a window with a auto created note with some Title and the shared content in the body: at this point, if you change the location, the "Save" buttono isn't tapable anymore and, this time, if you want to save the note you must tap on the edit button, add something to make it saves again and only now it saves in the location as Untitled but with the shared data in the body section. I hope i've explained this clearly. I think the better way is: share to joplin---> choose destination---> if auto title/body is ok, hit on save---> done without any further action.

**Comment by roman-r-m** [comment]
Are you using the version from Google Play? If so the fix for this issue has not made it into the latest version, it will be available in the next one.

**Comment by graphixillusion** [comment]
@roman-r-m ah ok then, let's wait for the next update: yes, i'm using the Google Play's version.
