### ISSUE TITLE
Malwarebytes pops up with Malware Ransomware warning and quarantines program (v1.0.224)

### ISSUE THREAD

**Issue by navlar** [laurent22/joplin#3421]
## Environment

Joplin version: 1.0.224
Platform: Windows
OS specifics: Windows Pro 10

## Steps to reproduce

1. Run Joplin
2. Malwarebytes closes Joplin and quarantines the executable

## Question

Is this version of Joplin infected or is this a false positive with Malwarebytes?
I'm not going to use it until I know it's not infected.

## Workaround

Reverted back to V1.0.220 - NO ISSUES with that version

## Logfile

Files quarantined:
- Joplin.Ink
- Joplin.exe

**Comment by laurent22** [comment]
The release seems to be clean:

Joplin Installer: https://www.virustotal.com/gui/file/b5f821d786fa27829c06943264ffe0d1f197149ab71133761b37b7033bd51d4e/detection

Joplin Portable: https://www.virustotal.com/gui/file/5f4baf9bb35766111eb69327c7e1c16517910944741f1650ff40166c8d875699/detection

In the popup where they tell you there's a virus, is there any link to report a false positive? Because we can't do anything on our side, it's just most likely a false positive by this anti-virus.
