### ISSUE TITLE
Desktop: Misleading sync message

### ISSUE THREAD

**Issue by roman-r-m** [laurent22/joplin#3424]
I've set up sync with Nextcloud and apparently mistyped the URL.
When pressing the sync button it shows after a while "Completed: 26/06/2020 21:44" but in the log I can see it actually failed with an error:
```
2020-06-26 21:44:54: "FetchError: request to http://cloud.rmusin.net/remote.php/webdav//Joplin/.sync/ failed, reason: connect ECONNREFUSED 213.168.251.194:80
Code: ECONNREFUSED
FetchError: request to http://nextcloud.host/remote.php/webdav//Joplin/.sync/ failed, reason: connect ECONNREFUSED <ip address>:80
    at ClientRequest.<anonymous> (C:\Users\MRR\AppData\Local\Temp\1dbRSt6aCXoLOne3bfdPhMi8Ydx\resources\app.asar\node_modules\node-fetch\index.js:133:11)
    at ClientRequest.emit (events.js:210:5)
    at Socket.socketErrorListener (_http_client.js:406:9)
    at Socket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)"
```

I think there should be a better indication that something has gone wrong.

**Comment by laurent22** [comment]
I have it listed as request that can be repeated https://github.com/laurent22/joplin/blob/0d2f253218e5b6bf6bd9c25c5d2d08e00b12e366/ReactNativeClient/lib/shim.js#L109 and we don't display errors for requests that can be repeated.

In your case, did it work after your synced again?

**Comment by roman-r-m** [comment]
As I later realized the problem was that I put `http` while the server was configured to only reply on https. So it didn't work until I have fixed the URL.

But it seems that its impossible to say from the error message whether it's an intermittent issue and retrying would help or not.

**Comment by laurent22** [comment]
Hmm, yes but network requests can fail in so many different ways so in some cases (like this one) it's hard to know what the issue is, and all we can do is provide the full error message.

A useful error here would be "please use https instead of http", but we can't know that from the error message actually, and adding such bespoke messages for everything would be tricky.

**Comment by roman-r-m** [comment]
Sure, there's no way to know that.
What I think would be useful is having some notification that the sync has failed. At present, it just says "Completed" which, while technically true, isn't very useful.

**Comment by jonath92** [comment]
I have a similar issue. I've synced joplin with nextcloud and didn't receive an error in the sidebar or any other notification in the GUI. However I have noticed that the filesize of the resource directory in nextcloud was much smaller than on the desktop. By investigating the .log file I then found out that some resources couldn't be synced because of a network timeout: 
```
2020-08-25 11:38:15: "FetchError: network timeout at: https://janajohnny.tk/remote.php/dav/files/johnny/apps/joplin_dev/.resource/c2afc7bc9fc64f9288d7a65fe54bfd12
FetchError: network timeout at: https://janajohnny.tk/remote.php/dav/files/johnny/apps/joplin_dev/.resource/c2afc7bc9fc64f9288d7a65fe54bfd12
    at /home/jonathan/Tmp/joplin/ElectronClient/node_modules/node-fetch/index.js:126:13"
```
The reason is that the file is pretty large. I can understand that Joplin is not able to sync such a big file to Nextcloud but as a user I really want to be notified about this in the GUI. Such an error can be overseen very easily and leading to data loss in the long time (not everybody has a good backup strategy).  

I initially thought that this is a bug in Joplin but it seems that this is actually a feature as Joplin consciously don't show errors in the sidebar for requests that can be repeated:

https://github.com/laurent22/joplin/blob/f3cb903901d474f22130b8ba9001fb20ce788574/ReactNativeClient/lib/synchronizer.js#L850-L854

I understand that it doesn't make sense to show errors in the GUI which disappears when repeating the request multiple times but  in Roman's and my case, important errors haven't been shown in the GUI because of the lines shown above. 

I actually think that the above if-clause is not useful because in the `file-api.js` file the method `tryAndRepeat`  should already make sure that a sync doesn't fail due to temporary errors.
