### ISSUE TITLE
[Feature request] - Hide todos or other notes

### ISSUE THREAD

**Issue by SamuelBlickle** [laurent22/joplin#345]
It would be nice to be able to hide todos that are already checked (and maybe other notes too). E.g. i have a lot of done todos which fill up my notebooks. I could delete them of cause but sometimes i still need the information or the files attached to the note/todo so i don't want to simply delete them. Maybe this could be done with some kind of special label?
The problem with too many todos is that regular notes get listed below all todos (done and not done) so they start disappearing somewhere deep down in the notebook. This could also be solved with an option to sort them "todos > notes > done-todos". But an option to hide elements would be nicer.

**Comment by dpunkturban** [comment]
that would be a nice feature

+1

**Comment by Abijeet** [comment]
I would also like that, but what happens when you have search? Should it list completed notes at that time? Or what if we filter by a tag, what then?

From a development stand point just having a flag that hides everything under all circumstances would be easier. To search / filter hidden notes you'd have to toggle the option under,

`View` > `Hide completed to-dos`

@laurent22 - thoughts?

**Comment by Abijeet** [comment]
@laurent22 - Hey, have you gotten a chance to review my comments?

**Comment by laurent22** [comment]
@Abijeet, I didn't look into it yet, but I've tagged it as Enhancement so it means I would accept pull requests for it.
