### ISSUE TITLE
Viewer can't scroll left, to the end of a right-aligned wide table

### ISSUE THREAD

**Issue by trespda** [laurent22/joplin#3452]
## Environment
Joplin version:
Joplin 1.0.224 (prod, win32)

Revision: 1899d86 (master)
Platform:
OS specifics:
USB portable installation
Win 10, 1909
OS build: 18363.900

## Steps to reproduce

1. In a note, enclose a line with `<div dir=rtl>` .
2. Within, create a table with long-enough string to make it wider that the viewer.
3. Tha's it. Notice the bottom scrollbar:

![3 one two Annotation 2020-07-03 143917](https://user-images.githubusercontent.com/34583545/86466181-d73c6100-bd3b-11ea-9b70-aa0102812e5c.png)

## Describe what you expected to happen

The width's scrollbar should be smaller and moveable in both directions. I presume that other types of unwrapped lines, if there are any, should be affected too.

**Comment by jdrobertso** [comment]
Out of curiosity I tried this in the new Code View editor as well, and it seems to have the same problem when wrapped in a `<div dir=rtl>`. My local build is all out of whack, but I can get it up and running and take a look at why this is happening.

![image](https://user-images.githubusercontent.com/3140223/86867992-709ba800-c099-11ea-8062-c3c951aeec18.png)

**Comment by jdrobertso** [comment]
@trespda What's your specific use case here? You mentioned you're trying to right-align the table, however, that's not what a `<div dir=rtl>` is going to do. The use case for switching the direction using a div would be if you were writing a document in Arabic or Hebrew or another right-to-left language (which would probably be pretty difficult in Joplin anyway unless I'm missing the setting that lets you swap the editor to rtl as well).

If you would like to right-align the text within a table, you should follow the guidance [here](https://vuepressbook.com/tutorial/tutorial5.html) on centering or right-aligning your table.

The behavior at current for other use cases of using a `<div dir=rtl>` to right-align things should honestly be considered a bug, because what that should do is flip all text like a mirror (which it is actually trying to do in your example image and mine, the renderer is just losing awareness of the size of the content in the case of a table).

I hope that helps with your use case. @laurent22 if you want I can still take a look at the behavior of adding a div here but I'm not sure if I'm confident enough to tinker with the mdToHtml code.

**Comment by trespda** [comment]
@jdrobertso I use Joplin to write in Hebrew. The editor looks alright, and the viewer rendering has its problems. Tables, as you can see, are flipped, which is a serious headache, and lines with mixed scripts have their direction broken.

It's not specific to Joplin, and it's hard to find a good app that has decent support for RTL. When I'm not lazy, I add the direction tag to envelop entire notes.

**Comment by jdrobertso** [comment]
@trespda Aw man, you had to pick the tough answer to that question. 😄 Oddly enough, the app that I get paid to work on had a user submit a password with Hebrew characters the other day, which entirely broke things in a brand new way, so it's cool that I'm getting to experience issues with Hebrew both places at the same time.

I'll take a look at this and see if I can find a fix for it. However, I'm finding myself pretty busy with daily life so for any future contributors (or potential contributors), please feel free to pick this up if you are so inclined.
