### ISSUE TITLE
search inside a note in android missing

### ISSUE THREAD

**Issue by danielb2** [laurent22/joplin#3476]
## Environment

Joplin version: 1.0.333
Platform: Android
OS specifics: 9

## Steps to reproduce

1. open a note
2. click the three dots in upper right
3. try to find a way to search for a string

## Describe what you expected to happen

I expect to find the search functionality in the menu, but it's missing and cannot be found anywhere

## sources
1. [[Feature Request] Search inside a note](https://github.com/laurent22/joplin/issues/382)

**Comment by danielb2** [comment]
Since this is expected and implemented behavior as per #382 isn't this a bug?

**Comment by danielb2** [comment]
bump

**Comment by danielb2** [comment]
still relevant

**Comment by danielb2** [comment]
hey @laurent22  this is kind of annoying to have to keep commenting and now creating a new issue. I created this because I want to be able to search notes in android. It's a real issue.  How can we address this ?

**Comment by laurent22** [comment]
I've re-opened the original thread - #382

**Comment by monperrus** [comment]
working on this issue, discussed in many places

* https://github.com/laurent22/joplin/issues/382 (locked by @laurent22 )
* https://github.com/laurent22/joplin/issues/3476 (this issue)
* https://discourse.joplinapp.org/t/android-app-search-inside-a-note/21572 (autolocked)
* https://discourse.joplinapp.org/t/how-to-search-for-text-in-note-android/33552 (autolocked)

Why do people believe it's not implemented? Because they don't find the search button.

The confusion is due to  the search icon appearing only in editing mode, after clicking on "edit".

One significant improvement would be to have the search icon in reading mode. Users would find it directly.
