### ISSUE TITLE
note geolocation set to 0. 0. when shared with OsmAnd~

### ISSUE THREAD

**Issue by LeoK987** [laurent22/joplin#3533]
## Environment

Joplin version: 1.0.333
Platform: Android
OS specifics: 9.1.0

## Steps to reproduce

1. create a note
2. check properties, tap View on map
3. choose OsmAnd~
4. map shown in the middle of the ocean.  check details: 0.0000S 0.0000W

Note: if choose Chrome in Step 3, then location seems correct.

**Comment by LeoK987** [comment]
still there - reply to bot

**Comment by LeoK987** [comment]
yes, issue still exists with 1.2.6

**Comment by reinhart1010** [comment]
The "Open on Map" button simply opens an OpenStreetMap URL (with zoom parameters: `https://www.openstreetmap.org/?lat=%s&lon=%s&zoom=20`). So the issue seems to be related to OsmAnd itself.

> And BTW, when open with Chrome, even though it comes up showing my neighborhood, it doesn't show a location marker of the note, whereas OsmAnd shows a marker that is at 0.0S 0.0W. So I even can't tell if Joplin sent the right location to Chrome.

This is also because the OpenStreetMap link was programmed to **not** display a marker at the center of the location.

@laurent22 I'd suggest to modify the URL parameters to display a central marker, such as https://www.openstreetmap.org/?mlat=-6.1805&mlon=106.8271&zoom=20. In this case, both `mlat` and `mlon` parameters behaves similarly with the former `lat` and `lon` parameters, but these will allow OpenStreetMap to render a marker at the center of the map, as shown below.

![image](https://user-images.githubusercontent.com/17312341/97071280-882b7c00-1609-11eb-9a56-2031d514a934.png)

I'll also be happy to open a PR for this too.

**Comment by reinhart1010** [comment]
While #3977 has been merged, it would be a good idea to test whether the issue has been actually resolved.

**Comment by LeoK987** [comment]
With Joplin 1.4.11 on the same phone as reported originally, issues remain the same as originally reported.  That is: if view details in OsmAnd app, there is a marker but it's at location 0, 0;  if view details in browser, the map shows my vicinity but there is no market.
