### ISSUE TITLE
Kanban / Board View

### ISSUE THREAD

**Issue by amandamcg** [laurent22/joplin#3567]
This is an idea I roughed out for a Board View of notes. This could be used for Kanban, Storymapping, Roadmapping, etc. You can see the original post here: https://discourse.joplinapp.org/t/kanban-plugin-idea/10271, but it is also copied below.

Here is a link to the prototype code that I used to make the gifs. Lots of wizard of oz, but just in case it is useful. https://github.com/amandamcg/joplin-new-theme-sandbox/tree/kanban

---

I keep posting about a [Kanban idea](https://discourse.joplinapp.org/t/feature-request-kanban-board-using-todo-md-format/10241/3?u=uxamanda), so I thought I'd flesh it out a little further. Seems like this will be better as a Plugin, so I will wait for that, but thought maybe I could get some feedback in the meantime. 

Caveats: I roughly used the new styles for this, but in no way is this attempting to show finalized design. Just wanted to rough out the concept. Sorry for the terrible GIF quality!

## Boards
![Board GIF](https://i.imgur.com/0ts9oIu.gif)
The way I envision this is that there is a new type of markdown file (like a note or to-do) called a board. These would appear in the normal note list, and clicking them would open them as a board. 

Each column in the board is a tag.

When it first opens, you can see that a board file is defined in yaml like traditional markdown. You can define which tag is which column, and give them an easier to read name (ready --> Ready to Review)

<details>
<summary>YAML example</summary>
<code>
<pre>
---
title: "Editorial Flow"
tags: 
- 'Blog Posts'
- 'Recipes'
type: board
columns: 
    1: 
        tag: none // this is none, so that it picks up any thing tagged "Blog Post" that doesn't have another column defined, an easy way to pickup new notes.
        name: inbox
    2: 
        tag: 'to-research'
        name: researching
    3:
        tag: 'writing'
        name: writing
    4: 
        tag: 'ready'
        name: ready for review
    5:
        tag: 'done' // i have this as an explicit "done" tag, but it would be cool if this picked up completed todo items. maybe a "done" tag if it is a note? couldn't figure out how to make that consistent, so I left it for now.
        name: done

---
</code>
</pre>
</details>

In this example, I am in the tag "Blog Posts" viewing the board "Editorial Flow".

## Notes
![Notes GIF](https://i.imgur.com/rUailNY.gif)
You can view and edit notes like normal in the right panel, just by clicking on them. You could drag the column to change the width, just like normal.

The fancy part is that dragging a note between columns automatically updates the tag.

In this example, the note "Fall Newsletter" had the tag "writing" and when I moved it, that was replaced with "ready". 

## Misc

![Miscellaneous GIF](https://i.imgur.com/O067ZDP.gif)
https://i.imgur.com/O067ZDP.gif

- Since columns are tags, when you add a column, you see a list of all the tags in use across the current notes and can add new ones.
- Since boards are just a special type of file to look at other notes, you can have many boards for the same set of notes. Think a GTD, story maps, roadmap planning etc.
- Also, you can reuse them across different tags, just by tagging the board to another collection. In this example, my Editorial Flow is tagged with "Blog Posts" and "Recipes"

**Comment by BenoitBotton** [comment]
Neat Idea Amanda. and a cool prototype

**Comment by andrewdmaclean** [comment]
This feature is definitely worth a written +1

**Comment by serpro69** [comment]
Very nice idea and prototype @amandamcg !

I wonder, since this is an "issue" in joplin now, does that mean we can expect this feature/plugin to be part of joplin sometime soon and not wait until someone decides to build a 3rd-party plugin?
This looks like it could really make me ditch trello, "todo-something-something", and a bunch of other apps and use joplin for everything from simple note-taking to GTD-lists and personal project management.

**Comment by ZwodahS** [comment]
Thanks serpro69 for the idea. I started using this last month and I already find it quite useful.
I also agree that the lack of overall view is the only problem.

One simple solution so that we don't break joplin's underlying data structure will be to just allow us to view a notebook as a board. The board will allow us to see all the sub notebooks and their notes(title) and we just need to be able to move them around the columns, which are just the various sub-notebooks. Essentially this is taking serpro69's idea and just making a view for the notebook with minimum data structure change.

We can also choose to show only the todo type notes and ignore the normal notes.

Would really love to see this.

**Comment by jrwrigh** [comment]
@ZwodahS How'd you start using this? It doesn't appear to be an actual plugin.

**Comment by ZwodahS** [comment]
@jrwrigh See the comment by serpro69.

I am doing it manually, but it work surprisingly well. Of course you don't get all the stats of a JIRA/Trello board.

**Comment by setpill** [comment]
Notebooks can be nested indefinitely, so that raises questions about how the overview should handle notes/todos that are outside of the proposed structure. To clarify, let's take the following structure.

* Notebook 1
    * Sub-notebook 1.1
        * Sub-notebook 1.1.1
            * Note A
            * Todo B
        * Note C
        * Todo D
    * Sub-notebook 1.2
        * Note E
        * Todo F
    * Sub-notebook 1.3
    * Note 1.G
    * Todo 1.H
* Notebook 2
    * Sub-notebook 2.1
        * Note I
        * Todo J
    * Sub-notebook 2.2
    * Sub-notebook 2.3
    
 Opening the Notebook 1 view might then result in the following view:
 
 * 3 columns, titled `Sub-notebook 1.1`, `Sub-notebook 1.2` and `Sub-notebook 1.3`.
 * Notes/todos C, D, E and F are visible in their respective columns.
 * Notes/todos A, B, G, H, I and J are not visible.
 
This has the strange side-effect that notes G and H, which are nested directly under Notebook 1, are not visible in the board view for Notebook 1.

**Comment by setpill** [comment]
There are benefits to using the existing notebook hierarchy, but I don't think it's the right approach here. In addition to the issue described above (to which the solution is non-trivial), it might not make sense for every notebook to have a board view. It might even be desirable to have different board views of the same notebook. E.g. one board could be separating todos into the typical "todo/doing/done", but maybe you also want to be able to sort todos into different time estimations (minutes, hours, days, weeks) so you can easily pick up something appropriate for the amount of time you have available.

**Comment by ZwodahS** [comment]
More or less agree with you. The suggestion above is for if we are not looking for a full-fledged kanban feature and just want something simple that work with existing data structure of Joplin.

**Comment by WillRieske** [comment]
[coddx ](https://github.com/coddx-hq/coddx-alpha)is a tool that can create a columnar view that is synced w/ an md file. See #3478.

**Comment by amandamcg** [comment]
FYI, this was developed into a plugin as part of Google Summer of Code (GSOC) and the first version was recently released by @mablin7. More info: https://discourse.joplinapp.org/t/kanban-board-project/17469/18 I am going to go ahead and close this issue.
