### ISSUE TITLE
Export notebook as PDF

### ISSUE THREAD

**Issue by davidromerot** [laurent22/joplin#3615]
It would be great to have the ability to export a complete notebook as a PDF file, with the notebook name as the title (and default filename) and a table of contents with hyperlinks to each page. I don't think this would be difficult to implement, but it will be very helpful.

**Comment by Tianonymus** [comment]
Until this may be implemented (or if it won't), here's a way to do this: https://github.com/Wandmalfarbe/pandoc-latex-template

**Comment by asprionj** [comment]
> Until this may be implemented (or if it won't), here's a way to do this manually: https://github.com/Wandmalfarbe/pandoc-latex-template

... this can also convert only a single MD file to PDF, right? So the missing link is a way of creating one single big MD file from all MD files in the notebook, which should be done at Joplin level (because it has all the metadata, correct cross-refs, etc.).

BTW, would be a really nice feature IMO!

**Comment by tristinDLC** [comment]
Pandoc is absolutely wonderful and I use it all the time. It does a wide variety of conversions to and from many various formats. It also has nearly infinite customizable features to build your final file exactly how you want it.

@asprionj In regards to your question about combing files into one, Pandoc can do it via `pandoc -s input1.md input2.md input3.md -o output.md` where the source (-s) is 3 separate markdown files and it creates an output (-o) markdown file. It can convert and create a wide variety of file types, but my example is what is probably most like what you're after. Theoretically, there should be a way to take the individual `.md` notes within a specified notebook and combine and convert them to a single `.pdf`. 

While I think it would be a great native feature, I think it might be better suited as a plugin so that it can use the already built robust features of Pandoc. Natively Joplin could maintain its current features of exporting to a basic HTML/MD/PDF file, but if you want finer control over your outputs, you'd run the task through the Pandoc plugin. Right now there are zero settings to alter your exported files which is a little frustrating (and should probably be its own issue ticket), so if a global export preferences page isn't created, defining Pandoc settings would be nice... honestly, probably both should happen. Native file export with basic customization settings and then if you need additional options, export via Pandoc.

**Comment by Aeternus-Sentiens** [comment]
I really want this feature. I feel like multi-page pdf export is a basic function for a note-taking application. Can this be implemented and looked over again please?
