### ISSUE TITLE
[Mobile] Joplin synchronisation doesn't run in background

### ISSUE THREAD

**Issue by Wenzel** [laurent22/joplin#3671]
Hi,

I noticed that while using Joplin on mobile, I was expecting the application to run in the **background**, and sync my notes every 30 minutes for example.

However, Joplin syncs only when the app has the focus, which is quite surprising.

Is this a bug, or a non implemented feature ? :thinking: 

Thanks !

**Comment by CalebJohn** [comment]
Hi @Wenzel Wenzel, This is a non implemented feature. You can read about some of the difficulties implementing it [here](https://discourse.joplinapp.org/t/android-background-sync-interval/1746/26).

If you have any other questions or potential bugs please bring it up on [the forum](https://discourse.joplinapp.org/) first, the github issue tracker is only supposed to be for confirmed issues. 

Since this comes up fairly frequently I'm going to drop links to some related issues in the hope that they'll be found the next time someone asked this.
https://github.com/laurent22/joplin/issues/727
https://github.com/laurent22/joplin/issues/1645
https://github.com/laurent22/joplin/issues/1501
https://github.com/laurent22/joplin/issues/1029 (ios)
