### ISSUE TITLE
Sync does work with latest versions of Android and iOS apps

### ISSUE THREAD

**Issue by n00b12345** [laurent22/joplin#3704]
## Environment

Joplin version: iOS version 10.0.52 and Database v32, Android version 1.0.339 and Database v33
Platform: iOS and Android
OS specifics: iPad OS and Android 10

## Steps to reproduce

1. Upgrade app from the play store
2. Database upgraded
3. No compatible database on iOS showing error that database version doesn't match that on client

## Describe what you expected to happen

Sync to work properly

**Comment by n00b12345** [comment]
Ideally there should have been a disclaimer or warning in the Android version about the upgraded iOS version with new database not being available.

**Comment by CalebJohn** [comment]
Looks like the iOS app was released at the same time
https://github.com/laurent22/joplin/releases/tag/ios-v10.0.53
The iOS app releases are always a few days behind due to the app review process not much can be done about it.
Of course that doesn't really help your situation, fortunately releases like this don't come around often and likely won't happen again for awhile.

**Comment by Rowabi** [comment]
Same problem with iOS here. If I understood this correctly, we have to wait for Apple to allow the update into the webshop. 
Hopefully this happens quickly.

**Comment by laurent22** [comment]
I released it yesterday so hopefully Apple should make it available either today or tomorrow.

**Comment by n00b12345** [comment]
> I released it yesterday so hopefully Apple should make it available either today or tomorrow.

It's out now! Issue resolved. I just updated it.

**Comment by Rowabi** [comment]
Great!  Best news todeay!!! 
Thanks for working on this greant product!
