### ISSUE TITLE
Duplicate notebooks following import of jex.

### ISSUE THREAD

**Issue by ufm-uk** [laurent22/joplin#3724]
Since the last update  Joplin appears to be creating a duplicate of every notebook with (1) after it.  Im using dropbox with it if that helps?

## Environment

Joplin version: 
Platform: 
OS specifics: 

## Steps to reproduce

1. Update to latest
2. Reload
3. Import a jex file, all existing notebooks get duplicated multiple times when the jex file is imported.

## Describe what you expected to happen

Just the new jex import should be created.

**Comment by boistordu** [comment]
I would really like to have a compareTo function to compare the notes that are imported ? We could maybe compare the names of the files if it's not re-generated randomly after an import.
The name of the notebooks, the name of the notes and the content. 
Because it s a bit of hassle. Or we could add a function to back it up like in standard notes on several cloud link...
Or both... what do you think?
