### ISSUE TITLE
Embedded pictures in the notes are not showing on clients running different OS

### ISSUE THREAD

**Issue by mks75** [laurent22/joplin#3739]
Hi, I just downloaded Joplin on two windows 10 and a Ubuntu 20.04 machine, and syncing notes using Nextcloud.
The notes are getting synced, but the embedded images in the notes are not getting sync from Windows to Ubuntu OS.
On Ubuntu, if you see the page in the code view, it shows the local windows 10 machine link for that picture?
Please advise.

Thanks - MKS

**Comment by CalebJohn** [comment]
It's probably possible that your attachments aren't downloading, you can check Tools -> Options -> Synchronization -> Show Advanced Settings -> Attachment download behavior
Select always and initiate a sync.

**Comment by MHoeller** [comment]
Joplin on Ubuntu 20.04 LTS and sync to  iPhone with iOS 13.6 is working

**Comment by thecursedfly** [comment]
The issue is that the **"Code View" feature breaks the image links** when the Joplin resources path is different between systems. I was also about to open a bug ticket for this.

What I noticed on Windows 10, using the portable application package is:

- when you insert an image the code becomes something like:
**![pasted_image.png](:/2597b2be6bb34165a768f5bdee2ddaac)**

- if you then switch to the code view and write anything anywhere, the code of any previously inserted image changes like:
**![pasted_image.png](file://C:/Users/username/Documents/Joplin%20Notes%20/JoplinProfile/resources/2597b2be6bb34165a768f5bdee2ddaac.png?t=1600936608728)**

The image is still visible, but if you move the location of the Joplin folder (me using a portable package, that's likely), all the image links in that note become useless.

The same happens when you sync between systems where the path to the Joplin resources folder is different. I tested this synchronizing via dropbox with my Android phone. On desktop I can see the image, while on Android I cannot.

**Comment by mks75** [comment]
Yes, I have the similar observations.
Image sync are lost when you write notes in "WYSIWYG editor" mode, as this changes the image reference. I have tested on v1.1.4 and following are the details:

[A] If you write notes in "Code View" mode, the references to images looks something like this on both Ubuntu and Win app.
![5b028863455c57408fdedd6956213122.png] (:/5e9f714fb3ea432d83c3a8b2f40562db)
The same gets sync and images shows up properly on both the app.

[B] However, now on Win app if you write something to this note in "WYSIWYG editor" mode, all the image references in this note changes to something like this.
![5b028863455c57408fdedd6956213122.png] (file://C:/Users/mks/.config/joplin-desktop/resources/5e9f714fb3ea432d83c3a8b2f40562db.png?t=1601164935901)
And soon, the same gets sync with Ubuntu app and all the images are lost on this.

[C] In Ubuntu app if you write something to this note in "WYSIWYG editor" mode, the image reference remains something like on both the apps
![a7ac47a54bf317878ebf1c490d397a0a.png] (:/2b8144c8b76f4c07a07e5970b47df903)
but on Win app the image shows a download sign icon 
![image](https://user-images.githubusercontent.com/34006918/94353288-60aeb700-003d-11eb-87e5-168ca75fc824.png)
and image doesn't show up.

Please advise.
