### ISSUE TITLE
Tab/shift-tab don't properly manage indentation (emacs mode)

### ISSUE THREAD

**Issue by meznak** [laurent22/joplin#3750]
When manipulating a list, tab no longer indents lines. If indented by adding spaces, tab indents to the deepest existing level; shift-tab unindents to the start of the line. This behavior appears specific to CodeMirror. 

## Environment

Joplin version: 1.1.1
Platform: macOS
OS specifics: 10.14.6 (Mojave)

## Steps to reproduce

0. Use Emacs mode
1. Start a list by typing a line that starts with a hyphen
2. Add a line to the list
3. Press tab to indent, but nothing happens
4. Indent the line by prefixing it with an even number of spaces
5. Add a line to the list
6. Press tab to indent, but nothing happens
7. Press shift-tab to unindent a single level, but it unindents completely
8. Press tab again to indent one level, but it indents to the deepest existing level

## Describe what you expected to happen
Tab should indent a list line by one level. Shift-tab should unindent the line one level.

## Logfile

[log-snipped.txt](https://github.com/laurent22/joplin/files/5220067/log-snipped.txt)

**Comment by CalebJohn** [comment]
Is it possible that you could get a video of the issue? This might be related to #3749  because I can't reproduce your problems here either.

I think one change that might be tripping you up is that pressing tab on a list item with text in it now inserts a tab character rather than indenting. This is probably a decision that is up for debate, but it hasn't been an issue yet.

**Comment by meznak** [comment]
Sure thing!

Probably relevant: Tab does not appear to insert tab characters, either. If I press tab mid-line, nothing happens. Continuing to type afterward places the new characters immediately after the one before tabbing.

[Screen Recording 2020-09-15 at 8.55.05 AM.mov.zip](https://github.com/laurent22/joplin/files/5226330/Screen.Recording.2020-09-15.at.8.55.05.AM.mov.zip)

**Comment by CalebJohn** [comment]
Is it possible that there is something specific about your computer that could be causing this? Custom keyboard? OS keybindings? Is there another program that could be hijacking the tab key somehow?

I really don't see what could be the issue, but I hope together we can figure it out. I'm not going to reply to #3749 for now, because I suspect these are the same issue.

**Comment by meznak** [comment]
Testing on my Linux laptop, I see the expected behavior. It's entirely possible this is a system issue, though I don't know what the cause could be.

On my mac, I am using an external keyboard and Karabiner, but testing with the keyboard unplugged and Karabiner disabled doesn't change anything. I've also exited all applications that I can (Some like Cylance can't be ended).

This looks like it might be relevant: https://github.com/codemirror/CodeMirror/issues/2428

**Comment by meznak** [comment]
I was able to narrow it down some more. If I select either the Default or Vim keyboard mode in the Joplin options, it works fine. The issue appears to be specific to Emacs mode.

**Comment by CalebJohn** [comment]
I should have asked about emacs mode first! That's almost certainly the issue. We have only defined list handling for the default keyboard mode, I guess in this case vim mode pulls some keybindings from default that emacs doesn't.

I'll look into adding the list continuation and tab/shift+tab into the emacs mode as well 👍

Thanks for putting in the work to help figure this out.

**Comment by meznak** [comment]
Excellent!

Happy to help make this great tool better.
