### ISSUE TITLE
Respect XDG_CONFIG_HOME variable, consider moving data to XDG_DATA_HOME instead

### ISSUE THREAD

**Issue by NGenetzky** [laurent22/joplin#3765]
## Environment

Joplin version: 1.1.3
Platform: Linux Joplin-1.1.3.AppImage
OS specifics: Ubuntu 20.0

## Steps to reproduce

1. Define the `XDG_CONFIG_HOME` environment variable as a writable path.
2. Start Joplin

## Describe what you expected to happen

I would expect the configuration (and data) to be located under the directory specified by `XDG_CONFIG_HOME` (`${XDG_CONFIG_HOME}/joplin-desktop/`).

Alternatively, it does seem like XDG_DATA_HOME might be a better location, but this would probably be a hard change to make, and it is unclear whether it is the right thing to do.

## Logfile

Attempted to enable debugging but failed. Hopefully, it is obvious without it.

### Scripts for reproduction with a fresh install

run.0.setup_test.sh

```bash
#!/bin/sh

set -eu

f_appimage='Joplin.AppImage'
wget 'https://github.com/laurent22/joplin/releases/download/v1.1.3/Joplin-1.1.3.AppImage' -O "${f_appimage}"
chmod 755 "${f_appimage}"

mkdir -p \
    "${f_appimage}.config" \
    "${f_appimage}.config/joplin-desktop/" \
    "${f_appimage}.home" \
    "${f_appimage}.home/config/joplin-desktop/"

# Enable debug
# TODO: not sure which path the prog uses.
echo '--open-dev-tools --debug --log-level debug' > "${f_appimage}.home/config/joplin-desktop/flags.txt"
echo '--open-dev-tools --debug --log-level debug' > "${f_appimage}.config/joplin-desktop/flags.txt"

"./${f_appimage}" &

find "${f_appimage}.home" > "log.0.home-files.txt"
find "${f_appimage}.config" > "log.0.config-files.txt"
```

run.1.convert_file_to_symlink.sh

```bash
#!/bin/bash

set -eu
f_appimage='Joplin.AppImage'
d_resources="${f_appimage}.home/.config/joplin-desktop/resources/"

(
    cd "${d_resources}"
    for fname in * ; do 
        [[ -f "${fname}" ]] || continue
        mv -T "${fname}" "_file_${fname}"
        ln -sT "_file_${fname}" "${fname}"
    done
)

find "${f_appimage}.home" > "log.1.home-files.txt"
find "${f_appimage}.config" > "log.1.config-files.txt"
```

**Comment by CalebJohn** [comment]
#887 contains some relevant discussion.

**Comment by Jonassenher** [comment]
I saw this now. Please re-open since this is still not fixed.

**Comment by sequencerr** [comment]
Hello, I assume this is main non locked issue, tracking the issue.
I understand that changing this might disrupt existing setups, so perhaps making XDG compliance opt-in via a configuration option would be a good compromise. This way, users like me who want to adhere to XDG standards can enable it, without affecting those who are happy with the current method.
My main concern was mixed config and data folders, data I may accidentally delete. So moving `.config/joplin-desktop/resources/` to `~/.local/share/joplin-desktop/resources/` is really necessary in my case. Can someone perhaps suggest some workaround? I thought of creating symlink, but I guess it isn't possible:

> The flatpak package writes outside of its sandbox *because* this change isn't implemented. 

_Originally posted by @BeatLink in https://github.com/laurent22/joplin/issues/6152#issuecomment-1046263827_

maybe let's keep it open because it's not "won't fix" nor feature "won't be merged"? hopefully this will get some progress working on, not necessarily break-changing, because I personally disagree to "if it works, don't touch it" to that degree.

UPD: 

> I'm not keen to change it. I know some users prefer to have the config dir elsewhere but for this it's possible to use a symlink.

_Originally posted by @laurent22 in https://github.com/laurent22/joplin/issues/6152#issuecomment-1046216868_
            
Ohh so it's possible. Maybe create some docs about configuration approaches? I couldn't find any in ["Using Joplin"](https://joplinapp.org/help/apps/), only [app home dir spec](https://joplinapp.org/help/apps/home_directory)

**Comment by sequencerr** [comment]
maybe let's keep it open because it's not "won't fix" nor feature "won't be merged". hopefully this will get some progress working on, not necessarily break-changing, because I personally disagree to "if it works, don't touch it" to that degree.
