### ISSUE TITLE
[Reporting a bug] It is impossible to install from package

### ISSUE THREAD

**Issue by tanrax** [laurent22/joplin#384]
### Operating system

- Linux

### Application

- Desktop

``` bash
snap install Joplin_1.0.83_amd64.snap
error: cannot find signatures with metadata for snap "Joplin_1.0.83_amd64.snap"
```
Also, when I search for the package with *snap find* it is impossible to find it.
``` bash
snap find joplin
No matching snaps for "joplin"
```

**Comment by tanrax** [comment]
Oops! I think there's been a mix-up. I saw it on your release.

![screenshot from 2018-04-08 09-40-31](https://user-images.githubusercontent.com/4553672/38464623-133def70-3b11-11e8-8c91-7e964979de7b.png)
Isn't it a snap package for linux?

**Comment by laurent22** [comment]
This package is generated by electron-builder but i don't know if it works actually, that's why I'm not linking it to the home page. Officially only the appimage package is currently supported

**Comment by AdamIsrael** [comment]
For what it's worth, the snap file was fine. Locally installed snap packages need to be installed with the `--devmode` flag. Otherwise, they're generally published to the [snap store](https://snapcraft.io/store). Then it's available to any user in a Linux OS that supports snaps via `snap install joplin`.

I'd love to help re-enable snap support, if you're interested.
