### ISSUE TITLE
UI issue / sync state "complete" while server is offline

### ISSUE THREAD

**Issue by mschindl** [laurent22/joplin#3851]
## Environment

Joplin version: 1.1.4
Platform: macOS
OS specifics: 10.15.7

## Steps to reproduce

1. Check sync state in UI after server (i.e. Nextcloud) is offline

## Describe what you expected to happen

![image](https://user-images.githubusercontent.com/26382876/94669107-1cf3d000-0311-11eb-9613-0950d1eeaf2f.png)
Ui should show an error and not "complete". 

## Logfile
-

**Comment by axq** [comment]
I agree this is misleading.  Happens on Android while in airplane mode, too.

**Comment by jonath92** [comment]
I also fully agree that it should be shown an Error in the GUI. This issue is similar to  #3424. However the current behavior is for some reasons as intended. I  have made a [pr](https://github.com/laurent22/joplin/pull/3775) for fixing this issue a couple of weeks ago but Laurent has rejected it and suggested to have a discussion about this on the forum. Therefore I opened this [topic](https://discourse.joplinapp.org/t/why-are-some-sync-error-messages-not-shown-in-the-gui/10750) on the forum which however unfortunately didn't gain much attention yet. So @axq and @mschindl I think it would help if you could reply to my post on the forum and hopefully we can convince Laurent so to change his mind (I think Laurent is an outstanding developer and I have great respect for him but I think in this case he is absolutely wrong).
