### ISSUE TITLE
editing a note found by search bar and chancel search switches to another note - bug?

### ISSUE THREAD

**Issue by TeresaM12** [laurent22/joplin#3904]
I´m in a note and decide to change something in a note concerning `Joplin`. I place `joplin` in the search bar, find my note with `joplin` in it and change something in there. To get rid of highlights or find the location of the note I chancel the search. But the moment I chancel the search I'm back to the note I was in before the search (therefore not the one I edited last).

I find this behavior irritating. It is definitely different than before and right at the moment I do not know how to locate the notebook to a note.

### Environment
Joplin 1.2.6 (prod, darwin)
Revision: f5f117c (master)

"problem" occurs under Win10 and MacOS 10.15

**Comment by laurent22** [comment]
Indeed that should be improved but somehow it's currently tricky to support. For future devs would might want to look into this: the issue is that clearing a search or selecting something in the sidebar has side effects, and these side effects conflict with each others (for example, searching for something, then selecting "All notes" would clear the search, and clearing the search would trigger some actions, which will undo the "All notes" selection).

The solution is to make the SearchBar and SideBar components being controlled by the same parent (probably MainScreen) so that their state can be properly managed.

See also this issue and the not so good fix that was implemented for it: https://github.com/laurent22/joplin/issues/3748

**Comment by TeresaM12** [comment]
The problem in my opinion is that the focus of a note is taken away even though the search criterion would be fulfilled by the selected/ displayed note already and it works indeed as long as I do not delete everything but just add or delete parts of the search term.
Therefore the problem occurs only when the search bar is emptied (and every selected note fulfills automatically the search criteria). 

I do not see how : [#3748](https://github.com/laurent22/joplin/issues/3748) could be of any help

**Comment by laurent22** [comment]
My comment was from a development point of view and at this level the linked issue is related.
