### ISSUE TITLE
Sync failure on iOS app for some notes

### ISSUE THREAD

**Issue by TheOtherGuy** [laurent22/joplin#3986]
I have a saved complete page (HTML) from a website which can save with no issues on desktop Joplin, but when I tried to sync using iOS Joplin, it will throw an error. It seems that the Wordpress code is causing some issue? I tried deleting the note and then resaving the page, but the same error occurs. Sync is done via Windows OneDrive.

## Environment

Joplin version: 10.2.1
Platform: iOS
OS specifics: iOS 13.5

## Steps to reproduce

1. Save this [webpage](https://mikethompsonblog.com/5-key-traits-socially-intelligent-people-mike-thompson) as a complete HTML page via Joplin clipper. There are a few other webpages which has similar issues.
2. It can be synced successfully on Windows Joplin.
3. Sync will fail on iOS Joplin.

## Describe what you expected to happen
Successful sync across platforms.

## Logfile
As attached.
![Joplin iOS Logfile](https://user-images.githubusercontent.com/8952368/97172209-a93acb00-17c9-11eb-8421-b42294fc1ff0.jpg)
![joplin iOS error message](https://user-images.githubusercontent.com/8952368/97172215-ab048e80-17c9-11eb-9f02-7d0307986ce0.jpg)

**Comment by laurent22** [comment]
Looks like the sync issue cannot be fixed as it is a bug in the network library we use. Specifically the React Native `fetch()` function will truncate strings that contain binary data (That binary data shouldn't be there but due to a bug in the clipper it was)

I'll keep the JEX file here anyway in case that bug is fixed some day so that it can be tested again:

[BROKEN JEX FILE](https://github.com/laurent22/joplin/files/5453046/The.5.Key.Traits.of.Socially.Intelligent.People.-.Mike.Thompson.Blog.zip)

As I'm not sure the JEX file will preserve the broken encoding, here it is directly from the sync target:

[984d0978d5684284b583ef121d058fe0.zip](https://github.com/laurent22/joplin/files/5453052/984d0978d5684284b583ef121d058fe0.zip)

I will however fix the issue that generated the invalid file in the first place.
