### ISSUE TITLE
Tags search works only one time

### ISSUE THREAD

**Issue by jr1234567** [laurent22/joplin#3998]
## Environment

Joplin version: 1.3.10
Platform: Linux
OS specifics: Ubntu 20.10

## Steps to reproduce

1. Select one Tags keyword/expression : ok it works, it displays  the corresponding notes 
2. Select a notebook : ok it works, it displays the notebook's content 
3. Select the same  Tags keyword/expression as above : it does not  works, nothing happens

**Comment by devangmukherjee** [comment]
Hi, I would like to work on this issue. Can someone please tell me where can I find the code for this?

**Comment by mzguy** [comment]
Just adding a workaround for this bug. If you click on a different tag, then you can go back to the original one you were attempting to search for.

**Comment by etham5** [comment]
I started to use tags since today and noticed this bug right away as well. There is one more detail to this bug: If you have only one tag in your tag list, you can't display the notes holding this tag by clicking the tag in the list, not even by selecting a notebook first and then selecting the tag again.

# Environment
Joplin version: 1.3.18
Platform: Windows 10 Education
OS specifics: Version 1803

**Comment by rentseen** [comment]
meet the same problem as @thomas-esau, I started to use Joplin few days ago and created just one tag, the tag selection only works for the first time.

Environment
Joplin version: 1.3.18
OS: Ubuntu 18.04
