### ISSUE TITLE
Keyboard shortcuts inconsistent in vim keyboard mode

### ISSUE THREAD

**Issue by mandre** [laurent22/joplin#4009]
Many of the keyboard shortcuts are inconsistent in vim keyboard mode. The shortcuts behave differently whether the focus is inside or outside of the markdown editor. They also work differently when in in vim insert mode or not.

For instance:
- <kbd>Ctrl </kbd> + <kbd>P</kbd>:
  - focus on markdown editor: Line up
  - focus on markdown editor in insert mode: Open GoTo Anything
  - focus outside of markdown editor: Open GoTo Anything
- <kbd>Ctrl </kbd> + <kbd>N</kbd>:
  - focus on markdown editor: Line down
  - focus on markdown editor in insert mode: New note
  - focus outside of markdown editor: New note
- <kbd>Ctrl </kbd> + <kbd>T</kbd>:
  - focus on markdown editor: New TODO
  - focus on markdown editor in insert mode: Add indentation
  - focus outside of markdown editor: New TODO

## Environment

Joplin 1.3.10 (dev, linux)

Client ID: dfed9e434d39407b9cfa007874a11857
Sync Version: 2
Profile Version: 34
Keychain Supported: No

Revision: e2698aaea (dev)

## Steps to reproduce

1.  Set keyboard mode to vim
2.  Try to use keyboard shortcuts
3. 

## Describe what you expected to happen

Keyboard shortcuts should be consistent across the application and respect the keyboard shortcuts defined in the option menu.

**Comment by mandre** [comment]
Yep, still an issue.

**Comment by DubininDmitry** [comment]
Please fix this issue. It is very annoying when working with vim keyboard mode.

**Comment by iochrdy** [comment]
One thing that I noticed with this bug... The default keyboard shortcut is Ctrl-P If I use that, goto anything works. If I modify the keyboard shortcut in the settings to something like Ctrl-G, it breaks and I cannot focus or type in the goto anything bar

**Comment by mandre** [comment]
Hello stale bot, issue is still there.

**Comment by mandre** [comment]
Stale bot is getting a bit annoying :expressionless:

**Comment by thejohnfreeman** [comment]
I've created a plugin to fix this issue: https://github.com/thejohnfreeman/joplin-plugin-fix-vim I'm sure it could also be fixed in the main project, but I thought this would be a good idea for a first plugin for me to get comfortable with the process while building something I'll use. There are [releases](https://github.com/thejohnfreeman/joplin-plugin-fix-vim/releases) for Joplin ^1.7.0 and Joplin ^2.0.0. Right now, the keybinding for Go to Anything doesn't work for Joplin 2.x.x, and is not expected to until [this change](https://github.com/laurent22/joplin/commit/00b39e46715c2afbb971fa7a40c5e43705a7c636) makes its way into a Joplin release, which I'm guessing will be 2.1.8.
