### ISSUE TITLE
[Feature Request] Add Google Drive

### ISSUE THREAD

**Issue by mxschmitt** [laurent22/joplin#402]
Implement Google Drive as storage provider like One Drive e.g.

### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

**Comment by DataThinkMonkey** [comment]
This would be awesome.

**Comment by donbowman** [comment]
documented here https://developers.google.com/drive/api/v2/reference/about/get

and general library for access here
https://developers.google.com/api-client-library/javascript/start/start-js

http://bytutorial.com/tutorials/google-api/introduction-to-google-drive-api-using-javascript
has some sample javascript code
as does https://github.com/gsuitedevs/node-samples/tree/master/drive

**Comment by gonyyi** [comment]
How about using git

**Comment by matteocrippa** [comment]
On desktop linux [grive2](https://github.com/vitalif/grive2) can be an option, so it's like a mounted folder.
On mac and windows there's already the official app to sync.
It would be great to have in android, so I can finally drop evernote :dagger:

**Comment by laurent22** [comment]
Due to the coming changes in Google Drive policy, sync with this service unfortunately will not be possible. We fall under section 4 of this [document](https://cloud.google.com/blog/products/identity-security/enhancing-security-controls-for-google-drive-third-party-apps), which means the app would need an independent Google-approved audit to be allowed. And that would [cost](https://cloud.google.com/blog/products/g-suite/elevating-user-trust-in-our-api-ecosystems) "from $15,000 to $75,000 (or more) depending on the size and complexity of the application."

I don't trust Google services much because they are constantly changing things to the detriment of users and developers, and to their own advantage. That's why I didn't implement this despite the popularity of the feature request, and unfortunately now it's certain that it won't happen.

As some users mentioned, one way is to sync your Google Drive with your computer, using Google's sync client, and then use Joplin filesystem sync and point to that folder. Then do the same in Android (in iOS it won't work I think). Otherwise there's always the option to switch to something like Nextcloud, Dropbox or OneDrive (although I wouldn't be surprised if Dropbox or OneDrive do the same as Google eventually).

**Comment by jbhanks** [comment]
> Due to the coming changes in Google Drive policy, sync with this service unfortunately will not be possible. We fall under section 4 of this [document](https://cloud.google.com/blog/products/identity-security/enhancing-security-controls-for-google-drive-third-party-apps), which means the app would need an independent Google-approved audit to be allowed. And that would [cost](https://cloud.google.com/blog/products/g-suite/elevating-user-trust-in-our-api-ecosystems) "from $15,000 to $75,000 (or more) depending on the size and complexity of the application."
> 
> I don't trust Google services much because they are constantly changing things to the detriment of users and developers, and to their own advantage. That's why I didn't implement this despite the popularity of the feature request, and unfortunately now it's certain that it won't happen.
> 
> As some users mentioned, one way is to sync your Google Drive with your computer, using Google's sync client, and then use Joplin filesystem sync and point to that folder. Then do the same in Android (in iOS it won't work I think). Otherwise there's always the option to switch to something like Nextcloud, Dropbox or OneDrive (although I wouldn't be surprised if Dropbox or OneDrive do the same as Google eventually).

Would you be willing to offer a paid version that either does work with Google Drive or has its own hosting? I've just started using Joplin, but it seems to meet my needs really well. I would definitely either pay a flat fee of ~$15-20 for Google Drive integration, or a couple bucks a month for preconfigured hosting.
