### ISSUE TITLE
Export as PDF doesn't export all notes

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#4061]
Check:

- When selecting multiple notes
- When right-clicking a notebook
- In File => Export All

All that normally should export multiple PDF files.

**Comment by JRLBell** [comment]
This issue/bug still is valid for version 2.3.3.  When selecting "Export all" from the "File" menu, and selecting "PDF - PDF file," only one note (the last selected or highlighted) is exported.  The option should probably be removed (PDF - PDF file) if it doesn't work.  The "Export all" from the "File" menu does work when selecting HTML and .JEX.  I didn't try the other options.

Perhaps by design, right clicking and selecting "Export" is non-existent when highlighting "All notes"  and the option to export to PDF is unavailable when right clicking on Notebooks (parent of sub-notebook) and choosing "Export."  

Maybe the options when choosing "Export all" from the "File" menu should probably be the same as when right clicking a Notebook and choosing "Export" i.e. no .pdf export option.

The PDF option is available when selecting an individual note and the single note does export correctly to a .pdf file.

**Comment by JRLBell** [comment]
This issue/bug still is valid for version 2.3.3. When selecting "Export all" from the "File" menu, and selecting "PDF - PDF file," only one note (the last selected or highlighted) is exported. The "Export all" from the "File" menu does work when selecting HTML and .JEX. I didn't try the other options.

Perhaps by design, right clicking and selecting "Export" is non-existent when highlighting "All notes" and the option to export to PDF is unavailable when right clicking on Notebooks (parent of sub-notebook) and choosing "Export."

The option should probably be removed (PDF - PDF file) if it doesn't work. Therefore, the options when choosing "Export all" from the "File" menu would be the same as when right clicking a Notebook and choosing "Export" (i.e. no .pdf export option).

The PDF option is available when selecting an individual note and the single note does export correctly to a .pdf file.
