### ISSUE TITLE
WYSIWGY - A bulleted list within a table turns into a hyphen points

### ISSUE THREAD

**Issue by armaccloud** [laurent22/joplin#4066]
## Environment

Joplin version: 1.3.15
Platform: Linux
OS specifics: Pop!_OS 20.10

## Steps to reproduce

1. Create a table
2. Create a bulleted list within a cell
3. Switch to another note, then switch back again
4. Verify the bullets have changed into hyphens

![Bulleted List in Table Cell](https://user-images.githubusercontent.com/9272078/98520434-51449f80-2272-11eb-965f-60957995810c.gif)

## Describe what you expected to happen
The bullet list remains a bullet list

**Comment by laurent22** [comment]
It's again one of these features that aren't supported in Markdown (bullet points inside tables) and thus aren't supported in the Rich Text editor. I doubt there's any solution for this.

**Comment by HOLLYwyh** [comment]
H

> ## Environment
> Joplin version: 1.3.15
> Platform: Linux
> OS specifics: Pop!_OS 20.10
> 
> ## Steps to reproduce
> 1. Create a table
> 2. Create a bulleted list within a cell
> 3. Switch to another note, then switch back again
> 4. Verify the bullets have changed into hyphens
> 
> ![Bulleted List in Table Cell](https://user-images.githubusercontent.com/9272078/98520434-51449f80-2272-11eb-965f-60957995810c.gif)
> 
> ## Describe what you expected to happen
> The bullet list remains a bullet list

Hello! In my Joplin1.7.11,  windows 10 ,I meet the same problem. I' m trying to find out the reason

**Comment by HOLLYwyh** [comment]
@armaccloud  I think I know what happened. You can  visit this page: https://joplinapp.org/rich_text_editor/ 
In Joplin, notes, even when edited with this Rich Text editor, are still Markdown under the hood. Commonly, we can use bulleted list in Rich Text editor. However, Joplin use Markdown as the core and we can't use bulleted list in Morkdown's table. So when you chage the note (or do something else), what you do in Rich text editor will be regarded as Markdown code, that's why you can't use bulleted list.
