### ISSUE TITLE
Sharing to Joplin on Android broken

### ISSUE THREAD

**Issue by eagleofnorth** [laurent22/joplin#4071]
1. Share a link from Firefox or Chrome by using Share > Joplin

2. Joplin opens and a new note appears (as expected) with title of web page as title of note and url of web page as content of the note.

3. Press the white arrow in the upper left corner and we are returned to Firefox.

Open Joplin and the newly "created" note is gone.

Joplin 1.3.13
Android 10 - Samsung Galaxy s10eoid broken

**Comment by roman-r-m** [comment]
So I've been looking into this all evening today and I think I've found the root cause.

What happens is if you share some text (sharing attachments actually works), Joplin will try to set the note body, but the new state is not saved and when the user closes the app, the note is deleted as an unchanged provisional note.

The reason it works with attachments is that `Note.attachFile` explicitly calls `scheduleSave`.

Now the interesting part is why it worked previously. Note screen, when mounted, installs a back button handler that checks if a note is modified and saves if it is and after that the note is no longer provisional.

But there seems to be a bug in the BackButtonService where it only calls the last handler out of the whole list:
https://github.com/laurent22/joplin/blob/17d835d694cf8afd459443f1ba279d8a9100eae5/packages/app-mobile/services/back-button.js#L12-L16

After some code change (which I've not identified) Note's backHandler is no longer the last one, and so it's never called, the modified note is not saved, etc

I've tried this and it seems to solve the issue (although now you need to click back twice to exit the app):
```javascript
		if (this.handlers_.length) {
			for (let i = this.handlers_.length - 1; i >= 0; i--) {
				const r = await this.handlers_[i]();
				if (r) return r;				
			}
		}
```
