### ISSUE TITLE
Sync with filesystem on Android doesn't work; produces "could not read directory" error

### ISSUE THREAD

**Issue by pyrrana** [laurent22/joplin#4081]
## Environment

Joplin version: 1.3.13
Platform: Android
OS specifics: Android 10

## Steps to reproduce

1. Create a folder and enter directory on Joplin
2. Synchronise

What I actually did:
- Initially tried synchronising with an existing Joplin folder (that already has files and folders shared from PC) using Syncthing.
- Tested later with by creating a new folder on device which yielded "directory could not be created" errors for locks and temp folder
- Manually created those folders and then it gave the same error ("could not read directory")

## Logfile

    """Error: Error: Could not read directory: /storage/emulated/0/Syncthing/Joplin/locks: Attempt to get length of null array. Path: /storage/emulated/0/Syncthing/Joplin/locks
    """Error: Error: Directory could not be created. Path: /storage/emulated/0/Joplin/locks
    """Error: Error: Directory could not be created. Path: /storage/emulated/0/Joplin/temp
    """Error: Error: Could not read directory: /storage/emulated/0/Joplin/locks: Attempt to get length of null array. Path: /storage/emulated/0/Joplin/locks

**Comment by laurent22** [comment]
The locks folder can sometimes be empty. Does Syncthing handle empty directory in a special way, like not syncing them or deleting them?

**Comment by pyrrana** [comment]
Maybe I wasn't clear, the locks folder is present at said directory. Also, I have storage permissions granted for Joplin, forgot to mention that.

**Comment by j710** [comment]
@pyrrana what exact storage permission has been granted? Media or files or both?

**Comment by gxylgbx** [comment]
Me too，But Joplin v1.2.6 release works fine.

**Comment by williamkray** [comment]
Brand new user with brand new install here, same issue. Freshly created folder with no syncthing setup at all, joplin refuses to sync to the folder. Attempting to create the missing folders just throws more errors.
![Screenshot_20201203-011543](https://user-images.githubusercontent.com/8409433/100989411-b30cc800-3505-11eb-9860-b21a185f4ac6.png)

**Comment by roman-r-m** [comment]
This might be fixed in the next release.

**Comment by nardusg** [comment]
> This might be fixed in the next release.

hope so, got the same issue

**Comment by nardusg** [comment]
It is still broken, newest version did not fix it

**Comment by cncser** [comment]
The version 1.4.11 has the same bug.

**Comment by alexanderadam** [comment]
Just to be sure: did you keep the App open and the screen on on your Android devices?

Because [there's currently no background sync implemented](https://github.com/laurent22/joplin/issues/3872), thus this can result in some sync errors (i.e. app started sync, screen goes off, app is killed and you have some weird state on your mobile device).

**Comment by williamkray** [comment]
@alexanderadam this issue is not related to background syncing, this is strictly a permissions issue with the android filesystem. i resolved the issue locally by installing an old old version, which apparently handled filesystem permissions differently, and then _upgrading_ to the newer versions. by doing this, android inherits the permissions granted by the older system when upgrading. however, this is not an ideal solution and needs to be resolved in the application.

**Comment by j710** [comment]
> @alexanderadam this issue is not related to background syncing, this is strictly a permissions issue with the android filesystem. i resolved the issue locally by installing an old old version, which apparently handled filesystem permissions differently, and then _upgrading_ to the newer versions. by doing this, android inherits the permissions granted by the older system when upgrading. however, this is not an ideal solution and needs to be resolved in the application.

Exactly right @williamkray it's simply the documented new framework for targeted/restricted file permissions in android 11

**Comment by timothyparez** [comment]
```
Joplin 1.7.11 (prod, linux)

Client ID: 77248642683e484fb9373ea47af753d0
Sync Version: 2
Profile Version: 34
Keychain Supported: No

Revision: f560563 (master)
```
This issue is also present on the latest Android version>

**Workflow**:

 - Install Joplin on Desktop (Ubuntu), Laptop (Ubuntu), Phone (Android)
 - On the desktop, create a number of notes 
 - Set `Syncthing` to share a folder between the 3 devices
 - Configure Joplin to synchronize to that folder on each device
 - It synced without errors the first time
 - Watch `syncthing` sync the notes to the Laptop and Phone (100% complete)
 - Click `synchronize` in Joplin, you get the `locks` directory does not exist error
 - Repeat this on the other 2 devices with the same error
 - Create the `locks` directory manually on the laptop and mobile
 - Hit the synchronize button on each of them, the laptop instantly gets all the notes
 - The mobile app gets most of them
 
Perhaps `syncthing` does something which deletes the `locks` folder?

**Comment by williamkray** [comment]
@timothyparez per my comment [here](https://github.com/laurent22/joplin/issues/4081#issuecomment-737775468) the android application throws those errors even without any syncthing installation. the issue is not related to syncthing.

**Comment by timothyparez** [comment]
Yes. I noticed it too late but mentioned it in the other issue I submitted.

**Comment by roman-r-m** [comment]
Can someone who has this issue confirm their
* Joplin version
* Android model and version
* the path you set for syncing

I'm trying to reproduce this in emulator on Android 10 & 11 and it work on both (also works on my Android 9 phone). I am setting the path to `storage/emulated/0/joplin`

**Comment by timothyparez** [comment]
Joplin Version: `1.7.5, database v34`
Android: `RedMi K30 Android 10 MIUI 12.0.4 Stable`
Path: `/storage/emulated/0/Documents/Notes`

Note again that this happens on Linux as well and that in my case I can fix it by manually creating the `locks` folder everywhere

**Comment by roman-r-m** [comment]
Still can't reproduce in emulator. I see a few error messages like
```
2021-02-27 22:47:01.225 8536-8664/net.cozic.joplin W/System.err: com.rnfs.IORejectionException: ENOENT: /storage/emulated/0/Documents/Notes/info.json: open failed: ENOENT (No such file or directory), open '/storage/emulated/0/Documents/Notes/info.json'
```
but it still syncs fine and files appear under `/storage/emulated/0/Documents/Notes`

**Comment by williamkray** [comment]
I just tested on a Pixel 3 with CalyxOS 2.2.0 (Android 11) and confirm there was no issue with syncing to `/storage/emulated/0/Joplin`.

**Comment by jlabeeuw** [comment]
Had the same issue. For me it worked to put a _placeholder 0-byte file into the locks folder. 
Now it starts syncing.

**Comment by timothyparez** [comment]
@jlabeeuw is correct, this solved the issue for me as well.  
The developer is very quick to remove the `bug` label even though  
this is pretty much a bug that affects many people and can be resolved by  
having the application automatically create that file.

**Comment by timothyparez** [comment]
This is still open
