### ISSUE TITLE
Code blocks syntax highlighting inconsistencies between editor and render

### ISSUE THREAD

**Issue by gitsomejorge** [laurent22/joplin#4132]
Joplin uses different syntax highlighting for code blocks in the editor and the viewer, amongst other strange behaviors between the editor and the viewer.

## Environment

Joplin version: 1.3.18 portable
Platform: Windows 10
OS specifics: Webdav sync enabled to Owncloud

## Steps to reproduce

Joplin performs proper syntax highlighting for "bash" code blocks, but the editor looks way better than the viewer.

![image](https://user-images.githubusercontent.com/30640196/100197785-d661c280-2ec8-11eb-8948-5a5622ec51bd.png)

If the code block does not begin with "bash", then it uses plaintext for the editor and tries to auto detect for the viewer.

![image](https://user-images.githubusercontent.com/30640196/100197868-fbeecc00-2ec8-11eb-82f3-14195875ab22.png)

In contrast, when using the "apache" code block. It shows as plaintext in the editor, but is properly highlighted in the viewer.

![image](https://user-images.githubusercontent.com/30640196/100197957-204aa880-2ec9-11eb-8445-0b02473451b7.png)

## Describe what you expected to happen
I expect to have the same code block highlighted in the editor and the viewer. I understand that Joplin uses highlight.js but I'm not sure how its implemented or if it uses another library as well.

**Comment by gitsomejorge** [comment]
Has anyone experienced this?

**Comment by mllanes** [comment]
I see it as well

**Comment by isdnfan** [comment]
looks similar to  #4254 and #4418

**Comment by isdnfan** [comment]
unchanged in Joplin 1.7.11 (prod, win32)

**Comment by ron-debajyoti** [comment]
Hi !
As a beginner, I went through the codebase and found out that the Editor is supported by `CodeMirror` and the viewer uses `highlight.js`(in `MdToHtml.ts`) directly. Since both of them have different ways of syntax highlighting with different languages supported for each of the two, we get such inconsistencies. I don't think we can change anything about it because it would involve a rebuild of the Editor. 
Perhaps @laurent22 can state his views on this too.

**Comment by pvharmo** [comment]
@ron-debajyoti 
There might actually be a way to fix this without a full rewrite of the Editor. We could use the [runMode](https://codemirror.net/demo/runmode.html) of CodeMirror to generate the code highlight in the viewer. It would replace the highlight.js module.

**Comment by adigitalself** [comment]
I would also like to wish this consistency. I write a lot of powershell code but syntax highlighting does not show in the editor while it does for bash.

![image](https://user-images.githubusercontent.com/49288880/146450177-8e0802af-2905-451e-b423-21a6a16ff23f.png)

**Comment by laurent22** [comment]
Sorry but there's nothing actionable in this issue. First, it's about version 1.3 and we're at 2.6, and syntax highlighting has changed since then. Second, if a particular language doesn't display we need to know which one - maybe we can add it, maybe not, but that should be in a new issue, based on version 2.6 anyway.

**Comment by Daeraxa** [comment]
I might well be wrong but I think it uses this pre-made list to define what mode files get loaded for codemirror. Powershell simply doesn't look like it is included in that list currently.
https://github.com/laurent22/joplin/blob/5c82e439a785c5b2652d3a8bedc83d6830689f24/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/Editor.tsx#L38-L70

As for the colours this is something I've noticed whilst prodding around for general styles and agree it should probably be unified. The richtext editor and the viewer both use the highlighting style from `atom-one-light` and `atom-one-dark` whereas codemirror is using the default codemirror theme colours.
