### ISSUE TITLE
<redacted> tag breaks edit window formatting

### ISSUE THREAD

**Issue by tippenring** [laurent22/joplin#4133]
## Environment

Joplin version:  1.3.18
Platform: Windows
OS specifics: Windows 10 20H4

## Steps to reproduce

1. Create a note with a 2 (or more) level bulleted list
2. On a second level add a <redacted> tag.
3. Edit window formatting after the <redacted> tag stops working.

## Describe what you expected to happen
Display formatting in the edit window following the <redacted> tag. There may be other failure modes I'm not aware of.

## Logfile

![image](https://user-images.githubusercontent.com/11577099/100270774-2e76e400-2f1e-11eb-951d-49dadddbcae4.png)

**Comment by CalebJohn** [comment]
The editing window provides highlighting for markdown and for html/xml (because the markdown renderer supports html content). You have opened an xml tag and haven't closed it, so as far as the editor understands the `test` line is within an html block, and it doesn't know that it's markdown.
If you replace the `redacted` tag with either of the below it will highlight correctly.
```
<redacted />
<redacted></redacted>
```

I think the demonstrated behaviour is correct though, because if the redacted tag was real and functioning this behaviour will "highlight" the text that has been redacted. Let me know if I misunderstood, or if this didn't make any sense.

**Comment by tippenring** [comment]
Yes, that makes perfect sense. My intent was to use the string "<redacted>" to indicate to the reader that I redacted content. I was not thinking of it as an XML tag. 

This report is completely a misunderstanding on my part. Not an issue after all. Thanks.
