### ISSUE TITLE
Notes search/filter results are erratic at best

### ISSUE THREAD

**Issue by DomingoMontoya** [laurent22/joplin#4178]
When typing in search, on main window, typing 'b' shows me one note that has the letter b. Typing 'be' will then show me tens of notes that have 'be' in the notes. Including several notes that have the word 'better' in them. But adding a 't' to the search, so it's searching for 'bet' returns no notes in search results.

## Environment

Joplin version: joplin 1.3.18
Platform: Linux
OS specifics: Arch

**Comment by CalebJohn** [comment]
If you want to search for "better" when only typing "bet" you'll need to add an asterisk on the end "bet*".  I understand that this is not intuitive because a lot of search utilities use a fuzzy or partial search by default. I believe that in the future it might be possible to have the asterisk search done as a default but as of now, you'll need to add it if you want that form of search.

**Comment by mardukbp** [comment]
The search function works like `grep -iw`. But most of the times I want only `grep -i`. This should be configurable.
