### ISSUE TITLE
squiggly lines in KaTeX formula (w/o spellcheck)

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#4196]
## Environment

```
Joplin 1.5.4 (dev, darwin)

Client ID: e354a932e6e143c782264aad4112b674
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: 6487fde09 (dev)
```

## Steps to reproduce

1. Turn off spell-checking
2.  enter
```
$$
\begin{pmatrix} -1 & 0\\ 0 & 1 \end{pmatrix} \begin{pmatrix} x \\ y \end{pmatrix} = \begin{pmatrix} -x \\ y \end{pmatrix} 
$$
```
3. 
<img width="555" alt="image" src="https://user-images.githubusercontent.com/223439/101269056-5f35f500-3738-11eb-85fe-6eb1268f19d3.png">

## Describe what you expected to happen

There should not be any squiggly lines.

## Logfile

No errors in log or console

**Comment by CalebJohn** [comment]
This has to do with the katex highlighter included with codemirror. For some reason it has a few tokens that it labels as errors that are completely valid (this might be a katex vs. latex issue). 

The fix for this is probably to patch the codemirror mode so that it more closely aligns with valid katex.
