### ISSUE TITLE
Desktop: Content script plugins don't ship with external js libraries

### ISSUE THREAD

**Issue by CalebJohn** [laurent22/joplin#4229]
When an external library is accessed through a contentScript it isn't packaged up on `npm run dist`. This means that it won't be distributed with the plugin, and any attempt to run the plugin from a jpl file will crash Joplin.

I tried requiring the library from the index.ts script. This correctly included the module in the dist files, but was only accessible to the index file. I think the same system of including libraries probably needs to be adapted for contentScripts.

I pushed [my project](https://github.com/CalebJohn/joplin-math-mode) to github so it can be used to reproduce the issue.

## Environment

Joplin version: master (4180d4bd28f2e5317e347b6262d58c0ed0c8b47f)
Platform: Linux Desktop 
OS specifics: Ubuntu 20.04

## Steps to reproduce

1. Create a plugin that uses a contentScript (CodeMirror in my case)
2. Access an external library through that plugin (mathjs in my case)
3. run `npm run dist` and attempt to use the plugin with the resulting jpl file
4. Observe that Joplin crashes because the library is unavailable

**Comment by laurent22** [comment]
Hmm, yes the content script runs in a different context that's unknown to the packager so it doesn't try to compile them, it simply copy them to /dist. One simple solution would be to compile that external JS file yourself with webpack (which would bundle your JS file and the mathjs package and dependencies into a single file), but it's indeed not very user friendly.

Otherwise, I guess there should be some config to declare external JS files, so that the generator can pick them up and compile them when webpack runs. Or maybe that can be auto-detected, which would be much better but could have its own problems. Like in your example it's clear that the only JS file in there should be compiled, but for users who have many JS files, perhaps some should be compiled and others shouldn't.

**Comment by CalebJohn** [comment]
For now I've updated the webpack to manually add the content script, you can see what I've done [here](https://github.com/CalebJohn/joplin-math-mode/blob/main/webpack.config.js)

>  I guess there should be some config to declare external JS files, so that the generator can pick them up and compile them when webpack runs

I think this will probably be the best solution, it's not as smooth as automatic detection. But I think in this case that's a good thing, plugin creators should only use contentScripts when they absolutely cannot do it through the plugin system.
