### ISSUE TITLE
Feature request - enable spell checking with markdown

### ISSUE THREAD

**Issue by cgoise** [laurent22/joplin#4237]
Nothing to add to the title. Really: we need markdown, and we need spellcheck. 

I just hate to open yet another (discord) account just for feature requests.. sorry. Instead abusing the bug report section .

Best wishes to (the author of) one of the most impressing OS software projects at the moment,
Till

**Comment by CalebJohn** [comment]
Hi @cgoise 

Spellchecking is already available for the markdown editor (as of v1.4.x). The editor component that Joplin uses (CodeMirror) doesn't support spellcheck that well, so we have spellchecking as an opt-in option under advanced settings. Take a look at the screenshot below, you can see the opt-in is at the very bottom. There have been some recent fixes (merged today actually) that will make it function better in the next stable release, so you might want to wait for that.

I understand that it isn't very visible yet, but that's because it's a new (and unstable) and we want to give it more testing before all Joplin users hop on it. 

![image](https://user-images.githubusercontent.com/2179547/102704108-709cf800-4234-11eb-9462-573412b6df46.png)

By the way, you can log into [the forum](https://discourse.joplinapp.org/) (discourse) using your github account so no need to make another account. (Although you do need to authorize it on your github, which I would understand if you don't want to).
