### ISSUE TITLE
Android not following line breaks

### ISSUE THREAD

**Issue by jfreak53** [laurent22/joplin#4250]
## Environment

Joplin version: 1.4.11
Platform: Android

Not following newline line breaks on android, most recent version from play store. iOS does the same thing for me. See video.

![20201226_084843](https://user-images.githubusercontent.com/731525/103152667-3d88c600-4758-11eb-8ae1-806010613b87.gif)

**Comment by jfreak53** [comment]
Hello???

**Comment by roman-r-m** [comment]
Just tried on the latest version (more or less) and could not reproduce this.
If you have synchronization set up, can you check the corresponding .md file in the storage to see what it contains.

**Comment by br4nnigan** [comment]
I experience the same (1.4.1.1, LineageOS16/Android 9). Doesn't matter if you have the Markdown option "softbreaks" on or off.

**Comment by roman-r-m** [comment]
Ok, now that you've mentioned softbreaks, I can see it with softbreaks on both on Android and on Desktop.
This seems to be working as expected though;

https://markdown-it.github.io/#md3=%7B%22source%22%3A%22This%20is%20line1%5CnThis%20is%20line2%5Cn%5CnThis%20is%20a%20line%20with%202%20trailing%20spaces%20%20%5CnNext%20line%5Cn%5CnClick%20the%20%60breaks%60%20checkbox%20above%20to%20see%20the%20difference.%5CnJoplin%27s%20default%20is%20hard%20breaks%20%28checked%20%60breaks%60%20checkbox%29.%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Afalse%2C%22typographer%22%3Afalse%2C%22_highlight%22%3Afalse%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D

**Comment by br4nnigan** [comment]
wow markdown is a bad choice for this editor. You are telling me that I'm actually writing markdown code and when I close the keyboard this code is converted to "display mode" markdown? Which normal user would want that? If I'm writing a note, and I'm making a linebreak, in which scenario would I want it not to be displayed? I thought I was writing WYSIWYG and it would be converted to markdown behind the scenes.

this is typical programmer reality disconnect "wow wouldn't it be cool if I could write code directly". No, 99% of people want to do three things in their note:

write letters, write spaces and write line breaks, and this most basic requirement is not met.

Honestly this is why FOSS is such a non starter. Because most free software is never intended to be of most possible use to the biggest possible audience. I mean I can understand that. It's the lack of motivation in form of profit, so a big part of it is personal fulfilment. And who am I to complain, did I pay for the app? No. The programmer offers it as a free service. And other than this issue I was delighted with it. Made it easy to drop Evernote. Good job.

Sorry for the offtopic, just letting thoughts flow. Have a nice day.

ps: affirming that the mentioned option has no effect for me

**Comment by br4nnigan** [comment]
btw the Desktop App shows the line breaks in the same note
