### ISSUE TITLE
MacOS: Text navigation and highlighting w/keyboard modifiers does not work

### ISSUE THREAD

**Issue by jkodroff** [laurent22/joplin#4257]
## Environment

Joplin 1.5.12 (prod, darwin)

Client ID: bfdd01e123ca4b11adf33dbdec174fbf
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: 66a5490 (master)

## Steps to reproduce

- Command + left/right should move to the start/end of the current line.  It moves 1 word, similar to Windows behavior.
- Alt + left/right should move left/right 1 word.  It does nothing.

**Comment by dasmurphy** [comment]
I have the same problem too. It is reproducible.

**Comment by tessus** [comment]
This is not a bug.

On macOS going to the beginning of a line is done with `Ctrl+A` and to the end of the line wih `Ctrl+E`. As it is done in every other application on macOS.

**Comment by dasmurphy** [comment]
@tessus May be you closed it too early, but every Application in MacOS also supports: **Option+<Left/Right>** for **Word Jumping** and **Cmd+<Left/Right>** for **Start and End** of line, but not **Cmd+<Left/Right>** for Word Jumping. This is not the Standard in MacOS.

Would it be possible to reenable the Joplin 1.4.19 function, since it works there correctly? thanks for a small answer.

**Comment by dasmurphy** [comment]
If anyone wants to fix it for themselfs:

In `usekeymap.ts` (line ~156+) change the following 4 lines:
```js
'Cmd-Left': 'goGroupLeft',
'Cmd-Right': 'goGroupRight',
'Ctrl-A': 'goLineStart',
'Ctrl-E': 'goLineEnd',
```

To:
```js
'Alt-Left': 'goGroupLeft',
'Alt-Right': 'goGroupRight',
'Ctrl-A': 'goLineStart',
'Ctrl-E': 'goLineEnd',
'Cmd-Left': 'goLineStart',
'Cmd-Right': 'goLineEnd',
```

That should fix it for all MacOS users. And they will be very happy. It would be awesome to include this change in the next release.

**Comment by tessus** [comment]
The main reason why I closed this was because it is not a bug. I understand your issue, but usability issues are discussed on the forum. The forum can be used with github credentials.

The point is that a few people complained (including me) that after the move from Ace to CodeMirror `Ctrl+A` and `Ctrl+E` no longer worked.

However, I think that your suggestion makes sense. Caleb was working on the CodeMirror keyboard shortcuts here: https://github.com/laurent22/joplin/pull/4136

I'm not sure why he changed `goGroupLeft` and `goGroupRight`, but I think it was because of this https://github.com/laurent22/joplin/pull/4136#issuecomment-742127790

**Comment by dasmurphy** [comment]
@tessus Thanks for the explanation. I saw the in the history the change already. It would be awesome if you could change my 6 lines. I can post something in the forums if necessary.

I saw this as a bug also, since it changed from 1.4.19 release to the new release without any notice in the changelog and the shortcuts are pretty standard this days.

So if you need a discussion for this, give me a short hin here. Thanks for all.

**Comment by tessus** [comment]
@CalebJohn what do you think?

**Comment by dasmurphy** [comment]
@tessus May be you use the Smart with the Cmd Things. I also tested it in SublimeText and it uses smart moving with the Cmd+<Left/Right> as well.

So here is an updated wish from me:
```js
'Alt-Left': 'goGroupLeft',
'Alt-Right': 'goGroupRight',
'Ctrl-A': 'goLineStart',
'Ctrl-E': 'goLineEnd',
'Cmd-Left': 'goLineLeftSmart',
'Cmd-Right': 'goLineRightSmart',
```

Also this is, because there are almost not Home/End Keys on the MacBook Keyboard. Thanks. :)

**Comment by tessus** [comment]
I'd be ok with this change. Let's see what Caleb and Laurent say.

**Comment by CalebJohn** [comment]
I'll make a PR right away, but I do have a question.

Currently `Ctrl-A` and `Ctrl-E` do go to the start and end of a continuous line (which is not necessarily the same as a visual line). Is this the expected behaviour? I can change the to use `goLineLeftSmart` and `goLineRightSmart` to align with the `home` and `end` keys.

**Comment by dasmurphy** [comment]
@CalebJohn I thought also about it before writing the lines the second time. I left this as they are currently so Mac users can use both effects of using smart movement and jumping straight to start/end of the real line. So please leave it as it is now. It's good for me and i think others will be also ok with it.

**Comment by tessus** [comment]
Hmm, this is actually a bit different. Here is how it works in macOS's TextEdit:

![image](https://user-images.githubusercontent.com/223439/103246993-54374480-4933-11eb-9c81-d84160df532b.png)

The `Cmd+Left/Right` depends on which line the cursor is:

![image](https://user-images.githubusercontent.com/223439/103247150-e2132f80-4933-11eb-8d9c-f2ea08c1b811.png)

**Comment by CalebJohn** [comment]
That's perfect, the commands @dasmurphy provided will do exactly that.
PR is up #4259

**Comment by tessus** [comment]
Ok, then I've misunderstood what the smart code does. e.g. I thought that `Cmd+Left` would actually position the cursor at the beginning of `This`.

**Comment by dasmurphy** [comment]
@tessus I tested TextEdit, it always jumps to the start of the line. When i look to other editors, it will work as i described.

SublimeText works the way i wrote the keymapping.
LibreOffice works as TextEdit.

I prefer the SublimeText way, since you get both ways to handle the cursor.

**Comment by tessus** [comment]
I'm just saying that SublimeText is rather the exception than the standard. That's all. I don't care either way, since I don't use the `Cmd+Left/Right` shortcuts ever.

But the way they work on macOS is usually the way they do in TextEdit. Or take the input text field in github. 

But as I mentioned before, it doesn't really matter to me as long as `Ctrl+A` and `Ctrl+E` will work as they do now (which is the case according to the PR). I just wanted to bring it up.

**Comment by dasmurphy** [comment]
@tessus You are correct. The normal handling is more like TextEdit. I acknowledge it.

**Comment by tessus** [comment]
@CalebJohn I haven't tested it yet, but I'm using `Opt+Left` for `Back` and `Opt+Right` for `Forward`.

```
  {
    "command": "historyBackward",
    "accelerator": "Option+Left"
  },
  {
    "command": "historyForward",
    "accelerator": "Option+Right"
  }
```

Will this PR render my shortcut assignment impossible?

**Comment by CalebJohn** [comment]
@tessus This PR won't affect your keybindings. Anything defined in `useKeymap` can be overwritten by the Joplin keymap editor.

**Comment by tessus** [comment]
Thanks, I've just tested it. (I had to get to my computer first. :-))

My keyboard shortcuts still work. It's just that the codemirror shortcuts are not available, since I can't change them (other than changing the source code). This is not a problem for me, and if this is working as designed, I'm ok with it!
