### ISSUE TITLE
bug 1 (on iOS) - related to discourse post <attachments in and out>

### ISSUE THREAD

**Issue by ajay-gh** [laurent22/joplin#4289]
## Environment

Joplin version: Joplin 10.5.1
Platform: iOS
OS specifics:  

## Steps to reproduce

1. open Joplin, any note
2. try to attach a binary file (in fact anything else but a picture file or a text file)
3. any such file is greyed out in the file selector, and cannot be attached

## Describe what you expected to happen
- one should be able to attach any file of any file type, at least all files available and shown in the iOS "Files" app

## Logfile
due to the nature of the bug, I doubt this can show up in any log

**Comment by laurent22** [comment]
Hi, before you spend too much time on this, I just want to say that's a lot of bug reports. Make sure a moderator is interested enough to read through and triage all this as otherwise they'll end up being auto-closed after a while. Personally this is not my priority at this point and I don't have an opinion on any of these issues.

**Comment by ajay-gh** [comment]
after update to version 10.7.2.  : binaries may now be added to a note, but they still behave weird
in particular when trying trying to share them later or save them
