### ISSUE TITLE
userstyle.css colors render incorrectly

### ISSUE THREAD

**Issue by alexxnz** [laurent22/joplin#4348]
I've been experimenting recently with userstyle.css, and it seems Joplin is not rendering certain colors correctly. I assume most basic colors are fine, but I only verified with white (using the hex codes #fff and #ffffff.)

## Environment

Joplin version: 1.6.7 (prod, win32)
Platform: Windows 10
OS specifics: 10.0.19041 Build 19041

## Steps to reproduce

1.  Edit userstyle.css to change the background color (example: `body {background-color: #e85f5c}` )
2.  Quit, and reopen Joplin.
3.  Use a screen color picker (I used the one that comes with [ShareX](https://getsharex.com/)) to verify what color Joplin renders.

## Describe what you expected to happen

I assumed the colors rendered would match exactly with the hex codes I selected. But they appear to be slightly different in most cases.
In my tests, #e3b5a4 is rendered as #dfb5a5, #acf39d renders as #b4f29d, and #e85f5c renders as #df615f, as just a few examples.

**Comment by alexxnz** [comment]
This is still an issue in Joplin version 1.7.11 (prod, win32)

**Comment by dpoulton-github** [comment]
`Joplin 1.7.11 (prod, win32)`

Are you happy your colour picker is working properly? When trying your examples I have always got a match.

![colours](https://user-images.githubusercontent.com/60117449/108012085-69118980-7000-11eb-899d-46b80b1e40c4.png)

_Ignore the fenced code block colour, I just pasted in the relevant line from my **userstyle.css** for comparison._

**Comment by alexxnz** [comment]
I don't use the color picker often, but I haven't had a reason to mistrust it.
I've taken a screenshot of Joplin and a website in Firefox rendering the same color but don't get the same result with the color picker. Even without the color picker, I can see a difference.
Do you get the same result on both halves of the image?

![image](https://user-images.githubusercontent.com/16849366/108013847-87fd2500-6fda-11eb-9c3b-d9f591fdb510.png)

**Comment by dpoulton-github** [comment]
GitHub reducing the image display size can affect colour accuracy. Checking your image at 1:1 I do see the difference. The right hand side is #e3b5a4 but the left (Joplin) is #dfb5a5. I've checked the colours on another Windows machine **and** a Linux machine and they both display the set colour. I have tried using different base themes (Light, dark, Nord, Dracula etc.) in case they have used something else to "tweak" the `<body>` tag. Basically I cannot reproduce what you are seeing. Have you used the dev tools to check that that there is nothing else in your css that is affecting the `<body>` tag?

Rather than being a bug report I wonder if taking this to the forum could get others to try their systems / suggest what may be happening?

**Comment by alexxnz** [comment]
I'm not super familiar with the dev tools, but I was poking around and didn't couldn't see anything that was altering the background color.
I went so far as to remove all other CSS code, leaving only the `body {background-color: #e3b5a4}` line. I still get the same result after restarting the application.
