### ISSUE TITLE
Search not restricted to notebook

### ISSUE THREAD

**Issue by hp6393** [laurent22/joplin#4370]
Windows 10 (64 bit)
Joplin 1.6.6 desktop

When a notebook has been selected in the left pane and then searching for a term, the search is not restricted to the selected notebook. Instead all notes are searched. When a notebook is selected, the **notebook:** filter should be selected by default.

**Comment by psdon** [comment]
As a regular user, this is kinda not preferable. Maybe do a top-down - down-top search approach. Top - down search meaning, if you're inside or opened a file. The search will go through from the current directory and it's subdirectory; then show it in by directory tree manner. Down - top search means, after Top - down has been finished searching, it will go up to from the current directory to it's parent directory and so on... So the result will be sorted from the hierarchy perspective

**Comment by hp6393** [comment]
I was basing this off the search behavior in Evernote, where selecting a notebook limits the search to the notes in that notebook and if you want to search all notes you select All Notes.

**Comment by saptarsi96** [comment]
You can do that in Joplin. 

- Ctrl + F ( To search in local notebook)
-  F6 ( To search globally )

![image](https://user-images.githubusercontent.com/29809001/105315376-32a14400-5be5-11eb-8a2f-67aee06adec6.png)

**Comment by alxpettit** [comment]
Aaagh >.< Someone make a new issue

**Comment by hp6393** [comment]
I agree that this is not intuitive and is a behavior inconsistent with other apps I use (i.e., Evernote and Zotero), but I am told this is by design. I can accept that. It is easily overcome by using the notebook tag in search.

I think the important thing is ensuring that users are aware of this behavior. Otherwise, search results may be misinterpreted.

________________________________

**Comment by rapettif** [comment]
What's the point of closing issues without fixing them?
If the application has a list of notebooks that can be selected, the obvious expected behaviour is for any operation to be restricted to the list of notes currently showing, which are the notes inside that notebook. Every computer program works like this. For example: if you search for a file on a file explorer, the search is restricted to the current directory and subdirectories.
Or at the very least, add an option to restrict the search to the current notebook. Typing notebook:[name] isn't practical, especially if [name] is quite long, includes spaces, etc.

**Comment by crabdancing** [comment]
@rapettif 

Agreed. I hate stale bots. :(
