### ISSUE TITLE
Text formating should be disabled while typing in code block

### ISSUE THREAD

**Issue by harivnair** [laurent22/joplin#4412]
Since the code block is not supposed to allow code formatting like **BOLD** and _italicize_, it should better be disabled.
Now the current behavior is that italicizing wraps the code inside `*code* `which is unwanted

## Environment

Joplin version: Joplin 1.6.6 (prod, darwin)
Platform: Joplin for Desktop for MacOS
OS specifics: MacOS BigSur

## Steps to reproduce

1.  Add some code inside code block
2. Using editor tool BOLDify or italicize any code or code comment
3. Its replicating the editor version of BOLD and italicize.

Expected result is either apply the formatting or disable the formatting for text inside `code block`

**Comment by tessus** [comment]
I disagree. The codeblock doesn't mean that the code couldn't be markdown. In which case you might want to edit the code using the formatting options. Maybe you don't. Others might.

This is certainly not a bug. It is rather a usability issue and should be discusssed on the forum.
However, I doubt it will lead to anything, because restricting the formatting toolbar buttons in such a way makes no sense.
