### ISSUE TITLE
There is a blank block in the note list when Joplin startup.

### ISSUE THREAD

**Issue by loveshizuka** [laurent22/joplin#4425]
There is a blank block in the note list when Joplin startup. Every time I open joplin, it will appear. Like this:

![2021-01-27_02-33-59](https://user-images.githubusercontent.com/25612355/105889259-f2a8e980-6048-11eb-8c3c-18c3fcc82905.png)

If I use the mouse to drag the border of the note list, the note title width will be restored.

## Environment

Joplin version: 1.7.4 (v1.68 has the same issue)
Platform: Windows 10
OS specifics: 20H2
Display resolution： 2k

## Steps to reproduce

1. Open the Joplin as usual.

**Comment by jasonmaskell** [comment]
This is happening to me too, since one of the recent versions of Joplin. I thought it was due to a plugin, but I've disabled them all, and it's still there. If I go to "Change Application Layout", it's actually made of two panels, that are vertically stacked - one above the other.

When this issue initially started for me, perhaps in the previous version of Joplin, or the one prior - the top blank panel actually had text to the effect of "if you see this switch back and forth a few times" - or something like that (I can't reproduce this text in the current version).

I can drag the editor panel to the side of the window, and that makes it disappear. However if I do that, then resizing the entire window smaller, results in the editor panel staying the same size - and being cut off due to extending outside to the left, past the edge of the window area. (This can be dealt with by resizing the window to be wider than this, and then manually resizing the editor panel to an appropriate width).

When starting Joplin with plugins disabled, this blank panel is not visible. It seems that one particular panel brings this issue out (due to adding other panels). Disabling all plugins and restarting Joplin, means that the blank panel persists. Closing Joplin and reopening - does this resolve it?

### Environment
Joplin version 1.7.11
Platform: Windows 10
OS Specifics: 20H2
Display resolution: 1920x1080

### Steps to reproduce
- Open Joplin as usual
Unsure if this issue is just there, or if any of the below are required to trigger it (it's now visible for me just by opening Joplin. The editor pane doesn't resize with the window).
- Go to "change application layout"?
- Enable all available plugins (installed through the settings interface)?
- Resize editor panel?

### Screenshots
How the blank panel looks in the "Change Application Layout" view (it's actually two blank panels):
![image](https://user-images.githubusercontent.com/12572556/108000897-c58f9b80-7036-11eb-888c-e9396ce6c9e0.png)

Back in normal view:
![image](https://user-images.githubusercontent.com/12572556/108000908-cf190380-7036-11eb-8b2e-1a9dcbbe3958.png)

Full screen window after manually resizing editor panel to the edge of the window:
![image](https://user-images.githubusercontent.com/12572556/108001333-e0aedb00-7037-11eb-867f-137da5bff839.png)

Then resizing the window back to a smaller size - the editor pane now extends outside the edge of the window (_Note:_ to resolve, you must resize the window wider than the editor panel, and then manually resize the editor panel. This will reveal the blank panel if the editor panel is resized narrower than the current window size):
![image](https://user-images.githubusercontent.com/12572556/108001478-469b6280-7038-11eb-9ede-68319e477776.png)

**Comment by jasonmaskell** [comment]
I've also tried clearing out the cache and tmp folders as suggested here: [https://discourse.joplinapp.org/t/a-markdown-outline-sidebar-plugin-for-joplin/13364/39?u=jasonmaskell](https://discourse.joplinapp.org/t/a-markdown-outline-sidebar-plugin-for-joplin/13364/39?u=jasonmaskell) - however it makes no difference.

**Comment by liu2z2** [comment]
I had the same issue -- had to remove `database.sqlite` in the config folder to reset some configuration and reconfigure it, which reduces some hassle to reconfigure `userstyle.css`, etc, but I was still a bit frustrated to retrieve my preferences. Hope it to be fixed in the future!
