### ISSUE TITLE
importing enex as md reported as importing as enex

### ISSUE THREAD

**Issue by seatrout** [laurent22/joplin#4432]
## Environment
Joplin 1.5.11 (prod, win32)

Client ID: 92a7bf43132d43dc83dc6958efba4cd1
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: c158878b6 (master)

WIndows 10, VErsion 20H2 

## Steps to reproduce

1. Import an enex file as markdown
2. Look at the progress screen while import is in progress
3. It will say the file is being imported as enex. This is not true
4. Check the imported file. It has been imported as Markdown

## Describe what you expected to happen

It should say that the file is being imported as Markdown

**Comment by seatrout** [comment]
This is still present on Joplin 1.6.8

**Comment by tessus** [comment]
Can you please state the exact message?

I can't find _file is being imported as enex_ anywhere in the code.

**Comment by laurent22** [comment]
Not sure we need a bug report for this. If you can fix the issue that's good, if not I think we can leave it as it is. It's not entirely wrong either - it's importing the file as if it was an enex file, that's what it means. I guess it's phrased that way because in the cli app, it's auto-detecting the type, so it's telling you it's detected an enex file.
