### ISSUE TITLE
Logo proposal for " Joplin "

### ISSUE THREAD

**Issue by moenawar85** [laurent22/joplin#447]
Hello Sir... I would like to contribute with your project by created a new logo. I'm waiting for your response and answer, If you like it I will send the original file that editable in CDR / PDF and PNG also. If you have any suggestion with color or something else I will fix it.

![new logo joplin_presentation](https://user-images.githubusercontent.com/36834147/39058050-fbe7fcb6-44e4-11e8-9173-9719c3b28ce2.png)

Best regards, Moenawar. 
Twitter: @moen85
You can contact me in discord : @moenawar#1364
My steemit account link :  http://www.steemit.com/@moenawar

**Comment by laurent22** [comment]
Thank you for the logo, however at the moment there's no plan to change the existing one (due to the work needed to update it everywhere). In the meantime, they are referenced [in this thread](https://github.com/laurent22/joplin/issues/307) so that we can look at them once we decide to update the logo.

**Comment by moenawar85** [comment]
Thank you indeed for the response/answer
