### ISSUE TITLE
Checkboxes only work for bullet list items using dash marker

### ISSUE THREAD

**Issue by setpill** [laurent22/joplin#4486]
Checkboxes only work if the bullet list item uses a dash (`-`) marker. According to the [Commonmark spec](https://spec.commonmark.org/0.29/#list-items), `-`, `+`, or `*` are all valid bullet list markers, so I would expect them all to work, but they don't.

## Environment

Joplin version: 1.7.11
Platform: Linux
OS specifics: Arch

## Steps to reproduce

Write the following in a note/todo:

```
- [ ] something
* [ ] another thing
+ [ ] a third thing
```

## Describe what you expected to happen

They are all rendered as checkboxes.

## Describe what actually happens

Only the first one is rendered as a checkbox.

**Comment by tessus** [comment]
Checkbox is not in the common mark speciffication or did you fing it somewhere?

It's nowhere specified that a check box is created by a bullet list marker a space and `[ ]`.

**Comment by setpill** [comment]
It is in the [Github Flavored Markdown spec](https://github.github.com/gfm#task-list-items-extension-). And you can also see it work here.

- [ ] this is a checkbox
* [ ] this is a checkbox
+ [ ] this is a checkbox

**Comment by setpill** [comment]
NB: It's not really considered good form to instantly close a bug report if you are asking for more information. It is in my experience a solid recipe for vitriolic conduct on this platform.

**Comment by tessus** [comment]
Well, then. Let's see what Laurent has to say. I can't remeber that we stated that we followed the github flavored markdown spec. If you find such a sentence, please point me to it.

**Comment by setpill** [comment]
https://github.com/laurent22/joplin#markdown

> Joplin uses and renders a Github-flavoured Markdown

**Comment by tessus** [comment]
It's not really considered good form to not answer my question either. I asked if you found the checkbox in the common mark specs. It was a rhetorical question, because it is NOT in the specs.

You left out the most important part. Try to read that sentence again:

Joplin uses and renders a Github-flavoured Markdown **with a few variations and additions.**

Ok. A variation would be that the checkox is created with `-` only. I'm done here.

**Comment by laurent22** [comment]
This is indeed working as expected, we only support `- [ ]`, which is what you get when you press the toolbar button.

**Comment by setpill** [comment]
> It's not really considered good form to not answer my question either. 

Which question did I fail to answer? I have tried to be efficient in providing answers and sources, any brevity was not meant in a negative sense.

> I asked if you found the checkbox in the common mark specs. It was a rhetorical question, because it is NOT in the specs.

I also never claimed it was. I did immediately provide a link to the GFM spec, which this project follows.

> You left out the most important part. Try to read that sentence again:
> 
> Joplin uses and renders a Github-flavoured Markdown **with a few variations and additions.**
> 
> Ok. A variation would be that the checkox is created with `-` only. I'm done here.

I am not sure why you are so intent on proving me wrong on a technicality. Clearly the "few variations and additions" do not mean that something in the spec is not supported without reason. You are weaponizing the letter (as opposed to the spirit) of the README against someone who is simply trying to help improve this amazing project by reporting a bug. I don't know what I have done that has caused you to react this way, but I am beginning to think the problem is not on my end.

**Comment by setpill** [comment]
> This is indeed working as expected, we only support `- [ ]`, which is what you get when you press the toolbar button.

Is there a particular reason for that quirk? I was planning on working on a PR to resolve this issue, but filed the issue first to have a clear rationale for my PR.

**Comment by laurent22** [comment]
Mostly because it's good enough as it is, based on how rarely this topic comes up (in many years, I don't remember it came up at all before).

**Comment by setpill** [comment]
I don't fully understand that argumentation, but perhaps I should just ask if you would accept a PR that fixes this?

**Comment by laurent22** [comment]
What I mean is that's it's not really needed, as few users (only you so far) ask for it. At some level I also prefer to keep simple the Markdown we support as it makes parsing and manipulating the text easier. So for that reason I'm afraid I won't accept a pull request to add this.

**Comment by setpill** [comment]
Maybe I'm naive in the interpretation of the codebase but it doesn't seem to add much complexity to change [this check](https://github.com/laurent22/joplin/blob/8f2594602c2dc0777d839dd232ffa6d8f606ae08/packages/renderer/MdToHtml/rules/checkbox.ts#L152). `+` and `*` are already supported bullet list markers outside of the `checkbox` context, so this would just improve consistency. If you are still opposed to it it's not so important to me, I just figured fixing this minor problem would make for a good entry level fix for me to set up a local dev env so I can get the ball rolling on contributing more useful things.

**Comment by laurent22** [comment]
Sorry I don't quite understand your motivations. If it's not so important for you, and not important at all for anybody else, then why are we discussing this? It's not a small tweak to change the flavour of Markdown we support and should be part of a wider discussion where the impact of the change is discussed properly, but of course there's no need to do this because nobody asked for this change.

If you're interested in contributing, what we mostly need at this point is bug fixing or improvements to the plugin system.

**Comment by setpill** [comment]
> It's not a small tweak to change the flavour of Markdown we support

As I understood from the readme, GFM is already supposed to be supported, hence my reasoning that this is an (minor) bug that I could relatively easy fix to get up to speed with the development practices of this project. I'll still fix it for my own learning process (and because I am used to using asterisks for my bullet lists, and type markdown mostly manually, so this does indeed bother me on a very slight practical level), but won't make a PR out of it, then.

**Comment by laurent22** [comment]
Note that you could probably get this working as a plugin, which means you won't need to run your own build of the app.

**Comment by setpill** [comment]
That's an interesting thought. Might be that I also can change some other _in my perception_ bugs, such as the usage of the expand tabs markdown-it plugin (it changes the whitespace, potentially causing bugs in whitespace-sensitive languages if one copypastes something from the rendered view).

**Comment by bj0** [comment]
I came here to create a ticket about this issue and found this one.  While I'm a little surprised at the tone of this thread, I wanted to add my experience/use case:

I was surprised that this didn't work the same as the 'task list items' extension in gfm, as that is what I'm use to in github, vs-code, and other places.  I think this would be a good change because it would be more consistent with what users who use this feature are use to.

For me specifically, I am moving all my checklists from vs-code loose markdown files to joplin, but all of them currently use the asterik (*) version, so I will have to go through them all and manually edit them to make them look right in joplin.

**Comment by tessus** [comment]
I think my tone was warranted. The OP opened a bug, which wasn't a bug. I explained that and closed the issue.

In the first post the OP mentioned common mark, which has nothing to do with checkboxes. After I mentioned that, the OP switched to GFM (trying to deflect), but ignored the fact that Joplin stated in its docs that it used GFM with a few variations and additions. Once again, the OP tried to wiggle out of it and I was done.

This doesn't mean you can't bring it up as a feature request or discuss this with others. Just not here, because gh is used for reproducible bugs only.
You can use your gh credentials to use the [forum](https://discourse.joplinapp.org/). There's a category for `feature requests`.

**Comment by setpill** [comment]
Couple of corrections:

* Commonmark spec was referenced for the bullet list markers.
* GFM spec was referenced for the task list item extension.
* Referencing the GFM spec in response to it being pointing out task list items are not in Commonmark was not a deflection, rather providing additional context/clarification.
* I did not try to "wiggle out" of anything, I simply explained why the "few variations and additions" part of the documentation did not explain that this inconsistency with GFM was intentional.

Let's not rehash this argument. If you still don't understand where I am coming from, it is fine to leave it be. You have already sufficiently discouraged me from contributing to this project, there's no need for further action.

**Comment by maxmeyer** [comment]
For the records – and besides the fact that his one is a rather old issue –, I was also surprised, that 

```
* List
```
works, but

```
* [ ] Bullet Point
```

does not work.

**Comment by pkoevesdi** [comment]
I can only agree: I'd need this too. 
Whether it is a feature request or a bug: why does it matter so much to get rude on wrong categorization!? If it's not in the spec, be graceful and acknowledge the need and consider putting it in the spec, or reclassify this issue as a feature request, instead of just throwing the wish in the garbage!

**Comment by Spreadcat** [comment]
Glad I checked the issues before I opened a new issue like this one.
I have also though about this many times and being bothered why the checkbox list only works with `-` and not consistently with the rest of the allowed list items in markdown.
This is definitely a feature I already expected to work based on consistency and I stumble over this on a regular basis. There's actually [a (closed) feature request](https://discourse.joplinapp.org/t/allow-all-types-of-lists-to-be-valid-checkbox-items/17510) in the forum regarding this, but it didn't expand beyond the first post.

If this is trivial to implement (as it looks to me, even without being able to contribute here), I'd really appreciate this minor change. It would make life a lot easier.
