### ISSUE TITLE
Opening and closing (with ESC) Tools->Change Application Layout five times, causes MaxListenersExceededWarning

### ISSUE THREAD

**Issue by ambrt** [laurent22/joplin#4493]
On dev Joplin 1.7.11(Ubuntu 18) without any plugins, when one opens  Tools->Change Application Layout and closes it with esc 5 times this warrning appears in Ubuntu console:

"(node:18148) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 
keymapChange listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit.
"

**Comment by laurent22** [comment]
I can't replicate this, does it always happen for you? What editor do you have open?

**Comment by ambrt** [comment]
> I can't replicate this, does it always happen for you? What editor do you have open?

I was running it through VS code console.
Will check if this happens on bare Ubuntu console.

**Comment by ambrt** [comment]
Editor is markdown and preview pane next to it.
Double checked and remove any plugins (even those disabled).
There are left overs from plugins in keymap-desktop.json (about 10 shortcuts)
but that's all.

**Comment by DantrazTrev** [comment]
@ambrt I was able to replicate this issue .

Maybe the listeners attached to the layout panels  `packages/app-desktop/gui/ResizableLayout/MoveButtons.tsx` in  are not been properly or timely deleted ?

I think this is originating from the `packages/app-desktop/gui/ResizableLayout/MoveButtons.tsx`
or from `/packages/app-desktop/gui/ResizableLayout/ResizableLayout.tsx`



PS : I'm not sure about the source

**Comment by ron-debajyoti** [comment]
Hi !
This warning is still shown in Ubuntu 18.04 for joplin v1.8.0.
I found out that this warning is being triggered starting from [this](https://github.com/laurent22/joplin/blob/0da3881aa6cddd465f6fba8ab8b0883b841cb83f/packages/app-desktop/gui/ResizableLayout/ResizableLayout.tsx#L174) line in `/app-desktop/gui/ResizableLayout/ResizableLayout.tsx`, which can be traced back to [this](https://github.com/laurent22/joplin/blob/0da3881aa6cddd465f6fba8ab8b0883b841cb83f/packages/app-desktop/gui/ResizableLayout/utils/useWindowResizeEvent.ts#L5) `useEffect` used here. 

I think denounce and useEffect ultimately ensures that at least one instance of "resize" that keeps listening and since `ResizableLayout` is invoked even without going to Views -> Change Application Layout (as we can readjust directly ), ultimately it keeps listening (even when there are no notes in view) and that's causing the warning. 

The listeners are only removed when I leave the notebook layout to either Tools -> Options or Help -> Sync Status.
I don't think there's much to be done in this case.

Would appreciate your views @laurent22

**Comment by laurent22** [comment]
I cannot replicate this anymore so the bug might have been fixed.
