### ISSUE TITLE
Even when I explicitly tell Joplin to not synchronize (Synchronization interval disabled), it still synchronizes automatically

### ISSUE THREAD

**Issue by RemyWi** [laurent22/joplin#4512]
Even when I explicitly tell Joplin to not synchronize (Synchronization interval disabled), it still trigger the synchronization automatically and try to sync to my target.
Not much to say other than that. 
My environment is a Nextcloud Server as a synchronization target with encryption enabled.

## Environment

Joplin version: 1.7.11
Platform: Microsoft Windows
OS specifics: Windows 10 18363.1316 Version 1909

## Steps to reproduce

1. Set up a synchronization target (Nextcloud to be identical) 
2. Put the interval of synchronization at disabled as well as the "Download of resources" at Manual. 
3. Play with your notes and expect a synchronization attempt at some point

## Describe what you expected to happen
- I would expect the application will not try to synchronize, never, and only a manual push on the synchronize button will do.

**Comment by CalebJohn** [comment]
You should take a look at issue #310 for some context, but the tl;dr is that the synchronization interval is the interval that Joplin uses when checking the sync target for changes. But Joplin will always push up changes ~5s after an edit. This is how the sync system works. (Just note if you do go through that thread, it's pretty old so there are a number of sync related bugs mentioned that have since been fixed).

Feel free to search for issues here on github, or [the forum](https://discourse.joplinapp.org/search?q=synchronization%20interval) if you're looking for more context.

**Comment by RemyWi** [comment]
Thank you Caleb.
I have a better understanding of the synchronization system. 
Though, it's still too bad there is no way to prevent Joplin to push edit sometimes, at least just temporarily.
Sometimes you are on a network where you don't want to send any data related to Joplin on the network. The use case was simply to put Joplin on "stealth" mode with 0 interaction with the network. I believe it's a fair use case, isn't it? 
Thank you for the workaround even if it's not gonna be applicable in my case.
