### ISSUE TITLE
Tags not syncing to android

### ISSUE THREAD

**Issue by aricooperman** [laurent22/joplin#4522]
Started to test using Joplin to replace Evernote. I imported a notebook at enex output from Evernote in the desktop app (linux). Everything looked good and bites plus tags showed up. Synced with Dropbox and then installed app on android, synced, and all notes were there but no tags.

## Environment

Joplin version: 1.7.5
Platform: Android
OS specifics: Android 11

## Steps to reproduce

Described above

## Describe what you expected to happen

Tags should sync and show up

## Logfile

Can provide relevant sections of logfile on request. It is too big to add all here

**Comment by CalebJohn** [comment]
This is usually because the sync has not been allowed to complete on the android side. 

Take a look at [this forum post](https://discourse.joplinapp.org/t/android-sync-and-encryption-issues/14797) for details on how to check the sync status.

I can't find the post, but a few days ago a user pointed out that you should disable automatic syncing on android while performing the first sync. You will need to keep the screen on and Joplin open, but the sync should come through more smoothly.

Please try syncing again and let me know if the tags come through. If they don't, please include screenshots of the synchronization details screen from both android and and your desktop version.
