### ISSUE TITLE
Plugin - Ghost panel and resizing issues

### ISSUE THREAD

**Issue by ambrt** [laurent22/joplin#4529]
These are two bugs but seem to be related to plugins' panels.

Basically if plugin creates panel conditionally (on a restart of an app)
the empty panel stays visible even if condition is not to create one.

The second is that if panel is on the right, the editor and preview panes aren't
resized when resizing whole window.
Gif below shows those two:
![Peek 2021-02-13 20-40](https://user-images.githubusercontent.com/10456131/107859716-aed12500-6e3b-11eb-8e1a-869209b92b4b.gif)

No errors in console.

Reproduction plugin on  "panel-bug" branch https://github.com/ambrt/joplin-plugin-referencing-notes/tree/panel-bug

I'm seeing it on Ubuntu with Joplin v1.7.11  but other user have reported
it on win and mac also: https://github.com/ambrt/joplin-plugin-referencing-notes/issues/4

There is a bug reported that happens on Zooming in/out while having side panel, seems to be related:
https://github.com/laurent22/joplin/issues/4508

**Comment by ambrt** [comment]
@laurent22 I've read on forum that you can't reproduce it.
Maybe one way to trigger this bug is to resize panel manually in View->Change application layout.
I had moment when i could turn on/off panels correctly when doing `joplin.panels.show/hide`
from plugin and then got bug again. 
I'm sure that i was resizing manually it but not sure when.

**Comment by TeresaM12** [comment]
problem still exists e.g. when using note tabs plugin and it seems as soon as a plugin is used which uses an extra pane

**Comment by HOLLYwyh** [comment]
I'm trying to solve this problem...

**Comment by roman-r-m** [comment]
Are you going to work on 2 issues at once: this and https://github.com/laurent22/joplin/issues/4433 ?

**Comment by mablin7** [comment]
I think this is the same issue I'm facing: when a plugin panel is closed (hidden) it still takes up space, but only if it was resized at some point.

I believe the problem is that, when a panel to the right of the editor is resized, it actually resizes the editor, which thereby gets assigned a fixed size in the layout, so it can no longer take up the free space left by the hidden panel.

Here I've removed the fixed size of both the notebook and the note lists, only the editor has a set width. You can see that, when the plugin panel is closed, the notebook and the note list expands to take up the free space:

![rec](https://user-images.githubusercontent.com/7415668/115152882-60c2e280-a073-11eb-9411-943bf0277e8a.gif)

This also explains the issue raised by @ambrt :

> Basically if plugin creates panel conditionally (on a restart of an app)
> the empty panel stays visible even if condition is not to create one.

The size of each panel is saved to `settings.json`, so even after a restart, they still can't expand to take up the space left behind by the panel that was once opened.

**Comment by laurent22** [comment]
This is strange because there's a validateLayout function that should take care of this - if all layout items have a fixed size, then the last item should be changed by this function to have a flexible size. So maybe the issue is that it's somehow not called when it should.

https://github.com/laurent22/joplin/blob/7151a4813843a4f9bcf303265dfb744e31d2bd05/packages/app-desktop/gui/ResizableLayout/utils/validateLayout.ts#L15

**Comment by mablin7** [comment]
Oh I did not know that. So maybe [my long post](https://discourse.joplinapp.org/t/fixing-ghost-panel-and-resizing-issues-4529/16814) on the forum proposing a solution was pointless..

**Comment by mablin7** [comment]
> This is strange because there's a validateLayout function that should take care of this - if all layout items have a fixed size, then the last item should be changed by this function to have a flexible size. So maybe the issue is that it's somehow not called when it should.
> 
> https://github.com/laurent22/joplin/blob/7151a4813843a4f9bcf303265dfb744e31d2bd05/packages/app-desktop/gui/ResizableLayout/utils/validateLayout.ts#L15

Oh yes, I've got it. It's because the plugin panel has no width, so the function assumes that that should stretch to take up the free space, but it's not visible. So I guess a visibility check here would solve the issue?

https://github.com/laurent22/joplin/blob/7151a4813843a4f9bcf303265dfb744e31d2bd05/packages/app-desktop/gui/ResizableLayout/utils/validateLayout.ts#L22

**Comment by laurent22** [comment]
> I did manage to get it to work in the end. For each item I had to find out whether it is last visible item in it's parent. For this I loop through the sibling items in reverse order and on the first visible one check whether it's the current item. If not we break, if yes we continue looping to find out whether all siblings have a fixed size. This is a bit less efficient than how it was, but it works.

That would make sense, and maybe we could replace the condition `if (itemIndex === parent.children.length - 1)` with something like `if (isLastVisibleItem(itemIndex, parent.children))` to abstract away the complexity.

**Comment by phpcitizen** [comment]
For me notetabs plugin creates a ghost panel

**Comment by jayarkay** [comment]
This issue was not resolved at least for me as of 6/25/2025 - running Joplin via AppImage on Fedora Workstation 42 until I saw this:

> For me notetabs plugin creates a ghost panel.

This finally helped! Thanks @bfcns
