### ISSUE TITLE
Fail to start using FireJail

### ISSUE THREAD

**Issue by nidamanx** [laurent22/joplin#4546]
## Environment

Joplin version: 1.7.11
Platform: Linux
OS specifics: Debian 10 Buster

## Steps to reproduce

1. $ firejail --appimage ./Joplin.AppImage

## Describe what you expected to happen
Joplin, which is a real good software, should start as all other AppImages I use(d) with [FireJail](https://github.com/netblue30/firejail)

## Logfile
I cannot attach the log file because the Joplin didn't start
Here is the result from the shell
```
$ firejail --appimage ./Joplin.AppImage
Mounting appimage type 2
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Warning: networking feature is disabled in Firejail configuration file

** Note: you can use --noprofile to disable default.profile **

Parent pid 15501, child pid 15504

**     Warning: dropping all Linux capabilities     **

Child process initialized in 125.37 ms

Parent is shutting down, bye...
AppImage unmounted
```

**Comment by rusty-snake** [comment]
The problem is that there is no profile for it yet (but there's a request in netblue30/firejail#1139). Therefore the default.profile is used which is a compromise between security and compatibility. This may work, or maybe not, or only with some limitations. For electron apps it only works if it is started with `--no-sandbox`.

If you want to not use `--no-sandbox`, you should use electron.profile (e.g. `firejail --profile=electron --appimage ./Downloads/LosslessCut-linux.AppImage`). However you need to use firejail 0.9.64.2 or higher, the electron.profile in 0.9.64 and below does not work out-of-the-box and you need to use `--seccomp='!chroot'` (if unprivileged unerns are enabled) or `--ignore=nonewprivs --ignore=noroot --ignore=protocol --ignore=seccomp --ignore=caps.drop --caps.keep=sys_admin,sys_chroot` (if unprivileged unerns are disable) in addition. Moreover you can not use `--appimage` if unprivileged unerns are disabled and you start the electron-app w/o `--no-sandbox`.

**Comment by nidamanx** [comment]
Thanks @rusty-snake
