### ISSUE TITLE
Math syntax highlighting in editor

### ISSUE THREAD

**Issue by jrwrigh** [laurent22/joplin#4554]
## Environment

Joplin version: 1.7.11 (prod, linux), d6b77db
Platform: Linux
OS specifics: Manjaro

## Steps to reproduce

1. Type in `$X_n$, word $x \in X$`

Get the following syntax highlighting:

![image](https://user-images.githubusercontent.com/20801821/108415700-1b0ca980-71eb-11eb-9a7b-d2bd06a0ff83.png)

`word` is being highlighted in blue for some reason.

## Describe what you expected to happen
By adding a space between the comma and the second `$` (ie.  `$X_n$ , word $x \in X$`) I get what I would expect:
![image](https://user-images.githubusercontent.com/20801821/108415819-3b3c6880-71eb-11eb-9ce4-f993e2508a8e.png)

**Comment by CalebJohn** [comment]
This is due to the regexes in the following file
https://github.com/laurent22/joplin/blob/dev/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useJoplinMode.ts#L23

These can definitely be updated to more closely align with the rendered view (but care needs to be taken to make sure rendering in other situations isn't broken).

If you or someone else who happens to see this would like to take on the task, I'd be happy to review it. But I don't have the time in the foreseeable future to correct this myself.

**Comment by jrwrigh** [comment]
No worries. I'm actually pretty handy with regex, but not with building Joplin. I can work with an online regex parser to trial a new string. Probably won't have time to figure out how to build Joplin to test it in the actual system though.

**Comment by jrwrigh** [comment]
In:
https://github.com/laurent22/joplin/blob/a6b866cbe1362e0a6254774aec398c149592826c/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useJoplinMode.ts#L23-L26

Replacing:
```const inlineKatexCloseRE = /(?<![\\\s$])\$(?!\S)/;```
with
```const inlineKatexCloseRE = /(?<![\\\s$])\$(?![^\s!"#%&'()*+,\-.:;<=>?@[\]^_`{|}~])/;```

should to the trick. Effectively, instead of doing the negative look ahead assertion (`(?!...)`) for any non-whitespace character (`\S`), we do the assertion for any single character except whitespace _and_ punctuation. Note I've not used the `[[:punct:]]` character class here as it includes a `$`, which would conflict with the `blockKatexCloseRE` regex.

Here's a link to the regex tester I was using, with the regex filled and some example text used: https://regex101.com/r/pqiO24/1 For posterity, here was the example text I was using for testing:
```
stuff $X_n$, word $x \in X$
$X_n$ , word $x \in X$

$$X_n = \sum_n^j x_n$$
```
So the last `$` should match for all but the block equation.

I can put this in a pull request if that'd be easier for you to review @CalebJohn.

**Comment by CalebJohn** [comment]
@jrwrigh 
Sorry for such a late reply, I typed up a response 2 days ago but it seems I failed to send it.

Yes please make a PR. No worries if you don't want to get the dev environment set up, I can test it on my machine. 

One thing I noticed while looking at this is that `inlineKatexOpenRE` will also need to change, since it has a look ahead

```javascript
 const inlineKatexOpenRE = /(?<!\S)\$(?=[^\s$].*?[^\\\s$]\$(?<![\\\s$])\$(?![^\s!"#%&'()*+,\-.:;<=>?@[\]^_`{|}~]))/; 
```
