### ISSUE TITLE
Self-hosted Joplin Server Unknown error (400) Delta cursor is invalid and the complete data should be resynced

### ISSUE THREAD

**Issue by Paulmicha** [laurent22/joplin#4559]
## Environment

Joplin version: 1.7.11
Platform: Linux
OS specifics: Pop! OS 20.04 LTS (based on Ubuntu / Debian)

## Steps to reproduce

1. Install remote Joplin Server (see attached docker-compose files below)
2. Correctly setup synchronization settings in the local client
3. Sync (Ctrl + S)

[docker-compose.yml.txt](https://github.com/laurent22/joplin/files/6010731/docker-compose.yml.txt)
[docker-compose.override.yml.txt](https://github.com/laurent22/joplin/files/6010732/docker-compose.override.yml.txt)

## Describe what you expected to happen

Tried to restart the app, delete empty dirs on the remote, some conflicts appeared. Still no files saved remotely (only dirs).
Switched to debug mode. It looks like https://github.com/laurent22/joplin/issues/4305

## Logfile

[log.txt](https://github.com/laurent22/joplin/files/6010668/log.txt)

**Comment by Paulmicha** [comment]
NB : the problem does NOT occur locally (tested the exact same docker-compose stack before on my LAN without any issue).

**Comment by adrynov** [comment]
Same here, worked fine yesterday.

**Comment by Paulmicha** [comment]
Without doing anything else, I tried again today, and the error occurred after having managed to sync a few files :

![screenshot-joplin-server-2021-02-20-18-51-35](https://user-images.githubusercontent.com/1526964/108609597-ac2b7e00-73ad-11eb-9936-ca1e9556d1b9.png)

Additional info, perhaps relevant :

- There's a 250ms latency on average when I ping my server.
- It's on a different timezone than my laptop's.

**Comment by didn0t** [comment]
I've just installed joplin server and am seeing the same error on a fresh setup.

**Comment by didn0t** [comment]
FYI, I exported my notebooks - deleted everything from the server and all of the clients.
I then reimported and got 2 desktop and 1 mobile client synced up with out error.
Has been running for a day with no errors so far.

**Comment by adrynov** [comment]
That is the only option so far

**Comment by pghpete** [comment]
I had a similar issue. I took @didn0t 's advice and basically rebuilt my environment after removing everything. Even the containers on the self-hosted sync server I have.  However it would "sync" everything (I could see the files populating on the server) but then choke on one particular file. It did this to one longfilename.md file before clearing and redoing things, then another on the rebuilt environment.  Here is the error and how I got around it eventually. In case anyone else runs into a similar issue.

```2021-04-02 15:42:12: "Error: PUT api/files/root://.resource/8125dcf34aa04d29af3311137281181e:/content: Unknown error (413): ```
```<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.14.1</center>
</body>
</html>
```
pulled from this file` /home/<username>/.config/joplin-desktop/log.txt` file.

ls -lah /home/<userid>/.config/joplin-desktop/resources | grep 1181e
cd  /home/<userid>/.config/joplin-desktop/resources
rm 8125dcf34aa04d29af3311137281181e.crypted
rm 8125dcf34aa04d29af3311137281181e.pdf 

And after a resync this worked.

**Comment by roman-r-m** [comment]
Maybe you could increase `client_max_body_size` in your nginx config to avoid this error.

**Comment by pghpete** [comment]
> Maybe you could increase `client_max_body_size` in your nginx config to avoid this error.

I hadn't thought about that. I'll have to read up on that value to ensure it's given a sane value. Thanks!

**Comment by fupenghao** [comment]
I had the same problem today, but luckily I finally resolved this issue.

Here is my method if you do not wish to read everything below.
(This problem could be easily solved by cleaning the locally saved Joplin Client data  without reinstall the Client.)

I am using the Joplin Server in docker and I am also using the Joplin Client App on both my windows 10 and iPhone.

First I set my Joplin Server using its default SQLite. Everything was fine using SQLite.
The error shown out when I tried to switch to a postgresSQL running in another docker server.

The same error just as you described "Self-hosted Joplin Server Unknown error (400) Delta ..."

I rebuilt the Joplin Server several times but the issue was still there.

And here is how I eventually solve the problem.
1. I rebuilt the Joplin server totally
   i. removed the docker Joplin volume created earlier
   ii. removed the database and user created in the postgresSQL earlier
   iii. rebuilt everything until the Joplin Server can run smoothly without any error.
   do not connect any of your Joplin client to the Server now.

2. On my iPhone.
   i. I clean the Joplin App data stored on my iphone then uninstalled the app.
   ii. I reinstalled the Joplin App and reconnected to the Joplin Server.
   Everything is working fine on my iPhone Joplin App now.

3. On my Windows 10
   i. I deleted the `C:\Users\(Here is your account name)\.config\joplin-desktop` folder
   ii. I deleted the `C:\Users\(Here is your account name)\AppData\Roaming\@joplin` folder
   iii. I uninstalled the Joplin software ,reinstalled it then connected to the Joplin Server
    Everything is working fine on the Windows 10 now.

* Pls notice that I only installed the Joplin Windows 10 software to the current user( not to everyone)
   If you installed the Joplin Windows 10 software for everyone, maybe there will be other folders you need to delete.


And finally I believe the problem is, the Joplin App stored some data on your device to compare with the data it fetched from the Joplin Server.
When I rebuilt the Joplin Server without cleaning the Joplin Client App data, the Joplin Client App would find some part of his previously locally stored data didn't match the data it fetched from the server. So it showed the error and stopped the sync.

So I believe if your Joplin Server is set correctly.
This problem could be easily solved by cleaning the locally saved Joplin Client data  without reinstall the Client.

**Comment by leder11011** [comment]
bump!
