### ISSUE TITLE
[Feature Request] Mark syntax

### ISSUE THREAD

**Issue by zblesk** [laurent22/joplin#457]
I'd like to use the Markdown "highlight"/"mark" syntax, `==like this==`. 

Sample implementation e.g. here: https://github.com/markdown-it/markdown-it-mark  

I can use the `<mark>` tag instead (and that works well within Joplin), but I'd appreciate having a shorthand syntax instead.

**Comment by laurent22** [comment]
Is it a standard Markdown feature?

**Comment by zblesk** [comment]
At this point, I honestly don't know what to consider "standard", when it comes to markdown. I've seen it plenty of times and it's really quite handy. And there's that markdown-it plugin, so it should be relatively simple to support. Beyond that, 🤷🏻‍♀️.

**Comment by mmahmoudian** [comment]
I was just searching on what is typical for highlighting the text in Markdown. Seems there is no defined standards, but most applications I found have used ==text== to highlight the text. I also found `<mark>´ in [stackoverflow](https://stackoverflow.com/questions/25104738/text-highlight-in-markdown#36039773) which works in Joplin but:

1. the text would be highlighted in a dark red color
2. the´codes´ would become unreadable due to gray background and white text color

It would be nice to have it as normal yellow color.

Also I would like to suggest that user be able to highlight the text while being in preview layout by selecting the text, rightclick and select highlight from the rightclick menu. (would be very convenient when reading the text

**Comment by alglez** [comment]
I was checking this for this feature. Recently I moved from evernote and a lot of my marks in evernote are not available in joplin, searching I found `<mark>` and it worked as expected. 

Checking the enex file, evernote mark those highlights as 

`<span style="x-evernote:highlighted;background-color:#F6EE96;">`

**Comment by CalebJohn** [comment]
This was fixed in #1347 by the addition of the markdown-it-mark plugin.

**Comment by bogusred** [comment]
w00t! Thank you @CalebJohn . Confirmed highlights work great!
