### ISSUE TITLE
I can not copy images to another editor from joplin.

### ISSUE THREAD

**Issue by EricoCartmanez** [laurent22/joplin#4602]
## Environment
Joplin version: Joplin 1.7.11 (prod, darwin)
Platform: 
OS specifics: macOS Mojave

When I copy content from Joplin to another editor, the images are missing. Which makes this tool unusable to me once Iike using it but I need to fill reports in .docx format. 
So when I'm done with my notes I want to copy the whole content to another editor but this is not possible.

**Comment by isdnfan** [comment]
same on Windows 10 + Joplin 1.7.11 - both Markdown and Rich-text editors are affected.

**Comment by harshitkathuria** [comment]
I would like to work on this issue.

**Comment by DantrazTrev** [comment]
Hey , Is anyone working on this issue I would like to take it up ?

**Comment by nishantwrp** [comment]
Hi @DantrazTrev, I am working on this issue.

**Comment by Ahmad45123** [comment]
Hmm the problem with this issue is that I don't think there's any "set" standard on how clipboards work or their format. But an initial idea I've got is to handle the event `GetContent` in TinyMCE and go through all <img> elements (probably using some regex ?) Then, replace each image element to its equivalent base64.

This way the clipboard would contain all image data built in and no depend on any file. This should help with copy pasting even to online websites.

IDK if this is the correct way to handle this so I think I'll wait to better to gather ideas first.

**Comment by nishantwrp** [comment]
I investigated the issue while also testing other editors like Libre Office Writer and found that in the following two scenarios.

### When only a image is selected and pasted somewhere

- Most editors copied the conent of the complete image instead of being dependent on the file. Thus allowing the image to be pasted both online and offline.

- In Joplin, the coped content was dependent on the file. Which makes it impossible to be pasted in online editors. But however, pasting the image in offline editors also didn't work because the file path being referred in the copied content was `file:///home/nishantwrp/.config/joplindev-desktop/resources/e9a37b3e9304420091eaf0b3a6e4db4d.jpeg?t=1616388657615` (Notice the ?t=1616388657615). Removing this extra part allowed images to be pasted in offline editors successfully. This seems like a small issue and can be fixed.

### When mixed content is copied i.e some text with image

- Most editors copied the content and this time the image copied was dependent on the file. Therefore, while pasting in online editors the images weren't present. In offline editors, the pasting worked perfectly fine.

- In Joplin, similar to the previous case the content was copied and the image was dependent on the file. Which results in images not appearing in online editors. But also images couldn't appear in offline editors because of the bug described in the previous case.


## My opinion

IMO, we can do the following two things to improve the functionality.

- When a single image is selected we can make the content of the image copied to the clipboard instead of being dependent on the file.
- We can fix the extra `?t=` bug described above which enable the users to completely copy content b/w offline editors.

 What do you all think?

**Comment by roman-r-m** [comment]
Makes sense to me. 

Maybe it's worth removing the `?t=` first for a quick win, as this alone seems to cover 2/3 cases.

**Comment by isdnfan** [comment]
on windows clipboard can handle different formatting [use-rich-edit-clipboard-operations](https://docs.microsoft.com/en-us/windows/win32/controls/use-rich-edit-clipboard-operations?redirectedfrom=MSDN) for Linux I have no reference handy. 

As more portable approach there is a library which offers conversion to/from different markup formats, it is available for every relevant platform, maybe there is a way to integrate it?
>Pandoc is a Haskell library for converting from one markup format to another, and a command-line tool that uses this library.
[pandoc](https://pandoc.org/MANUAL.html)

**Comment by nishantwrp** [comment]
@roman-r-m, good idea. I'll make a PR to fix the `?t=` issue.

**Comment by nishantwrp** [comment]
@laurent22 can you please open this issue. I think there's one part left to properly fix this issue i.e. "When a single image is selected we can make the content of the image copied to the clipboard instead of being dependent on the file."

**Comment by laurent22** [comment]
In this case a new issue needs to be opened. This is the reason why we don't accept multiple bug reports within an issue - otherwise it means we either close it too early or never close it.

**Comment by nishantwrp** [comment]
Ah okay got it. Filed #4764 for this issue.
