### ISSUE TITLE
The combined search returns no results for Chinese

### ISSUE THREAD

**Issue by novelx** [laurent22/joplin#4613]
The fantastic search feature is a bold reason that I'm using Joplin. When I search one Chinese word it works pretty well, and it's fast and accurate. I recently found that when I type in two Chinese words seperated by ' '(space) in the search box, there's always no result returned, despite what words I search and what they are organized in the original notes. I used to think that it is as design, but recently I found that when I type in two English words it works pretty well and returns the notes that contain both of the words.

## Environment

Joplin version: 
Platform: macOS
OS specifics: Catalina 10.15.7

## Steps to reproduce

1. create a note with content "目录  文件" (two spaces between the Chinese words) or "文件目录"
2. in the search bar, input "目录 文件" (one spaces between the Chinese words which implies "AND") 
3. No notes were found.

## Describe what you expected to happen

The search results contain all of the notes that contain both word "目录" and word "文件".

**Comment by StinkyBenji** [comment]
Do you still have this issue? I just tried to reproduce your problem, I didn't run into the problem that you mentioned.

**Comment by mablin7** [comment]
I think I can reproduce it, but I don't speak Chinese, so @novelx please correct me if I misunderstood something.

Latin script, search finds note which contain all words:
![image](https://user-images.githubusercontent.com/7415668/111301691-cbd36080-8652-11eb-84c7-e06c2cdffa83.png)

Chinese test note:
![image](https://user-images.githubusercontent.com/7415668/111301841-f6bdb480-8652-11eb-8199-6711033a07dc.png)

Chinese test query (two non-consecutive characters taken from the text):
![image](https://user-images.githubusercontent.com/7415668/111302117-4ac89900-8653-11eb-8bdf-43f3f87bf5aa.png)

I believe the problem comes from Sqlite's FTS tokenizer and the fact that Chinese script does not require spaces between words. According to [this comment](https://github.com/groue/GRDB.swift/issues/413#issuecomment-423429307):

> ...the built-in tokenizers (unicode61 and others) are latin-oriented. They split strings into tokens according to latin word boundaries (spaces, tabs, newlines, etc.). They don't handle Chinese and generally languages that do not use latin word boundaries. A Chinese sentence such as 你會說中文嗎？ will give a single token: 你會說中文嗎.

One way to get around this is using a [custom tokenizer](https://sqlite.org/fts3.html#custom_application_defined_tokenizers), like [this one](https://github.com/haifengkao/SqliteSubstringSearch) implementing fast substring search for FTS, but it would require compiling a C module for all supported platform, which would complicate Joplin's build process. 

A far simpler solution would be just not to use FTS for Chinese texts at all, and just use substring matching (`LIKE '%文%'`). This would be of course much slower, but requires minimal changes to the codebase.

PS. I discovered that the `any:1` search filter doesn't seem to work for Chinese texts.

![image](https://user-images.githubusercontent.com/7415668/111306950-21ab0700-8659-11eb-88d2-24a78aa4537c.png)
As you can see the characters match individually:
![image](https://user-images.githubusercontent.com/7415668/111307102-4bfcc480-8659-11eb-9d85-f65bce26cde0.png)
![image](https://user-images.githubusercontent.com/7415668/111307150-5919b380-8659-11eb-9df9-4793f44bc1b9.png)

It might be a completely unrelated bug though.

**Comment by StinkyBenji** [comment]
ahh, you are right @mablin7, I didn't understand the issue correctly, I simply searched two words next to each other and it works fine as you described.
And the substring matching works well.

**Comment by novelx** [comment]
> I think I can reproduce it, but I don't speak Chinese, so @novelx please correct me if I misunderstood something.

@mablin7 You are right! You did exactly what I mentioned in the original post to reproduce the issue.

**Comment by novelx** [comment]
Anyway I want let it open and hope it will be fixed soon

**Comment by leon0625** [comment]
Hope this problem can be fixed soon.
Searching for multiple Chinese keywords is so important.
