### ISSUE TITLE
What is going on with `import Plugin from '../Plugin'` in the plugin template?

### ISSUE THREAD

**Issue by thejohnfreeman** [laurent22/joplin#4643]
In the [template](https://github.com/laurent22/joplin/tree/dev/packages/generator-joplin/generators/app/templates) used by the Yeoman generator, there's a [top-level directory `api`](https://github.com/laurent22/joplin/tree/dev/packages/generator-joplin/generators/app/templates/api) containing type declarations for the plugin API. Most of the files in that directory [start](https://github.com/laurent22/joplin/blob/dev/packages/generator-joplin/generators/app/templates/api/Global.d.ts#L1) with `import Plugin from '../Plugin';`

What is import line doing? There is no `Plugin.ts` or `Plugin` directory in the one above `api`. There is no path alias in `tsconfig.json` for any `Plugin` module. The import appears meaningless. If I try to compile with `tsc --project tsconfig.json`, I get many repeated errors for all of those imports. I guess the Webpack configuration suppresses those errors, because they don't appear when Webpack builds the plugin.

Similarly, there is a [dangling import](https://github.com/laurent22/joplin/blob/dev/packages/generator-joplin/generators/app/templates/api/JoplinWorkspace.d.ts#L1) (`import { FolderEntity } from '../../database/types';`) in `JoplinWorkspace.d.ts`. Only one copy of that one, though.

I don't want to be bound to Webpack. I don't want to version control type declarations for the plugin API alongside my plugin code. I want to put those type declarations in a separate NPM module that I can depend on, and I want to experiment with other bundlers, like Snowpack. First, I have to understand what is going on with the TypeScript compilation. I hope this can lead to me contributing a Snowpack configuration, an NPM module for the type declarations, and a smaller, easier to understand and update template for plugins that builds faster and with better diagnostics.

**Comment by laurent22** [comment]
The /api folder is generated using [updateTypes.sh](https://github.com/laurent22/joplin/blob/dev/packages/generator-joplin/updateTypes.sh). Essentially, it generates the types for the whole project but only copy the files from [packages/lib/services/plugins/api](https://github.com/laurent22/joplin/tree/dev/packages/lib/services/plugins/api) to [packages/generator-joplin/generators/app/templates/api](https://github.com/laurent22/joplin/tree/dev/packages/generator-joplin/generators/app/templates/api) (which is the Yeoman generator).

So that's why it has references to classes that are not included, but at least with the WebPack setup it's not an issue (unused types are just ignored).

Your approach with an external package that contains the types would indeed be preferable but not sure how to do that.

**Comment by thejohnfreeman** [comment]
I've announced the release of my approach [here](https://discourse.joplinapp.org/t/beta-easier-workflow-for-making-plugins/17472).
