### ISSUE TITLE
Copying code block results in two copies of the text

### ISSUE THREAD

**Issue by alan666notb** [laurent22/joplin#4669]
## Environment

Joplin version: Joplin 1.7.11 (prod, win32)
Platform: Windows
OS specifics: 10

## Steps to reproduce

1. Open a note with a code block in it.
2. Right click on the code block & select 'Copy'
3. Paste into somewhere else, E.g. notepad.

## Describe what you expected to happen
The text block should be pasted into notepad, instead I get two copies concatenated.
E.g. if the code block contains "#!/bin/sh ", I get "#!/bin/sh #!/bin/sh " pasted.

**Comment by YannyTwoo** [comment]
I'd like to work on this.

**Comment by YannyTwoo** [comment]
I'd like to work on this.

**Comment by coderrsid** [comment]
I can reproduce this issue on macOS too. Working on this. Thanks

**Comment by coderrsid** [comment]
As much as i could understand, we are stripping HTML from the code but as in code, the text exists twice. First, in <pre>...</pre> tag and between <code>...</code> tag, so it gets repeated in clipboard after stripping html to get text. 

<img width="541" alt="image" src="https://user-images.githubusercontent.com/35633575/112632258-e5985300-8e5d-11eb-8fa4-e01dddc64561.png">

**Comment by laurent22** [comment]
Yes, the issue is that the "joplin-source" block is actually hidden, but somehow it gets copied to the clipboard as clear text. Perhaps there's some HTML or CSS attribute that can be set which says "don't copy this part"?

**Comment by coderrsid** [comment]
Yeah, i think so. But when i went through electron clipboard api and there are only few methods with not such modifications, rather i found a solution of getting substring from this string starting after '<code tag>' and ending before '</code tag>'

**Comment by jalajcodes** [comment]
> But i am thinking that would it be stable always?

I think a better way to fix this would be to check and ignore `joplin-source` block while stripping html to text. What do you think?

**Comment by laurent22** [comment]
Wouldn't `user-select: none` do the job?

**Comment by jalajcodes** [comment]
> Wouldn't `user-select: none` do the job?

I'm not sure if its the right way but I tried adding it to the `joplin-source` block via dev tools, it didn't work

**Comment by coderrsid** [comment]
Yeah i tried that too, i guess electron api says the same. Although i am able to solve the problem by the code block i shown.

![Screen-Recording-2021-03-27-at-1](https://user-images.githubusercontent.com/35633575/112684730-75a7be00-8e99-11eb-852b-6d6f90aea52f.gif)

**Comment by mablin7** [comment]
First, I think that the content of `pre.joplin-source` tag should be copied to the clipboard, because it will work for other editables too, like mermaid diagrams.

Also, I think using string methods to work with HTML is not a very good idea, because any change to the tags or attributes will break it. Maybe we could pass the whole node, instead of the HTML code? Here `getContent` can be replaced with `getNode`:
https://github.com/laurent22/joplin/blob/3fa13828cdd59c56aaacb15b4ef6bda442ac524a/packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/utils/useContextMenu.ts#L72

Then here just get the `textContent` of the tag with class `joplin-source` for the text. For the html, I suppose you should somehow strip the source tag, but without mutating it, because it's still a reference to the original node. I guess that's the big downside to this approach: passing around mutable references. 
https://github.com/laurent22/joplin/blob/3fa13828cdd59c56aaacb15b4ef6bda442ac524a/packages/app-desktop/gui/NoteEditor/utils/contextMenu.ts#L55-L56

My other idea would be to still pass the HTML code as a string, and then in the `handleCopyToClipboard` function parse it again, like so:
```javascript
const el = document.createElement('div');
el.innerHTML = options.htmlToCopy;
/* get the tags we need here */
```

**Comment by coderrsid** [comment]
Yeah i agree that will break. But getting the content is fine from editor.
Rather i got other idea of using regex for parsing content, so i tried but then i got two pre tags (one with `joplin-source` attributes and other with `hjls` classname) when i tried to match with regex. So, used the one with `joplin-source` anyways, i found the way using regex without mutating it.

Instead of just stripping the whole html, 
https://github.com/laurent22/joplin/blob/3fa13828cdd59c56aaacb15b4ef6bda442ac524a/packages/app-desktop/gui/NoteEditor/utils/contextMenu.ts#L55

First retrieving our pre tag for the singular content 
` text: htmlUtils_1.default.stripHtml(options.htmlToCopy.match(/<pre [^>]+>(.*?)<\/pre>/g)[0]),`

@laurent22 , you think this'd be the way?

**Comment by roman-r-m** [comment]
Usually, parsing xml with regex is a bad idea.

**Comment by coderrsid** [comment]
yeah @roman-r-m, i tried to read about it. Yes, you're right. Then the way i can see is we make a dummy element with innerHtml assigned as the string `options.htmlToCopy` as suggested by mablin and then using `querySelector` we can take out tag's `textContent` with class name as `joplin-editable > joplin-source`. 
I tried this way and was able to pull out the text easily. But i already have a PR in queue. So any dev can go ahead and make that or can i ?

**Comment by alokprasad** [comment]
Any update on this bug i am still facing the issue.
```
Joplin 3.5.11 (prod, win32)

Device: win32, 12th Gen Intel(R) Core(TM) i7-1265U
Client ID: c91c1a1bdbb04b2abacb166d82279124
Sync Version: 3
Profile Version: 49
Keychain Supported: Yes
Alternative instance ID: -

Revision: e75875c

Backup: 1.5.1
Freehand Drawing: 4.2.0
Quick HTML tags: 0.2.0
```
its not about pasting , even if you open code block and manually type text appears twice. e.g below i have typed
"Hello" once but its appearing twice

<img width="487" height="98" alt="Image" src="https://github.com/user-attachments/assets/7eee458b-5200-4d5e-9d8e-fa10acf3ca66" />
