### ISSUE TITLE
updating a disabled plugin automatically enables it

### ISSUE THREAD

**Issue by tessus** [laurent22/joplin#4683]
## Environment

```
Joplin 1.8.0 (dev, darwin)

Client ID: e354a932e6e143c782264aad4112b674
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: 131a7e736 (dev)
```

## Steps to reproduce

1. Install a plugin
2. Disable the plugin
3. Wait until there's an update
4. Update the plugin
5. The plugin is automatically enabled

## Describe what you expected to happen

I expected the plugin to stay disabled. 

## Logfile

There are no errors in the console nor in the `log.txt`.

**Comment by mightomi** [comment]
I like to work with this issue if it's okay

**Comment by tessus** [comment]
Let's wait what Laurent has to say. Maybe it's feature and not a bug. Who knows.

**Comment by StinkyBenji** [comment]
Hey, I am new to Joplin and currently exploring plugins codebase. 

https://github.com/laurent22/joplin/blob/35063ac05cfb3735caa193a4eb2760c42337c5da/packages/lib/services/plugins/PluginService.ts#L42-L48

I think the reason for automated enabling is due to the default plugin setting? does it make sense to you?

**Comment by StinkyBenji** [comment]
Hey there, I am new to Joplin and currently exploring plugins codebase.

https://github.com/laurent22/joplin/blob/35063ac05cfb3735caa193a4eb2760c42337c5da/packages/lib/services/plugins/PluginService.ts#L42-L48

I guess.. the reason for this issue is due to the default plugin setting?

https://github.com/laurent22/joplin/blob/35063ac05cfb3735caa193a4eb2760c42337c5da/packages/lib/services/plugins/PluginService.ts#L375-L384

Here is the update process,
I guess, if I understand it correctly, when the user initiates an update, the setting will turn to default again?

**Comment by StinkyBenji** [comment]
Heyy, I am new to Joplin and currently exploring codebase.
Can I ask if it's the first time that you observe this issue?

**Comment by StinkyBenji** [comment]
https://github.com/laurent22/joplin/blob/35063ac05cfb3735caa193a4eb2760c42337c5da/packages/lib/services/plugins/PluginService.ts#L286-L289

Not sure if this is a mistypo, should it be ``` return settings[pluginId].enabled == false; ``` ?

**Comment by tessus** [comment]
@StinkyBenji was I not clear in my second comment? I said _Let's wait what Laurent has to say. Maybe it's feature and not a bug. Who knows._

**Comment by roman-r-m** [comment]
Well, he labelled it "High" so presumably it is a bug?

**Comment by tessus** [comment]
Ok, didn't see the label.

**Comment by StinkyBenji** [comment]
:sweat_smile: :sweat_smile: :sweat_smile: sorry, I had the same presumption..

> Well, he labelled it "High" so presumably it is a bug?

**Comment by tessus** [comment]
No, my fault. I didn't see the label.

> Can I ask if it's the first time that you observe this issue?

No, it is not the first time. I've noticed this for a while now. I don't understand the question. Why is this relevant?

> hmm I guess? maybe add a check here?

I have to check the code. Look for what happens when you click update. Then change the code and test it. (You can create a local test plugin. The generator already creates a valid plugin.)

**Comment by StinkyBenji** [comment]
I am not sure if I can debug this from loading a local plugin. when I load local plugin, I can't see enable/delete button, only for development use.

> No, it is not the first time. I've noticed this for a while now. I don't understand the question. Why is this relevant?

emm, I am just curious. Because I haven't used Joplin before. I guess it only happens to already published plugins?? Plz correct me if I am wrong.

**Comment by roman-r-m** [comment]
If you cant find a way to test locally you can always publish a plugin yourself and use it for testing.

**Comment by Vedant1202** [comment]
Hello, 
I have a local plugin which is basically the boilerplate "Hello World" plugin. I made changes to it by added a few more `console.info` statements and ran `npm run update`. I, however, do not see any updations in its version which is 1.0.0

Please let me know if there's any other step that I might be missing.

![image](https://user-images.githubusercontent.com/35070972/111380558-85b9e380-86ca-11eb-9fd0-4d12a89e3b74.png)

**Comment by ron-debajyoti** [comment]
I tried to replicate the issue on my Ubuntu 18.04. Just like @Vedant1202, the plugin stays disabled on updating but the versioning remains the same.

**Comment by tessus** [comment]
@Vedant1202 @ron-debajyoti this does not show up when using local plugins, because you can't update local plugins via the UI.

**Comment by JackGruber** [comment]
@ron-debajyoti I think it should work if you install a plugin via jpl in an old version and then update it via GUI.

**Comment by Vedant1202** [comment]
@tessus @JackGruber thanks for the heads up. Do we have any published plugin that satifies the case? Or would we have to wait until an update is pushed?

**Comment by JackGruber** [comment]
Install for example the version 1.3.2 of the https://github.com/JackGruber/joplin-plugin-note-overview/releases plugin manuel. Than you can upgrade from the GUI.

**Comment by mablin7** [comment]
I fixed it, it was [this line](https://github.com/laurent22/joplin/blob/8de46ed462bba8bd934cedf602400adf565b4bb2/packages/app-desktop/gui/ConfigScreen/controls/plugins/useOnInstallHandler.ts#L41). I just had to set enabled on the newly created plugin settings. Before I submit a PR I wanted to ask for advice on testing this. Should I add a test case for this and if so how?

**Comment by mablin7** [comment]
Btw I discovered that a great way for testing plugin update related things, is to fork [joplin/plugins](https://github.com/joplin/plugins), bump the version of a plugin in manifests.json, then set [this line ](https://github.com/laurent22/joplin/blob/dadec484e9e8352c084e5131641da64d676c3900/packages/app-desktop/gui/ConfigScreen/controls/plugins/PluginsStates.tsx#L48) to point to your fork. Also make sure to disable cache in the devtools because github raw files are served with a 5 minute expiry.

**Comment by roman-r-m** [comment]
> Should I add a test case for this and if so how?

Are there any tests for this functionality at all?

**Comment by mablin7** [comment]
> > Should I add a test case for this and if so how?
> 
> Are there any tests for this functionality at all?

I can't find any tests for this module (`useOnInstallHandler.ts`). I'll submit the PR then.

**Comment by tessus** [comment]
Yea, UI stuff is hard to test. Sometimes we can test functions/methods that are used by the UI, but it makes not always sense
