### ISSUE TITLE
Uncaught Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed

### ISSUE THREAD

**Issue by aashrafh** [laurent22/joplin#4731]
## Environment

Joplin version: 1.7.11
Platform: Linux
OS specifics: Manjaro

## 

I'm trying to develop a basic ```Joplin Plugin``` which simply takes an image and generate the OCRed text using ```tesseractjs```

This is my code:

```
import joplin from 'api';
import { ToolbarButtonLocation } from 'api/types';

const { createWorker } = require("tesseract.js");
const worker = createWorker();

joplin.plugins.register({
	onStart: async function() {
		...

		await joplin.views.panels.onMessage(view, async (message) => {
			console.log('Plugin: Recieved Message: ', message);
                        await worker.load();
	                await worker.loadLanguage('eng');
	                await worker.initialize('eng');
			const { data: { text } } = await worker.recognize(message.hash);
			console.log('Plugin: Reconized Text: ', text);
		    await worker.terminate();
		});
		
		...
	},
});

```

I tried the code of tesseractjs in a separate script using **Node** and it works fine so it's not a tesseract issue but when I add the script to the plugin it throws the following error:

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/DHKRu.png

Any suggestions?

**Comment by roman-r-m** [comment]
Yep, tried that too.
You need to see what `createWorker` does: it forks a new node process passing it a certain script.
Now, you have 2 issues there:
1. That script is not bundled with your plugin - this you can solve by fiddling with webpack config (at least that's how I did it)
2. You need to provide the correct script to that fork method. However due to how Joplin executes plugin scripts this was not trivial, don't remember in details why exactly.

**Comment by roman-r-m** [comment]
However, this isn't really a bug in Joplin, at best it's an enhancement.

**Comment by laurent22** [comment]
Yes this is more of a support request.
