### ISSUE TITLE
Desktop: Disappearing text in markdown editor

### ISSUE THREAD

**Issue by roman-r-m** [laurent22/joplin#4750]
Joplin 1.7.11 and also on dev branch. Linux Mint, no plugins.

Not sure if the title is very good, the video below should explain it all.
On the 2d line I am typing "1.<enter>" and the line disappears.

![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/995612/112752217-cddddd80-8fc9-11eb-8dc5-fa1ad7114d8b.gif)

**Comment by lkiThakur** [comment]
### Steps to reproduce 
Open any note in markdown editor 
Type "1." or "-" or "*" (without quotes) in any new line and press enter.

So the bug is due to the ordered or unordered list feature as i guess ; I can try to fix it .

**Comment by aashrafh** [comment]
I think the issue is that they get translated into ```Bullet List```, ```Numbered List```, or ```Checkbox``` as follows:
* ```Number + Dot``` in an empty line = **Numbered List**
* ```"*", "-", or "+"``` in an empty line = **Bullet List**
* ```- [ ]``` in an empty line = **Checkbox**

I concluded this relation because of the default behavior of the previous actions. For example, if you started a new bullet list item but you don't want it you just need to press enter and the bullet mark will disappear which is good if you really wanted to delete that but annoying if you don't.

**Comment by roman-r-m** [comment]
Just found that if, instead of `enter`, I press `shift+enter` then Joplin does not delete the marker.
@CalebJohn what do you think, is it a bug or expected behaviour?

Btw, I was trying to write something like this (with 3 backticks, just not sure how to best escape them)
```
1.
``
code here
``
```

Oh and here's another oddity - if there are leading spaces each time I press enter the text shifts left some amount until it reaches the start of the line, on the next press it disappears as above

![ezgif com-gif-maker(3)](https://user-images.githubusercontent.com/995612/112767583-76faf700-900f-11eb-998a-74881cfba9e6.gif)

**Comment by CalebJohn** [comment]
@roman-r-m I suppose it's a bug related to expected behaviour. 

The code that causes this is meant to handle automatically inserted list elements. For example
```
1. This is the first item of a list
2. <This was inserted automatically, pressing enter should delete it>
```
If a list item is indented the code is supposed to de-dent to the previous indent level.
Of course, neither of these features should be applying in the case that you've shown for two reasons.
1. When the list element is not a part of another list, and was not automatically generated
2. Until there is a space following the `1.`, it's not actually a properly formatted list and shouldn't behave as one

Actually, while I was writing the above, I noticed that this input box on github has the same behaviour. The only difference is that Github waits for the space.

Too fix this issue I think we need to address the two issues listed above. Namely, if the previous line isn't a list element pressing <enter> should indent as normal. And if the list element is not properly formatted <enter> should also behave as normal.

**Comment by lkiThakur** [comment]
> we need to address the two issues listed above. Namely, if the previous line isn't a list element pressing should indent as normal. And if the list element is not properly formatted should also behave as normal.

I have now implemented these two points in my local repository; I will be soon opening a pull request after testing the newly implemented features for few hours.
