### ISSUE TITLE
Joplin opens window during most desktop changes

### ISSUE THREAD

**Issue by Presence-Eternal** [laurent22/joplin#4823]
## Environment

Joplin version: 1.711
Platform: Windows 
OS specifics: 10 Pro 64 20H2

## Steps to reproduce

Joplin when running in background will open its window if I change pretty much any aspect of my primary display. I most frequently encounter this when turning the display off for the night, but changing the scaling or resolution will also do this. No other applications appear to be doing this. Joplin otherwise behaves normally. It is of course a minor problem, but has been happening for months now. 

## Describe what you expected to happen

Joplin should only open window when requested.

**Comment by mu88** [comment]
I'm encountering a very similar issue: every time when starting my notebook after hibernate or sleep mode, Joplin opens, but is completely broken: either I don't see nothing but the window frame (see screenshot) or I can see all UI controls, but they are somehow broken: I can neither click any button nor write any text.

The same happens when returning to the desktop after playing a game in full screen mode.

I'm using the latest version of Joplin on Windows 10 Version 20H2, Build 19042.868
![2021-04-09_10h43_23](https://user-images.githubusercontent.com/4560672/114158821-6dce2c00-9925-11eb-98f2-faffd972c914.png)

**Comment by roman-r-m** [comment]
I think this is another manifestation of https://github.com/laurent22/joplin/issues/4517 (or the underlying issue mentioned there)

**Comment by happyTonakai** [comment]
Same issue. I have two monitors and whenever I turn off each of them, a freezing Joplin window pops up.
