### ISSUE TITLE
Using '^' character and a number directly after it jumps you back to the beginning of a note

### ISSUE THREAD

**Issue by szuecs-andras** [laurent22/joplin#4924]
## Environment
Joplin 1.8.3 (prod, win32)
Sync Version: 2
Profile Version: 35
Keychain Supported: Yes
Revision: 26a91416c

Joplin version: Joplin 1.8.3 (prod, win32)
Platform: Windows
OS specifics: Windows 10 20H2

## Steps to reproduce

1. write note
2. write "^1" (or other number)
3. cursor jumps back to beginning of note

## Describe what you expected to happen
write normally, wo/ jumping back to the beginning of the note

**Comment by JackGruber** [comment]
Hm I can't reproduce this.

- What plugins do you have active?
- In which editor? 
- Does this only occur with long notes?

**Comment by szuecs-andras** [comment]
1. I didn't install any plugins
2. I'm using markdown, not the normal editor
3. this occured with any note I made

**Comment by JackGruber** [comment]
Do you use a differen keyboard layout?

Do you have set shortcuts? 

1. Close Joplin
2. Rename `%userprofile%\.config\joplin-desktop\keymap-desktop.json` to somthing else 
3. STart joplin
4. Make your test again
5. Close Joplin
6. Delete the newly created `%userprofile%\.config\joplin-desktop\keymap-desktop.json`
7. Rename your keymap-desktop.jsonback

I can't find the issue right now, but someone described that when they switched from Indian to English UK keyboard layout, the letter was always inserted as text for shortcuts.

**Comment by tobiasdam** [comment]
I experienced the same behaviour, it occurred when
- the keyboard layout is set to a German layout
- the "Enable spell checking in Markdown editor? (WARNING BETA feature)" is `enabled`

It seems to happen when using a dead key with an "unsupported key". Pressing \` + 6 (backtick) triggers the cursor jump while \` + a (à) does not.

**Comment by tobiasdam** [comment]
When "Enable spell checking in Markdown editor? (WARNING BETA feature)" is `disabled`, most dead keys like ^ or ´ are working, but \` (backtick) + "unsupported key" still triggers this behaviour

**Comment by ithz4** [comment]
Hi everybody! 
I can confirm this weird behavior, too. I'm using Joplin for nearly two years, but as far as I know, this bug was not there from the beginning and came with updates. Just as I was about to create a ticket I saw that this one already exists.
Because I have to work with lots of inline-codes or code-blocks, it is very annoying that the cursor will jump to the very beginning of a note if you use the shortcut (`Shift` + `` ` ``) for code.
This happens if you hit (`Shift` + `` ` ``) two times:
![YsxfzmfKCW](https://user-images.githubusercontent.com/68545589/120817696-390bd900-c552-11eb-8061-2a0a1af7365a.gif)

![zro381nUXy](https://user-images.githubusercontent.com/68545589/120816032-ac145000-c550-11eb-96f0-4e7f33c8c95d.gif)

I'm using a german keyboard layout and can confirm the bug for the caret and backtick symbol (in combination with the shift key).
The spellchecker is enabled (en and de).

# Environment
Joplin version: Joplin 2.0.4 (prod, win32)
Platform: Windows
OS specifics: Windows 10

**Comment by szuecs-andras** [comment]
> Joplin 2.1.8 (prod, win32)
> 
> Client ID: 97348e3d52dd4268bbfa57b1059d853c
> Sync Version: 2
> Profile Version: 39
> Keychain Supported: Yes
> 
> Revision: 94ea177b7

It's still relevant on the latest version

**Comment by ithz4** [comment]
As a workaround, I actually unchecked the Option _Enable spell checking in Markdown editor? (WARNING BETA feature)_ and this behavior is no longer apparent. 
Since the error still occurs in the latest version (2.1.8), this is currently the only working solution for me, although I find the spell checker very useful.

**Comment by tobiasdam** [comment]
Some key combinations (e.g. \` + 6 (backtick) ) still trigger this behaviour, when the option `Enable spell checking in Markdown editor? (WARNING BETA feature` is _unchecked_.

**Comment by JackGruber** [comment]
Ok with `Enable spell checking in Markdown` I can reproduce this behavior for the `^` + a number.

**Comment by th-ros** [comment]
I had the same problem with cursor jumping to the beginning of a note while using a text expanding apllication like TyperTask or Beeftext (<https://beeftext.org/>).

If I check the option `Enable spell checking in Markdown editor? (WARNING BETA feature)` in the joplin config I cn reproduce the bug. For example I write the short word `:br` and normally this should replaced by `Best regards`. But joplin remove the last letter `r` from `:br` so only `:b` is there. Then the cursor jumps to the beginning of the note and the text `Best regards` will be typed.

If I uncheck the option `Enable spell checking in Markdown editor? (WARNING BETA feature)` both applications (TyperTask and Beeftext) will work fine.

Perhaps this will help to find the bug.

My joplin version 
```
Joplin 2.4.4 (prod, win32)
Client ID: b22eab1d4553499c946b0e892834e3a1
Sync Version: 3
Profile Version: 39
Keychain Supported: No
Revision: 8f68c32
```
