### ISSUE TITLE
Unable to choose programs to open attached files even though it is chosen in the system.

### ISSUE THREAD

**Issue by FernandoMarques-Santos** [laurent22/joplin#5078]
While opening an attached file, Joplin asks me to choose a program from a list. This occurs exactly three times for each extension. On the fourth time, Joplin seems to assume the correct program and opens directly. The same behaviour occurred while choosing for "toggle external editing".

While for "toggle external editing" you can choose which program to use in settings, for the attachments there is no location whatsoever where you can reset to another program *inside* Joplin. Of course, the logical conclusion is that Joplin is using the list of system preferred programs. But again, it is not (as you can reproduce below), hence a possible bug.

Joplin is now locked to using Xreader (for pdfs), when I wanted it to point to Evince (which is actually the default / preferred program on the system).

I tried with no success to have the choice once more (reinstalled Joplin, deleted folder joplin-desktop folder in .config files, rolled back using timeshift [excluding Home folder in my case]), and still Joplin opens directly. This points to a problem in Home folder, but **not** the .config/joplin-desktop

When I uninstall Xreader, Joplin just does not open the file.

## Environment

Joplin version: 1.8.5
Platform:
Linux Mint 20.1 x64
Kernel: 5.4.0-74-generic
DE: Cinnamon

## Steps to reproduce (I did on another computer - same problem)

1. Fresh Linux Mint 20.1 x86_64 Cinnamon install in English.
2. Install Joplin1.8.5 from the Software manager (tested from another source, same problem)
3. pick a .pdf and attach on a note (via drag and drop)
4. Choose "Document Viewer"
5. Open again and choose "Document Viewer" two more times.
6. The third time the program opens without a choice.
7. Close Joplin.
7. Install evince and/or okular via the software manager
8. Choose Evince as preferred (System Settings> Preferred Applications)
8. Restart the machine for good measure.
9. Open the attachment

The problem:

12. **It will open using Xreader**

This is of concern as someone may want to redefine defaults in the long run and will be locked with the same programs *forever*. Besides, sometimes may be important to choose another program to open to edit the attachment (like figures for example). Otherwise, the attachment feature becomes useless.

**Comment by CalebJohn** [comment]
The only officially supported way to install Joplin is [through the provided AppImage file](https://github.com/laurent22/joplin#desktop-applications).  The flatpack or snap packages (not sure which you're using) provide a layer of sandboxing that definitely has its uses, but can cause issues like the one you're having. 

Because these install methods are not supported, you'll need to contact the package maintainer for whichever package you've installed. Or you can install the official version which won't have this problem.

This issue has come up before, so you should definitely check out this forum link for more info.
https://discourse.joplinapp.org/t/problem-using-external-editor/17225/11

**Comment by FernandoMarques-Santos** [comment]
That worked indeed. Thank you!

**Comment by MrCarroll** [comment]
Looking into it a bit more, you can actually force the behaviour you want although the UX isn't amazing, change it around for MIME types/ app associations that are relevant to you. I always think Cinnamon might not be informing Flatpak properly when you change the default app, because the same behaviour on Gnome 3.36/Ubuntu 20.04 actually does force the popup again for me.

`flatpak permission-set --data "{'always-ask':<true>}" desktop-used-apps text/markdown net.cozic.joplin_desktop org.gnome.gedit 0 3`

It actually works for the snap too

`flatpak permission-set --data "{'always-ask':<true>}" desktop-used-apps text/markdown snap.joplin-desktop org.gnome.gedit 0 3`

Probably more for the benefit of future users at this point but I thought I'd put it here so it's somewhere in the issue tracker anyway.
