### ISSUE TITLE
synced note from android not displaying in joplin desktop

### ISSUE THREAD

**Issue by danielb2** [laurent22/joplin#5099]
## Environment

```
Joplin 2.0.11 (prod, darwin)
Client ID: c49067c17dd94e6dab4bf2f4a702df21
Sync Version: 2
Profile Version: 39
Keychain Supported: Yes
Revision: 981b1d8
```

Android:

2.0.2
Database v39

## Steps to reproduce

1. create note on android joplin
2. using filesystem option, wait for it to sync
3. after verifying note was synced on the desktop computer, sync on desktop

## Describe what you expected to happen

Expected to see note synced

## Actual

Note + metadata file are present on filesystem, but was not read into the desktop client

## Logfile

Note: I didn't see anything in the console output that gave anymore insight than the logfile.

[log.txt.tar.gz](https://github.com/laurent22/joplin/files/6678299/log.txt.tar.gz)

**Comment by danielb2** [comment]
Note to self: `4874bcc0a7554c0282cfd4f15facecf0`  note not being synched. This way I can perhaps provide more useful info later when someone has time to look at this and I've forgotten the note in question.

**Comment by danielb2** [comment]
actually it's looking like they're out of sync since I upgraded  desktop to version 2.x

**Comment by JackGruber** [comment]
Could you post the log from android and desktop. 

The desktop client does not see any new elements in the sync target. 
```
2021-06-18 09:30:23: "BasicDelta: Report: {"timestamp":1623962440402,"older":5357,"newer":0,"equal":1}"
2021-06-18 09:30:23: "Operations completed: "
2021-06-18 09:30:23: "fetchingTotal: -"
2021-06-18 09:30:23: "Total folders: 40"
2021-06-18 09:30:23: "Total notes: 1806"
2021-06-18 09:30:23: "Total resources: 1588"
```

Have you checked if your sync between devices is working? 
Is the time/date the same on both devices?

**Comment by danielb2** [comment]
Sync was working fine until update. Time is the same. I don't have to post the from android right now, but desktop is posted above.

Either way, I would think the desktop should sync the file and show something in the logs. I can share the files (meta and content) it should be synching.

**Comment by danielb2** [comment]
@JackGruber  I'm not sure how to get the logs for the android, but given that it's the desktop client that's not synching the note, are the logs for android relevant?

**Comment by danielb2** [comment]
I just tested it by creating a new note on the android device. The new note was synched without any problems, but the original note still has not synched.

**Comment by JackGruber** [comment]
Havae you checkt if the file `4874bcc0a7554c0282cfd4f15facecf0.md` is updated by resilio sync?

**Comment by danielb2** [comment]
> Havae you checkt if the file `4874bcc0a7554c0282cfd4f15facecf0.md` is updated by resilio sync?

It was never synched since it was created though. I modified the file, and now it was created on desktop. I guess now we'll not know why it wasn't synched in the first place.

**Comment by danielb2** [comment]
I'm going to close this now since I don't know if I can reproduce it and it's no longer an issue for that note

**Comment by danielb2** [comment]
I'm also noticing that image files from the past haven't been synced. They show up in the .resources folder, display fine in the joplin android app, but they didn't get synced to desktop

**Comment by jacquesh** [comment]
I occasionally get similar behaviour. I'm using the android & desktop clients with filesystem sync that I sync myself between devices using a separate program (namely [syncthing](https://syncthing.net)). I'm not sure how to reproduce it in my case because it only happens for some notes, not all. In all cases where I've seen this, I have verified that the actual file sync between devices has happened successfully (the exact same files exist on each device), it's just Joplin's sync with the filesystem that seems to not be detecting the new files. The system time on my two devices is the same (at least down to minute granularity).

I do see though, that on my android device, the notes that are missing from the app are also missing from `/storage/emulated/0/Android/data/net.cozic.joplin/sync_dir` (I assume this is just where files get written when they're saved or synced-in by the app?). If I export a sync report CSV from the desktop app, the missing notes are not visible there. I see the sync report from android includes a lot more info:
[syncReport-1628624983523.txt](https://github.com/laurent22/joplin/files/6964246/syncReport-1628624983523.txt)
The only thing in there that looks like an error to me is the "Could not refresh lock - cancelling sync".

**Comment by b-m-f** [comment]
I am experiencing the same issue.

The underlying Filesystem for the Sync is a Samba Share

**Comment by danielb2** [comment]
This is still happening. Just happened to me again
