### ISSUE TITLE
Sync issue between Joplin 2.1.7 and Joplin docker server 2.1.1

### ISSUE THREAD

**Issue by marcogiorgio** [laurent22/joplin#5150]
## Environment

Joplin version: 2.1.7
Platform: Windows
OS specifics: 

## Steps to reproduce

1. Update Joplin for Windows to version 2.1.7
2. Test sync
3. Got error 400 Not allowed PUT

After updating to Joplin 2.1.7 on Windows, I can't sync with the latest dockerized Joplin server (still 2.1.1).
This is the error I get from the log file:

Hi, I don't know if it's related or it is another issue, but after the update I get the error:

> Code: 400
Error: Not allowed: PUT 
    at newError (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\JoplinServerApi.js:191:28)
    at JoplinServerApi.<anonymous> (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\JoplinServerApi.js:215:31)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\JoplinServerApi.js:5:58)"

I have a dockerized Joplin server whose version is still 2.1.1 (docker tag: latest)

**Comment by Paulmicha** [comment]
I can confirm the same issue.
I've recorded a video to show the exact steps - here, under Windows 7 (but **I did exactly the same test under Arch Linux (Endeavour OS) today, with the same result**) :

Here's the first recorded occurrence of the bug :
https://files.paulmichalet.com/s/frYnfkHPNtqS6Qw

Here's the record of the log file attached below :
https://files.paulmichalet.com/s/Nao6mXDcfCDFGsg

Log file :
[error.log](https://github.com/laurent22/joplin/files/6755041/error.log)

Important note : under Debian-based Linux (Pop!_OS 20.04 LTS) with an already installed Joplin with contents, the same test **successfully synchronized** (although quite slowly...)

But, I hit another issue - perhaps related : impossible to share a folder (_error : No such folder_ - when it is in fact done synchronizing everything).

![error-no-such-folder](https://user-images.githubusercontent.com/1526964/124286618-882f3480-db25-11eb-8644-5fe0cdc23528.png)

**Comment by pghpete** [comment]
Sames issue using CentOS as the server and PopOS, Android, and Fedora as the clients.

**Comment by maxtruxa** [comment]
I had the same issue while using the Android app.
Upgrading the server to the [latest beta version](https://hub.docker.com/r/joplin/server/tags) (<code>joplin/server:2.1.6-beta</code>) fixed it for me. <code>joplin/server:latest</code> still points at <code>joplin/server:2.1.1</code> which apparently is incompatible with current client versions.

**Comment by alzxjm** [comment]
Same issue for me. macOS desktop client and `joplin/server:latest`. Error persists with client version 2.1.8.

**Comment by h-b** [comment]
I have the same issue. Since I am using Joplin a lot (usually via WebDAV), I'd like to go into more detail, maybe it helps. Today I installed the latest joplin/server:latest and connected it to my PostgreSQL server.

* I started with the Linux client (2.1.8) by switching from my WebDAV sync target to the Joplin server. It successfully synced everything, which took a couple of hours. From the docker log, most of that time was not syncing, but `2021-07-03 12:22:06: ShareService: Starting maintenance...` which was repeated every couple of minutes. Now, after a few edits, the client starts to say "Last error: Error: Not allowed: PUT".
* After the Linux client synced everything, I changed the sync target of my MacOS X client (2.1.8) to the Joplin server and clicked "Delete local data and re-download from sync target". It successfully started syncing, but stops after 100 fetched items and says "completed". It continues syncing 100 items when I click on sync or the automatic sync every 5 minutes starts syncing. This will take a lot of time, since I have thousands of items.
* I removed the Android app from my mobile, reinstalled it and configured my Joplin server. From the very beginning, the client keeps telling "Error: Not allowed: PUT", although the sync check is successful. Nothing at all is synced.

While all this happens, the docker server output says repeatedly:

```
2021-07-03 15:15:56: App: PUT /api/batch_items (1ms)
2021-07-03 15:15:56: [error] App: 400: PUT /api/batch_items : Not allowed: PUT 
```

The reason I am trying the Joplin server is because of WebDAV issues since the last update of the Synology WebDAV server. Also here "PUT" errors occur, but with a different text saying "Error: PUT....... 403 Forbidden.....". I worked around via Joplin file system sync and unison sync with a mounted WebDAV share - which is not possible on mobile device of course.

Since neither WebDAV nor Joplin server work after I used Joplin extensively for years, I am kind of stuck now. My last hope is to fallback to OneDrive or Dropbox to get a running system again, until this issue is fixed. I should mention that I use encryption, maybe this only happens with encryption.

**Comment by maxtruxa** [comment]
I can only repeat myself. `latest` is currently still equal to `2.1.1`. You will need to specify the image version explicitly (e.g. `joplin/server:2.1.6-beta`). Looking at [the changelog](https://github.com/laurent22/joplin/blob/dev/readme/changelog_server.md), I'd say you need at least `joplin/server:2.1.3-beta`:
> New: Add support for uploading multiple items in one request (3b9c02e)

**Comment by banigithub-2** [comment]
Yes, I upgraded a number of devices syncing with Joplin Server 2.1.1.  I see all the Server versions are beta since then, so I'm weighing up the relative risk of upgrading to server 2.2.6 (beta) vs trying to downgrade everything and re-download notes.
Anyone have any opinions?  I don't have a feel for how soon 2.2.x will have a non-beta release.
I'm totally loving the Joplin Server with 2.1GB data and clients across lots of OS's, in case anyone was in doubt about how awesome I think this project is.

**Comment by marcogiorgio** [comment]
> Yes, I upgraded a number of devices syncing with Joplin Server 2.1.1. I see all the Server versions are beta since then, so I'm weighing up the relative risk of upgrading to server 2.2.6 (beta) vs trying to downgrade everything and re-download notes.
> Anyone have any opinions? I don't have a feel for how soon 2.2.x will have a non-beta release.
> I'm totally loving the Joplin Server with 2.1GB data and clients across lots of OS's, in case anyone was in doubt about how awesome I think this project is.

I personally downgraded the Windows client and I am sticking with that version until a non-beta server version comes up

**Comment by banigithub-2** [comment]
Thanks Marco.

**Comment by merdely** [comment]
> I personally downgraded the Windows client and I am sticking with that version until a non-beta server version comes up

What version of the client did you downgrade to?  And it works with Joplin Server 2.1.1?

**Comment by marcogiorgio** [comment]
2.0.11

**Comment by marcogiorgio** [comment]
> downgrade

2.0.11

**Comment by marcogiorgio** [comment]
> > I personally downgraded the Windows client and I am sticking with that version until a non-beta server version comes up
> 
> What version of the client did you downgrade to? And it works with Joplin Server 2.1.1?

2.0.11

**Comment by merdely** [comment]
I did some testing.  The AUR (Arch User Repository) package for 2.1.7 got the error.  But I downloaded the AppImage from Github and it doesn't have the error.  So I'm happily using that right now.

**Comment by banigithub-2** [comment]
I’ve downloaded my clients to 2.0.11, which does the trick for clients you _can_ downgrade.
I’ve got a problem with IOS (iPad) - you can’t it seems get hold of earlier versions of the Joplin IOS app to downgrade to.  I would be great if you could turn off the incompatible features on the client.

**Comment by mbacalan** [comment]
Having the same issue here, using Joplin Server 2.1.1 via Docker. Downgrading Windows client to 2.0.11 works but can't do the same for Android client so can't sync on mobile.

**Comment by marcogiorgio** [comment]
> Having the same issue here, using Joplin Server 2.1.1 via Docker. Downgrading Windows client to 2.0.11 works but can't do the same for Android client so can't sync on mobile.

I have the latest Android version available from the Play Store and the app syncs correctly with Joplin Server 2.1.1

**Comment by mbacalan** [comment]
> I have the latest Android version available from the Play Store and the app syncs correctly with Joplin Server 2.1.1

I'm using Joplin 2.1.4 on Android 9 and Joplin Server 2.1.1 via Docker and reverse proxied via NGINX.

I can sync on Windows desktop after downgrading like I mentioned but Android gives PUT errors for `api/batch_items` endpoint and doesn't sync.

Tried a previous v2 release for Android via APKMirror too and result is the same.

**Comment by Joshndroid** [comment]
Fresh setup... Linux desktop app and android app from play store. Get this exact issue on both devices. sigh. can we get the latest tag container updated?

**Comment by marcogiorgio** [comment]
The Docker image has been updated. The version is: 2.2.10. The issue should be solved. I'll close the ticket as soon as I can test it

**Comment by mbacalan** [comment]
> 
> 
> The Docker image has been updated. The version is: 2.2.10. The issue should be solved. I'll close the ticket as soon as I can test it

I tested and can confirm that syncing is working on both Windows and Android. Thanks for the update!

**Comment by Joshndroid** [comment]
> The Docker image has been updated. The version is: 2.2.10. The issue should be solved. I'll close the ticket as soon as I can test it 

Thank you for the update
