### ISSUE TITLE
Could not connect to puglin repository in Windows version

### ISSUE THREAD

**Issue by LeoMontealegre** [laurent22/joplin#5161]
## Environment

Joplin version: 2.1.8
Platform: Windows
OS specifics: Windows 10 Entreprise (v 20H2)

## Steps to reproduce

1.  Clic on Tools tab.
2. Clic on Options. 
3. Clic on Plugings.
4. I have the message even if I haven't searched for a pluglin.

## Describe what you expected to happen

I expect to have the chance to search for a piglin and then be able to install.

## Logfile

![Snag_6b3bb1c](https://user-images.githubusercontent.com/81310893/124657587-b176fa00-de70-11eb-9208-bac5a02db368.png)
[LogFileSectionWhenErrorFlags.txt](https://github.com/laurent22/joplin/files/6772446/LogFileSectionWhenErrorFlags.txt)

**Comment by LeoMontealegre** [comment]
I tryed to open Joplin as ADMIN, i got the same issue !

**Comment by laurent22** [comment]
Something's blocking the request.

**Comment by LeoMontealegre** [comment]
Is there something I can do from my side ?

Thanks,

Leo

De : Laurent ***@***.***>
Envoyé : 6 juillet 2021 16:07
À : laurent22/joplin ***@***.***>
Cc : Montealegre Lobo, Leonardo ***@***.***>; Author ***@***.***>
Objet : Re: [laurent22/joplin] Could not connect to puglin repository in Windows version (#5161)


Courriel provenant de l'externe
ATTENTION, avant d'accéder à une pièce jointe ou à un lien de ce courriel, assurez-vous que celui-ci provient d'un tiers de confiance.

Something's blocking the request.

-

**Comment by JackGruber** [comment]
You can check why you cannot access the following page
```
https://raw.githubusercontent.com/joplin/plugins/master/manifests.json
```

**Comment by LeoMontealegre** [comment]
I can access the page using the same PC where my Joplin is running
![Snag_af05735](https://user-images.githubusercontent.com/81310893/124786988-2bad8a00-df16-11eb-826b-cf02ae3c78a0.png)

**Comment by wanghongtaocn** [comment]
The same problem.

**Comment by MGshizi** [comment]
I have met the same problem, too.

**Comment by laurent22** [comment]
If you run `curl https://raw.githubusercontent.com/joplin/plugins/master/manifests.json` from the terminal, does it work?

I assume we need to add a bunch of headers to trick the GFW but it's hard to tell which ones without being behind it.

**Comment by wanghongtaocn** [comment]
> If you run `curl https://raw.githubusercontent.com/joplin/plugins/master/manifests.json` from the terminal, does it work?
> 
> I assume we need to add a bunch of headers to trick the GFW but it's hard to tell which ones without being behind it.

Curl works from terminal.

**Comment by laurent22** [comment]
Now that we have the download link in the repo readme we can set least link to that when the manifest fetch fails

**Comment by amazinghaha** [comment]
when this issue happened，the PC's hosts need to add  ' 199.232.96.133    raw.githubusercontent.com '
you can ping url' raw.githubusercontent.com' in shell, it  shows ip = 0.0.0.0 
![image](https://user-images.githubusercontent.com/77572673/129476229-5ad82703-441d-431b-a94e-a812fc544e47.png)

**Comment by laurent22** [comment]
I can't fix this issue unfortunately because I can't replicate it.

Ideally if someone in China maybe could try various configurations, for example by adding browser http headers to the requests, that might help find out the issue. In the meantime I've added a link to the browse the plugins online when such an error occurs.

**Comment by wanghongtaocn** [comment]
Joplin 2.3.5 can connect to plugin repository. The problem seems to be
solved.

Best Regards,
Hongtao Wang


Laurent ***@***.***> 于2021年8月28日周六 下午10:48写道：

**Comment by JaimeZeng** [comment]
met the same problem.

```bash
Joplin 2.3.5 (prod, linux)
```

**Comment by JaimeZeng** [comment]
I found a solution that works for me.

Specify the proxy in joplin configuration file `/usr/share/applications/joplin.desktop`. e.g.

```bash
# Exec=/usr/bin/joplin-desktop
Exec=env http_proxy=http://127.0.0.1:7890 https_proxy=http://127.0.0.1:7890 /usr/bin/joplin-desktop
```

Or edit hosts file with this [repo](https://github.com/ineo6/hosts). Use this method, the download speed is very slow.

```bash
185.199.108.133  camo.githubusercontent.com
```

**Comment by JaimeZeng** [comment]
> I can't fix this issue unfortunately because I can't replicate it.
> 
> Ideally if someone in China maybe could try various configurations, for example by adding browser http headers to the requests, that might help find out the issue. In the meantime I've added a link to the browse the plugins online when such an error occurs.

Due to github.com is not stable for some contries, e.g. China. we could not connect to github repository. So we always change it to mirror site (hub.fastgit.org, ghproxy.com) instead of direct site. 

e.g. The following page 

```markdown
[https://raw.githubusercontent.com/joplin/plugins/master/manifests.json](https://raw.githubusercontent.com/joplin/plugins/master/manifests.json)
```

mirror site page

```markdown
[https://raw.fastgit.org/joplin/plugins/master/manifests.json](https://raw.fastgit.org/joplin/plugins/master/manifests.json)
[https://cdn.jsdelivr.net/gh/joplin/plugins@master/manifests.json](https://cdn.jsdelivr.net/gh/joplin/plugins@master/manifests.json)
[https://cdn.staticaly.com/gh/joplin/plugins/master/manifests.json](https://cdn.staticaly.com/gh/joplin/plugins/master/manifests.json)
[https://ghproxy.com/https://raw.githubusercontent.com/joplin/plugins/master/manifests.json](https://ghproxy.com/https://raw.githubusercontent.com/joplin/plugins/master/manifests.json)
```

Its a solution that works for China users. Chinese can use a mirror site, others use direct site to access the manifest page.

**Comment by laurent22** [comment]
That's brilliant I didn't know about these mirrors in China, thanks for the info @JaimeZeng. So I think what we can do is first try the regular GitHub request and, if it fails, try one of the mirrors.

How about the [release page](https://github.com/laurent22/joplin/releases), is it generally working in China? Because that's from that we fetch new version when updating.

**Comment by JaimeZeng** [comment]
> That's brilliant I didn't know about these mirrors in China, thanks for the info @JaimeZeng. So I think what we can do is first try the regular GitHub request and, if it fails, try one of the mirrors.
> 
> How about the [release page](https://github.com/laurent22/joplin/releases), is it generally working in China? Because that's from that we fetch new version when updating.

The github-release page did not work in China.

More generally, none of these sources are accessible without proxy client from China, including the following sites.

```bash
github.githubassets.com
central.github.com
desktop.githubusercontent.com
assets-cdn.github.com
camo.githubusercontent.com
github.map.fastly.net
github.global.ssl.fastly.net
gist.github.com
github.io
github.com
api.github.com
raw.githubusercontent.com
user-images.githubusercontent.com
favicons.githubusercontent.com
avatars5.githubusercontent.com
avatars4.githubusercontent.com
avatars3.githubusercontent.com
avatars2.githubusercontent.com
avatars1.githubusercontent.com
avatars0.githubusercontent.com
avatars.githubusercontent.com
codeload.github.com
github-cloud.s3.amazonaws.com
github-com.s3.amazonaws.com
github-production-release-asset-2e65be.s3.amazonaws.com
github-production-user-asset-6210df.s3.amazonaws.com
github-production-repository-file-5c1aeb.s3.amazonaws.com
githubstatus.com
github.community
media.githubusercontent.com
```

**Comment by JaimeZeng** [comment]
GitHub mirrors can be found here.

https://github.com/XIU2/UserScript/blob/master/GithubEnhanced-High-Speed-Download.user.js#L45-L69

**Comment by laurent22** [comment]
Hi everyone, the latest release includes a fix for the Plugin repository access in China:

https://github.com/laurent22/joplin/releases/tag/v2.4.8

Basically if it cannot connects to GitHub it uses one of the mirrors suggested by @JaimeZeng. Please give it a try if you can and let me know if it's any better.

A few notes:

- When it's using a mirror, it should display so below the search bar with a message "Content provided by xxxx"
- Also when using a mirror, no plugin is marked as recommended. This is because we don't control the repository so cannot know if the plugins are the same or have been altered (they probably haven't but we can't be 100% sure).

**Comment by rxliuli** [comment]
For users with proxies, I recommend Proxifier, which can proxy network requests from all applications on the computer, even if the application itself does not support proxies

![image](https://user-images.githubusercontent.com/24560368/134444214-7619b132-d844-4354-bf34-d0372df87981.png)

**Comment by imaxwen** [comment]
version 2.6.10 still has this issue, and some of the mirrors does not work any more.
Maybe the solution of this issue is to access the `https://raw.githubusercontent.com/joplin/plugins/master/manifests.json` behind a system proxy. `HTTP_PROXY` or `HTTPS_PROXY` of system env

**Comment by leenzhu** [comment]
Joplin 2.13.2 in Windows still has problem to connect plugin repository in China.

```js
	const mirrorUrls = [
		defaultContentUrl, /* https://raw.githubusercontent.com/joplin/plugins/master */
		'https://cdn.staticaly.com/gh/joplin/plugins/master',
		'https://ghproxy.com/https://raw.githubusercontent.com/joplin/plugins/master',
		'https://cdn.jsdelivr.net/gh/joplin/plugins@master',
		'https://raw.fastgit.org/joplin/plugins/master',
	];
```

Since Joplin first tries to connect the defaultContentUrl(https://raw.githubusercontent.com/joplin/plugins/master/.gitignore), which hangs for a long time in China at most time.

And then sometimes the GFW of China allows Joplin to access 
`https://raw.githubusercontent.com/joplin/plugins/master/.gitignore`, but it will block `https://raw.githubusercontent.com/joplin/plugins/master/manifests.json`, event GFW allows Joplin to access `manifests.json`, it seems always blocking the plugin downloads.

I mean that it still doesn't work as expect by taking the `defaultContentUrl` as the first mirror in China.

I'm expecting that Joplin could provide a mirror setting and let user adjust the priority of the mirror urls. Since the second builtin mirror `https://cdn.staticaly.com/gh/joplin/plugins/master` has been broken, it would be better if user could cusomize the mirrors.

Thank you!

**Comment by kamasylvia** [comment]
Same problem on Joplin 3.2.13 (prod. win32). But it works fine on my Mac Mini. Both PC and Mac have already actived proxy. I guess Joplin connect the plugin repo without proxy, because other application on my Windows PC can access the blocked websites with proxy, only Joplin can't.

**Comment by necrevistonnezr** [comment]
Same Problem with Joplin 3.5.11 on macOS 26.2.
```
Joplin 3.5.11 (prod, darwin)
Gerät: darwin, Apple M2
Client-ID: f3d59262fb6143ef9b3444fb72affb8c
Sync-Version: 3
Profil-Version: 49
Unterstützter Schlüsselbund: Ja
Alternative Instanz ID: -
Revision: e75875c
Backup: 1.5.1
macOS theme: 1.5.20
```

If I run
`curl https://raw.githubusercontent.com/joplin/plugins/master/manifests.json`

I get
```
<html>
<head><title>302 Moved Temporarily</title></head>
<body>
<center><h1>302 Moved Temporarily</h1></center>
<hr><center>Umbrella Cloud Security Gateway</center>
</body>
</html>
```
