### ISSUE TITLE
Joplin crashes on Kubuntu 21.04 when insalled via snap

### ISSUE THREAD

**Issue by rajmondburgaj** [laurent22/joplin#5183]
Everytime I open Joplin and right click on any node in the leftside bar the app freezes and then crashes,

![image](https://user-images.githubusercontent.com/7545874/125347534-51de8a00-e35b-11eb-9ad9-777ca478eb84.png)

Joplin 2.1.8 (prod, linux)

Client ID: 11daacbf5e3c4affb86e77b89bc3c9a1
Sync Version: 2
Profile Version: 39
Keychain Supported: No

Revision: 94ea177

**Comment by MrCarroll** [comment]
The snap isn't an official distibution, but I wouldn't expect the issue you're having presuming 2.2.7 worked fine, there was few changes between 2.2.7 and 2.2.8.

Would you be able to confirm whether this happens when running in safemode, and with the AppImage releases at all? Otherwise you can run `sudo snap revert joplin-desktop` to revert back to 2.2.7 if you still have a version cached locally. This does reset all your notes, settings and plugins to the same state they were in when the upgrade takes place however, so you'd need to consider whether they're already synced elsewhere and considering making an export/backup if not.

If it does appear to be a snap specific bug feel free to open up an issue here https://github.com/MrCarroll/joplin-desktop-snap

**Comment by rajmondburgaj** [comment]
Hi @MrCarroll , I just installed the snap version and I dont know if this worked in the previous version or not. But I will try and use the official way of installing the app.

Thanks
