### ISSUE TITLE
onNoteChange Event is only emitted for the current note

### ISSUE THREAD

**Issue by BeatLink** [laurent22/joplin#5197]
In the joplin plugin API, the onNoteChange event is only emitted for the currently selected note, not for any other note. This artificially limits the capabilities of plugins implementing handlers for this event, as this means plugins either only respond to the currently selected note or must turn to polling and other means of checking for note changes which is an inefficient use of CPU. 

The offending line in the API can be found here: https://github.com/laurent22/joplin/blob/dev/packages/lib/services/plugins/api/JoplinWorkspace.ts#L84

## Environment

Joplin version: Current Dev Branch: 5214da0a4475fb84bf1f11b419f5f7f35592c43a
Platform: All
OS specifics: Applicable to all OS platforms using the API

## Steps to reproduce

1. Register a plugin
2. Add the following to the main plugin function `joplin.workspace.onNoteChange((event) => console.log('note changed', event))`
3. Compile the plugin and run it using joplin dev mode
4. Make changes to various notes
5. Note that the console log message is only sent when the note being changed is currently selected

## Describe what you expected to happen

The onNoteChanged event should be emitted for all changed notes, not just the currently selected one. If a plugin developer wishes to listen to only changes on the selected note, it is trivial to compare the note id in the event handler to the results from the selectedNoteIds, or selectedNote API methods

**Comment by laurent22** [comment]
Why do you need this for?

**Comment by laurent22** [comment]
Based on your code you don't really need to process events in real time, and I'm sure it would cause issues especially when synchronising or importing notes, which could generate thousands of events that your code will have to handle. There's a reason why it's implemented as it is now. And even with real time events, you'd still need to handle the case where the plugin is disabled, then re-enabled - in that case you would have missed events and would need re-process everything.

What you probably need is something like a /events API end point, which would return the events you need since a particular point in time. You would then poll this every x minutes to update your data. The data for this is there but it's just not exposed at the moment.

**Comment by laurent22** [comment]
For now I've created a spec for it: https://github.com/laurent22/joplin/issues/5199

**Comment by BeatLink** [comment]
> What do you need this for?

https://discourse.joplinapp.org/t/plugin-repeating-to-dos/16470/13

**Comment by BeatLink** [comment]
Until said API is implemented I will have to code the plugin to poll all tasks for any recent changes via a loop as there is no alternative

**Comment by laurent22** [comment]
That might work. You might want to check /search too, and retrieve only the non-completed tasks.

**Comment by BeatLink** [comment]
BUMP: The issue is still active and awaiting the resolution of #5199

**Comment by laurent22** [comment]
Closing in favour of #5199
