### ISSUE TITLE
Chinese article cannot display space

### ISSUE THREAD

**Issue by newyorkthink** [laurent22/joplin#5254]

**Comment by laurent22** [comment]
How do you add these two spaces on GitHub for example? Is it working there?

**Comment by newyorkthink** [comment]
@laurent22 
I give you example.
![2021-07-31_17-52](https://user-images.githubusercontent.com/87791643/127736130-114e8a4e-7f59-4d2f-97dc-ddb1dafa3eca.png)

I add these two spaces in Joplin software,but i export this article to pdf. 
and i open this pdf, the two space can't display, it is not working.

**Comment by newyorkthink** [comment]
now i use markdown “&emsp;&emsp;” insert article.
it look not easy.
every paragraph add “&emsp;&emsp;”.
![2021-07-31_17-58](https://user-images.githubusercontent.com/87791643/127736373-e77159e1-2cfe-424b-9a8f-e4cd4323ccb3.png)

**Comment by laurent22** [comment]
I don't think what you want to do is possible because it's not part of the Markdown spec. So if you want this to be changed, you'd have to bring up the issue to the CommonMark repository.

Another way maybe would be to use custom CSS. For this, I'd suggest asking on the forum as some users might be able to help you.
