### ISSUE TITLE
White splashes during webview initialization

### ISSUE THREAD

**Issue by pshirshov** [laurent22/joplin#5311]
Even when the app uses dark themes it shows white splashes during startup, while switching between notes and while switching between MD and RTE modes.

This is a very old problem which was (and still is) haunting Firefox, Chrome and many Electron apps.

Could you fix that in Joplin please? 

The fix seems to be more or less simple: https://www.christianengvall.se/electron-white-screen-app-startup/

https://user-images.githubusercontent.com/295225/129454981-6e90603d-f32d-4eb0-9e05-ae4a606a822a.mov

**Comment by CalebJohn** [comment]
This does indeed seem easy to change, and I couldn't help myself so I went ahead and implemented it in [a branch](https://github.com/CalebJohn/joplin/commit/4c5e44f88222b4605f2e648b86f3a21545ad602c). It works as advertised, but since Joplin takes ~3s to load on my computer, it's kind of painful to wait that long with no indication that the app is starting. 
Maybe some others can weigh in, but I think to do this right, we'd need some sort of a loading screen popup.

**Comment by CalebJohn** [comment]
My very unscientific test was to launch Joplin on my desktop (v2.2.7) and to measure the time it took for any indication that the app had launched, and then how long it took to paint. 
Basically it too 3.5s to open any window, and an additional 2.3s to actually draw content in the window. 

So my personal preference would be to implement this change. Because there's already a perceptible delay to launching, so why not increase it a bit.

**Comment by pshirshov** [comment]
Startup splash is just a half of the problem though. Splashes on switching are even more annoying.

**Comment by elsiehupp** [comment]
> since Joplin takes ~3s to load on my computer, it's kind of painful to wait that long with no indication that the app is starting.

I haven't built your branch, but on macOS an application should bounce in the dock while it is loading. I'm guessing Windows and Linux do not have a corresponding behavior?

In [the linked fix](https://www.christianengvall.se/electron-white-screen-app-startup/), there are two options, and you did the `ready-to-show` one. If, instead, the fix where to change the background color, it would make sense to inherit from the highest-level `div` with a defined `background-color` CSS attribute. On my computer, with the default dark theme, this `div` (which does not have a name) has a `background-color` of `rgb(29, 32, 36)`:

<img width="241" alt="div attributes" src="https://user-images.githubusercontent.com/9206310/131609721-5b6c7095-cdfc-4e3d-b1c0-dbf3b1d71fbf.png">

If you wanted to show a loading placehold rather than just a blank screen, a simple place to start could be just showing the application icon in the middle of the window, presuming this could be relatively simple to add. Beyond that, idk, below the application icon you could have an OS-specific loading indicator, such as the macOS loading spinner, which [someone has apparently implemented in pure CSS](https://codepen.io/jmak/details/LsCet). There are also various NPM packages that implement loading spinners specifically in React—[[1](https://www.npmjs.com/package/react-spinners)][[2](https://www.npmjs.com/package/react-loader-spinner)][[3](https://react-bootstrap.github.io/components/spinners/)]—with style options that are varying degrees of annoying, lol. Pure CSS is probably simpler to implement, though.

Obviously the best thing would be someone with a strong love for Joplin's specific branding to create a custom loading animation based on the icon/logo itself, but that's well beyond me.

**Comment by pshirshov** [comment]
Here is another electron app which fixed startup splash: https://github.com/UltimateHackingKeyboard/agent/pull/1582

The main problem is UI splashes during mode switch though.

**Comment by elsiehupp** [comment]
The issue is still present.

**Comment by CalebJohn** [comment]
Not stale

**Comment by elmodor** [comment]
I still have the issue that joplin has a white splash during startup in 2.6.10 on windows.

**Comment by pshirshov** [comment]
Still happening in 2.5.12
