### ISSUE TITLE
Synchronisation error since Joplin update on iPhone this morning

### ISSUE THREAD

**Issue by Steuma** [laurent22/joplin#532]
### Operating system

- iOS

### Application

- Mobile

Since the Joplin update this morning (probably to 10.0.22?) my iPhone behaves strange
when synchronising. It does not complete the sync but hangs every time I try to sync
and goes into background after some time (~60 seconds), after having
completed 6 from 36 loaded objects. It also hangs every now and then when I am in
config now. Here are my snapshots with error messages from my iphone.

=> Not useful screenshots of log deleted

Synchronisation with my iphone worked ok before the update and from Windows it still
seems to work ok now.

Cheers, Steuma

**Comment by laurent22** [comment]
What sync target are you using? Is that Dropbox?

**Comment by Steuma** [comment]
Yes that is sync with Dropbox.

**Comment by Steuma** [comment]
Close was a mistake :-(.

**Comment by laurent22** [comment]
Unfortunately the error message is not clear enough to fix the bug. As a first step, the next release will have clearer error messages so that we know what the issue is.

**Comment by laurent22** [comment]
Could you try with the latest version (10.0.24)? I think the error will still happen but it should be possible to see what it is, which will help fixing it.

**Comment by Steuma** [comment]
Hi Laurent,
just today I got the update to the new version. This is the new log from the unsuccessful sync ...

![1](https://user-images.githubusercontent.com/38250883/40474026-2f1a3b4e-5f3e-11e8-8733-822ad9890447.JPG)
![2](https://user-images.githubusercontent.com/38250883/40474033-3263ee6c-5f3e-11e8-94f7-b46245bfe005.JPG)
![3](https://user-images.githubusercontent.com/38250883/40474036-3503fc02-5f3e-11e8-9793-4507359e28dc.JPG)
![4](https://user-images.githubusercontent.com/38250883/40474041-37340ab2-5f3e-11e8-9f54-1fb8b15c2451.JPG)
![5](https://user-images.githubusercontent.com/38250883/40474047-393f7f58-5f3e-11e8-8812-33b441c32b2e.JPG)
![6](https://user-images.githubusercontent.com/38250883/40474050-3bbf0a28-5f3e-11e8-9837-05a513ee0d6d.JPG)
![7](https://user-images.githubusercontent.com/38250883/40474053-3f72ad6e-5f3e-11e8-96e6-ace7d4ded62d.JPG)

**Comment by laurent22** [comment]
Hi, the date on the log above is 18 May but the app was released after that. Have there been any new error since 23-24 May?

**Comment by Steuma** [comment]
Oops sorry, I did not realize this - it seems that only the old data is visible when I click on 'errors only'
on the protocols page. There is newer data visible, when I look at all data.
![1](https://user-images.githubusercontent.com/38250883/40584052-bf7de858-619a-11e8-814b-f0bb18d9573d.JPG)
![2](https://user-images.githubusercontent.com/38250883/40584054-c23e3ba6-619a-11e8-988d-467e33fdf36e.JPG)
![3](https://user-images.githubusercontent.com/38250883/40584055-c45a2a80-619a-11e8-80cf-282a030a78d5.JPG)
![4](https://user-images.githubusercontent.com/38250883/40584056-c6f898f8-619a-11e8-86e0-d888165d82eb.JPG)
![5](https://user-images.githubusercontent.com/38250883/40584057-c8a5baaa-619a-11e8-96f6-03bb841d7aa7.JPG)
![6](https://user-images.githubusercontent.com/38250883/40584058-ca87f680-619a-11e8-9324-966165d90506.JPG)

I hope that helps better in diagnosing ;-). It still does not complete any Sync with Dropbox and
I have to cancel the sync early in order for Joplin to not lock up so I am able to look at the protocol
page. If stay on sync Joplin goes into background after a while.

Thanks, Steuma

**Comment by Steuma** [comment]
Yes, I still do have the same issue with Syncing my iPad, as well as my iPhone.
Now that I am back from vacation :-) I had a little spare time to test something.
I even see the 'not syncing' issue with a complete empty database now.
Here is what I did:
**Desktop (Windows):** 
close Joplin
remove ~/.config
start Joplin, which creates an empty database
configured language German
configured Webdav as network sync option (I tested before that Webdav or Dropbox makes no difference)
configured 'Encryption options' with password
-> synced to network
**iPhone:**
removed Joplin program from iPhone
installed Joplin newly (this gives me a clean new database)
configured language German
configured Webdav as network sync option
configured 'Encryption options' with password
-> synced with Network
**Result:**
Created local items: 1
Fetched items: 4/8
State in Progress.
... after this the phone waits for ~60 seconds and then Joplin vanishes into background
this is the same messages I do see every other time I try to sync now.
After the first sync I did have a couple of more password requests on the Encryption
page though in Desktop as well as on the iPhone. I filled in the password into each of
them, but nothing did change because of doing this.

If my explanation does not help to fix the issue aready, I will install the new version as
soon as I receive it and send you the error messages here again.

Cheers, Steuma

**Comment by Steuma** [comment]
Hi Laurent,
is there any news to this issue? I did not see any new IOS version of Joplin until now.
This issue is very frustrating for me as the most important feature or me was security
and the sync between Windows and IOS to have access to information from
both sides. Just as a reminder, this was working perfectly before I upgraded Joplin on
IOS on May 18. Would it be possible for me to get back to the version before the
recent one? 
Apart from this it should be real easy to follow the steps to reproduce the issue the
way I explained in my post above with an empty database. Am I really the only user
that has this problem and if so what could be the difference between me and others
that do not see the sync issue?

Thanks in advance, Steuma

**Comment by laurent22** [comment]
I've tried what you described above but it works for me. Regarding this:

> ... after this the phone waits for ~60 seconds and then Joplin vanishes into background
this is the same messages I do see every other time I try to sync now.

Do you have any particularly large resource on the sync target? I know it will crash with resources bigger than 10 MB but possibly also smaller.

**Comment by christophberger** [comment]
Yesterday I tried Joplin for macOS and for iOS, and I ran into the very same problem. My notes are encrypted, and I have imported 1000+ notes from Evernote, all of which seem to have synchronized fine to my webDAV server. 

On the iPhone (a 6 Plus with latest iOS), synchronization gets stuck reproducibly at the same point at each attempt. When I delete and reinstall Joplin on the iPhone, synchronization gets stuck at a different point, but then also reproducibly at that point again on every retry.

Status right before the iOS app pops into the background and stops synching:

![img_20180722_222344_5979](https://user-images.githubusercontent.com/3835890/43057668-e62bbb08-8e43-11e8-8c7b-cf3cc29d8de4.PNG)

The sync does not always fail at the first local item; previous attempts (before reinstalling) were able to create a large number of local items.
 
Log output:

![img_20180723_001240_5980](https://user-images.githubusercontent.com/3835890/43057749-47d6f674-8e44-11e8-9a4a-9feec816bf08.PNG)

The largest file on the webDAV server has 467.9 KB. All files on the server are markdown files, possibly because I only imported notes from Evernote, and this seems to only include links to the original locations of images and attachments, rather than the files themselves.

Console output:

[JoplinSyncFail.txt](https://github.com/laurent22/joplin/files/2218010/JoplinSyncFail.txt)

**Comment by laurent22** [comment]
It seems the issue is that on iOS the app can somehow runs out of memory, so indeed when it happens it will always happen at the same point afterwards.

Relevant log lines:

> default	07:18:01.675561 +0200	kernel	EXC_RESOURCE -> Joplin[2702] exceeded mem limit: ActiveHard 650 MB (fatal)
> default	07:18:01.675697 +0200	kernel	27284.063 memorystatus: killing_specific_process pid 2702 [Joplin] (per-process-limit 10) - memorystatus_available_pages: 18019

To fix this, we'll need to analyse the sync process and find a memory leak (tried to find it on desktop, which uses the same sync algorithm, but no memory leak there).

**Comment by caffeine-1** [comment]
Same issue on IOS with Dropbox sync, large import from Evernote,  hope a fix can be found. 

Works great on Linux.
