### ISSUE TITLE
The latest version of IOS APP, when configuring Webdav, URL does not support domain name, only IP

### ISSUE THREAD

**Issue by dantezhu** [laurent22/joplin#5350]
The latest version of IOS APP, when configuring Webdav, URL does not support domain name, only IP。
If use domain, It will show error msg like: `network request fail`

## Environment

Joplin version: 12.3.1
Platform: iOS
OS specifics:  IOS 14.6

## Steps to reproduce

1. configuring Webdav
2. use domain as url, like http://example.com:3333
3. test the configure
4. It will show error msg like: `network request fail`

## Describe what you expected to happen

sync well.

## Logfile

![image](https://user-images.githubusercontent.com/1105212/130102841-48b932b3-30b7-4de1-95f3-d19e4b4995e7.png)

**Comment by mkjor** [comment]
I ran into the same problem

**Comment by dantezhu** [comment]
active this problem 😄

**Comment by dantezhu** [comment]
active again.. any one can help?

**Comment by robman0815** [comment]
Same Problem here. When using the IP, ist works. 

Joplin 12.3.1 on iOS 14.7.1
WebDAV Server on Synology NAS

**Comment by Fruzzle** [comment]
Just a quick update: The WebDAV sync failure in the Joplin iOS app v12.3.1 still remains.  I've verified it under iOS 12.4.1 as well as iOS 14.7.1, and it fails on both.  I wanted to mention this in case there was some suspicion that the iOS version itself mattered (it does not).  The previous app version (12.2.1) works fine (I have two phones, rather conveniently, so I've only upgraded one of them).
I've tried it with both HTTP and HTTPS; same failure with both.  Changing the URL to specify an IP address instead of a DNS name  is a temporary workaround, but not a permanent solution for obvious reasons.
The error log snippet posted by dantezhu is all the useful information that can be gleaned from the logs on the device.

**Comment by hak0** [comment]
Same here for my Joplin Server. Both Andorid and Windows clients work fine but iOS client failed to sync when using domain name.

**Comment by Fruzzle** [comment]
The most recent version of the iOS app (v12.5.3) now seems to connect and work properly for WebDAV endpoints, **as long as** they are HTTPS.  The last version that worked with HTTP appears to be v12.2.1.
Given recent iOS security tightening, it may not be feasible to use insecure HTTP URLs going forward, at least not fully-qualified ones.  Given this, I believe this issue can be closed.

**Comment by adenoz** [comment]
Today, I was able to sync to Joplin in iOS using a sub-domain name. For example sub.domain.com using fully signed https connection (using Let's Encrypt certs in my Nextcloud server). So at least for https this issue is no longer valid. Self-signed certs don't seem to work though.

**Comment by mkjor** [comment]
The workaround with the IP of the WebDAV server is working for me (but is not nice). If I revert the IP back to the host name the synchronization does not work anymore. From this view the issue persists and is not fixed.

As I understand, the problem is a iOS issue while using plain HTTP to a host name. I don't know the iOS APIs and I can't say whether Apple will change anything...
