### ISSUE TITLE
Inconsistent spacing between leading text, a bulleted list and trailing text

### ISSUE THREAD

**Issue by tihomir-kit** [laurent22/joplin#5357]
When adding a bulleted list, it has more spacing between the top piece of text and the list than between the bottom piece of text and the list. This feels unintuitive and makes it feel like the bulleted list is associated with bottom text, where it's typically more associated with the text above it. Other rendering engines typically leave the same amount of spacing top and bottom.

## Environment

Joplin version: 2.3.5 (but I've noticed this on 2.2.x as well and perhaps even earlier
Platform: Windows 10
OS specifics: Windows 10, up to date

## Steps to reproduce

1. Enter the following into a new note:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

- Item 1
- Item 2

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
```

You should see a bigger gap between top text and list than bottom text and the list:

![image](https://user-images.githubusercontent.com/535842/130235414-543dc9df-cba5-41cd-9999-5fbfe5722689.png)

## Describe what you expected to happen

I would expect to see even spacing like this:

(This is how GitHub renders the same markdown - it's even spacing top and bottom):
![image](https://user-images.githubusercontent.com/535842/130235117-1e5ca748-b1f7-4058-b9b3-c466285ca6f8.png)

(This is how MS Word renders a bulleted list - again it's even spacing top and bottom):
![image](https://user-images.githubusercontent.com/535842/130235294-a8a10525-668a-42db-84b9-757af1d5ec22.png)

## Logfile

Does not apply (I think).

---

Thanks!

**Comment by pinkman7009** [comment]
Can I take up this issue?

**Comment by tihomir-kit** [comment]
Keep open please.

**Comment by iceboundflame** [comment]
Came here to file the same bug, a minor rendering issue but it's quite disconcerting. Here's a comparison of Joplin vs StackEdit rendering. Would be grateful for a fix! (@pinkman7009 are you still planning on trying?)

![Screen Shot 2021-11-01 at 19 13 05](https://user-images.githubusercontent.com/933687/139775579-2a23bbfe-0819-4115-a273-432b65f64c27.png)

**Comment by pssandhu** [comment]
I think this is due to the margins above and below the `p` tags being different. The default has the top and bottom margins as 0.6em and 1.35em, respectively.

You can add the following to the custom stylesheet for rendered markdown in the settings to make the margins equal:
```css
p {
    margin-bottom: 0.6em;
}
```

p, h1, h2, h3, h4, h5, h6, ul, and table all share the same default margins. So I guess resolving this issue would require a small design change

**Comment by tihomir-kit** [comment]
Keep open please.

**Comment by tihomir-kit** [comment]
Keep open.

**Comment by olbotta** [comment]
The solution provided above works.
However i think having default spacing above the bulleted list, as descirbed by @tihomir-kit, should be the default

**Comment by tihomir-kit** [comment]
Keep

**Comment by pssandhu** [comment]
Still an issue

**Comment by pssandhu** [comment]
Keep open

**Comment by pssandhu** [comment]
Keep

**Comment by pssandhu** [comment]
Keep open

**Comment by pssandhu** [comment]
Still an issue

**Comment by tihomir-kit** [comment]
keep

**Comment by tihomir-kit** [comment]
keep. might have to write a "keep open" bot :D

**Comment by pssandhu** [comment]
Keep :)

**Comment by pssandhu** [comment]
Keep

**Comment by tihomir-kit** [comment]
keep

**Comment by pssandhu** [comment]
Keep

**Comment by pssandhu** [comment]
Keep

**Comment by pssandhu** [comment]
Keep open

**Comment by pssandhu** [comment]
Keep open

**Comment by pssandhu** [comment]
Keep

**Comment by pssandhu** [comment]
Keep open

**Comment by pssandhu** [comment]
Still an issue

**Comment by pssandhu** [comment]
Keep

**Comment by tdltdc** [comment]
Keep

**Comment by deepspaceaxolotl** [comment]
This is still the case and I'd appreciate reopening this issue to fix it. At the moment, lists look to be associated more with the following text than the preceding text, which is less than ideal, particularly when the list follows from the preceding text directly.

IMO, it would be even better if, if the text before a list is not separated by an empty row, it were spaced _closer_ to the list, [similar to the rendered markdown here](https://stackoverflow.com/a/69903551) (though perhaps with _some_ minor spacing rather than 0). I think this is a common enough usecase for lists, being attached to some previous text, that there should be some way of visually structuring text like this. But at the very least, making sure lists aren't spaced closer to following text than preceding text seems prudent (that StackOverflow thread features [a form for a potential solution](https://stackoverflow.com/a/79262456)).
