### ISSUE TITLE
Spaces on begining line in code blocks have been removed

### ISSUE THREAD

**Issue by garyyeap** [laurent22/joplin#5367]
<img width="1203" alt="圖片" src="https://user-images.githubusercontent.com/798943/130346769-6e6df217-fe9e-46b8-8168-53ea1c04c56b.png">

<img width="607" alt="圖片" src="https://user-images.githubusercontent.com/798943/130346780-7c956b7a-225e-4425-b168-c2a9218a5e2f.png">

**Comment by garyyeap** [comment]
The issue still exists

**Comment by garyyeap** [comment]
Is this considered a bug or not?

**Comment by lkiThakur** [comment]
```    
           yes I think this  a bug 
since codeblocks are supposed to preserve whatever is written inside them.
```
as shown in above code block github's markdown also preserves leading and trailing whitespaces.
discourse also does same
even the markdown editor of joplin preserves whitespaces at ends it's a bug while taking input in that dialogue box

I tried solving it through #5589 but that wasn't accepted unfortunately 😀 
but the issue is still open this means that it is perhaps considered as a bug so will be solved by someone in near future .

**Comment by garyyeap** [comment]
So is this still consider a bug?
