### ISSUE TITLE
Not every unicode symbols are good treated

### ISSUE THREAD

**Issue by jbfagotfede39** [laurent22/joplin#5382]
I'd like to add unicode symbols in markdown notes. It's ok with some symbols like `&#9658;` or `&#767;` or `&#2400;` but it's not ok with apple symbol `&#63743;` (see [here](https://unicode-table.com/fr/F8FF/)).

## Environment

Joplin version: 2.3.5
Platform: macOS
OS specifics: 10.15.7

## Steps to reproduce

1. Paste `&#9658;` and `&#63743;` in a note

**Comment by tessus** [comment]
_In Unicode, the Private Use Areas (PUA) are three ranges of code points (U+E000–U+F8FF in the BMP, and in planes 15 and 16) that, by definition, will not be assigned characters by the Unicode Consortium. The code points in these areas cannot be considered as standardized characters in Unicode itself. They are intentionally left undefined so that third parties may define their own characters without conflicting with Unicode Consortium assignments. Under the Unicode Stability Policy, the Private Use Areas will remain allocated for that purpose in all future Unicode versions. Assignments to Private Use Area characters need not be «private» in the sense of strictly internal to an organisation; a number of assignment schemes have been published by several organisations. Such publication may include a font that supports the definition (showing the glyphs), and software making use of the private-use characters (e.g. a graphics character for a «print document» function). By definition, multiple private parties may assign different characters to the same code point, with the consequence that a user may see one private character from an installed font where a different one was intended._

This means your milage may vary depending on font, application, ... You can't expect consistent behavior, nor that it works at all.

**Comment by jbfagotfede39** [comment]
> _In Unicode, the Private Use Areas (PUA) are three ranges of code points (U+E000–U+F8FF in the BMP, and in planes 15 and 16) that, by definition, will not be assigned characters by the Unicode Consortium. The code points in these areas cannot be considered as standardized characters in Unicode itself. They are intentionally left undefined so that third parties may define their own characters without conflicting with Unicode Consortium assignments. Under the Unicode Stability Policy, the Private Use Areas will remain allocated for that purpose in all future Unicode versions. Assignments to Private Use Area characters need not be «private» in the sense of strictly internal to an organisation; a number of assignment schemes have been published by several organisations. Such publication may include a font that supports the definition (showing the glyphs), and software making use of the private-use characters (e.g. a graphics character for a «print document» function). By definition, multiple private parties may assign different characters to the same code point, with the consequence that a user may see one private character from an installed font where a different one was intended._
> 
> This means your milage may vary depending on font, application, ... You can't expect consistent behavior, nor that it works at all.

Thanks for explanation
