### ISSUE TITLE
onNoteSelectionChange() is triggered twice after a search

### ISSUE THREAD

**Issue by msbentley** [laurent22/joplin#5447]
This is related to an issue I raised on the [Persistent Layout plugin](https://github.com/benji300/joplin-persistent-layout/) - specifically https://github.com/benji300/joplin-persistent-layout/issues/7. The issue is (I believe!) that after a search has been executed the first note in the list is selected, but `onNoteSelectionChange()` is trigerred twice, in this case causing the plugin to take the correct action, and then revert it.

## Environment

Joplin version: 2.4.6
Platform: linux
OS specifics: ubuntu 20.04

## Steps to reproduce

1. Install the Persistent Layout plugin
2. Create notes tagged with the special tags for the different layouts
3. Search for a note which has a different layout tag than the currently selected.
3. Observe that the layout does not seem to change.

As far as I understand, although the bug here is with the plugin, the behaviour stems from Joplin and has to be fixed here. My apologies if this is not the case, I just wanted to raise the issue since it is a big one for my workflow ;-)

**Comment by ken1kob** [comment]
I analyzed this issue and fixed it.

## In a nutshell
- The main cause (a functional bug) is in persistent layout plugin. [(fix is here)](https://github.com/benji300/joplin-persistent-layout/pull/10)
- A performance bug is also in Joplin. [(fix is here)](https://github.com/laurent22/joplin/pull/5449)
- Asynchronous/concurrent programming is not easy.

Although either of the first or second pull request fixes the issue, applying both is better.

## For details

### Main cause

Two onNoteSelectionChange() invocations are triggered, but they are different. See the following a event sequence, which is one example involving this symptom.
Line1 triggers Line2 (green), and Line3 triggers Line4 (red). So, there are two (green and red) series of concurrent running callbacks.

```diff
# 01. App: Reducer action NOTE_UPDATE_ALL
   - state.selectedNoteIds === []
+ 02. onNoteSelectionChange() callback of the plugin is scheduled.
# 03. App: Reducer action NOTE_SELECT
   - state.selectedNoteIds === ['b5beac327000456e8b94fc149a8bb379']
- 04. onNoteSelectionChange() callback of the plugin is scheduled.
+ 05. PluginRunner: Got message (3): joplin.workspace.selectedNote
   - joplin.workspace.selectedNote().id === 'b5beac327000456e8b94fc149a8bb379'
- 06. PluginRunner: Got message (3): joplin.workspace.selectedNote
   - joplin.workspace.selectedNote().id === 'b5beac327000456e8b94fc149a8bb379'
# 07. Loading existing note b5beac327000456e8b94fc149a8bb379
+ 08. PluginRunner: Got message (3): joplin.data.get (3) ["notes", "b5beac327000456e8b94fc149a8bb379", "tags"]
- 09. PluginRunner: Got message (3): joplin.data.get (3) ["notes", "b5beac327000456e8b94fc149a8bb379", "tags"]
+ 10. PluginRunner: Got message (3): joplin.settings.globalValue editor.codeView
- 11. PluginRunner: Got message (3): joplin.settings.globalValue editor.codeView
+ 12. PluginRunner: Got message (3): joplin.commands.execute toggleEditors
+ 13. CommandService::execute: toggleEditors
+ 14. App: Reducer action SETTING_UPDATE_ONE
- 15. PluginRunner: Got message (3): joplin.commands.execute toggleEditors
- 16. CommandService::execute: toggleEditors
- 17. App: Reducer action SETTING_UPDATE_ONE
```

As you noticed, Line2 and Line4 callback invocations are triggered at the different times and different conditions (state.selectedNoteIds === [] and state.selectedNoteIds === ['b5beac327000456e8b94fc149a8bb379']). So, there is no problem in Joplin itself.

Since plugin callbacks are async, the two scheduled callback invocations are executed later. In this case, two invocations start in a row and are executed concurrently. When Line2 invocation starts, state.selectedNoteIds was already changed to a new value, which is the same value with the value visible from Line4 invocation.

In summary, two onNoteSelectionChange() callback invocations are different. But, they look duplicates when they are executed.

In asynchronous or concurrent programming, this type of coding troubles sometimes happens. Coping with it is a plugin programmer's responsibility, I think. It is very difficult and burdensome for Joplin to provide a concurrent system without such troubles. (because it means developing a new safe asynchronous execution system.)

To coping with such trouble in a plugin side is not so difficult.
Keep in mind that some of messages (callback invocations) are out-of-dated.

In this case, a sample fix is shown in [this pull request](https://github.com/benji300/joplin-persistent-layout/pull/10). The approach of this code is that it keeps tracking the state of Joplin in a plugin itself and validates the messages from Joplin. 

### Performance bug

Joplin also has a minor problem about this issue.
I noticed `reducer.ts/updateSelectedNotesFromExistingNotes()` causes unnecessary `selectedNoteIds` change events. It is not a functional bug, but is redundant and a performance bug. The problematic code and its fix is in [this pull request](https://github.com/laurent22/joplin/pull/5449).

Additionally, if this bug did not exist, this bug of persistent layout plugin would not come to the surface.
