### ISSUE TITLE
Mermaid Graph freezes the app, making data unaccesible and unrecoverable

### ISSUE THREAD

**Issue by lantob** [laurent22/joplin#5455]
This is loosely related to #5295 (I am terribly sorry if this is not a real issue)

## Environment

Joplin version: 2.3.5
Platform: Linux 64b
OS specifics: manjaro linux

## Steps to reproduce

1.  I created a git graph using mermaid (see below for code), supposedly with false intendation and no closing brackets. 
2.  The App crashed.
3.  The app is rendered completly unresponsive upon restart. 

I tried spamming CTRL+E to edit the markdown in an external editor, but this didnt work. The opened .md is indeed empty, Joplin is still unresponsive and frozen after restart. It is only killable through console via sudo kill.

I have also tried to install the cli version instead,  but apparently they don't share directories. I have also tried to simply copy the data, but the $HOME/.config/joplin-desktop does not contain any .md files. I did update the app-image through the website, since I saw the other issue being resolved via a new version, this did not help though.

I can't provide logs, since I can't enable debugging.

The mermaid code currently showing is
```
```mermaid
gitGraph:
commit
branch newbranch
checkout newbranch
commit
commit
commit
checkout Pu
commit
commit
```

**Comment by laurent22** [comment]
In which way is it loosely related? That looks like exactly the same issue?

**Comment by lantob** [comment]
The other guy could at least try out different code in a new instance. I cannot access Joplin at all. Sorry, if this a duplicate, though.

**Comment by laurent22** [comment]
Ok I see, it's the same issue although in your case it freezes the app before you can do anything. This is quite annoying, we've tried to disable this broken gitGraph extension but Mermaid doesn't have this option.

Ideally you should start in safe mode but I realise now there's no easy way to do that if the app freezes (as opposed to crashing). Otherwise, if you have the cli app, you could do that:

- Make sure the desktop app is closed (kill the process to make sure)
- Start the cli app using `joplin --profile /path/to/user/.config/joplin-desktop`
- Delete the problem note
- Close the cli app

Now re-open the desktop app and it should work. If not let me know.

**Comment by lantob** [comment]
This indeed makes it able to re-access the data. Even though I tried it in a different enviroment, this might help someone else finding themselves stuck.

**Comment by shelllee** [comment]
joplin will be freezesed immediately when opened if the md file selected last time contains mermaid graph. for this situation, one way is to edit the sqlite database's (in `/path/to/user/.config/joplin-desktop`) setting table for it's `activeFolderId` and `clientId` target value, which could be found in `folders` and `notes` table.

![image](https://user-images.githubusercontent.com/11704124/137482394-0e5d8bc5-f008-42af-b168-57ce4a891d21.png)
