### ISSUE TITLE
Code block frustrates me.

### ISSUE THREAD

**Issue by katzeprior** [laurent22/joplin#5466]
## Environment

Joplin version: 2.3.5
Platform: Linux
OS specifics: Opensuse

## Steps to reproduce

1. put the code block written below in a note, (doesn't matter if its zsh or bash and joplin will choose the right one automatically
```zsh
echo "SGVsbG8gV29ybGQhCg==" | base64 -d
find / -name stubby.yml
grep "https" | test -d getdns.spec.backup
```
I know its not really joplins fault because github has the same issue but I am frustrated af and idk what to do.
when i add ls after the grep command joplin shows the right colours for all the commands and the arguments.

## Describe what you expected to happen
https://imgur.com/a/37uGLPa
but without the ls because if i remove the ls it doesn't keep the right colour scheme.

## Logfile
Log file is not needed in this instant.

**Comment by Daeraxa** [comment]
I always assumed the markdown viewer showed what was in the codemirror editor if you defined it in the code block. If you look here if you define sh as the code block language then even with the ls added it shows it in the default way. I wonder what it is interpreting it as when you add the ls.
![image](https://user-images.githubusercontent.com/58074586/133459173-b9276175-914b-493d-9c37-f4587c6b748e.png)

**Comment by CalebJohn** [comment]
After too much time spent playing around with this I've determined that [highlight.js](https://github.com/highlightjs/highlight.js) is guessing that the language is [vimscript](https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md) when you add the additional command. You can confirm this by adding some specific bash stuff (like comments) to get the algorithm to correctly deduce bash. You can see my example below.

![image](https://user-images.githubusercontent.com/2179547/133554458-52b39fe1-95b8-4226-a712-ac23986f4048.png)

So if anything this is an upstream problem, but really I don't know what they can do. There is a unfortunately a lot of overlap between languages so now auto detector will be 100% accurate. My recommendation would be to always specify the language so that it doesn't change around on you. In your case you can probably get away with always specifying "vim" since you like the highlighting better.

I'm going to close this since it isn't really a bug, but feel free to take it upstream with highlight.js, they'll be able to potentially make the fix there. 
In case you're curious, they have a [writeup](https://github.com/highlightjs/highlight.js/blob/main/docs/language-guide.rst#relevance) about how the auto-detection works. You might find it interesting.
