### ISSUE TITLE
iOS decryption

### ISSUE THREAD

**Issue by vpopescu** [laurent22/joplin#549]
### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

### Application

- [ ] Desktop
- [x] Mobile
- [ ] Terminal

- [x] Storage:  box.net over webdav.
- [x] Device: IPad Pro (12")

I can't get joplin iOS to decrypt my notes. The logs don't show any errors (shows one master key was downloaded and none was previously available, automatically enabling encryption

I can sync okay, but the notes don't get decrypted. The notes are created by the windows app. 

First issue:

On my app encryption window, I see 4 master keys, three with a red X and one with a blue checkbox. I am not sure if the red X is supposed to be a delete button, or it indicates the status of the active key. However I can't figure out how to delete them to start from scratch (deleting and reinstalling the app did not get rid of them). How do I clean things up? If it's something on the file storage, how do I find this?

UI comment - besides the confusion about how to delete the master key, is it necessary to have one save button per key? Right now I click and it flashes briefly but doesn't give me any feedback beyond this.

Second issue:

After entering the password, and clicking the 'save' link at the right side (is that the right save link? it seems a little odd). the app still says "Press to set decryption password" on the top orange box. So I don't think it's seeing that I saved the password.

So my "encryption" window now says:

"Press to set the encryption password" (orange bar)
and...
Encryption is enabled...
and...
Decrypted items: 0/25

Known issues in iOS or am I doing something wrong?

**Comment by vpopescu** [comment]
Thanks, that clarified. I got it to work after entering the password on all the keys.  Would it be possible to identify the key and the client (hostname, etc) that created it?

The problem is that now I have three clients that are part of this environment, but it is showing me four master keys. I don't know what the fourth key is and is not accepting my password for that key (when I try to save, it stays with a red 'x' even though it saves it). Would be nice if I could get rid of it as to not cause confusion in the future. Do you document somewhere how to clean obsolete keys?

**Comment by laurent22** [comment]
If you open the database.sqlite file, in the master_keys table the "source_application" field will tell you where the master key was created.

Currently it's not possible to delete master keys and I doubt it will ever be possible as it's not possible to know if a master key is going to still be useful or not (due to the decentralised nature of Joplin, there's no way to know what data the clients connected to a sync target have). Also I wouldn't want people to accidentally delete a master key and then lose access to their encrypted data.

I guess there could be an option to hide a master key, though it wouldn't be particular useful since normally there's no need to look at the list of master keys (except at the beginning to provide the password).
