### ISSUE TITLE
userstyle.css not working

### ISSUE THREAD

**Issue by lipejdc** [laurent22/joplin#5518]
Hello!

I am not sure if this is a bug or not. I tried many times to add css styles to my markdown and they don't work. I already tried quitting Joplin, restarting the computer, reinstalling Joplin and nothing solved it, no matter what I write as a style.
I use Windows 10 64 bit. Here is my Joplin version:

![joplin-version](https://user-images.githubusercontent.com/81684474/135591200-a06c86d2-7d92-44d0-8d98-a2067a03c11e.JPG)

Here is my userstyle.css (I only added colors to h1, h2 and h3):

![joplin-css](https://user-images.githubusercontent.com/81684474/135591254-1b139123-7dc8-48e4-8102-e6375d960019.JPG)

Here an example how it doesn't work:

![h1h2h3](https://user-images.githubusercontent.com/81684474/135591314-e2e93858-d6ec-4477-88a0-d76f5d10cc49.JPG)

I am quite new to markdown and Joplin do I apologize in advance if I am doing something wrong or overseeing something.

**Comment by tessus** [comment]
You are using the wrong file. Please use the [forum](https://discourse.joplinapp.org/) for usabilty questions. Search for "custom css".
userstyle.css -> rendered html
userchrome.css -> Joplin UI and editor

**Comment by lipejdc** [comment]
Before creating a new thread in the forums, there is this warning message:

"For bug reports, please post them on GitHub - https://github.com/laurent22/joplin/issues
If you are not sure if it's a bug or not, PLEASE POST ON GITHUB ANYWAY."

As I was not sure if it was a bug or not, I posted it here.

I added css to both userstyle.css and userchrome.css and nothing changes (neither rendered markdown nor markdown editor).

**Comment by tessus** [comment]
> As I was not sure if it was a bug or not, I posted it here.

That's fine. This is why I told you it is not a bug and better be discussed on the forum. There you already have all the answers actually.

Your css is also wrong. Why do you think that using `<h1>` would change anything in the editor? The editor uses different classes.

Btw, changing these files requires a restart of Joplin. This means terminating the app, not closing the window. -> see the FAQ how to do that. Another thing: why did you make a screenshot of text? How is someone supposed to reproduce your problem? Should they type everything manually, instead of doing a copy and paste? Sorry, I get a bit testy when it comes to pasting text as a screenshot when a copy/paste would do and makes my life a lot easier.

Either wat, there are many css posts, all of them expain what to do and how to do it.

https://discourse.joplinapp.org/t/joplin-customization/11195?u=tessus
https://discourse.joplinapp.org/t/share-your-css/1730?u=tessus
