### ISSUE TITLE
Markdown formatting not added when inserting links using WYSIWYG editor

### ISSUE THREAD

**Issue by tomasz1986** [laurent22/joplin#5534]
## Environment

Joplin version: v2.4.9 (but probably applies to any)
Platform: Windows (but probably applies to all desktop)
OS specifics: Windows 10

## Steps to reproduce

1. Switch to the WYSIWYG editor.
2. Insert a new link as follows.
   ![image](https://user-images.githubusercontent.com/5626656/135958711-c5395dfe-63cf-4f4d-8c27-53108ce9155e.png)
3. Switch to the Markdown editor.

## Describe what you expected to happen

The expected result of the insertion is `[https://www.google.com](https://www.google.com)`. However, the actual result reads just `https://www.google.com` with no additional formatting.

The problem affects only those links, which have the same content in the URL, text to display, and/or title fields.

**Comment by laurent22** [comment]
Yes I think links like `[url](url)` are simplified to just `url`. I don't think that will be changed as this simplification makes imported notes, from the web clipper in particular, much simpler.

**Comment by tomasz1986** [comment]
The main problem I have with those is that they're not clickable, unless the Linkify plugin is enabled.

There's a way to hack this "simplification" though, and the simplest method seems to be to set the title to a single space.

**Comment by Daeraxa** [comment]
I would argue that it also means that the functionality of two identical looking buttons is different between the markdown editor and the richtext editor which doesn't quite feel right as that button on the markdown edtitor gives you the full markdown formatting tag for URLs.
Also as @tomasz1986 mentions, if you aren't using the (optional) linkify plugin then it simply isn't a link - you might as well have just pasted in the URL instead of using the insert link tool (which is technically happens regardless of using linkify or not) - the whole point of clicking the button in the toolbar is to be able to insert a "proper" markdown link rather than just a plaintext URL.

**Comment by tomasz1986** [comment]
I'd also like to add that links in this form are not clickable, and opening them requires copying the address and pasting it manually into the Web browser. What I mean is that even though they are styled like links, there is no "open URL" entry in their right-click menu.

As you can see on the screenshot below,

![image](https://user-images.githubusercontent.com/5626656/138025178-0f95fb3f-fb1f-4088-a697-a1138cd05b35.png)

there only "copy path to clipboard" and "copy link address" are available, which actually do the exact same thing. There is also "open", of course, but it does absolutely nothing in this case.
