### ISSUE TITLE
can't make the task done when the screen is halved

### ISSUE THREAD

**Issue by Yalchin403** [laurent22/joplin#5604]
## Environment

Joplin version: 
Platform: 
OS specifics: 

## Steps to reproduce

1.  2.4.9
2. Windows 10 home
3.

**Comment by Daeraxa** [comment]
I think you might need to provide a bit more information than that - the bug template is there to be filled out for a reason.
I just had a quick attempt to play with window sizes and ticking a task and can't see a problem.
Halved how? In what direction? What Joplin version? What OS? The log files might well be useful if something is failing.

**Comment by Daeraxa** [comment]
I just tried it on 2.5.4, on Windows 10 and was able to click the todo note checkbox as well as the note tickboxes in both editors.

**Comment by tomasz1986** [comment]
The issue title should be changed to something more relevant, but I know this problem very well myself. This happens if you shrink the Joplin window horizontally, so that the WYSIWYG editor buttons become hidden under the three dots menu.

Basically,

![image](https://user-images.githubusercontent.com/5626656/138008425-5b8c09e7-70ef-4b5c-8bfa-aa6489ddbe6a.png)

becomes

![image](https://user-images.githubusercontent.com/5626656/138008441-088442d7-1222-4e44-a405-a056e6d90e57.png)

In this shrunken state, you cannot tick the boxes unless click the three dots first and make the relevant buttons visible first.
