### ISSUE TITLE
Webclipper fails to connect to client

### ISSUE THREAD

**Issue by leprasmurf** [laurent22/joplin#561]
### Operating system

- Windows 10 Pro
Version: 1709
OS Build: 16299.431

### Application

- Desktop

### Summary

I've updated Joplin to version 1.0.95 and installed the clipper chrome extension

 There was some error creating the note: Could not find clipper service. Please make sure that Joplin is running and that the clipper server is enabled.  My attempt to clip a page failed with the following message:

```
There was some error creating the note: Could not find clipper service. Please make sure that Joplin is running and that the clipper server is enabled.
```

There are a number of possible issues, it is windows afterall, but I have been unable to isolate the issue. 
 Joplin desktop is in debugging mode and see the following on the console:

```
2018-05-25 12:13:53: "Starting Clipper server on port 41184"
```

I am able to telnet from the local machine:

```
leprasmurf@Athena:~$ telnet localhost 41184                                                                                       Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
^]
telnet> quit
Connection closed.
```

It would be great if the Web Clipper extension had a "test connectivity" button and/or some sort of configuration that allowed for a user to specify the address, port, and notebook to save to.  Unless the clipper extension wrote directly to the WebDAV target and bypassed the local app.

**Comment by laurent22** [comment]
That's odd, especially since it seems the service is running. Did you get a message from the firewall to ask you to allow access for Joplin?

Also could you check if you can access the server via http?

    curl http://127.0.0.1:41184/ping

> It would be great if the Web Clipper extension had a "test connectivity" button 

Yes indeed, I will make the connectivity status clearer in the next version.

**Comment by leprasmurf** [comment]
PEBKAC.  I'm also using FoxyProxy for some split-horizon DNS chicanery.

Once I disabled the proxy I was able to save a note.

**Comment by pcause** [comment]
I can't get the webclipper to connect with my Joplin.  Using the latest addon to firefox and 1.0.99.  I use Firefox nightly.  The curl test (above) works from both windows cmd.exe and wsl linux.  Here is the debug data from the console window from the time I clicked debug Joplin and then opened the clipper.

> Could not map contract ID '@mozilla.org/widget/printdialog-service;1' to CID {06beec76-a183-4d9f-85dd-085f26da565a} because no implementation of the CID is registered.
Could not map contract ID '@mozilla.org/fxaccounts/push;1' to CID {1b7db999-2ecd-4abf-bb95-a726896798ca} because no implementation of the CID is registered. components.manifest:165
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ i18n.js:26:1
[Show/hide message details.] Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. webrequest.js:118
Use of nsIFile in content process is deprecated.
NetUtil.jsm:266:12
Error: ID already exists: detect-forms ext-menus.js
Error: ID already exists: generate-password ext-menus.js
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://c6ceef42-1b56-48b8-9b0a-0cb61e334f8e/popup/build/static/js/main.4bb74f6e.js
Source Map URL: main.4bb74f6e.js.map[Learn More]
[Show/hide message details.] Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. webrequest.js:118
Error: ID already exists: detect-forms ext-menus.js
Error: ID already exists: generate-password ext-menus.js
Error: ID already exists: remove-open-in-this-container ext-menus.js
Error: ID already exists: separator ext-menus.js
Error: ID already exists: hide-container ext-menus.js
Error: ID already exists: move-to-new-window-container ext-menus.js
[Show/hide message details.] Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.
webrequest.js:118
Error: ID already exists: detect-forms ext-menus.js
Error: ID already exists: generate-password ext-menus.js
Error: ID already exists: remove-open-in-this-container ext-menus.js
Error: ID already exists: separator ext-menus.js
Error: ID already exists: hide-container ext-menus.js
Error: ID already exists: move-to-new-window-container ext-menus.js
Popup: Init bridge main.4bb74f6e.js:1:17775
Popup: Env: dev main.4bb74f6e.js:1:18683
findClipperServerPort: Trying 27583 main.4bb74f6e.js:1:20125
Popup: Creating React app... main.4bb74f6e.js:1:40319
Popup: Restoring saved state: 
Object {  }
main.4bb74f6e.js:1:19537
null main.4bb74f6e.js:1:157546
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://c6ceef42-1b56-48b8-9b0a-0cb61e334f8e/popup/build/static/js/main.4bb74f6e.js
Source Map URL: main.4bb74f6e.js.map[Learn More]
findClipperServerPort: Trying 14801 main.4bb74f6e.js:1:20125
findClipperServerPort: Trying 41083 main.4bb74f6e.js:1:20125
findClipperServerPort: Trying 19545 main.4bb74f6e.js:1:20125
findClipperServerPort: Trying 12650 main.4bb74f6e.js:1:20125
findClipperServerPort: Trying 4134 main.4bb74f6e.js:1:20125
findClipperServerPort: Trying 24706 main.4bb74f6e.js:1:20125
findClipperServerPort: Trying 17858 main.4bb74f6e.js:1:20125
findClipperServerPort: Trying 3869 main.4bb74f6e.js:1:20125
findClipperServerPort: Trying 26089 main.4bb74f6e.js:1:20125
null main.4bb74f6e.js:1:157546
>
Note that the webclipper is started in Joplin on port 41184 but I don't see that port tried in the above log.
