### ISSUE TITLE
Floating keyboard on iPadOS 15.1 leads to UI error

### ISSUE THREAD

**Issue by xto3** [laurent22/joplin#5663]
### Platform and app information

iPadOS 15.1
Joplin App 12.4.2

Most of the time, I use the floating keyboard on my iPad:
https://support.apple.com/en-us/HT210758

### Sequence

- When you edit a note on iPad with that floating keyboard
- Another window comes across after a few seconds and covers almost all the editing screen
- As a result, you cannot edit the note anymore
- It’s not strictly speaking a crash but in the end you get stuck and you need to force the app to close to make it usable again

### Expected behavior

The open note in Joplin should remain editable with the floating keyboard as it does with the standard keyboard.

### Screencast

https://user-images.githubusercontent.com/93558124/139756443-fe2dd1ae-68bf-4cce-a388-02f859214c5f.mov

**Comment by grem11n** [comment]
Facing the same bug with:
- iPad OS 14.7.1 (18G82)
- Joplin 12.4.2

**Comment by xto3** [comment]
Hi!

The last version of Joplin doesn’t seem to address the issue. 

Is there any plan to address it in the future?

Thanks again for the good job with Joplin!

**Comment by grem11n** [comment]
Although, it looks like a duplicate for:
* https://github.com/laurent22/joplin/issues/3768
* https://github.com/laurent22/joplin/issues/4980

Looks like https://github.com/laurent22/joplin/issues/4980 has the most activity in it. However, this issue is not addressed yet. Moreover, according the the input from those two issues, it affects not only iPadOS, but iOS as well.

**Comment by xto3** [comment]
Thanks for your reply!

Indeed, I hadn't see those issues prior to post. I will have a look on #4980.
