### ISSUE TITLE
Dark mode search function not found string too dark

### ISSUE THREAD

**Issue by Githob2021** [laurent22/joplin#5666]
Joplin version: 2.5.10
Debian Linux flatpak

In the latest version just released, when using dark mode and the search function and a result is not found it is no longer blinding. This is great.

One improvement to be made is the text "Could not find the specified string." is way too dark and almost unreadable.

**Comment by laurent22** [comment]
screenshot?

**Comment by Githob2021** [comment]
Screenshot https://imgur.com/kp7uWw4

**Comment by Githob2021** [comment]
> screenshot?

Screenshot https://imgur.com/kp7uWw4

**Comment by MUzairS15** [comment]
Hello @laurent22  I am new to Joplin community and want to contribute to this project, can you pls help me started with this issue, which files should be referenced?
ThankYou

**Comment by Daeraxa** [comment]
> Hello @laurent22 I am new to Joplin community and want to contribute to this project, can you pls help me started with this issue, which files should be referenced? ThankYou

Have a look at this thread for general advice on this kind of question (https://discourse.joplinapp.org/t/cant-find-file-to-contribute/21238). I don't mean to sound harsh or to knock your enthusiasm but finding where the problem lays is pretty much the minimum barrier to entry to contribute, the maintainers can't constantly help people find files and advise on how to fix, otherwise they might as well do it themsevles.

**Comment by Rishabhraghwendra18** [comment]
Hi @MUzairS15 . Are you working on this issue ?

**Comment by MUzairS15** [comment]
Thankyou @Daeraxa , yes @Rishabhraghwendra18  I am working on it.
