### ISSUE TITLE
The latest version of 2.5.1 crashes on iOS 12

### ISSUE THREAD

**Issue by sim0nwan9** [laurent22/joplin#5671]
My mobile phone system is ios12.0, I can still work normally on version 2.4.1, and version 2.5.1 will crash immediately

**Comment by laurent22** [comment]
Unfortunately I don't have an iOS device to test, but it seems to work on simulator. Any chance you could provide a crash log as described there? https://joplinapp.org/debugging/#creating-a-low-level-bug-report-on-ios

**Comment by laurent22** [comment]
Also does it display something (like the list of notes) before crashing?

**Comment by brenobaptista** [comment]
I can confirm this on my iPhone 6. When I open the app it begins to load for like a second then it closes. I still receive notifications though

**Comment by bmecchi** [comment]
Hello guys!

@laurent22 , first of all many thanks for your support and kindly attention.

I am facing same issue, just after update Joplin.

Attached:
1. iPhone model and software version - image.
2. Screen behaviour - movie.

![Joplin issue at iPhone 6 running iOS 12-5-5](https://user-images.githubusercontent.com/93725446/140376073-3fb84800-997d-4d86-b22d-332e5820205c.jpeg)

https://user-images.githubusercontent.com/93725446/140376401-04446e07-52ce-4fea-9aac-1c6d0d473713.mp4

Below is the text of last crash report (have several out there, but chose the newest one).
Could not attach the ".ips" archive, once is not supported by Github, so I copy and paste here.

---
{"app_name":"Joplin","timestamp":"2021-11-03 13:18:29.28 -0300","app_version":"12.5.1","slice_uuid":"9961a743-47cd-38c1-a227-4bf3fb9b6c91","adam_id":1315599797,"build_version":"75","bundleID":"net.cozic.joplin","share_with_app_devs":false,"is_first_party":false,"bug_type":"109","os_version":"iPhone OS 12.5.5 (16H62)","incident_id":"A1612D29-C704-4728-883B-C54F927382ED","name":"Joplin"}
Incident Identifier: A1612D29-C704-4728-883B-C54F927382ED
CrashReporter Key:   3f17f82a863d3734d204c254c19293eef8a2dcec
Hardware Model:      iPhone7,2
Process:             Joplin [7564]
Path:                /private/var/containers/Bundle/Application/E0529FC5-90F9-4031-B2FA-7B3EB5765DC7/Joplin.app/Joplin
Identifier:          net.cozic.joplin
Version:             75 (12.5.1)
AppStoreTools:       13A1030d
AppVariant:          1:iPhone7,2:12.2
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           net.cozic.joplin [1941]


Date/Time:           2021-11-03 13:18:29.1402 -0300
Launch Time:         2021-11-03 13:18:28.8665 -0300
OS Version:          iPhone OS 12.5.5 (16H62)
Baseband Version:    7.80.04
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, Library not loaded: /System/Library/Frameworks/LinkPresentation.framework/LinkPresentation | Referenced from: /var/containers/Bundle/Application/E0529FC5-90F9-4031-B2FA-7B3EB5765DC7/Joplin.app/Joplin | Reason: image not found
Triggered by Thread:  0

Thread 0 Crashed:
0   dyld                          	0x0000000100a9e418 0x100a5c000 + 271384
1   dyld                          	0x0000000100a9da58 0x100a5c000 + 268888
2   dyld                          	0x0000000100a9da88 0x100a5c000 + 268936
3   dyld                          	0x0000000100a608f8 0x100a5c000 + 18680
4   dyld                          	0x0000000100a636e4 0x100a5c000 + 30436
5   dyld                          	0x0000000100a5d044 0x100a5c000 + 4164

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016f9ea9a0   x3: 0x00000000000000b5
    x4: 0x000000016f9ea5a0   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000390
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x206567616d69203a  x11: 0x6e756f6620746f6e
   x12: 0x20200a6e696c706f  x13: 0x203a6e6f73616552  x14: 0x6f6e206567616d69  x15: 0x00646e756f662074
   x16: 0x0000000000000209  x17: 0x0000000000000010  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016f9ea5a0  x21: 0x00000000000000b5  x22: 0x000000016f9ea9a0  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x000000000000002f  x26: 0x0000000100ab75e0  x27: 0x0000000100ab7000
   x28: 0x0000000100ab7a00   fp: 0x000000016f9ea570   lr: 0x0000000100a9da58
    sp: 0x000000016f9ea530   pc: 0x0000000100a9e418 cpsr: 0x00000000

Binary Images:
0x100414000 - 0x10063bfff Joplin arm64  <9961a74347cd38c1a2274bf3fb9b6c91> /var/containers/Bundle/Application/E0529FC5-90F9-4031-B2FA-7B3EB5765DC7/Joplin.app/Joplin
0x100a5c000 - 0x100ab3fff dyld arm64  <c08f675c016c30b8a87de35aef8f6b20> /usr/lib/dyld

EOF
---

Thanks
BMecchi

**Comment by bmecchi** [comment]
BTW. Working just fine on Windows app and on a LG G8X running Android 11.

**Comment by bmecchi** [comment]
Hi Laurent!
Oh! Bad news. Sorry to hear that.
Will it be possible to downgrade to last working version?  Maybe version 2.4.1?
Can the ".api" file be sent to us?
Personally I use 3U tools for IOS sync with iGadgets and maybe I can upload older version...

**Comment by brenobaptista** [comment]
I think it's possible to flag that older hardware is not supported and upload an old version of the app to Apple's servers for people to get it. I remember seen some apps like that in the past.

**Comment by bmecchi** [comment]
Hi, Laurent!

Thank you so much for your attention and kindness.

If you don´t mind, it is great.
As a curious user, I believe apps are downloaded on a kind of container, maybe ending by ".tar" or ".api" filename.
On Windows 10 they are recognized as compressed files and, despite not recommended, it can be open it with Winrar.
If you could send one of them, for 2.4.1 version, I'll be glad to make a try.

Regarding App Store, as far as I could learn (I am late adopter for IOS due to high cost of hardware), DEVs can chose to keep or not older versions available on App Store.

As an example I have an old iPad 2, running IOS 9.3.5, last month I decided to put it on my office to use it as a music player. Tried to download Spotify and got message saying that newer version was no longer compatible with the iPad and asking if I would like to download the last compatible version for my gadget. I chose yes and got the version, working perfect so far. 
Of curse I also know there will be no updates for this version.

This was Spotify option to keep the older version available, not Apple's.

For Joplin, I guess will be necessary to mark 2.5.1 as not compatible with IOS 12 and keep in the Joplin's App Store files the version 2.4.1 for that users.

As I am only a curious user and not a DEV, I have no clues to give you the directions on how to do that, sorry for that. 

Many thanks,
Braulio Mecchi

**Comment by laurent22** [comment]
To give an update, the latest version is using some framework (LinkPresentation) that appears to be missing on iOS 12. So I've applied the fix as described [here](https://developer.apple.com/forums/thread/690551) but somehow it didn't change anything and it still crashes because of this framework.

Perhaps someone more knowledgeable can look into it and get it working with iOS 12? (the crash happens on simulator too)

I have also checked on the App Store and although the old versions are still there it's not possible to expose them to users, and it's also not possible to sideload apps as in Android.

That's unfortunately a typical situation with Apple. They lock down and control all the devices and distrubution channels, so if something doesn't work there's not many options other than upgrading the OS or device.

**Comment by ajay-gh** [comment]
Nevertheless one of the comments above is right and it bears the solution. Apple sees your iOS version when you connect to the Appstore. And when this is somehow foreseen by the developer, user of the last iOS version(s) get the latest App version, and users of older iOS version are asked "would you like to download the latest version for your iOS version"... Obviously the developer has control over what is available to whom - and this wasn't done for Joplin. In the problematic case described here above, the update of the App for users of iOS 12 should simply have been blocked in the first place. 
The solution, the dev differentiates the downloads (as described before), then users of iOS12 remove the new App which causes the problem, and downloads Joplin again. This time Apple will present the choice of either downloading the latest app or the working app.
I hope this helps. Best

**Comment by laurent22** [comment]
As I mentioned I've already checked. If you know more, perhaps you can provide a screenshot showing what screen I should look for and what option I should change? Because I've searched and couldn't find anything.

**Comment by Daeraxa** [comment]
The only information I can find on it is that if you upgrade the minimum version then you can enable last compatible versions for download. 
Bear in mind that I have no knowledge of how apple dev accounts work here but the way I understand it is:
- Dev releases app 1.0 with min version of ios12
- Dev updates app 2.0 and enables min version of ios13
- Users on ios12 can only download 1.0 app and ios13 users can only download 2.0
- Dev can go to `iTunes Connect → My Apps → app → App Store → Pricing & Availability → Last-Compatible Version Settings → Available Versions.` to disable the 1.0 app if they wished and now the ios12 users can no longer download the app at all.

Essentially in this case I imagine you would have to make 2 ios releases, one targeting 12 as min version as a republished version of the last known compatible joplin version then a second release republishing the current release with the upgraded min version for ios13+

Essentially everyone could upgrade to the middle step then ios12 users remain locked on that forever whilst new releases target only 13+ users.

I could be talking out of my behind of course but thats what a bunch of google-fu has led me to believe.

**Comment by laurent22** [comment]
Thanks @Daeraxa that makes sense, I'm going to try that.

**Comment by laurent22** [comment]
Please give a try to the latest 2.5.3 in the App Store and let me know if it fixes the problem.

**Comment by bmecchi** [comment]
IT WORKS!
Thank you very much, @laurent22.
Your efforts and kindly attention very appreciated.

**Comment by snakyjake1** [comment]
> IT WORKS! Thank you very much, @laurent22. Your efforts and kindly attention very appreciated.

Whew !!!!!!!!!
