### ISSUE TITLE
Sync fails on Android after updating to version 2.6.1

### ISSUE THREAD

**Issue by bacteriostat** [laurent22/joplin#5673]
I have filesystem sync enabled and after upgrading to the new joplin version, sync fails with the following error:

`Error: Could not upgrade from version 0 to version 1: Error: File 'storage/emulated/0/Documents/Notes/.sync/version.txt' does not exist and could not be created, or it is a directory.`

## Environment

Joplin version: 2.6.1
Platform: Android
OS specifics: Stock Android 11

## Steps to reproduce

1. Enable File System Sync
2. Open the app and wait for it to synchronize or manually tap synchronize button in navigation drawer

## Describe what you expected to happen
Notes should sync

## Log screenshot from the app
![Screenshot_20211104-100943](https://user-images.githubusercontent.com/32611672/140259071-8c897773-ee55-4c26-8739-4a1f67c7f34e.png)

**Comment by ttyS4** [comment]
Just to confirm this is a regression, downgrading to 2.5.5 helps.

**Comment by roman-r-m** [comment]
I suspect this is related to RN upgrade which landed in 2.6

**Comment by BeatLink** [comment]
Any updates on this?

**Comment by bacteriostat** [comment]
Don't want to sound rude but shouldn't this bug be higher priority? Syncing is an important functionality IMO.

**Comment by BeatLink** [comment]
I agree that this should be a higher priority. With this bug unsolved, the mobile application is all but useless for anyone using filesystem sync

**Comment by EricBrunel** [comment]
I saw that version 2.6.3 of the mobile app had been released. Did anyone with this issue try it? Is there any improvement?

**Comment by bacteriostat** [comment]
@EricBrunel Nope, the issue remains.

**Comment by BeatLink** [comment]
I confirm, the issue remains. My only fix for now was to install the older version from google play

**Comment by corona6** [comment]
I have same error.

`.sync/version.txt`
```
2
```

`.sync/readme.txt`
```
2020-07-16: In the new sync format, the version number is stored in /info.json. However, for backward compatibility, we need to keep the old version.txt file here, otherwise old clients will automatically recreate it, and assume a sync target version 1. So we keep it here but set its value to "2", so that old clients know that they need to be upgraded. This directory can be removed after a year or so, once we are confident that all clients have been upgraded to recent versions.
```

Joplin version: 2.6.3
Platform: Android
OS specifics: Android 11

**Comment by callahan22** [comment]
I'm having the same issue, however, I can cause it and resolve it by setting up the config differently on the phone.

Essentially, I have an external Storage set up on the Nextcloud instance which points to a sub folder on a share on my NAS. All accessible on Nextcloud using the Joplin account I have set up on Nextcloud for this purpose.

If I set the WebDAV path in the Android app as: https://nextcloud.myserver.com/remote.php/dav/files/_svc_joplin, the app will sync fine and the temp/lock folders along with the notes, will be uploaded to the Joplin user space on Nextcloud. If I change the WebDAV path on the phone to : https://nextcloud.myserver.com/remote.php/dav/files/_svc_joplin/Joplin (which is where I want to point it to so that the notes are stored on my NAS), I get the error you are talking about here. I have also included the debug log in case that helps to resolve the issue.

For ref, the Joplin account has full access to the external storage. I can log onto the Nextcloud instance as the Joplin user, navigate to the External mounted storage and create/delete files folders manually so I don't know why the app has an issue doing it. I did see in some You Tube vids that there was a Joplin web api app you could install in Nextcloud but that doesn't seem to be available anymore so I assume it's not needed.

If anyone has any suggestions of a fix to this issue, I'd appreciate it!
[syncReport-1641155783193.txt](https://github.com/laurent22/joplin/files/7799776/syncReport-1641155783193.txt)

**Comment by BeatLink** [comment]
Then again, maybe this issue should be closed in favor of https://github.com/laurent22/joplin/issues/5779. It seems most of the conversation is happening there anyways
