### ISSUE TITLE
Better support for editing lists, 

### ISSUE THREAD

**Issue by ho1ger** [laurent22/joplin#568]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile

### Idea / Improvement

Better support for editing lists in Joplin would be highly appreciated. 

#### Nesting

* When editing a list
* pressing "tab" in a new line
     * should result in nesting the list
     * like this.

#### Checkboxes on Enter

* [ ] When editing a list with check boxes, 
* [ ] pressing enter should result in a new line with a check box, 
* not just in a new bullet.

**Comment by X-Ryl669** [comment]
If you want to do a todo list, currently, it's very troublesome. You have 2 ways to do it, and both are painful.

1) Using tasks (for each item, you need to create a new task so that's 2 click + 1 touch + enter text per item)
2) Using a note + markdown (for each item, you have to write "- [ ]" which is painful since you need to switch keyboard state, and well, not intuitive either for newbies).

A better way could simply to add a "list" mode, in addition to `new task`, `new note` where each paragraph is a list item (as specified above)

**Comment by laurent22** [comment]
This has been implemented in one of the recent versions.

**Comment by X-Ryl669** [comment]
Nope, just downloaded version 1.0.129 on Android and it does not work (or it's not clear)
Maybe I'm missing something ?

**Comment by laurent22** [comment]
It's on desktop, on mobile it cannot currently be implemented due to buggy text input in React Native.

**Comment by rhklite** [comment]
This issue still persists for me. 

I'm on Ubuntu 16.04, desktop.
I downloaded the appImage from the README.txt file at [this link](https://github.com/laurent22/joplin/releases/download/v1.0.120/Joplin-1.0.120-x86_64.AppImage)
