### ISSUE TITLE
Bold Text is Green When Using Dracula as the Theme.

### ISSUE THREAD

**Issue by Ryonez** [laurent22/joplin#5681]
In the current state bold text are changed to green color while the normal text is white in color.

Windows:
![image](https://user-images.githubusercontent.com/16157130/140605258-d2dffe87-d674-4237-951e-8baa20eec587.png)
Android:
![94b2b5a0-f099-4ef5-9b2a-dd9e75fe72dc](https://user-images.githubusercontent.com/16157130/140605286-a9cb4563-1b41-4283-9a3e-b4aa07a06056.jpg)

## Environment

Joplin version: Windows - Joplin 2.5.10 (prod, win32), Android -  Joplin 2.4.3

## Steps to reproduce

1. User the Dracula Theme
2. Write some bold text
3. ?
4. Profit

## Describe what you expected to happen
The color not to deviate from the rest of the text.

**Comment by special0star1** [comment]
You can set your favorite colors.

strong { font-weight: bold; color:#B3ACA2; }

**Comment by jovial-snyder** [comment]
Looks like it has not been working correctly for probably more than one theme since December 21: https://github.com/laurent22/joplin/commit/46438a588881f4cbedb1aea53b90089097869fc5#diff-15a6101371e0d04a189c70a76a288d4e91f42e8d91680345bf00621e19b710a4

Adding 
`strong { font-weight: bold; color:#50fa7b; }`
to the custom stylesheet fixes it.
