### ISSUE TITLE
iOS Sync Date Is Incorrect

### ISSUE THREAD

**Issue by JRLBell** [laurent22/joplin#5697]
## Environment

Joplin version: 12.5.3
Platform: iOS
OS specifics: iPhone 12 Pro Max 14,8,1

## Steps to reproduce

1. Press the Synchronise (also misspelled on the app) menu item at bottom of menu bar
2. 
3. 

## Describe what you expected to happen

I expect the date to be today's date. Today is 11/09/2021, date showing is 09/11/2021. Yesterday, it was showing 08/11/2021.  I'm not sure that is progress. Recently created notes exist and are synchronized. So, synchronization is working, it's just the date that is incorrect.  Date is correct on iPhone, other apps, etc.

## Logfile

I don't know how to get a log file from on the iPhone.  I see no place to see a log file.

**Comment by Daeraxa** [comment]
There is nothing wrong with the data, you are aware that other date formats exist? You have it set in DD/MM/YYYY rather than what I presume you want which is MM/DD/YYYY. You can change that in your config.
Also 'Synchronise' is not an incorrect spelling, the entire world doesn't work on American spelling.
