### ISSUE TITLE
Infinite note conflicts if client and server time is different

### ISSUE THREAD

**Issue by frego** [laurent22/joplin#5738]
Here is my setup:
- Private joplin server running the latest version (2.5.5).
- 3 thick clients: osx (2.5.12), windows (2.5.12) , linux (2.5.12).
- 2 android clients synching (2.4.3).

OSX & Windows are on Europe/Paris timezone.
Linux was on Europe/Vatican timezone.

Steps to reproduce:
- Create a new note on linux with system set to timezone Vatican, sync.
- Sync on OSX or Windows, the note appears.
- The note duplicates on OSX and Windows each time there a new sync creating a high number of conflicts. Overtime and before I noticed, I had over 3000 conflicts.

Problem solved changing the zone Europe/Vatican to Europe/Paris on my linux.

**Comment by laurent22** [comment]
We only use UTC time so the time zone wouldn't make any difference. However if the actual time was incorrect, then yes it would be a problem, but there's not much to do since we rely on timestamps for sync. By default the apps will try to use the server time though, but if that fails they'll use the device time.

**Comment by frego** [comment]
My server timezone is UTC.

The duplication madness stopped after I switched to Europe/Paris instead of Europe/Vatican. Before the switch, the time showed was one hour ahead for Europe/Vatican, which should not be. Vatican should also be UTC+1 during winter time, as for Paris.

The conflicts was probably generated because for Europe/Paris, the note created from Vatican was always in the future.

Why then Joplin clients did not use the server time?

**Comment by laurent22** [comment]
Sorry I'm mistaken actually, it's only for the lock mechanism that the server time is used, otherwise it's just device time everywhere.

Don't know about the time zones, but we only store the time as the number milliseconds since 01/01/1970 in UTC, so changing the time zone would not have any effect. Actually if there was such a major bug we'd be flooded with constant bug reports about it beause it would happen every time someone goes to a different country with Joplin on their phone.

**Comment by frego** [comment]
Alright, closing the issue then.

**Comment by laurent22** [comment]
And "date -u" shows the same time in all devices?

**Comment by roman-r-m** [comment]
Yeah, the clocks were out of sync, so not a time zone issue really.

Somehow I was expecting linux to sync time out of the box

**Comment by roman-r-m** [comment]
Sorry for the (somewhat) false alarm.

I suspect the issue might be not due the client-sever clock difference but rather clentA-clientB clock mismatch.
Though I've checked again and in that test all 3 clocks were different.
