### ISSUE TITLE
Sync to selfhosted Joplin-Server fail after upgrade to 2.6.2

### ISSUE THREAD

**Issue by monnypython** [laurent22/joplin#5754]
Hi, since the update of Joplin-Desktop (WIN 10) to 2.6.2 the synchronization with my Joplin-Server instance no longer works. The sync works fine on my Android with Joplin 2.6.1. I didn't make any changes on the server. Sync does not work in safe mode either.

## Environment

Joplin version: 2.6.2 
Platform: WIN 10
OS specifics: 

## Steps to reproduce

1. Update Joplin Desktop
2. Try to Sync fails with the following Message:
![image](https://user-images.githubusercontent.com/42573701/142573741-dea7a10f-f1c1-4f64-81d9-e33bc2759879.png)

3. 

## Describe what you expected to happen
Synchronization of the notes as in 2.5.12 and on my Android phone.

## Logfile
[-1637302404885.log](https://github.com/laurent22/joplin/files/7568186/-1637302404885.log)

**Comment by dasrecht** [comment]
I've ran into similar issues being on Server Version 2.5.9-beta now with 2.6.11-beta everything works again. I guess there's a backwards compatibility issue between the 2.5.x and 2.6.x versions which would be understandable.

**Comment by laurent22** [comment]
Could you post the complete error message? It should be either in the Joplin Server log or app log https://joplinapp.org/debugging

**Comment by monnypython** [comment]
Here are the files according to the instructions from the documentation ("debugging"):
[-1637314885941.log](https://github.com/laurent22/joplin/files/7569287/-1637314885941.log)

Steps for logfile-content (because logfile is currently to big):
1. close Joplin
2. remove log.file
3. start Joplin
4. wait until Sync-Error is present
5. close Joplin
6. move logfile to github
7. 
[log.txt](https://github.com/laurent22/joplin/files/7569381/log.txt)

**Comment by laurent22** [comment]
Ok it's because you need to upgrade Joplin Server: https://discourse.joplinapp.org/t/pre-release-v2-6-is-now-available-updated-18-nov/21821

But I need to check why it's sending back an HTML page instead of JSON object.

**Comment by monnypython** [comment]
@dasrecht Thanks for the hint! 
@laurent22 OK. After changing my docker-compose.yml from "...:2.5.8-beta" to "latest" and pulling new image i get a "502 bad gateway"....

The Server can not start because "Auto-migrating database" fails :/:

![image](https://user-images.githubusercontent.com/42573701/142609281-3a281501-cddd-4768-874f-baa775b026b2.png)

**Comment by laurent22** [comment]
See here for this error: https://discourse.joplinapp.org/t/potential-breaking-change-in-next-joplin-server-update-2-5-10/21444

**Comment by monnypython** [comment]
Thanks for your help!
I'll take a look at this tonight and then give you a quick feedback. I am not sure now whether the ticket should be closed. So I leave the decision up to you.

Short question:
Shouldn't the information for the required server update also be in the comments in the desktop release notes?

**Comment by laurent22** [comment]
I try to limit the info in the dialog box to the essential because there's not enough space. The complete info for pre-releases is always in the forum, and in general if you're self-hosting Joplin Server it's best to at least watch the /news category, since this is where I'll announce any breaking change.

**Comment by monnypython** [comment]
OK. Thanks for the hint. I did not know that...
Now that I have deleted the duplicates according to the instructions, everything works fine again.
Thanks for your help.

**Comment by calvinbui** [comment]
i've started hitting this issue too since upgrading my android app to 2.6.3 and decided to downgrade my client.

server version 2.6 is still beta which is why I haven't upgraded to it. I've been sticking to the `:2` docker tag which is the latest stable (2.5.1). this is set to update automatically for me each night.

likewise in the past when I've used the `:latest` docker tag,  there was a time when it was incompatible with the stable version of android and I had to upgrade all my clients to a beta version too.
