### ISSUE TITLE
Web Clipper doesn't clip Article date

### ISSUE THREAD

**Issue by notehoarder** [laurent22/joplin#5767]
Web Clipper doesn't clip Article date.

90% of time, when using "Clip Simplified Page" the Article date is not clipped.  
Can adjustments be made to fix?

"Clip complete page" is too much - ads etc...
"Clip selection" - time consuming to highlight

Using Web clipper 2.1.3 - Brave - Mac

**Comment by Daeraxa** [comment]
What do you mean by article date? Do you have an example?

**Comment by tomasz1986** [comment]
> What do you mean by article date? Do you have an example?

Not the OP, but I've always had the same issue with the Clipper.

You can try with the following example: https://kitchenstewardship.com/monday-mission-homemade-yogurt-the-easy-way.

The line containing the date and the author isn't clipped.

![image](https://user-images.githubusercontent.com/5626656/142801936-e884e836-26c9-43ef-bb26-96992f12e692.png)

I usually always go to the note and add it manually, because I personally consider both the date and the author essential information, especially when it comes to news articles.

**Comment by notehoarder** [comment]
Sorry replied to this on Joplin forums earlier:
Sample articles where clipper doesn't clip article date...

https://americanmilitarynews.com/2021/11/space-tourisms-arrival-spurs-us-rules-for-inevitable-mishaps/

https://reclaimthenet.org/duckduckgo-introduces-new-app-tracking-protection-for-android/

https://www.zerohedge.com/political/well-never-give-protests-erupt-across-europe-over-govt-covid-tyranny
