### ISSUE TITLE
gnome41 cannot  show joplin icon

### ISSUE THREAD

**Issue by newyorkthink** [laurent22/joplin#5802]
![image](https://user-images.githubusercontent.com/87791643/143792425-f76d7e6f-3c40-4627-8c4f-33f55791d7e1.png)

![image](https://user-images.githubusercontent.com/87791643/143792448-f669485d-75f4-484e-8605-9a9b79ee783a.png)

**Comment by CalebJohn** [comment]
How did you install Joplin? Did you use the [recommended method](https://github.com/laurent22/joplin#desktop-applications)? Too me it looks like you're missing the .desktop file which gnome uses to get the icon. The recommended installation method creates this file for you, otherwise you'll need to do it manually.

**Comment by newyorkthink** [comment]
> 

I not installed joplin. I used to joplin appimage file.

**Comment by CalebJohn** [comment]
If you want use the AppImage in that way, you'll need to install the [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) application to integrate it with your system. From my understanding this is the recommendation from the AppImage community. 

Your alternative is to use the Joplin recommended method above.
