### ISSUE TITLE
he Joplin extension is not available on this tab due to: Missing host permission for the tab

### ISSUE THREAD

**Issue by johandeclercqdemocon** [laurent22/joplin#5842]
example url : hln.be

## Environment

Joplin version: 2.5.10
Platform: 
OS specifics: ubuntu 20

## Steps to reproduce

1. add joplin externsion to firefox 94 or chrome 96.0.4664.45
2. grant permission in joplin app
3. you will see the error appearing when you try to use the extensions. 
 
chrome : The Joplin extension is not available on this tab due to: tabsExecuteScript: Cannot load {"file":"/content_scripts/JSDOMParser.js"}: Cannot access a chrome:// URL

firefox : he Joplin extension is not available on this tab due to: Missing host permission for the tab

**Comment by CalebJohn** [comment]
@johandeclercqdemocon That is due to browser permissions on "special" tabs. The extension will work properly on other websites. You can see [this forum post](https://discourse.joplinapp.org/t/the-joplin-extension-is-not-available-on-this-tab-due-to-missing-host-permission-for-the-tab/21371) for more information.
