### ISSUE TITLE
Editor loses cursor focus when Ctrl+F search is closed

### ISSUE THREAD

**Issue by steel-steven-87** [laurent22/joplin#5850]
When you search for a string and close the search, the editor loses focus. This is a major annoyance when working with Joplin because it breaks the ability to navigate the opened note using the keyboard. The user is forced to use the mouse to click on the editor to continue editing.

This seems to be a thing where Joplin deviates from any other text editor out there. I have looked at different editors, e.g. notepad, VSCode, KWrite, LibreOffice Writer or just editing text here in a browser when submitting this bug. All of the other editors seem to allow the user to use Ctrl+F to jump to a specific part of the text and retain the cursor focus when the search menu is closed.

I think fixing this issue would make Joplin more consistent with the standard behavior of other editors and make it more "keyboard friendly" which is something that any power user would appreciate.

## Environment

Joplin version: 2.5.12
Platform: Windows/Linux

## Steps to reproduce

1. Open a note in edit mode.
2. Open the search using Ctrl+F.
3. Type in a word that has at least one match in the note.
4. When the matching word is found and highlighed, press Escape key to close the search.

The editor loses keyboard focus.

## Describe what you expected to happen
When the search is closed, the editor should retain the focus and the keyboard cursor should be at the position of the matching word that was highlighted just before the search was closed.

**Comment by ken1kob** [comment]
This is an enhancement rather than a bug fix. I agree with your suggestion. Seamless keyboard operation is essential for a note-taking app.

To implement this, in addition to focusing, the editor's cursor should be moved. In the current Joplin's Markdown Editor, its cursor is not moved for each search. So, it's the change of the UI, which needs some discussions.

I think there are three options:
1. Set a selection using the current highlighted search result.
2. Move a cursor to the tail of the current highlighted search result.
3. Do nothing (close this issue).

My recommendation is option 1 or 2. Option 1 is the same behavior with WYSIWYG Editor, VS Code and so on.

@laurent22, could you ask your opinion?

**Comment by laurent22** [comment]
Yes option 1 would indeed be good, especially if it's consistent with what other editors are doing.

**Comment by ken1kob** [comment]
I see. I've created a PR #5919 which implements option 1.
