### ISSUE TITLE
Webclipper does not create embeded video

### ISSUE THREAD

**Issue by foxmask** [laurent22/joplin#586]
### Operating system

- Linux

### Application

- Desktop

trying to capture with the webclipper https://unodieuxconnard.com/2018/05/03/priere-de-ne-pas-enerver-le-legionnaire/ where a youtube video is present, the preview of the simplified  (and also with complete) version displays the embeded video but the render in joplin does not display it at all

**Comment by foxmask** [comment]
embeded video in markdown is [explain here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#youtube-videos)

this will give 
```
[![video](https://img.youtube.com/vi/8GGG4TjcDFQ/0.jpg)](https://youtu.be/8GGG4TjcDFQ)
```

**Comment by laurent22** [comment]
I think video is out of scope of this project because even a small video these days can be 10-20 MB, and users could even accidentally clip 1GB videos or more, which wouldn't work on mobile and consume too much space.

Linking to YouTube could be an option but I'm not a big fan of it because then the data is not permanent. 2 years from now, the notes will have links to deleted content. Basically I'm not sure there's a good solution so this is probably out of scope.
