### ISSUE TITLE
Suggestions on tray icon function optimization 关于托盘图标功能优化的建议

### ISSUE THREAD

**Issue by yimisunrise** [laurent22/joplin#5863]
This is not a BUG, it's a suggestion!
Currently, you can only right-click to open Joplin. Hopefully, the tray icon supports the single mouse button to open Joplin directly.
Thank you very much!

--------------------------------

这条不是BUG，是建议！
当前只能右键打开Joplin，希望托盘图标支持鼠标左键单机直接打开Joplin。
谢谢！

**Comment by yiyinyiyang** [comment]
Maybe there is something wrong with your computer, I can open Joplin with the left mouse click on the tray icon, test environment window10  jopin v2.5.12

**Comment by Daeraxa** [comment]
> This is not a BUG, it's a suggestion!

The GitHub repository is only for bugs, as the new issue button shows these options. Feature requests are for the forums which the bottom item links to
![image](https://user-images.githubusercontent.com/58074586/146183623-c24e6c06-c30e-4979-ba18-86b498dbd13f.png)

However... you might want to include which OS you are using because the behaviour can differ greatly on different OSs, on Linux Mint w/ cinnamon desktop a left click offers a menu to open or quit (same as right click) which is consistent behaviour with other tray icons.

**Comment by yimisunrise** [comment]
> > This is not a BUG, it's a suggestion!
> 
> The GitHub repository is only for bugs, as the new issue button shows when it gives you these options. Feature requests are for the forums which the bottom item links to ![image](https://user-images.githubusercontent.com/58074586/146183623-c24e6c06-c30e-4979-ba18-86b498dbd13f.png)
> 
> However... you might want to include which OS you are using because the behaviour can differ greatly on different OSs, on Linux Mint w/ cinnamon desktop a left click offers a menu to open or quit (same as right click) which is consistent behaviour with other tray icons.

Thanks for the reminder!I'll pay attention next time!

**Comment by yimisunrise** [comment]
> Maybe there is something wrong with your computer, I can open Joplin with the left mouse click on the tray icon, test environment window10 jopin v2.5.12

My operating system is Deepin 20.3 and indeed left clicking on the Joplin icon on my system did not respond.I thought it was intentional, so I suggested it.
----------
我的操作系统是deepin 20.3，确实在我的系统上左键点击Joplin图标没有任何反应。我还以为是故意这样设计的，所以提了这建议。
