### ISSUE TITLE
Desktop: Export of mermaid render no longer works on 2.6.4+ 

### ISSUE THREAD

**Issue by graphit0** [laurent22/joplin#5879]
PDF and HTML File export of mermaid renders stopped working on 2.6.9 and shows up as plain code

![image_2021-12-18_23-45-34](https://user-images.githubusercontent.com/44114323/146658923-6ddcfeb2-204f-4969-afb8-b1ad3404acdf.png)

## Environment

Joplin version: 2.6.9 
First appears at 2.6.4: 2.6.2 is unaffected
wonder if commit 98ed2be518d2d390199e18ae8a25a8882a8eacff might have something to do with it
Platform: prod, win32; prod, linux is untested
OS specifics: Tested on Windows 7, [reported on Mac OS 12.0.1](https://discourse.joplinapp.org/t/mermaid-rendering/22456?u=graphit0) as well

## Steps to reproduce

1. Create a note
2. paste mermaid graph 
```mermaid
flowchart TD
a --- b
```
3. Export the note as PDF or HTML File
4. Open the note and see unrendered mermaid code

## Describe what you expected to happen
The rendered graph to be present in exported document

## Notes
- PlantUML, katex, tables, checkboxes, etc are unaffected
- Mermaid graphs render fine in the Joplin view mode
- HTML Directory export seems to be unaffected

## Logfile
```
Export HTML result:  
{warnings: Array(0)}
warnings: []
[[Prototype]]: Object
constructor: ƒ Object()
hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()
toString: ƒ toString()
valueOf: ƒ valueOf()
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
__proto__: (...)
get __proto__: ƒ __proto__()
set __proto__: ƒ __proto__()
```

**Comment by tessus** [comment]
To also put my findings here:

I have reverted both Mermaid commits (06e427fc5a6310502bfd924a0c6796ce53af884c and c499473467e2e25aaee0a610612251d655e4caf1) for testing and it still does not work, so it has nothing to do with these 2 commits.

Unfortunately I don't know what the culprit is, but at least I could eliminate my 2 commits related to Mermaid.

**Comment by Daeraxa** [comment]
Results of me playing around:

It is broken in the same commit as the other issue, the html pack commit https://github.com/laurent22/joplin/commit/98ed2be518d2d390199e18ae8a25a8882a8eacff

Did some more playing and got rid of just the last function and got the graph back, so it is something in there or something that it calls upon. (commented out the whole last `public async close()` function and change it to just `async close() {}`)

Played a bit more and changed this line https://github.com/laurent22/joplin/blob/41cb47b6c849dbf98ae924582d00be196188032a/packages/lib/services/interop/InteropService_Exporter_Html.ts#L35 to false and it works again - because it then bypasses the extra code in that function I mentioned before.
`this.packIntoSingleFile_ = 'packIntoSingleFile' in options ? options.packIntoSingleFile : false;`

Is there a reason why exporting to PDF needs to go via the additional code added for the HTML single file packing? The change notes imply this should only fire for exporting as a single HTML.

**Comment by tessus** [comment]
> Is there a reason why exporting to PDF needs to go via the additional code added for the HTML single file packing? 

Not that I can think of, but I didn't make that change. I remember a few issues we had a while back with toc not working when certain unicode characters were used in headings. But it had nothing to do with single file packing.

**Comment by laurent22** [comment]
Hmm, yes if it can't be fixed in htmlpack we can probably just bypass it for PDF export. It's indeed not necessary in this case.

**Comment by yiyinyiyang** [comment]
In the 2.5.12 version of the test, working fine, but in the latest 2.6.9 version, when exporting PDF and html mermaid render effect will not work.
