### ISSUE TITLE
Scroll jump when checkbox is toggled

### ISSUE THREAD

**Issue by shinglyu** [laurent22/joplin#5890]
## Environment

Joplin version: 2.6.10
Platform: macOS
OS specifics: macOS Catalina 10.15.7

## Steps to reproduce
1. Preference > Theme > Solarized Light (Important!)
1. Create a note like so:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit.

---
- [x] 1
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [x] 6
- [x] 7
- [x] 8
- [x] 9
- [x] 10
- [x] 11
- [ ] 12
- [ ] 13
... # Add as many items as needed until you need to scroll
```
2. Scroll the left editor pane past `- [ ] 1`
3. Check or uncheck a checkbox

## Describe what you expected to happen
The editor and preview pane should not scroll. However the editor and preview jumps up one line whenever I check or uncheck a checkbox. 

I noticed that it has to do with the Theme. In Solarized Light the `---` and `***` divider is rendered as:

<img width="795" alt="Screenshot 2021-12-20 at 14 23 47" src="https://user-images.githubusercontent.com/3250983/146774397-0c269c7e-a6c7-4588-a986-45685663a0f6.png">

But in default theme Light, it's like: 

![Screenshot 2021-12-20 at 14 23 55](https://user-images.githubusercontent.com/3250983/146774441-490bd0fe-9c2d-4725-8e19-0fadb7793c35.png)

That extra line rendered in the editor pane causes the jump.

**Comment by laurent22** [comment]
@ken1kob, I think there's a regression due to the scroll update here as well.

I had this issue before - the problem is that when a checkbox is clicked on the Preview, the note text is updated too, which in turn updates the preview again, and that makes it update the scroll position. If I remember well I had fixed it by disabling that unnecessary second update - it's unnecessary because the checkbox is already updated on JS side. And since there was no longer an update, scrolling also didn't get changed.

Perhaps it's a matter of replicating that behaviour in the new scroll code?

In fact for me it happens even with the default light theme, with this text specifically:

```markdown
Lorem ipsum dolor sit amet, consectetur adipiscing elit.

---
- [x] 1
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [x] 6
- [x] 7
- [x] 8
- [x] 9
- [x] 10
- [x] 11
- [ ] 12
- [ ] 13
- [ ] - [x] 1
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [x] 6
- [x] 7
- [x] 8
- [x] 9
- [x] 10
- [x] 11
- [ ] 12
- [ ] 13
- [x] 1
- [ ] 2
- [ ] 3
- [x] 4
- [x] 5
- [x] 6
- [x] 7
- [x] 8
- [x] 9
- [x] 10
- [x] 11
- [x] 12
- [ ] 13
- [x] 1
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [x] 6
- [x] 7
- [x] 8
- [x] 9
- [x] 10
- [x] 11
- [ ] 12
- [ ] 13
- [x] 1
- [ ] 2
- [x] 3
- [ ] 4
- [ ] 5
- [x] 6
- [x] 7
- [x] 8
- [x] 9
- [x] 10
- [x] 11
- [ ] 12
- [ ] 13
- [x] 1
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [x] 6
- [x] 7
- [x] 8
- [x] 9
- [x] 10
- [x] 11
- [ ] 12
- [ ] 13
- [x] 1
- [ ] 2
- [x] 3
- [x] 4
- [ ] 5
- [x] 6
- [x] 7
- [x] 8
- [x] 9
- [x] 10
- [x] 11
- [ ] 12
- [ ] 13
```

**Comment by ken1kob** [comment]
> Perhaps it's a matter of replicating that behaviour in the new scroll code?

The cause is CodeMirror's layout uncertainty. When CodeMirror is updated, the layout is re-calculated, and its result slightly differs. Especially, the translation between lines and pixel heights is affected.
  - Ref. [heightAtLine or any line's top position which out of viewport might not accurate · Issue #4045 · codemirror/CodeMirror](
https://github.com/codemirror/CodeMirror/issues/4045#issuecomment-223401948)
  - This cause is the same with the minor problem reported in [the comment in issue#5918](https://github.com/laurent22/joplin/issues/5918#issuecomment-1002357960).

By saving the scroll position before the update and restoring it, the problem can be suppressed. PR #5941 fixes the problem.

> I had this issue before - the problem is that when a checkbox is clicked on the Preview, the note text is updated too, which in turn updates the preview again, and that makes it update the scroll position.

In the current sync scroll implementation, things go as the above. However, if CodeMirror layouts the result regardless of check box on/off, the same scroll positions are taken, and there is no chance of scroll jumps. So, PR #5941 doesn't stop writing the html back to Viewer.

**Comment by ken1kob** [comment]
By further tests, I found some rare cases of small jumps still exist.

To suppress them, it is needed to minimize the layout updates of CodeMirror. The commit 2eb5bae updates only the line of the clicked checkbox using `CodeMirror.replaceRange()` instead of the whole document.

After the commit was applied, no such scroll jumps have been observed in my tests.
