### ISSUE TITLE
"code" query parameter is missing

### ISSUE THREAD

**Issue by matyle** [laurent22/joplin#5910]
when I use the onedrive for Edu , I cannot  auth joplin. It shows ""code" query parameter is missing". How can I fix it

**Comment by Bobby-Hua** [comment]
Hi! I have the same issue and will really appreciate a fix! Someone suggested using a personal account, but I have to keep my oneDrive edu on sync. Looks like when both my personal and edu accounts are on sync, I still get the same issue.

**Comment by Mingeax** [comment]
In fact, it is a problem about edu organization. Ordinarily user need to gain authorization from the edu organization to access onedrive API by edu account. 

For more infomation, you can have a look at the DevTool of the page with ' "code" query parameter is missing ', and see the request header under the network option.You would find some message such as"Using application 'Joplin' is currently not supported for your organization *** because it is in an unmanaged state. An administrator needs to claim ownership of the company by DNS validation ...". It can explain all.

**Comment by Bobby-Hua** [comment]
Thanks for the explanation! That makes a lot of sense.

**Comment by imnuke** [comment]
> Ordinarily user need to gain authorization from the edu organization to access onedrive API by edu account.

Hello, thanks for your explanation, but is there any way I can gain authorization from my edu organization to access onedrive API by edu account?
