### ISSUE TITLE
On the desktop app, create a screen that list all the resouces

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#592]
On the desktop app only, create a new screen that lists all the resources. Each row in the list would have:

- Resources title
- Resource file size
- A "View" link that opens the resource in an external viewer
- An marker showing whether the resource is linked to at least one note or not
- A "Delete" button

The goal is to be able to manually manage resources and delete them if they are no longer needed.

It should also be possible to sort by file size so that the largest resources can be manually deleted if not really needed.

More info in this thread: https://discourse.joplin.cozic.net/t/setting-the-delay-before-deletion-of-orphan-resources/210

**Comment by borisrorsvort** [comment]
Since the goal is to identify and cleanup resources, the ui should probably emphasize this more. The table list seems a rather poor ux metaphore for this. 
The first question that comes to my mind is, why the user should care? Can't we auto delete the resource if it's not used anymore? imho that's fit most of people usage.
If we really need to viz that process, a more thumbnail grid based approach with previews seems more appropriate, and default filters on the unused one.
But if possible i'd go for the seamless approach

**Comment by alanfortlink** [comment]
So hey, is that okay if I work on this issue?
