### ISSUE TITLE
[Desktop] Sort & new note/todo buttons do not reappear

### ISSUE THREAD

**Issue by roman-r-m** [laurent22/joplin#5953]
[Reported by atomlib on discord](https://discord.com/channels/610762468960239627/610762468960239629/927461889053712384):

> Typically when I place cursor inside the Search… field to type something, these buttons on the right disappear to make space for the input. After I remove input focus from the Search… field, they reappear again.

> However, if I go to View → Change application layout while I had input focus in the Search… field, the buttons do not reappear on focus being lost. They will appear only if I place the cursor inside the field and remove the focus from the input field.

**Comment by asrient** [comment]
Hi, I'm interested in working on this issue. Is it up for the grab?

Also I did some research on the issue, seems like when we open pages like layout-editor and settings the search bar is remounted without calling `onBlur` before. Therefore local states (like the query str) of the component are lost. So I think there are 2 ways to solve this: 
- Either exit the search whenever these pages are opened  
- Or store and retrieve the query string from the `AppState` instead of the local state.

For option 1:
- we add a hook similar to componentOnMount and check if the current focusedField of AppState is search, which is actually false since the component just got remounted, if that's the case we exit the search.

**Comment by roman-r-m** [comment]
> Hi, I'm interested in working on this issue. Is it up for the grab?

Go for it.

**Comment by asrient** [comment]
Hi, 
The fix is here: [commit](https://github.com/asrient/joplin/commit/20124aed866478f6fc5d8219ac25ee2a6c176e03).
I will create a pull request soon. But since I found in the guidelines PRs without tests will be rejected. I was wondering since this is a relatively small fix if we can write unit tests for this. Can anyone tell me if tests are required for this and if so any resources or ideas about how to write a test for it. Thanks.

**Comment by roman-r-m** [comment]
I don't know if it's even possible to have unit tests for a change like that.

Maybe have a look at existing tests, see if there are any for this component or similar ones.
