### ISSUE TITLE
[request] support asciidoc

### ISSUE THREAD

**Issue by Zasch** [laurent22/joplin#60]
### Operating system

- [X] Windows
- [ ] macOS
- [X] Linux
- [X] Android
- [ ] iOS

### Application

- [X] Desktop
- [X] Mobile
- [X] Terminal

---

I'm a big fan of asciidoc and therefore would like to use it in joplin. Any chance you support asciidoc in a future release?

**Comment by laurent22** [comment]
Unfortunately it's unlikely that any other document formats will be supported. The reason is that it would be way too complex to have multiple notes with potentially different doc format for each note, and multiple text editors/viewers. So unless someone comes up with a smart way to support this, it probably won't be possible.

In terms of note editing the only thing that seems possible is a wysiwyg editor, but the backend would still be Markdown.

**Comment by laurent22** [comment]
Closed as this is unfortunately out-of-scope

**Comment by donbowman** [comment]
gitbook is somewhat similar in architecture (markdown etc) and has an integration w/ asciidoc + plantuml
https://github.com/GitbookIO/gitbook-asciidoc , https://www.npmjs.com/package/gitbook-plugin-uml
