### ISSUE TITLE
搜索不到正确结果

### ISSUE THREAD

**Issue by YouLe2016** [laurent22/joplin#6012]
## 问题描述
笔记中确实有对应记录，但却无法搜索出来。
大家也可以试试这两个词，是否真的搜索不出来

### 第一个
![image](https://user-images.githubusercontent.com/23033537/149438586-5a59eeb4-f125-4efc-8ecb-6234b0a2e922.png)
搜索结果：
![image](https://user-images.githubusercontent.com/23033537/149438784-5ea8095f-507e-4b44-bcdb-d55adae62f2f.png)
### 第一个
![image](https://user-images.githubusercontent.com/23033537/149438821-d6920fcc-a868-46bd-8e56-99b4f5dd9bfd.png)
搜索结果：
![image](https://user-images.githubusercontent.com/23033537/149438716-70f4176c-bf94-4d64-81f7-f5c3374ba58f.png)

## 版本信息
Joplin 2.6.10 (prod, win32)

客户端 ID: f13ebd1b73f44841a639bcccba9ec8f1
同步版本: 3
配置文件版本: 41
支持的密钥链: 否

修订: 98fba37

**Comment by graphit0** [comment]
For the record, the ongoing work on asian scripts search is documented here:
https://discourse.joplinapp.org/t/improving-search-with-asian-scripts/17457

Better support in Chinese is provided here: 
https://t.me/joplin_cn

自动翻译
作为记录，正在进行的亚洲文字搜索工作记录在此：https://discourse.joplinapp.org/t/improving-search-with-asian-scripts/17457

这里提供了更好的中文支持：https://t.me/joplin_cn

**Comment by jerrylususu** [comment]
From my experiments, this bug seems to be happen when there is no space between Chinese punctuation characters and numbers/words. If an additional space is added, then the search will work as intended. You can try with the following example. In which case 2, 4, 5 and 7 will work, but not for case 1, 3 and 6. 

```
1 无空格 no space：19990999
2 有空格 has space： 200001111

3 无空格 no space：（21111111）
4 前后空格 space before & after：（ 22222222 ）

5 english punctuation, no space: (DFS)
6 chinese punctuation, no space:（BFS）
7 chinese punctuation, space before and after:（ CSLR ）
```

Sadly, as currently Joplin seems to use the full text search ability provided by SQLite FTS, there is no easy fix. For users, here are 2 workarounds:
1. Always add space before & after Chinese punctuation characters.
2. Use SQLite browsers (such as DB Browser for SQLite) to manually query the notes.

For Joplin developers, it would be great if a slower but character-by-character search can be implemented, which doesn't use index but simple SQL, such as `SELECT * FROM "main"."notes" WHERE "body" LIKE '%keyword%'`. Also this slow search will not have advance features (such as multi keyword), but at least it can find notes that is not accessible using FTS search.

---
Chinese Translation

根据我的实验，看起来如果中文标点前后没有加空格的话，就会导致附近的词语也无法被搜索。这一问题的根源应该是 Joplin 搜索使用的底层技术：SQLite Full Text Search。这一全文搜索机制，对中文的索引优化不佳。在上文的示例中，2/4/5/7 行可以被搜索到，剩下的却不行。

作为用户而言，没有什么特别好的办法，可能只有：
1. 尽量避免使用中文标点。如果非要使用，就在前后都加空格。（对于现有的笔记，可能可以想办法批量替换）
2. 实在不行，就用数据库软件手动通过 SQL 查找笔记

作为开发者，可能可以实现一个不通过 SQLite FTS 的搜索机制，虽然可能慢了一些，但至少能搜出东西。
