### ISSUE TITLE
Resources still exist after deleting them or deleting the entire note (for Mac OS)

### ISSUE THREAD

**Issue by mhdhamouday** [laurent22/joplin#6031]
Files or Images in the resources folder is still existing after deleting them or deleting the entire note 

## Environment

Joplin version: 
Platform: macOS
OS specifics: Mac 12.1

## Steps to reproduce

1. Create a new note
2. Add an image to it.
3. Delete the image.
4. Check the resource folder /Users/username/.config/joplin-desktop/resources (you will find it)

Note: I have waited for more than two days and the deleted image still exists.

**Comment by Daeraxa** [comment]
Do you have note revisions turned on?

**Comment by mhdhamouday** [comment]
No note history is off (I have tried to disable it to test if it helps but the problem still exists)
I use the last version of Joplin (2.6.10).

**Comment by rejjjer** [comment]
I have the same issue, and the steps to reproduce are the same.

I use `Joplin 2.6.10, Linux AppImage`.

The attachments still exist in `~/.config/joplin-desktop/resources` after deleting a note.

The history feature is off.

I have an S3 bucket for synchronization. It's also full of dead attachments, which is frustrating.

**Comment by asrient** [comment]
Hi, I digged up a bit into the issue, these are the points I discovered:
- I think [note delete](https://github.com/laurent22/joplin/blob/dev/packages/lib/models/Note.ts#L729) function should be taking care of the resources too, which it does not currently. Since this is in core lib package I guess this issue should exist in every platform, not just macos.
- We can call the resource-delete func here but I'm not sure if we reuse resource files across all notes. Can someone confirm this? If so we cannot simply just delete all the resources, it might be used by other notes as well.

If this issue is still available? I want to work on it if so.

**Comment by Daeraxa** [comment]
Best not to work on anything that hasn't been triaged as a bug by the maintainers.

**Comment by mhdhamouday** [comment]
Yes, the problem still exists.
I don't think it's a good idea to reuse resource files across all notes, I have been now tested to add an image to a new note using the attachment button, then I create a new note and upload the same image. 
Result: resource folder has two images so Jophin doesn't reuse the resources in this case.

I tried to copy the same image from the first note by clicking on the copy button, then I paste it to the second note, I checked the resource folder and I found just one image there, so Jophin reuse the same resource in this case. 

I think Jophin should delete the resource file when deleting the note because it's can kill the privacy of Jophin because the users will not know that their resources still exist in the device & cloud after deleting them.

**Comment by asrient** [comment]
Thanks @mhdhamouday for checking this up, I hope the maintainers consider this a bug too since this can eat up a lot of space both locally and on cloud

**Comment by asrient** [comment]
My previous analysis was bit wrong, I'm just putting it here so that my previous comments don't create confusion. Resources are not directly deleted on note delete, I'm guessing this is done to support noteHistory feature. Instead we use a service every few minutes `ResourceService::deleteOrphanResources` to delete all resources that are not linked to any notes and and not been used recently that is been determined by `revisionService.ttlDays` setting, we are using this value even if `Note History` is disabled. This is where the confusion arrises. Since the default value is `90` even if note revisions are turned off they will get deleted after 90 days (unless user has changed the setting). I think if the note revisions feature is turned off we should not use that ttl. Sorry for the confusion before and spamming, I was looking at the wrong place, I'm still just getting started with the codebase 😅. By changing the `ttl` to few seconds I was able to confirm that unwanted resources deleted properly, so I'm guessing they will be deleted automatically after 90 days for most users.

**Comment by mhdhamouday** [comment]
@asrient Thank you very much! Now it's working when I set not history to 0.
