### ISSUE TITLE
Linux virtual memory size

### ISSUE THREAD

**Issue by eko-wibowo** [laurent22/joplin#6050]
### Joplin Version
Joplin 2.6.10 (prod, linux)

Client ID: 82332ea92d144ddfb5767ae32703e16f
Sync Version: 3
Profile Version: 41
Keychain Supported: No

Revision: 98fba37

### OS Release

PRETTY_NAME="Parrot OS 4.11"
NAME="Parrot OS"
ID=parrot
ID_LIKE=debian
VERSION="4.11"
VERSION_ID="4.11"

Running as a guest OS on virtualbox 6.1, host OS is windows 10

## Steps to reproduce

1. Open top
2. Open joplin
3. 

## Describe what you expected to happen

The system becomes slow and lagging after opening joplin, the amount of virtual memory swap seems super high. Is this expected?

## Logfile

https://pastebin.com/Du4X3Yea no error from the console

**Comment by laurent22** [comment]
Do you use any plugin?

**Comment by eko-wibowo** [comment]
I have no plugin, this is recent fresh install.

- no plugin 
![image](https://user-images.githubusercontent.com/2567321/150921659-74f57e92-551e-4ed5-ae21-e811e2da1b60.png)

is there any other log / dump that I can pull?

**Comment by roman-r-m** [comment]
Electron dev tools can take a memory snapshot but my guess it you won't see this excessive memory usage here.

I've just checked on my system (Manjaro, running on bare metal, not in VM) and I can also Joplin consuming 16-20G of virtual memory. Yet I do not see any performance issues.

This all makes me think that there may be something else going on. Maybe specific to running in VM.

**Comment by banan314** [comment]
Joplin is consuming 22G for me, the same version 2.6.10. I can confirm this issue, running Joplin causes a significant overall decline in performance of the system (Linux, Ubuntu-based, Pop OS).

**Comment by brianredbeard** [comment]
@banan314: 22G sounds like a lot and (were I to hazard a guess) you're calculating _virtual_ memory and not *resident* memory (e.g. in @eko-wibowo's screenshot above `VIRT` is not the column you want to note but `RES`).

Be careful though, even if you were to take all of the RSS values for Joplin and all of it's child processes and perform a summation on them this would still overestimate usage due to shared memory usage (`SHR` in the screenshot) and some other factors.

If you wanted to get a better "high water mark" than trying to guess from looking at `top` and using the basic GNU toolset try the following:

```bash
$ ps  -p $(pgrep -i -d, -f joplin) -o pid,comm,rss | awk '{RSSTOTAL += $3; print $0} END {print "\nTotal Memory:", (RSSTOTAL/1024), "MB"}'
    PID COMMAND           RSS
3521566 @joplinapp-desk 91740
3521570 joplin           1920
3521574 @joplinapp-desk 22732
3521575 @joplinapp-desk 23056
3521577 @joplinapp-desk  8068
3521609 @joplinapp-desk 52764
3521616 @joplinapp-desk 26636
3521624 @joplinapp-desk 167244

Total Memory: 384.922 MB
```
This first runs the command `pgrep -d, -f joplin` which grabs just the PIDs of all processes which have "`joplin`" (case insensitive) in the process name and returns them as a comma delimited string.  Then `ps` is run again feeding the list of pids into `-p` to isolate only those process ids in the result set and return just the `pid` ("process id"), `comm` ("command name"), and `rss` ("resident set size") fields.

This table is then fed into `awk` via a pipe, which sums the third column from each line and finally reports it (divided by 1024) to the user as "Total Memory: "

------
Alternatively your window environment may provide better system monitoring tools.  For example, when using `gnome-system-monitor` I see the following:

![Screenshot from 2022-02-17 14-22-47](https://user-images.githubusercontent.com/57542/154580984-a1dce680-24f8-4950-8c44-4fc2dd9248bf.png)
