### ISSUE TITLE
Javascript exception while writing notes

### ISSUE THREAD

**Issue by brandontan** [laurent22/joplin#6111]
## Environment

Joplin version: Joplin 2.6.10 (prod, darwin)

Platform: MacOS 
OS specifics: 12.1 Monterey M1

## Steps to reproduce

1. Not easily reproducible
1. Occurred during note taking , pasting large chunks of data into rich editor

Please see attached screenshot

## Describe what you expected to happen

Pasting large chunk of text or images into rich editor should not result in JS exception

## Logfile

![CleanShot 2022-02-06 at 12 18 43](https://user-images.githubusercontent.com/1005474/152667660-d014ca39-a6f9-48c3-918f-45544f7517fa.png)

**Comment by laurent22** [comment]
Could you provide more info to replicate this more consistently?

**Comment by brandontan-888** [comment]
It happened again. Currently, I have 900+ notes and is sync with my SSD drive. The screen will go white and freeze. I had to force quit it. 

It happened when a note is rich editor mode with lots of pasted content

**Comment by laurent22** [comment]
We'd need a JEX file to replicate the issue, and steps to follow - what text to copy and paste, how many times, how often, etc. Without any info it's very low priority.

**Comment by brandontan-888** [comment]
What is the JEX file? Please advise.

**Comment by brandontan** [comment]
What is the JEX file? Please advise @laurent22

**Comment by Daeraxa** [comment]
https://joplinapp.org/help/#exporting

**Comment by brandontan** [comment]
Is that sharing my personal notes ???

**Comment by brandontan** [comment]
Thought JEX is a debug log file??

**Comment by Daeraxa** [comment]
Debug log is debug log (https://joplinapp.org/debugging/).
JEX is an export of your actual note contents.
The issue you raised is about your own system crashing with an exception, without reliable replication steps (including exactly what features/numbers/sizes of notes/database) for the crash then the JEX file is the next best option as you can seemingly produce it with your data.

If you can't provide accurate and reliable replication steps and you can't provide your data that can potentially reproduce the issue then the issue is probably a lost cause unless somebody else can find a way to reproduce it. Assuming you have searched the forums and GitHub for previously logged issues about this specific crash message it implies that this is a rarely seen problem and for all we know, entirely environmental.

**Comment by brandontan** [comment]
I will enable : joplin --debug --log-level debug and send the log file when it occurs again. Thanks

**Comment by Daeraxa** [comment]
Even with a debug log the issue still might require replication steps and/or example data that can reproduce the problem.

**Comment by brandontan** [comment]
understood. As I mentioned, I was in the rich editor and it just froze on me with a white screen.
