### ISSUE TITLE
Joplin server NTP timeout.

### ISSUE THREAD

**Issue by bulletforkiller** [laurent22/joplin#6141]
My Joplin server didn't response after I updated Joplin server to 2.7.4, the web page returns 502, too.

![image](https://user-images.githubusercontent.com/25951144/153688121-8942da13-5887-4371-bdc9-991412fea475.png)

![image](https://user-images.githubusercontent.com/25951144/153688263-3c62be9e-d13f-4d88-939d-e717841799a5.png)

## Environment

Joplin version: 2.6.10
Joplin server version: 2.7.4 (docker)
Platform: Linux
OS specifics: Kali Linux 2022.1 (flatpak)

## Logfile

```
2022-02-12 00:20:23: App: Starting server v2.7.4 (prod) on port 22300 and PID 7...
Error: Cannot retrieve the network time from pool.ntp.org:123: Timeout waiting for NTP response.
    at Timeout._onTimeout (/home/joplin/packages/lib/vendor/ntp-client.js:79:22)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

**Comment by laurent22** [comment]
Set MAX_TIME_DRIFT to 0

**Comment by bulletforkiller** [comment]
Thank you, it works now.

**Comment by kja999** [comment]
Thanks for the update here! Worked for me too

**Comment by Tymose** [comment]
For me above workaround was allowing docker container to start but was not addressing root cause of this leaving another issue open (meaning joplin server was not able to connect to mail server to send messages). 

The root cause seemed to be that with my configuration (all traffic through Pi-hole in docker and whole DNS resolution redirected to Pi-hole on router) joplin server docker wasn't able to resolve server names (neither for NTP server nor for SMTP mail server). It can be checked by trying to ping any server name (wasn't working in my case) and ping any IP address (was working). 

There were two solutions I've found: 

1. Running joplin server in host mode. Will require setting up in `docker-compose.yaml` file: 
   - `network_mode: host` 
   - get rid of `ports:` set up as it is not used for `host` mode (might not be ideal as port 22300 will be directly mapped to local host) 
   - changing from `POSTGRES_HOST=joplin-db' to POSTGRES_HOST=XXX.XXX.XXX.XXX' where XXX.XXX.XXX.XXX is IP of your physical machine on which docker is running 

2. Updating `resolv.conf` in joplin server docker to contain DNS server address 
   - create `resolv.conf` file in same folder as your `docker-compose.yaml` file with contents (1st and 4th line are from original resolv while 2nd and 3rd are adding DNS servers IP addresses): 
      ```conf 
      nameserver 127.0.0.11 
      nameserver 1.1.1.1 
      nameserver 1.0.0.1 
      options ndots:0 
      ``` 
   -  update section for joplin-server in `docker-compose.yaml` with: 
      ```yaml 
      volumes: 
         -  ./resolv.conf:/etc/resolv.conf:ro 
      ``` 

BTW - I've ended up runnig server with second solution as it seems closer to original config recommended.

It should not be required to disable TIME DRIFT if any of above workarounds will be used plus sending mail (if configured correctly) should work without issues. Hope it will help someone.

**Comment by AleksandrKudashkin** [comment]
I have a similar setup as @Tymose , running pihole as dns resolver in docker but on the same host as joplin server. Both PiHole and Joplin-server are dockerized (using `docker run`). I wanted to suggest an alternative workaround.

We [could provide a dns server](https://docs.docker.com/network/#dns-services) address(es) when starting a container. That address you provide will end up in `/etc/resolv.conf` inside the container. Then, for docker on linux there is a default gateway IP address between host and container we can use:

```
--dns 172.17.0.1
```


It works if you run container with `docker run` instead of `docker compose`. Docker run by default runs on `bridge` network while docker-compose will create a separate network for each compose file. For compose, the gateway IP might be different, but I haven't tested that.

I would speculate the issue might have to do with how ufw and docker don't work together. I can see pihole gets the dns requests sent from inside the container, but the container never gets back the response. Still, I haven't dug this up more.
