### ISSUE TITLE
Some pictures cannot be opened after a period of time.

### ISSUE THREAD

**Issue by felixxiao99** [laurent22/joplin#6192]
## Environment

Joplin version: 2.6.10
Platform: macOS  Catalina 10.15.7

Joplin version: 12.7.1
Platform: IOS 15.3.1

## Steps to reproduce

Some pictures cannot be opened after a period of time.
<img width="407" alt="image" src="https://user-images.githubusercontent.com/50790338/155518924-f179ed9b-d0c7-4263-a639-40f554d54dfa.png">

I copied the url of the pictures that I can see and the url of the pictures that I can't see, and found that their formats are different
for example:
the url of the image I can't see :
<img width="754" alt="image" src="https://user-images.githubusercontent.com/50790338/155519974-fbf17da6-f6ce-41eb-a12f-ba7152d56af7.png">

The url of the image I can see:
<img width="525" alt="image" src="https://user-images.githubusercontent.com/50790338/155520011-bc6c8d2e-b6fa-467a-bd3a-2756bdd30387.png">

I use the Synology at home to build a private cloud, and use Synology's own WebDAV service to synchronize Joplin(I used DDNS and port mapping); 
Synology is not powered on 24 hours a day, but only when it needs to be accessed;
So is this possible？When Synology is shut down, Joplin automatically synchronizes and finds that the WebDAV service cannot be accessed, resulting in some kind of error that causes some pictures to be lost?

**Comment by JackGruber** [comment]
The second picture points to a local file path, in the jopline resource folder. Did you attached this file by hand in to this note?
Are these old notes? Because there was a bug in a previous version which created exactly this path. 
That the synology is off/not accessible is not a problem!

Images/Files managed by Joplin normally look like this:
```
[some file XYZ](:/c50924deef9e463f9c82f1c612b10941)
![image XYZ](:/c5fre24deef9e463f9c82f1c612b10831)
```

**Comment by felixxiao99** [comment]
Thank you for your reply. My habit of writing notes is to write a paragraph of text and see a satisfactory picture. I will take a screenshot with the screenshot software, paste it into the note, and then continue to write down the note.
Sometimes I organize my notes, insert some pictures into some old notes, usually take screenshots with screenshot software, and paste it in some places.

**Comment by felixxiao99** [comment]
@JackGruber  The most recent note with missing pictures was created on January 18, 2022. The notes after the 18th did not lose pictures, but I only created 3 notes after the 18th, so I don’t know if they are representative.

**Comment by JackGruber** [comment]
Try the following:

Change the image from 
![grafik](https://user-images.githubusercontent.com/24863925/155662722-d3c3b077-a4b6-4744-86ce-6fc956272e18.png)
to only the resource ID. Replacing `file:///USers/felix/.config/joplin-desktop/resources/` and `.png` to nothing. 
So that the image code looks like this: `![image XYZ](:/c5fre24deef9e463f9c82f1c612b10831)`
