### ISSUE TITLE
Desktop: paste table into WYSIWYG no longer works

### ISSUE THREAD

**Issue by ghosttie** [laurent22/joplin#6198]
Copying a table from Excel and pasting it into Joplin used to work in 2.6, but this morning I upgraded to 2.7 and now it just pasts the table as text

## Environment

Joplin version: 2.7.13
Platform: Windows
OS specifics: Windows 10 build 19044.1526

## Steps to reproduce

1. Copy some cells from excel
2. Paste them into Joplin

## Describe what you expected to happen

Creates a markdown table

## Logfile

[log.zip](https://github.com/laurent22/joplin/files/8142195/log.zip)

**Comment by sneira** [comment]
I have the same problem since I upgraded to 2.7. I've found a couple more cases that also fail:

- Copying a table from a website (it does keep some formatting, like bold text)
- Copying a table from a Joplin note, be it the same you're on, or a different one

While doing some tests I've noticed that it works fine if the note where you paste the table is empty. If it already had some content, that's when pasted table loses the format.

**Comment by ghosttie** [comment]
It hasn't been fixed yet

**Comment by ghosttie** [comment]
It hasn't been fixed yet

**Comment by ghosttie** [comment]
It hasn't been fixed yet

**Comment by ghosttie** [comment]
It hasn't been fixed yet

**Comment by ghosttie** [comment]
It hasn't been fixed yet

**Comment by ghosttie** [comment]
It hasn't been fixed yet

**Comment by ghosttie** [comment]
It hasn't been fixed yet

**Comment by ghosttie** [comment]
It hasn't been fixed yet

**Comment by tomasz1986** [comment]
This should already be fixed in the current release candidate.

**Comment by ghosttie** [comment]
It hasn't been fixed in a released version yet, if it's been fixed in the code then this issue can be closed with that status

**Comment by ghosttie** [comment]
This has been resolved in the most recent version (2.9.17)
