### ISSUE TITLE
[Bug] UI App and Terminal App doesn't share data.

### ISSUE THREAD

**Issue by raguay** [laurent22/joplin#62]
### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [X] Desktop
- [ ] Mobile
- [X] Terminal

*If it is a bug if possible please provide a screenshot showing the problem*

*If there is an error, please copy and paste the full error message*

---
The data in the terminal application and the data in the Desktop application for macOS isn't the same. For me, it would be best to use the same data library. I installed the UI program first and added some notes and notebooks. I then installed the terminal app and ran it. It comes up empty. If I create notes in the terminal app, they are only in the terminal app and vise-versa.

**Comment by laurent22** [comment]
Hmm, in theory you could point the two apps to the same directory (using the --profile flag followed by the directory) since all apps use exactly the same database structure. However you might want to double-check that it works as I haven't tested it.

In general the preferred and maybe most robust way to have the same data in multiple applications is to sync them to the same target. For now it would have to be OneDrive, but soon I will also enable syncing to a local directory so you won't need to go through OneDrive.
