### ISSUE TITLE
UX: Custom notebook ordering is cumbersome

### ISSUE THREAD

**Issue by tangodev** [laurent22/joplin#6202]
Hello,

I'm happy to see Joplin get custom notebook ordering. There's one thing however that's stopping the now revamped notebook tree from greatness: **actually moving the notebooks around as expected is difficult**.

There's no visual feedback telling me where exactly the dragged notebook will land. So I consistently put it as a sub-notebook. Joplin has already solved this for notes:

![better-drag-example](https://user-images.githubusercontent.com/12778629/155850558-fc375a1b-37d0-4e19-98bd-44d32c65ee13.png)

*Notice the bold white line. ALSO: instead of smooth movement, the line is always jumping between notes, removing the need for pixel precision*.

When I placed a notebook as a sub-notebook I couldn't figure out how to undo that. I kept pushing to the left, because that's what most software has taught me to do.

Here https://github.com/laurent22/joplin/issues/6045 you have an example of someone with the same issue.

## Environment

```
Joplin 2.7.13 (prod, linux)

Client ID: [redacted]
Sync Version: 3
Profile Version: 41
Keychain Supported: No

Revision: 5b5165d
```

## Steps to reproduce

1. Have multiple notebooks;
2. Enable custom notebook ordering;
3. Drag a notebook somewhere between other notebooks.

### Expected results

The notebook is given a custom place within the tree.

### Actual results

The notebook "slips" and becomes a sub-notebook. It's not obvious how to reverse that.

## References

https://discourse.joplinapp.org/t/sort-order-buttons-and-per-notebook-sort-order/20013

**Comment by deepspaceaxolotl** [comment]
Definitely an enhancement I support. Is custom ordering of notebooks (not notes within them) possible, though? No matter how I try, I can't get them to have a custom order, they just slip and become subnotebooks.

**Comment by deepspaceaxolotl** [comment]
Could this get the enhancement label?

**Comment by Daeraxa** [comment]
Enhancements need to be raised and discussed on the forum, github issues are for bugs and regressions.

**Comment by tangodev** [comment]
@Daeraxa We're in murky waters, typical IMHO for UX issues. I'd argue it's an *issue* because if there's a feature to rearrange something, it should "just work". I have never managed to do that.

An enhancement was IMHO the addition of the *feature*, ie. "you could not rearrange, but now you can".

But because of lack of accuracy, I (and looks like not only) end up putting the object in the wrong place. Hence, *issue*.

**Comment by Daeraxa** [comment]
@tangodev 

My general take on it is just what is provided when creating an issue on GH, the only link that allows creation of one is:
![image](https://user-images.githubusercontent.com/58074586/166148430-4ba0007e-1a07-4d68-9c7b-6818526f2eb8.png)
Which means that either something isn't working as intended or has been broken, anything that currently doesn't exist at all should be done via the forum.

In the case of this issue I'm not quite sure what you are describing because, as far as I know, there is no custom notebook ordering in Joplin, only custom note ordering so the UI enhancement you are asking for seems to be for a feature that doesn't yet exist. Dragging and dropping is currently only for notebook nesting, sorting is by name or updated date (and their reverse) only.

**Comment by deepspaceaxolotl** [comment]
(@tangodev Hey! Would you maybe be okay with editing my username out of your comment above and deleting/hiding the pre-edit version? I've decided to change my username on Github and want to make sure the old username doesn't randomly pop up since I want to use it for a separate identity outside of coding-related projects. Wasn't sure how else to contact you about this so I might delete this comment after you reply, hah.)

**Comment by deepspaceaxolotl** [comment]
(@tangodev Changed my username now, thanks so much for editing your mention of me out!! <3 If you'd be able to delete the comment's original revision from history, I'd really appreciate it just so I know no one can associate that old username with this account, for internet hygiene purposes.)
