### ISSUE TITLE
Synchronization deletes several notes when mapped folder is disconnected due to network failure

### ISSUE THREAD

**Issue by edugodoyo** [laurent22/joplin#6304]
Synchronization deletes several notes when mapped network folder is disconnected due to network failure. I use Amazon WorkDocs as network folder. This issue happened several times. The notes simply disappear and very few go to Conflicts notebook. I tried to set Synchronization interval to 'Disabled' but when I start Joplin after recovering network connection the notebooks are gone.

## Environment

Joplin version: 2.7.15
Platform: Mac
OS specifics: MacOS 12.2.1 (Monterey)

## Steps to reproduce

1. Map a network folder in Amazon WorkDocs
2. Set network folder as synchronization target 'File System'
3. Set Synchronize interval to 5 mins
4. Disconnect abruptly network during a synchronization

## Describe what you expected to happen
Joplin should discard the synchronization when folder is not accessible and keep local files intact. Preferably is it should do a backup in the background in the local storage to recover from a sync failure.

[debug.log](https://github.com/laurent22/joplin/files/8315638/debug.log)

**Comment by JackGruber** [comment]
This is the problem with the filesync and network drives.
If it can't find the file, no matter if it's not there or the connection was lost, the sync assumes the files were deleted and deletes the associated local data as well.
This issue has been discussed in other issues if I remember correctly and was not considered as a bug, because the sync is not designed for this.
