### ISSUE TITLE
inline attributes indents the text 2 spaces forward

### ISSUE THREAD

**Issue by grvsh02** [laurent22/joplin#6334]
## Environment

Joplin version: 2.7.14
Platform: Linux 
OS specifics: Ubuntu

## Steps to reproduce

1. Create a note and start typing something in the rich text editor.
2. add a strikethrough using '~~' or any other inline attribute at the start and at the end of your text
3. The preview jumps 2 spaces forward.

## Describe what you expected to happen

There should be no indent due to any inline attributes.

![image](https://user-images.githubusercontent.com/50337734/160441515-618346d3-4573-47cc-b3e3-983fa3822235.png)

**Comment by CalebJohn** [comment]
This is the expected behaviour, but I see how it's not immediately obvious.

With markdown add content to the below a list item adds it as a "child" of the list item. 
<img width="519" alt="image" src="https://user-images.githubusercontent.com/2179547/160489399-e396dee3-75da-433d-aaa8-e5b61d07b483.png">

As you can see in my example, the content on the newline is nicely aligned.

When you add \*\* to the beginning of a list item, it is no longer a list item and becomes the the text `3. banana`. As you see in your example, it is now nicely aligned with the list item.

You have 2 resolutions:
1. Apply the bold to banana, but not 3.
2. Add an extra indent so that the entire line gets a paragraph of it's own. (Note: in this case it won't be continuing the numbered list)

<img width="536" alt="image" src="https://user-images.githubusercontent.com/2179547/160489847-e7a69961-7e62-4bee-a9b7-0aebbeb57d07.png">
