### ISSUE TITLE
Link of the "Auto Alarm" plugin is not working

### ISSUE THREAD

**Issue by marph91** [laurent22/joplin#6361]
## Steps to reproduce

1. Visit https://github.com/joplin/plugins or https://discourse.joplinapp.org/t/plugin-list/17671
2. Click on the home icon of the "Auto Alarm" plugin

It redirects to https://github.com/joplin/plugins/blob/master/github.com/zph/joplin-plugin-auto-alarm, which is not existent. Probably just the `https://` prefix is missing at the readme.

## Describe what you expected to happen

Redirect to the correct page https://github.com/zph/joplin-plugin-auto-alarm.

**Comment by Daeraxa** [comment]
This should be reported to the plugin developer as indeed they didn't include `https://` in their manifest.

The bit that is weird is the github url being added. It seems github automatically adds a github base url to any non url markdown link.

https://github.com/joplin/plugins/blob/2601993dc12ecdbf4697f0f4d385f738cb321ddf/README.md?plain=1#L21

The forum post just shows a non clickable link because the markdown url is incorrect.

`| [🏠](github.com/zph/joplin-plugin-auto-alarm) `

Sure there could be a bunch of workarounds but it would be far easier for the maintainers to just put real URLs in their plugins if they want the links to work.

**Comment by marph91** [comment]
Ok, thanks for clarifying. I wasn't sure how the page is generated, so I created an issue here. I will create an issue at the plugin repo.

**Comment by harshalkaigaonkar** [comment]
Hey @Daeraxa @marph91, is it still relevant/open?

**Comment by Daeraxa** [comment]
No, there is no bug label, the issue is closed and the conversion makes it clear what direction this was taken in.

**Comment by harshalkaigaonkar** [comment]
> No, there is no bug label, the issue is closed and the conversion makes it clear what direction this was taken in.

okay, sorry for the inconvenience.
