### ISSUE TITLE
Joplin Server sync fail for Android app

### ISSUE THREAD

**Issue by ACasset** [laurent22/joplin#6377]
Hello :)

I'm having a very very weird and intermittent network issue with the Android app.

## Environment

Joplin version: 2.7.2
Platform: Android
OS specifics: up-to-date Android 10 with Samsung OneUI 2.5

## Steps to reproduce

1. Fresh install of Joplin (or full data cleanup), the app starts with the 5 default notes
2. Configure sync with Joplin Server on a custom domain
3. Tap "Check synchronization configuration"
4. The app stalls on "Checking... Please wait." for a while, then randomly works, then fails during sync, etc. It's very wobbly and not constant.

## Describe what you expected to happen

Sync conf check succeeds, then I can sync notes.

## Additional details

I did first suspect my phone or my server setup :
- This is likely not a connectivity issue on my phone : I did try to reboot it, change networks (either Wifi or VPN), and when I open a Termux, I can resolve my custom domain and get a response from /api/ping
- This is likely not a server setup issue : I can sync Joplin desktop with it AND I tried setting up a simple webdav server (which worked again with desktop, but had the same behavior with the Android app)

My custom domain :
- is hosted on OVH
- has A and AAAA DNS entries, nothing more
- has a fresh LetsEncrypt SSL certificate
- handles all data through a nginx reverse-proxy on default ports

When I tail the nginx logs and try to either check config or sync on the Android app, nginx does not receive any requests at first. When it randomly works, it receives all at once, usually triggering a HTTP 429.

The app logs show nothing besides the beginning of sync.

If I try a domain that is hosted somewhere else (i.e. something completely different like google.com, a misstype in my custom domain, a non-existent subdomain or either an existing subdomain hosted on another server), the sync conf check does fail immediately instead of hanging.

If needed, I can purge my server and provide a set of credentials.

## Logs

[Logs.txt](https://github.com/laurent22/joplin/files/8446019/Logs.txt)

**Comment by ACasset** [comment]
Just tried on another phone (Android 11, MIUI 12.0.2), and it works :(

So I guess the root cause is either from Android 10, or Samsung

Anyone ever heard of this specific issue?

**Comment by yajo** [comment]
In my android tablet and phone, sync gets stuck quite often. Actually the whole app gets stuck when it happens. On the desktop, it syncs perfectly.

**Comment by Jappie3** [comment]
Having the same problem on my Android Samsung phone rn: it worked perfectly, I changed my domain (aka new url for Nextcloud as well) and now it refuses to sync. Reinstalled the app, still no luck. I can visit the remote.php/dav url perfectly fine in my browser (on my phone), but the Joplin app apparently can't reach it? There are also no error logs in my server related to this issue.

Update: not even 10 minutes after this comment it started syncing... I didn't change anything and I have no clue how. The only advice I can give is to let it just sit there and sync for a good 15-20 mins... maybe something will happen. I have quite a few notes, so maybe it just took a while?
I also turned off Cloudflare (I use CF's free tier to proxy my traffic through their servers as to not have my IP exposed) caching by enabling developer mode, but I don't think that helped (it has been about an hour since I turned it off I think). Something else I tried was turning off DuckDuckGo's app tracking protection, but I don't think this ultimately resolved the problem either since DDG didn't list any tracking attempts from Joplin being blocked.
