### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by milotype** [laurent22/joplin#6435]
1. Several strings do not translate allthought translated in the `.po` file
2. Several strings cannot be translated, because they are missing in the `.pot` file

## Environment

Joplin version: 1.7.15, revision: 8352e23
Platform: macOS
OS specifics: macOS 10.11.6

## Steps to reproduce

Please review the attached screenshots.
**NOTE**: I've put them all into one issue as they share same problems. (I hope you don't mind).

## Describe what you expected to happen

1. All translated strings in the `.po` file should translate
2. All missing strings should be added to the `.pot` file

## Screenshots

![menu-edit](https://user-images.githubusercontent.com/43657314/164204577-84be123b-c85c-4fa5-a63b-eda2a9415164.png)
![settings-appearance](https://user-images.githubusercontent.com/43657314/164204590-b05c55c7-7b04-4cf1-8f80-7983843ad3f2.png)
![settings-general](https://user-images.githubusercontent.com/43657314/164204593-7ed65da2-0346-4866-9a70-ec1b9255b2a9.png)
![settings-plugins](https://user-images.githubusercontent.com/43657314/164204595-fb2e6df9-9e67-42bb-bec2-a75a4b199bea.png)
![settings-synchronisation-2](https://user-images.githubusercontent.com/43657314/164204599-67335145-38a3-4f78-aba9-50813cf64de2.png)
![settings-synchronisation](https://user-images.githubusercontent.com/43657314/164204600-18042f8f-a417-4f81-9346-05d4424bfea0.png)
![tooltip](https://user-images.githubusercontent.com/43657314/164204603-c830e3aa-82dc-4054-a8ae-8971670919c9.png)

**Comment by roman-r-m** [comment]
Maybe this could be a good first issue?

**Comment by Elaborendum** [comment]
Just want to mention that the first one wasn't present in the previous version (2.7.13), and the last one seems to work in other languages:
![imagen](https://user-images.githubusercontent.com/71190696/164335624-b9aa20c5-138c-4e6c-a42f-2b83411efa4c.png)

**Comment by laurent22** [comment]
Thanks for the detailed report. I looked into it but couldn't find any actionable item unfortunately:

- There are advanced settings that we don't translate because I'm not sure they will stay
- This is especially true of features marked as "beta"
- The sync target items cannot be translated without changing the app initialisation sequence so that won't be done for now (but I agree it would be good to find a way to translate these items)

Regarding the "Toggle sort order field" string, it is translatable (it's in French for instance), but maybe it wasn't translated in your language, but that will come.

I've just missed the Undo/Redo strings, I'll check that now.

**Comment by laurent22** [comment]
Undo/Redo is fixed now.
