### ISSUE TITLE
Formatting ( bullets markdown) is off 

### ISSUE THREAD

**Issue by brandontan** [laurent22/joplin#6454]
## Environment

Joplin version: Joplin 2.7.15 (prod, darwin)
Platform: Mac 12.3.1
OS specifics: 

## Steps to reproduce

https://cln.sh/7Ebfku

## Describe what you expected to happen

The bullets should be formatted correctly

**Comment by Daeraxa** [comment]
I can't replicate this on the current dev build (on Linux), can you provide the exact markdown?
(I can replicate the bolding behaviour but that is simply because it is activating a second level setex style header and is consistent with the commonmark implementation, its the `1. 0.1` bit I can't seem to replicate).
