### ISSUE TITLE
FileLock after encryption & synchronization

### ISSUE THREAD

**Issue by armaccloud** [laurent22/joplin#648]
### Operating system

- Linux
- Android

### Application

- Desktop
- Mobile

### Description
I cannot get Joplin synchronized on my Android after encryption.

The steps I took:

- Turned on encryption on the desktop (Joplin 1.0.103 (prod, linux))
- Performed Full Synchronization
- Opened the app on Android (1.0.128) & Synchronized
- In the encryption settings it noted that items were decrypted, however I didn't have to input my password. I entered the password in the empty password box and saved.
- Re-initiated sync, during which it now gets stuck with the following error

![screenshot_20180626-010121-300x1000](https://user-images.githubusercontent.com/9272078/41880408-3819043c-78de-11e8-8de6-67c23f4c2ca2.png)

When removing the specific resource file from the cloud storage, it still  stops the sync with this same error.

**Comment by laurent22** [comment]
It's not a Joplin issue actually. If you are using Nextcloud, the recommended way is to use something like Redis to handle the file locking mechanism because it's more reliable. To fix your current situation, there are many posts about it on the Nextcloud forum - in my case, when I had this issue, I've simply deleted the content of the file_lock table. For other WebDAV services there will probably be similar solutions.
