### ISSUE TITLE
Stick to XDG FreeDesktop.org directory spec for the binary

### ISSUE THREAD

**Issue by gerardbosch** [laurent22/joplin#6524]
## Environment

Joplin version: 2.7.15
Platform: Linux

Hi there!

Not exactly a bug, more an observation/idea.

When you install on Linux with:

```console
wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash
```
the AppImage binary is downloaded into `~/.joplin/`, what makes homedir a little messy. This is also relevant for automated backups - which would involve to add an ad-hoc exclusion to your backup configuration in order to not backup the binary. Specially relevant for cloud backup as typically they cost $ per stored MB.

So it may be a good idea to store the binary to some other directory that follows the XDG base spec, not very sure but `~/.local/bin/joplin/` may be suited? This (or similar way) people can globally exclude such binaries directory form their backup.

Cheers!

**Comment by Aeledfyr** [comment]
Relevant issues: #6085, #6079, #3765, #887
Relevant pull request: #6152
Relevant forum post: https://discourse.joplinapp.org/t/xdg-base-directory-specification-compliance/16444

Most of those are about the location of config and save data, but are about a similar issue of following the XDG base spec.

From having seen many similar issues in the past, this will likely only move forward if:
1. There is a trivial migration/upgrade path that covers all possible cases
2. This only moves the binary, and not user data
3. This issue doesn't get marked as stale (so bump it every month...)
4. Someone fully implements this and sends a PR

If you or someone else plans to make a PR, it will likely stall unless it handles all possible migration cases.

Also, it's likely that this won't happen anyway; see this comment: https://github.com/laurent22/joplin/pull/6152#issuecomment-1060459928
(Though that's less of an issue with the binary, since it's already in different places depending on the installation method.)
