### ISSUE TITLE
Sync just spins forever on Android (Dropbox with encryption)

### ISSUE THREAD

**Issue by Nermit** [laurent22/joplin#6627]
Recently, sync stopped working on Joplin for Android when syncing to Dropbox with encryption. It still works fine on my desktop computer. No error is reported, the synchronising icon just spins forever. If I press cancel, it says "cancelling", but the icon just keeps spinning until I force close the app. I have tried reinstalling the app, and setting up Dropbox sync and the master password again.

## Environment

Joplin version: 2.8.1
Platform: Android (Samsung Galaxy S9+)
OS specifics: Android 10, OneUI 2.5

## Steps to reproduce

1. Set up Dropbox sync
2. Set up encryption with a master password
3. Watch, as the synchronising icon spins forever.

## Describe what you expected to happen
I expected the sync to finish in a reasonable amount of time, as it always has until the past week.

## Logfile

[syncReport-1656696900345.txt](https://github.com/laurent22/joplin/files/9030820/syncReport-1656696900345.txt)
[dumpstate-2022-07-01-13-59-23.zip](https://github.com/laurent22/joplin/files/9030852/dumpstate-2022-07-01-13-59-23.zip)

**Comment by HDkarlsen** [comment]
I have the same issue -- but it only happens intermittently. Not sure what causes it. Sometimes it helps to restart the app or wait a random amount of hours and the issue resolves itself and I can sync without problems. Then it reappears days later.

Same setup as Nermit, only I have a Samsung Galaxy A8.

Edit: I wrote this as I ran into the issue again. This time I left the app open and syncing. After about ten minutes it finally synced. It only had three small notes to sync, so it spent much longer than necessary. Perhaps the issue is not that it doesn't sync, but that it takes much longer than normal?
