### ISSUE TITLE
Hello! After copying and pasting web pages and images, the editor doesn't show anything. . . 

### ISSUE THREAD

**Issue by zhouxinghong** [laurent22/joplin#6676]
Hello! After copying and pasting web pages and images, the editor doesn't show anything. . . After many tests this is a serious bug that needs to be fixed in time. . .
Version: 2.8.8~2.9.1
System: Windows 10

**Comment by personalizedrefrigerator** [comment]
I don't think I'm experiencing this issue — copy-pasting from Firefox into Joplin works for me (I'm on PoP! OS/Linux):

https://user-images.githubusercontent.com/46334387/180639268-3b6601b0-3790-4741-8f73-ef590edfe3b1.mp4

Is this what was leading to the issue?

---

Because I haven't been able to reproduce this issue, having Joplin's logs would be helpful: What shows up in the debugging console?

<details><summary>Opening the debugging console</summary>

1. Click "Help", then "Toggle development tools"
![](https://user-images.githubusercontent.com/46334387/180639407-f8b1844c-1645-4432-8792-4ed87abcfead.png)
2. Click "Console" in the window that shows up
![](https://user-images.githubusercontent.com/46334387/180639439-ce405305-a5fa-4d54-bcf3-1d74ef02a85d.png)

</details>
