### ISSUE TITLE
Terminal client with non interactive commands support

### ISSUE THREAD

**Issue by bufferovercat** [laurent22/joplin#67]
It would be great if the terminal client has command line support as parameters. This way it could be easy to automate some tasks or implement a rudimentary IFTTT maker channel integration with some scripts.

Thanks!

**Comment by laurent22** [comment]
Hi, this used to be supported but is currently broken. Basically normally you can write:

    joplin use "my notebook" # Switch to the given notebook
    joplin mknote "My note" # Create a note "My note" in "my notebook"

Also the other commands are also supported. I think it won't take much to fix this so I'll take a look at it.

**Comment by bufferovercat** [comment]
Nice! Waiting for the update, thanks!. Is there any changelog section for each client version?

**Comment by laurent22** [comment]
This should be fixed in the latest version - type `npm -g update joplin`. I've also added some documentation for it: http://joplin.cozic.net/terminal/#shell-mode

**Comment by laurent22** [comment]
Closing this for now since it should be fixed. If you come across some issue or think some command is missing feel free to let me know or create a pull request.

Adding new commands can be done by adding a file in "CliClient/command-NAME.js" - the file will be automatically detected and available as a command. See for instance the `cat` command, which displays detailed info about a note: https://github.com/laurent22/joplin/blob/master/CliClient/app/command-cat.js
