### ISSUE TITLE
WYSIWYG editor's newlines gets broken and prints double newline

### ISSUE THREAD

**Issue by mu-us61** [laurent22/joplin#6723]
## Environment

Joplin version:  2.8.8
OS:  windows 10 , 64-bit

## Steps to reproduce

1.  open wysiwyg editor and just type some stuff with new lines
2.  then switch to markdown editor from right top icon , the again back to wysiwyg editor
3.  now in wysiwyg editor newlines broken forever always prints double new lines, instead of 1

## Describe what you expected to happen
it should just print a newline

I just installed joblin so I am not sure maybe this bug happens in other circumstances too

![brokenlines](https://user-images.githubusercontent.com/73366454/183310335-bb1e29fe-fa07-46a5-80f3-2b95264be46e.gif)

**Comment by Daeraxa** [comment]
I believe this is (semi) intentional. When you start a new richtext page the first line is contained within `<div id="rendered-md">` and subsequent lines are just new `<p>` lines under the same parent.
When you leave the editor and come back it correctly places the lines *inside* `<div id="rendered-md">`

i.e.
before:

```html
<body id="tinymce" ...snip...>
    <div id="rendered-md">test</div>
    <div>test2</div>
    <div>test3</div>
</body>
```

after:

```html
<body id="tinymce" ...snip...>
    <div id="rendered-md">
        <p>test</p>
        <p>test2</p>
        <p>test3</p>
    </div>
</body>
```

I think this is related to a hack to get the richtext editor to work correctly.

The "broken" behaviour is actually the correct one. TinyMCE by default inserts a `<p>` on a return. If you want a `<br>` then you need to <kbd>shift</kbd> + <kbd>return</kbd>

**Comment by mu-us61** [comment]
I understand thanks for explanation, but that means if you are using WYSIWYG editor as primary with all your stuff and someday if you press markdown button by accident, all your work will be messed up, this makes WYSIWYG editor unusable , then it should be locked on WYSIWYG editor and switching to markdown must be blocked or entire page will be messed up at some point , as it is switching editors buggy

**Comment by Daeraxa** [comment]
It isn't anything to do with switching editors, it happens when you change notes.
i.e. with the richtext editor on:
- Create new note
- Add content, it single spaces
- Click a different note and come back to the original
- Format has changed
