### ISSUE TITLE
The pasted picture gets bigger

### ISSUE THREAD

**Issue by akkuman** [laurent22/joplin#6797]
## Environment

Joplin version: 2.9.4
Platform: windows
OS specifics: win10 21H1

## Steps to reproduce

1. sceenshot to png
2. download pngquant from https://pngquant.org/
3. compress PNG file lossy using pngquant: `pngquant 64 --ext=.png --nofs --speed 1 --strip --force --skip-if-larger "xx.png"` 
4. copy the xx.png to clipboard
5. paste on joplin

![image](https://user-images.githubusercontent.com/7813511/187846570-7ca453a4-210f-4213-94cb-cd5ab1cbc680.png)
![image](https://user-images.githubusercontent.com/7813511/187846763-572c097a-96ab-477d-9f3b-81090e41ca6c.png)
![image](https://user-images.githubusercontent.com/7813511/187846793-2ed4d3e8-415d-4464-9c00-6d359e4584c4.png)
![image](https://user-images.githubusercontent.com/7813511/187846948-96fa40e1-38a5-4fb1-99ff-06fd588964c7.png)
![image](https://user-images.githubusercontent.com/7813511/187847017-588ae825-82c2-4eb0-baf2-df183671e48c.png)

**Comment by akkuman** [comment]
I see. It's not Joplin's problem. The images in the clipboard are actually in bitmap format, so it's not actually the original image that I pasted

Will Joplin offer an image compression option so that users can define their own parameters for image compression?

**Comment by Daeraxa** [comment]
There is a plugin (Attache) which will allow you reduce the sizes of your images (in resolution) but I don't think there are any plans to introduce compression, it will just use the source file you give it - in this case if you attached the image rather than pasting from clipboard it then I suspect the file size would have remained the same.
