### ISSUE TITLE
Joplin does not show any sync error (terminal)

### ISSUE THREAD

**Issue by coolwanglu** [laurent22/joplin#6852]
## Environment

Joplin version: 2.8.1
Platform: linux (terminal)
OS specifics: Ubuntu 22.04 + Docker + node image

## Steps to reproduce

1.  Set up Dropbox sync and add some notes
2. Completly disable network
3. Run joplin sync
4. Joplin acts as everything succeeded, the exit code is 0 and there's no error shown in the stdout/stderr. Note: network errors are logged in log.txt

## Describe what you expected to happen

joplin shows errors to the terminal, and exit with a non-zero code

**Comment by coolwanglu** [comment]
Hmm I was planning to create a post in the forum, but the template mentioned `For bug reports, please post them on GitHub`

**Comment by wh201906** [comment]
The desktop version has the same behavior. It doesn't report the network errors when syncing.
I guess it's because they think the network errors are always temporary and they can be resolved somehow. I don't know if it's good to show no warnings or errors to users. Users will think everything work fine as they just see a `Completed` in the output with no errors, while the sync actually doesn't work at all.
https://github.com/laurent22/joplin/blob/052d9f03d6b7687b1ba5102fef9b9bb79f343c41/packages/lib/Synchronizer.ts#L1102-L1106
Anyway, I think posting the issue on both the forum and GitHub is fine.

**Comment by hleskien** [comment]
Still not fixed. Occurs on different platforms (see #7052).

**Comment by hleskien** [comment]
Still not fixed. Occurs on different platforms (see https://github.com/laurent22/joplin/issues/7052).

**Comment by wh201906** [comment]
Still not fixed.

**Comment by wh201906** [comment]
Still not fixed.

**Comment by hleskien** [comment]
Still not fixed.

**Comment by hleskien** [comment]
Still not fixed.

**Comment by hleskien** [comment]
Still not fixed.
