### ISSUE TITLE
Joplin search shows no content (Iphone 12s)

### ISSUE THREAD

**Issue by scfrank-pri** [laurent22/joplin#6859]
Whenever I type in something in "search" on Iphone12s, I get the white screen with the black bar (on the very top - see screenshot attached), but no content. The black bar has nothing to touch on. 
This problem is persistent over past app updates, that's why I report it here. Thanks. 
![IMG_5913](https://user-images.githubusercontent.com/80214660/190858060-c004178a-f23d-49d4-9a42-766c5ce25f55.PNG)

**Comment by personalizedrefrigerator** [comment]
Because of an upstream react-native bug, the following accessibility settings break Joplin on iOS:
![Reduce motion and prefer cross fade transitions shown checked in accessibility settings](https://user-images.githubusercontent.com/46334387/190874773-78ae2f92-8730-4a09-948a-d9df8eb20cf2.jpeg)


See also https://github.com/laurent22/joplin/issues/6682#issuecomment-1236104332


Thank you for reporting this! Hopefully it will be fixed soon.

**Comment by personalizedrefrigerator** [comment]
Still an issue.

**Comment by scfrank-pri** [comment]
I can confirm that the solution discussed above works for me:

[accessibility settings break Joplin on iOS](https://github.com/laurent22/joplin/issues/6859#issuecomment-1250133420)

Goto Settings -> Accessibility -> Motion -> Disable "Prefer Cross-Fade Transitions" 
(for me no need to disable also "Reduce Motion" -- a feature to save battery) 

This solved the problem. Thank you!
