### ISSUE TITLE
Custom sort order not synchronized

### ISSUE THREAD

**Issue by la-la-lars** [laurent22/joplin#6956]
## Environment
_Platform_: 
Windows + Android

_Windows_:
Joplin version: Joplin 2.8.8 (prod, win32)
Sync-Version: 3
Profil-Version: 41
Revision: c2a6a13
Platform: 
OS specifics: 

_Android_:
Joplin version: 2.8.1
Database version: 41

## Steps to reproduce

1. create notebook on Windows
2. create some tasks in the notebook
3. set sort order to custom
4. move tasks to desired order
5. sync to Android (in my case via filesystem on both systems, filesystem folder synced via syncthing)
6. open notebook on Android
7. make sure custom sort order is selected (not sure if this setting itself is synced?)
8. => sort order is not the same as on Windows

## Expected: 

Sort order should be the same for the notebook on both Windows and Android after synching (when custom sort order is selected in both - ideally the selected sort order should be synced, too).

This is especially frustrating when trying to create a todo list of tasks with prioritized order...

**Comment by laurent22** [comment]
In Android there's an option to use the custom order (by taping on the top right arrow). Did you do this?

**Comment by la-la-lars** [comment]
Yes, I did, and it is ticked appropriately in the popup.
The order is still not the same as on the other synced device.

**Comment by TaoK** [comment]
I believe I've isolated this to `packages/lib/models/Note.ts`, where updating note order explicitly and intentionally *doesn't* change the `user_updated_time`: 

```
	// Update the note "order" field without changing the user timestamps,
	// which is generally what we want.
	static async updateNoteOrder_(note: NoteEntity, order: any) {
		return Note.save(Object.assign({}, note, {
			order: order,
			user_updated_time: note.user_updated_time,
		}), { autoTimestamp: false, dispatchUpdateAction: false });
	}
```

What I don't know, is *why* the author (@laurent22 ) originally didn't expect order changes to cause note syncs. I assume it's to avoid a flurry of updates if/when existing notes don't have an order value? As far as I can tell the sort-update algorithm only updates the moved notes' "order" fields, so marking them updated seems like a very reasonable thing to do.

**Comment by laurent22** [comment]
updated_time triggers a sync, not user_updated_time

**Comment by TaoK** [comment]
Ah, my apologies for the incomplete/incorrect understanding.

~~What I have found so far, is that if I remove all three "special things" in the above snippet (the `user_updated_time` preservation, the `autoTimestamp` disabling, and the `dispatchUpdateAction` disabling), then things behave more or less as *I* originally expected: the `updated_time` on the reordered note is updated, and sync works correctly. Of course, `user_updated_time` is also updated, which you appear to identify as a bad thing.~~

~~I'd be curious to understand *why* we would want to preserve the previous `user_updated_time` in the face of user action, reordering in this case. Is it a generic aspect of a "conflict minimization" strategy, or is there a more specific functional imperative?~~

~~If I only remove the `autoTimestamp`-disabling, I actually get the same outcome: both `updated_time` and `user_updated_time` get updated, and broadly everything works as I expected. (so then, the other two measures above are wasted/ineffective; if removing `autoTimestamp`-disabling is the right thing, then the `updateNoteOrder_` method might as well be removed altogether).~~

~~With your clarification about wanting to preserve `user_updated_time`, I guess these lines of code in `packages/lib/BaseModel.ts` might be the root problem, but I don't understand the background to them so I can't be sure:~~

```
		if (options.autoTimestamp && this.hasField('updated_time')) {
			o.updated_time = timeNow;
		}
```

~~There is a subsequent comment about why disabling `autoTimestamp` avoids updating `user_updated_time`, but I haven't understood whether/how the same argument applies to `updated_time`, or whether the condition above is an error.~~

~~For my personal purposes I'm happy just removing the `autoTimestamp: false` bit and letting `user_updated_time` be changed, but ideally I'd prefer to propose a pull request to address the issue for others also - is it easy to determine whether the "disabling autoTimestamp avoids updating `updated_time`" lines are intentional or not?~~

The last option, I guess, if `user_updated_time` *should* be preserved, and disabling `autoTimestamp` *should* also disable the auto setting of `updated_time`, is to add a new/extra line to the `updateNoteOrder_` method, explicitly setting `updated_time` to `time.unixMs()`. That seems to be making things more complicated rather than simpler (it's duplicating the implementation of "last-updated-setting"), but may be the safest option, at least in the face of my ignorance?

Fwiw, this last approach does seem to achieve what you seem to imply is the correct behavior: `user_updated_time` remains unchanged, `updated_time` is updated, and sync works as expected.

EDIT 2023-02-07: crossed out initial incorrect musings - further review of the code indicates that some callers setting `autoTimestamp: false` expect `updated_time` to remain unset, and others explicitly set it. It looks like a "simple bug" that `updateNoteOrder_()` was not setting it.

**Comment by TaoK** [comment]
Looking at other places, it seems likely that explicitly setting `updated_time` is indeed the idiomatic thing to do in this project, regardless of any resulting minor logic duplication. In `packages/app-cli/app/command-set.js`, for example, that's exactly what happens.

Indeed, in that specific case the implementation is equivalent but different - setting `updated_time` to `Date.now()` instead of setting it to `time.unixMs()`. I will assume this is the right pattern, and prep a pull request if/when I get the opportunity.

**Comment by TaoK** [comment]
@laurent22, I submitted a pull request with a fix that seemed to do the right thing in my testing (and didn't cause any existing tests to fail), but you closed it saying "updated_time is already updated in the save() call".

I'd love to understand what you mean exactly - I would ask in the pull request, but when you closed it, you or some automation also locked it, so it looks like I'm not able/allowed to ask for clarification there.

In my testing as of commit 40399cf3e1e9ecd (Dec 27, 2022), the `save()` method did *not* set `updated_time`, because of the `autoTimestamp: false` option.

Is there a more recent fix that changes this behavior? Is there a specific version I should be working with? (I had been working with an older commit because a recent build was failing to start the Desktop app for me).

**Comment by laurent22** [comment]
Yes sorry, that's a good point. I'll need to check because I don't understand why the  autoTimestamp call is setup that way. Maybe there's a reason or maybe it's indeed a rather important bug that's been around for many years. It would mean that note order has never synced even though it's supposed to. I've reopened the PR to keep track of it

**Comment by TaoK** [comment]
> It would mean that note order has never synced even though it's supposed to.

That's kind of right: note order only syncs if another unrelated change is made to the note after the sort order change.

**Comment by TaoK** [comment]
~~The pull request is still locked for commenting, so I'll add one more comment that really belongs there, here:~~

~~In defense of the "set updated_time" change, a search for `autoTimestamp` in the codebase yields  a reasonably even division between two types of usecases:~~
* ~~Places where we are trying to preserve `user_updated_time`, and we *explicitly set `updated_time`* as in this change:~~
  * ~~NotePropertiesDialog.jsx#closeDialog()~~
  * ~~Note.ts#moveToFolder()~~
  * ~~RevisionService.test.ts#'should preserve user update time'~~
  * ~~notes.ts#POST~~
  * ~~ShareService.ts#shareNote()~~
* ~~Places where we are performing import-related activities, and explicitly want to preserve both `user_updated_time`, *and* `updated_time`~~

~~So it looks like not setting `updated_time` was a simple oversight, and this change is a simple bugfix.~~

~~I could/should have explained this better in the pull request - my musings above are outdated.~~

(comment moved to the pull request #7729)

**Comment by TaoK** [comment]
(@laurent22, my apologies for tagging you explicitly in a separate comment, I should have done so above; fwiw, I don't believe much investigation is warranted)

**Comment by la-la-lars** [comment]
@TaoK thanks for looking into this! Much appreciated!

**Comment by znebby** [comment]
I just setup Joplin yesterday and have the latest versions on Windows (2.9.17) and Android from the Play Store (2.10.8) - which appears to be the version this was fixed it (https://joplinapp.org/changelog_android/), but custom sort order is not being synced from Desktop to Android.
