### ISSUE TITLE
[Feature request] Add Sync only on Wi-Fi option (mobile)

### ISSUE THREAD

**Issue by pled** [laurent22/joplin#720]
### Operating system
- Android
- iOS

### Application
- Mobile

I am using Nextcloud to sync' my notes between desktop and mobile. On the mobile, I would like to have the option to sync only when Wi-Fi is On. It allows me to better control my data usage.

**Comment by pled** [comment]
As far as I can see, there is still no such option with 1.0.305. It still requires the community's attention if community considers this option as relevant...

**Comment by vinieich** [comment]
Just adding that it would be very useful to me too. Too bad I don't know (yet) how to code 😞

**Comment by mablin7** [comment]
I think this is an essential option for mobile. I have some experience with react-native, I'll look into this one.

**Comment by mablin7** [comment]
## Spec
### Settings
- add "Sync only over WiFi" option to settings, on mobile only

### Registry
- add an option `isOnMobileData` with corresponding setter
- add a check before sync starts that aborts of `isOnMobileData`  is true
- add manual override, so that manual sync can be still run

### Mobile sidebar
- add an icon at the bottom, which indicates if user is on mobile data and thus automatic sync is disabled

**Comment by roman-r-m** [comment]
How are you going to decide whether to enable sync on not? Netifno has a few connection types for which the answer isn't obvious to me, namely:
* bluetooth
* vpn
* wimax

**Comment by mablin7** [comment]
Yeah that's not very straightforward. I figured the safest is to only
disable if the connection type is `"cellular"`. In any other case, there's
no effect. I think this will cause the least distruption in cases where
network type can't be determined.

If you agree, I'll update the spec to be more specific.

**Comment by roman-r-m** [comment]
I think `bluetooth` may be in the same category as `celluar`,  `wimax` and `vpn` are probably closer to wifi

**Comment by mablin7** [comment]
Oh, I didn't notice it until now, but actually NetInfo has a propery called `isConnectionExpensive` that seems to be perfect for our use case:

> ##### `type` is `bluetooth`, `ethernet`, `wimax`, `vpn`, or `other`
> 
> `details` has these properties:
> 
> | Property                | Type      | Description                                                                                            |
> | ----------------------- | --------- | ------------------------------------------------------------------------------------------------------ |
> | `isConnectionExpensive` | `boolean` | If the network connection is considered "expensive". This could be in either energy or monetary terms. |

So how about disabling sync when network is `cellular` _or_ when `isConnectionExpensive` is true? I'll do a few tests to see how this behaves, although I surely can't test wimax, and I'll have to look into the bluetooth type.

**Comment by roman-r-m** [comment]
> Oh, I didn't notice it until now, but actually NetInfo has a propery called `isConnectionExpensive` that seems to be perfect for our use case:

On android this resolves to [ConnectivityManagerCompat.isActiveNetworkMetered](https://developer.android.com/reference/androidx/core/net/ConnectivityManagerCompat#isActiveNetworkMetered(android.net.ConnectivityManager)) which has this comment
> Returns if the currently active data network is metered. A network is classified as metered when the user is sensitive to heavy data usage on that connection due to monetary costs, data limitations or battery/performance issues. You should check this before doing large data transfers, and warn the user or delay the operation until another network is available.
> This method requires the caller to hold the permission Manifest.permission.ACCESS_NETWORK_STATE.

Seems reasonable but you'll need to ensure this permission is set. Plus worth checking if anything similar is needed for iOS.

**Comment by mablin7** [comment]
Great, thanks!

**Comment by mablin7** [comment]
> Plus worth checking if anything similar is needed for iOS.

On iOS it seems, the library is checking this flag: [`kSCNetworkReachabilityFlagsIsWWAN`](https://developer.apple.com/documentation/systemconfiguration/scnetworkreachabilityflags/kscnetworkreachabilityflagsiswwan). I don't know much about iOS permissions, but the documentation doesn't mention anything, so I think it should be fine.

**Comment by guy-rouillier** [comment]
Just an observation, Android has an option to download updates only when on WiFi.  You might want to check out how that's being done.

**Comment by J-Metsis** [comment]
Hello!

While this feature certainly are needed somewhere, in my location this has not been an issue ,what, at least for ten years, that is most people have unlimited mobile data transfer connection(*). Given that in EU came into effect the regulation of "no-extra-charge for data transfer with EU" already a couple of years ago, this whole point has become or is in the progress of becoming moot for quite a many user.

*: Actually I switch my Iphone onto Wi-fi only to backup it (after the phone has reminded me about the matter), because Apple has not realised the situation and there is no setting for allowing backups using the mobile connection.
