### ISSUE TITLE
Filtering tags on Android doesn't consider first letter

### ISSUE THREAD

**Issue by filwi** [laurent22/joplin#7323]
When adding tags on Android, the tag filtering doesn't look at the first letter of the tag.

This happens regardless of if the starting letter is a capital letter or not. Any sequence of letters in the tag is found OK, except for the a sequence starting with the starting letter.

Example: if searching for "Writing", I type "W" and a lot of tags containing w come up, but not writing. Typing in the whole tag (i.e. "Writing" in this example) doesn't show any tags.

Typing in "riting" without the W, shows the Writing tag in the list of filtered tags.

This is true regardless of the initial letter - it is as if the filter starts the comparison with the second letter of the tag.

## Environment

Joplin version: 2.8.1
Platform: Android
OS specifics: Android 12

## Steps to reproduce

1. Open note
2. Open note menu (top right corner)
3. Choose Tags
4. Tap Filter tags
5. Type tag name

**Comment by laurent22** [comment]
I can't replicate this.

Edit: Also we prefer bug report that actually follows the template rather than long descriptions that may or may not contain a bug report. In that particular, the fact that typing "Writing" doesn't return "Writing" is probably the bug? And that's what I can't replicate. The rest is as designed

**Comment by JackGruber** [comment]
I think the problem is Upper/Lower case (Impoirted tags could be uppercase). I have discoverd this a few weeks ago and wanted to take a closer look into it. But I forgot to write a bug report.

**Comment by filwi** [comment]
Tried searching with both upper case and lower case, but same result. 

Here's a recording of how it looks on my android:

https://user-images.githubusercontent.com/8066290/203505096-e2e60818-6280-48a0-a254-3da2b3e1ad59.mp4

**Comment by roman-r-m** [comment]
Can't replicate this either.

**Comment by JackGruber** [comment]
I can reproduce the behavior. But it occurs only with capitalized tags.

**Comment by JackGruber** [comment]
because the filter search only in lower case, but the var contains upper and lower case.
https://github.com/laurent22/joplin/blob/2762ce2bb8002a177b89bdaefd3dad83c7bef0c7/packages/app-mobile/components/screens/NoteTagsDialog.js#L94

but unfortunately my dev env for mobile apps is not working at the moment  :(
