### ISSUE TITLE
v2.9.17 does NOT remember last window position, the position it was at when closed.

### ISSUE THREAD

**Issue by PaduaPlay** [laurent22/joplin#7341]
Joplin v2.9.17 does not reopen at the last window position, the position it was at when closed.

Opens at some default window position.

With v 2.8.8 it was reopening at the last window position, the position it was at when closed.

Reopening at the last window position is preferred.

Thanks for considering.

**Comment by x0rsw1tch** [comment]
Came here to report the same issue. In the previous version, somehow, I was able to get it to remember it's window position after a restart or logout, but can't remember how I did it. For some reason, since the last upgrade, I haven't been able to get it to remember it's last position, so it always opens in the wrong position/size, annoying.

**Comment by PaduaPlay** [comment]
Seems this issue is not resolved in 2.9.17.
Switched out of Joplin to QOwnNotes for a while. 
Will try again after 2.10 is released.
