### ISSUE TITLE
Simplified Chinese translation error

### ISSUE THREAD

**Issue by younglg** [laurent22/joplin#7345]
Bug feedback: Simplified Chinese translation is wrong, Notebook should be translated as "笔记本" instead of "笔记笔记本". Hope to fix.

**Comment by tessus** [comment]
Can you please open a PR? I am not comfortable doing this myself, since I do not speak or write Mandarin.

Additional explanation: There are many translation strings that include the word notebook. Just a few [examples](https://github.com/laurent22/joplin/blob/dev/packages/tools/locales/zh_CN.po#L2719-L2734). I wouldn't know whether the characters change depending on the position in the sentence, nor do I really know how, since there are no spaces between words.

**Comment by tomasz1986** [comment]
Isn't this already fixed? There is no "笔记笔记本" in the current translation file. Basically, "笔记笔记本" appears to be a simple error where someone by mistake put "笔记" twice (e.g. when copying and pasting, etc.).

**Comment by wh201906** [comment]
I think it's better to provide which version you are using and where the translation error is(screenshot or detailed description), then others can locate the code/translation and fix it.
可以提供一下你正在使用的版本以及翻译错误出现在什么位置吗？你可以截图粘贴到这里或者描述一下。

**Comment by YiZhiRikka** [comment]
> I think it's better to provide which version you are using and where the translation error is(screenshot or detailed description), then others can locate the code/translation and fix it. 可以提供一下你正在使用的版本以及翻译错误出现在什么位置吗？你可以截图粘贴到这里或者描述一下。

I dont know syntax, but I compare it with translation of zh_TW, and I think the following line should be "笔记本" instead of "笔记&笔记本".
https://github.com/laurent22/joplin/blob/8371e2ece69f3765e69e093667d65ac937a68988/packages/tools/locales/zh_CN.po#L2717

https://github.com/laurent22/joplin/blob/8371e2ece69f3765e69e093667d65ac937a68988/packages/tools/locales/zh_TW.po#L2717

**Comment by wh201906** [comment]
Oh I see it.
![图片](https://user-images.githubusercontent.com/62299611/204270498-329adba2-5ea7-478d-a373-e9484eb14ded.png)
@YiZhiRikka You are right. Thank you for finding this out.
The ampersand in the `Note&book` is used to specify letter `B` as the accelerator key of `Notebook` menu. I think the translator might misunderstand it.
