### ISSUE TITLE
[ Feature Request ] - Global key to show/hide

### ISSUE THREAD

**Issue by coelias** [laurent22/joplin#745]
### Operating system

- Windows
- macOS
- Linux

### Application

- Desktop

It would be nice to set up a key/combinaition of keys that brings Joplin window to the top and hides it as well. That, allows for quick note writing and going back to the previous app you were working with.

**Comment by innocuo** [comment]
I was looking into this. [Electron supports global shortcuts](https://electronjs.org/docs/api/global-shortcut); I tested on Mac, works ok.

It's kinda easy to implement in ElectronAppWrapper, but the shorcut would need to be hardcoded, because Settings aren't loaded when ElectronAppWrapper starts.

A hardcoded shortcut could conflict with a shortcut in another app, so at the very least there should be an option to enable/disable it. If so, a new setting is needed, and the code that registers the shortcut can't be in ElectronAppWrapper. I don't know a suitable place where this code could be added.

**Comment by i-need-to-tell-you-something** [comment]
This sounds like something that should really be handled in your window manager, not in the application itself. Look into it's documentation or just Google how to achieve that for any window in what you use (Gnome/KDE/macOS/Windows10/WindowsXP/XFCE/xmonad/etc). Make sure you are hiding it rather than closing, so that the startup time will be shorter.
