### ISSUE TITLE
Error providing Joplin application icons to Linux GUI (Desktop Icon is correct, but Menu and Panel icons incorrect)

### ISSUE THREAD

**Issue by riwide** [laurent22/joplin#7542]
Installation of Joplin Icon in Linux Menu All Applications, and Panel (bottom bar of Linux screen) fails. 
In Linux Menu All Applications the icon is not visible (and probably very narrow).The application name is correct.
In Panel the icon is detectable by a slight gap between adjacent icons. If you hover mouse over that slight gap you will see the mini window for the active Joplin app.

## Environment

Joplin version: 2.9.17
Platform: Linux AMD64, 3840*2160 screen
OS specifics: Linux Mint (Cinnamon) 64 bit 21.1

## Steps to reproduce

1. Install Joplin with recommended script.
2. In Linux Menu, All Applications, Right click Joplin Name (Icon is missing - defect 1) and add to Panel.
3. Observe error behaviour (defect 2, Panel icon missing, but active narrow placeholder present.

**Comment by riwide** [comment]
Clarification of Linux version:
 Kernel: 5.15.0-56-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: Cinnamon 5.4.12
    tk: GTK 3.24.33 wm: Mutter dm: LightDM Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy

**Comment by stephan-dev** [comment]
I've had the same problem since last Joplin update 2.9. As it's an AppImage, I've read that the problem might be with the WM_Class. The WMClass is : `"joplin", "Joplin"`. It's apparently not a fix, but indeed I may have noticed a difference since last update : in the .desktop launcher, WMClass was "joplin", now it's capitalized "Joplin".
I've tried to switch back to lowercase. Didn't work.
```
Linux Mint 19.3 Cinnamon 4.4.8 (same on Ubuntu 18.04)
```

Nevertheless, workaround (alternative follows below) : 
- find the launcher `appimagekit-joplin.desktop` in `.local/share/applications`
- right click => properties. Stay in "basic" tab, click empty space on the left (where an icon should be)
- search for joplin in the local icons search that appears
- hopefully the Joplin icon is there. Hit "select". Done.

Additionally, aka "alternative" : 
- find the launcher, double-click. Click "mark as safe". This changes the name (that is displayed) to simply joplin.desktop (I noticed this is not as simple on Ubuntu, but this step is not required)
- then change the icon in the same way. (ubuntu : icon, if exists, is in `~/.local/share/icons/hicolor/512x512/apps/` (joplin.png)

I didn't have the "narrow placeholder" that you describe, so maybe the problem is different. So please tell me if the same workaround works for you.

**Comment by Daeraxa** [comment]
I think the change in 2.9 got reverted? https://github.com/laurent22/joplin/pull/7559

**Comment by stephan-dev** [comment]
I didn't know, that's good. I did check for new versions before posting, but I'm on stable. I see that the revert happened last week.
So it was was `Icon=@joplinapp-desktop` vs `Icon=joplin`. I almost deleted what I said about WM_Class, it was clearly not that. But it was the first thing I found after a web search, I thought I was on to something.
