### ISSUE TITLE
in Joplin-server, only server_name of ngnix conf that matches APP_BASE_URL is working

### ISSUE THREAD

**Issue by aspx1981** [laurent22/joplin#7606]
Hello,
I have installed and run Joplin-server and I configured and use ngnix as reverse proxy.

I have different values in server_name variable of my ngnix-joplin-server.conf
......
_server_name joplin.domain.local notes.domain.local notesync.domain.local_
.....
and the APP_BASE_URL env variable is like:
_APP_BASE_URL="${APP_BASE_URL:-https://joplin.domain.local}"_

so when I visit https://joplin.domain.local in firefox everything is ok
but when I visit https://notes.domain.local and https://notesync.domain.local
I got "_Invalid origin: http://notes.domain.local._"

if I change the _APP_BASE_URL="${APP_BASE_URL:-https://xxxxxxxx.domain.local}"_
to every other CNAME at time it works respectively.

I tried also to put 127.0.0.1 or localhost, but no luck.

everything seems ok from nginx, so I don't understand if I'm missing something in the this is a limitation of Joplin-server ? nodejs ? or ??

Thanks

**Comment by dpoulton-github** [comment]
Joplin Server only accepts requests that use the URL defined in `APP_BASE_URL`. That's why the response for the other domains is "Invalid Origin". I do not think that this is a limitation or a bug but how Joplin Server is actually designed.

**Comment by davidgolden** [comment]
Add `proxy_set_header Host $host;` to your nginx location block.

**Comment by aspx1981** [comment]
hello, sorry for late reply but still same issue:

when I visit https://joplin.domain.local/ in firefox everything is ok
but when I visit https://notes.domain.local/ and https://notesync.domain.local/
I got "Invalid origin: http://notes.domain.local."
only change the APP_BASE_URL="${APP_BASE_URL:-[https://xxxxxxxx.domain.local}](https://xxxxxxxx.domain.local}" make it work.

maybe it won't considered as a bug, but I think there's should be a solution.

**Comment by dpoulton-github** [comment]
> hello, sorry for late reply but still same issue

Yes, because Joplin Server only accepts requests that use the FQDN defined in `APP_BASE_URL`. That's why the response for the other domains is "Invalid Origin". 

> but I think there's should be a solution.

A solution to what? Unless I am missing something I can't see why you need three different FQDNs pointing at the same thing?

The Joplin Server docker container is running a single service, Joplin Server. It only needs one FQDN and using `APP_BASE_URL=https://joplin.domain.local` in the environment variables tells Joplin Server what that FQDN is. It can then use it for setting things such as published note URLs.

**Comment by amdavidson** [comment]
I am facing an issue with this not-bug as well, for a different reason.

I have the container working properly through a proxy, but I haven't been able to engineer a container healthcheck because I can only ping the service through the reverse proxy and cannot access it at `localhost`.

Is there a compelling reason that `APP_BASE_URL` only works at the exclusion of all other URLs?
