### ISSUE TITLE
App becomes unresponsive while trying to sync notes with filesystem on Android 12

### ISSUE THREAD

**Issue by piotrek-k** [laurent22/joplin#7648]
User experience of loading notes to Joplin from filesystem is currently terrible. Although it might be possible to load them (notes seem to appear slowly), app becomes unresponsive after sync starts.

I successfully used this app on an older version of Android, on lower-specs device without any problems. Number of notes I currently have in Joplin: approx: 700.

## Environment

Joplin version: 2.9.8
Platform/OS specifics: Android 12

## Steps to reproduce

1. Fresh install of application
2. Remove "getting started" notes that are added automatically after installation
3. Set up synchronization target like that: 
<img src="https://user-images.githubusercontent.com/5506878/213869309-de3e5162-a90a-4675-ba25-86e59a4c9cd5.png " height="400">
4. Start sync

My notes are not encrypted.

## What happens

* Since start of synchronization, the app is running very slowly, to the point where it is impossible to use it normally.  The app reacts to any activity after a few seconds. 
* Notes seem to appear, but at a very slow rate. 
* Yellow bar appears saying "some items cannot be synchronized. Press for more info". After pressing it, this appears:
<img src="https://user-images.githubusercontent.com/5506878/213869607-fa66b775-d0fc-4118-8b36-53933ce219ba.png " height="400">

* Cannot cancel synchronization. It is possible to press the button on menu on left side, but it does nothing: synchronization continues.

Exported debug log:
[syncReport-1674309301554.txt](https://github.com/laurent22/joplin/files/10472292/syncReport-1674309301554.txt)

**Comment by laurent22** [comment]
Please try the latest pre-release as there's a fix for this: https://github.com/laurent22/joplin-android/releases/tag/android-v2.10.5

**Comment by piotrek-k** [comment]
This solved the issue partially. Indeed, thanks to this update Joplin no longer freezes, but process of synchronization is still very slow. Moreover, import cannot be done in background which means I need to keep screen on to keep synchronisation going. Kind of strange, are 700 text notes really amount of data that would require so much processing?

**Comment by AvatarMod** [comment]
I have same issue too. After start of synchronisation UI become almost absolutely unresponsive.

@laurent22 I think, this is because Google's Scoped Storage? 
I'll test performance on Android 11 Scoped Storage with compare to direct access. 
My results for internal storage:

|Create|Open|Delete|SAF Create|SAF Open|SAF Delete|
|---|---|---|---|---|---|
|2-5ms|2-4ms|2-3ms|24-60ms|18-34ms|81-127ms|

I test with [app](http://magicbox.imejl.sk/wp-content/uploads/apps/FileOperations.apk) from [forum](https://magicbox.imejl.sk/forums/topic/storage-access-framework-performance/)

I have about 1200 encrypted .md files in Joplin directory at external storage, and SAF performance for this storage several times worse than SAF on internal storage.
