### ISSUE TITLE
Note list does not show the bottom 2 notes

### ISSUE THREAD

**Issue by alondmnt** [laurent22/joplin#7814]
## Environment

Joplin version: Joplin 2.10.6 (prod, darwin)
Platform: macOS
OS specifics: Monterey 12.6

## Steps to reproduce

1. Create a new notebook and start adding notes, or open a notebook with enough notes.

## Describe what you expected to happen

1. When adding notes, the scroll bar will appear only after 2 notes disappear from the bottom of the list.
2. When scrolling to the end of the note list, 2 notes will remain hidden.

<img width="251" alt="image" src="https://user-images.githubusercontent.com/17462125/220280816-ca4b7d7f-bc31-4417-b262-0889850730c1.png">

**Comment by tomasz1986** [comment]
Do you use any custom CSS? If yes, please check without it.

For the record, I've had this problem happen after changing the default note height.

**Comment by alondmnt** [comment]
No custom CSS, no plugins. My (wild) guess was that it has something to do with the new design of the "New note"  / "New to-do" buttons, that take up extra space.

**Comment by tomasz1986** [comment]
Good point. So, this is related to https://github.com/laurent22/joplin/pull/7780. I've just updated to the newest version and can confirm the bug.

There is a "workaround" to scroll using the `Up/Down` arrow keys on the keyboard, however if you do that, then the whole top bar with the buttons disappears and doesn't came back even if you scroll up again…

**Edit**: Unrelated to the issue at hand, but the two buttons also have a redundant `title` attribute. It's unnecessary, because it shows on hover the exact same text as already written in the buttons themselves.

**Comment by laurent22** [comment]
@julien-me, looks like your change introduced a regression. Probably the note list height is somehow hardcoded and that needs to be updated

**Comment by julien-me** [comment]
There is indeed more going on in the calculation of the height than I originally thought.

I opened https://github.com/laurent22/joplin/pull/7823 to fix it.
