### ISSUE TITLE
Flipped drawer hides options in Arabic on Android

### ISSUE THREAD

**Issue by osamz** [laurent22/joplin#7840]
When Using Android application while device language is Arabic (RTL), the drawer icon show on right, but main layout slides to right, and drawer options titles aligned to right, which hides most of them specifically if app language is Arabic! I took screenshot while app in English to make bug more clear.

System in Arabic, App in Arabic (default).
![image](https://user-images.githubusercontent.com/13044444/221353300-0e44a139-1bd0-48eb-9454-b01ce918b33a.png)

& if App in English:
![image](https://user-images.githubusercontent.com/13044444/221353306-a010b7fe-7078-43a4-9d3a-109fbf04c99a.png)

## Environment

Joplin version: 2.8.1 (Play Store).
Platform: Android
OS specifics: Android 9.0 (Samsung OneUI 1.0)

## Steps to reproduce

1. Open App
2. Touch Drawer Icon 

## Expected to happen
to be as English, when System in English:
![image](https://user-images.githubusercontent.com/13044444/221353314-8ae634ca-7cc8-4f0d-bc7b-fca1cecceb27.png)

**Comment by osamz** [comment]
Same issue was mentioned before in: https://github.com/laurent22/joplin/issues/3991#issuecomment-720390408

**Comment by osamz** [comment]
No, No one takes care about this problem... no one.

**Comment by asalthobaity** [comment]
This issue is actually a persisting UX annoyance on Android.  Although Joplin run, I can not properly or easily select the note from the notebooks list (drawer) since this drawer show just the beginning part of notebook names.  Any help from the developers community will be much appreciated!

Environment
Joplin version: 2.13.10 (F-Droid Store).
Platform: Android
OS versions: Android 14 (Samsung OneUI 6.0)

I see the issue here is more of less the closed issue (https://github.com/laurent22/joplin/issues/631) or these two open (https://github.com/laurent22/joplin/issues/3991) and (https://github.com/laurent22/joplin/issues/8999)
