### ISSUE TITLE
syncing to AWS S3

### ISSUE THREAD

**Issue by mbadros** [laurent22/joplin#7874]
I have been successfully syncing my Joplin notes to AWS S3 for a while. Beginning late last year, I noticed that my AWS bill (which I use for multiple services) had been creeping up. After a lot of research and digging, I identified significant daily outbound data transfers (5-6 GB/day) from my Joplin bucket that caused me to exceed monthly transfer limits and incur charges. Further work identified the problem as daily "ListBucket" calls that result in large transfers. The screenshot below shows a spreadsheet derived from underlying AWS billing data -- I've redacted only my customer number and a portion of the bucket name. Column I shows daily outbound data transfers on the order of 5-6 GB (my notes in total are only about 8-10GB).

![image](https://user-images.githubusercontent.com/4357482/222973588-8d89defb-ce7f-4497-90ca-a99cfd4f6a64.png)

Besides leaving AWS for another sync -- any thoughts on fixing this? Is this a bug in the Joplin sync -- the increase in monthly AWS charges possibly traceable to this began around August 2022.

Thanks

## Environment

Joplin version: 2.10.8 (and previous versions dating back to Aug 2022, when I think this started)
Platform: Linux -- syncing to AWS S3
OS specifics: Mint

## Steps to reproduce

1. syncing to AWS S3

**Comment by laurent22** [comment]
I don't think this can be fixed or that it is a new problem. I didn't implement the S3 driver, but to know what's in the bucket the app needs to list the objects in it, and that's the ListBucket call you see. Maybe you notice it more now that you have more objects in the bucket

**Comment by mbadros** [comment]
I understand the point, but I think there's still something odd going on. My total size of Joplin notes (including the content of the notes) is about 10GB -- seems strange that a "ListBucket" operation should result in the transfer of half of that just to get only the filenames and metadata. Thanks for your response.

**Comment by roman-r-m** [comment]
I believe Joplin does not always trust the file update time provided by S3 (or other sync targets for that matter), so it has to fetch the content to read update time. However usually this should only be done for a very few items, not half of all your notes. 
You may want to check that the clocks on all your machines aren't too out of sync.

**Comment by roman-r-m** [comment]
From a quick look at the S3 API it looks like it supports setting user-defined metadata when uploading files (https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html#UserMetadata) so to mitigate this Joplin could the update time in file metadata, and check it when listing.

Btw, something similar can be done for WebDAV with PROPPATCH

**Comment by mbadros** [comment]
@roman-r-m (or anyone else with an opinion) --

When syncing Joplin notes, is it best (or better) practice to have each Joplin device have its own AWS access id and access key or should all Joplin devices share the same AWS access id and key, or does this not matter? (I'm just a single user of Joplin -- but I have instances of Joplin on my multiple devices -- desktop, laptop, iPhone, iPad) ... thanks

**Comment by roman-r-m** [comment]
I am not sure, I've never used S3. Maybe @leematos knows - he wrote this code after all

**Comment by leematos** [comment]
In theory my updates only swapped out v2 api for v3. I didn’t change any sync logic except for error handling formatting. 

I’m theory you can use separate keys as long as they all have the same perms. I’m 99% I am using separate keys. (I’m using a Linode bucket tho but it should work fine on AWS)

In theory you should be able to see in the logs what your sync requests are doing and how often they are making those calls. What is your sync interval?

also, I know AWS can have some fancy bucket rules with expiry and invalidating etc etc etc. any chance your bucket has things like that which might be causing Joplin to think it needs to redownload?

—- 
I don’t know what command maps to listbucket?

https://github.com/laurent22/joplin/blob/dev/packages/lib/file-api-driver-amazon-s3.js

can you see if you can correlate in your client logs and the s3 side?

—-
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/index.html

It’s confusing because any docs for “listbucketS” is for seeing what buckets the user has access to. Our code doesn’t do that. We only try to access the bucket you define.

**Comment by leematos** [comment]
Roman actually jogged my memory. We did have to do a hack around time offset so if clocks are weird it might be a factor. 

https://github.com/laurent22/joplin/blob/d871b3c7d603b75ef4c7128d32c21b70edab5cf7/packages/lib/file-api-driver-amazon-s3.js#L211

If you wanna try commenting out that line and reporting back that could be it. 

This hack was weird because without it I can remember if it was desktop or mobile but syncs would often fail due to a request time too skewed error and it was something to do with the JS runtime context.

**Comment by leematos** [comment]
In theory the issue is fixed upstream so if we upgrade the s3 api package we should be able to remove that hack. https://github.com/aws/aws-sdk-js-v3/pull/2686

**Comment by laurent22** [comment]
> This hack was weird because without it I can remember if it was desktop or mobile but syncs would often fail due to a request time too skewed error and it was something to do with the JS runtime context.

S3 previously had an eventual consistency model, so that could be why? Now they have read-after-write consistency so perhaps this hack is no longer necessary

**Comment by leematos** [comment]
The workaround was for the connection encryption. If the clocks are too far from each other the encryption can’t work iirc.

**Comment by mbadros** [comment]
Thank you all for the thoughts and recommendations. I made some changes to the versioning settings -- ultimately removing the archival copies from AWS and aligning the Joplin settings across devices for keeping version history. 

I think the problem is resolved -- my daily usage seems to show my usage is primarily for S3 Storage and not for massive Data Transfers. The data transfer component has gone from 5-6 GB/day to usually well under .05 GB/day.
