### ISSUE TITLE
Warning when Installing 1.0.106

### ISSUE THREAD

**Issue by AmrEldib** [laurent22/joplin#788]
### Operating system
- Windows

### Application
- Desktop

When running the 1.0.106 installer, I get this warning on Windows 10 Build 17713.rs5
![image](https://user-images.githubusercontent.com/769272/45337452-f6ea1000-b53c-11e8-98f4-01b40d283045.png)

This is a routine warning for unsigned installers. However, there's a note to report warnings in the release notes: _If you get a warning or the application cannot be installed, please report on the forum on GitHub._

Side note: I understand the reason for not signing installers, but if it's at all possible, it's much better to sign them. Thanks!

**Comment by tessus** [comment]
The question here is the following. This is an open source project without remuneration, so who's going to pay for that developer account? Actually, you'd need seperate ones for macOS, Android, iOS, Windows. 

I've run into similar issues as a developer before and I sign my stuff with gpg.

**Comment by laurent22** [comment]
There's indeed a few fees like yearly Windows certificate, yearly Apple Store and certificate fees, as well as the one-off Android store fee and server fees, but thankfully donations now cover these. The above warning was due to a test as was checking what would happen if I don't sign the app, but in the end I'm going to renew the certificate to avoid these warnings.

**Comment by laurent22** [comment]
Closed as this will be fixed in the next release.
