### ISSUE TITLE
Move by dragging shows "Copy" plus icon

### ISSUE THREAD

**Issue by truthsword** [laurent22/joplin#7881]
Minor bug

When moving a note by dragging it with the mouse, the overlay icon shows the "copy" plus "+" instead of the standard "move" icon. For example...

![](https://i.imgur.com/NcHufPA.png)

## Environment

Joplin version: 
Joplin 2.9.17 (prod, win32)

Client ID: f97e5c660ed34a03b0d2e95051855674
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: a84a8e7
Platform: 
Win10x64

## Steps to reproduce

1. Select note from Notebook A
2. Drag note to Notebook B
3. Notice mouse file drag icon shows "copy"
4. Release mouse, and file is **moved" to Notebook B

## Describe what you expected to happen

Mouse file move icon should be shown (no plus)

**Comment by laurent22** [comment]
I guess you mean this icon? 

<img width="100" alt="image" src="https://user-images.githubusercontent.com/1285584/223284309-7e5199ca-766d-4d03-900f-8d5fbf9804a6.png">

**Comment by truthsword** [comment]
Generally the plus sign indicates copy, and its absence indicates move.

**Comment by palerdot** [comment]
Plus sign is shown in the cursor because, it looks like the default `effectAllowed` property during **drag start** is `copy` - https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/effectAllowed

The most idiomatic way to deal with this issue is to set `effectAllowed: move` in dragStart event. This will not show a copy icon. Please note, this will not show a drag icon either. In my `Mac`, I had a cursor like following gif
![effectAllowed-move-cursor](https://user-images.githubusercontent.com/4299398/225236200-66364ce6-125d-47bd-a97b-93bb2b10cd34.gif)

@laurent22  If we specifically want a drag icon, we have to manually add/remove classes during `dragStart` and `dragEnd` respectively, as browsers do not allow us to customize the dragging styles via css/classes. The solution would be something similar to https://stackoverflow.com/a/44486243/1410291.

**Comment by laurent22** [comment]
Whatever cursor appears when we set "effectAllowed: move" is good enough. The one you've shown is still better than the + cursor
