### ISSUE TITLE
Can close, but not open menu on mobile with swipe gesture

### ISSUE THREAD

**Issue by 1661410107114145152525** [laurent22/joplin#7918]
On the latest Joplin Android app I can not open the side menu with all my tasks with a slide gesture, though closing it with a gesture is working.

## Environment

Joplin version: 2.10.8
Platform: Android
OS specifics: Samsung Galaxy S21 Ultra, latest OS.

## Steps to reproduce

1. Try to slide from left to right, to open the menu, as it is possible in every other app (not website).
2. Fail a hundred times
3. Decide to ask here for help <3

## Describe what you expected to happen
Menu with all notes should open. If I swipe from right to left while it's open, it closes, so why are not both directions working properly?

**Comment by laurent22** [comment]
Hello, I had to revert this pull request unfortunately because it doesn't build on Android. I'm getting this error:

> Task :react-native-reanimated:buildCMakeRelWithDebInfo[arm64-v8a] FAILED
C/C++: ninja: error: '../../../../build/third-party-ndk/hermes/jni/arm64-v8a/libhermes.so',
needed by '../../../../build-main/intermediates/cxx/RelWithDebInfo/6w4f694p/obj/arm64-v8a/libreanimated.so',
missing and no known rule to make it

https://github.com/laurent22/joplin/commit/12746c5ff9b25f3992a5ee0ce7f8feac4b697c13

Is it not possible to use the built-in RN animation library instead of reanimated?

**Comment by personalizedrefrigerator** [comment]
> Is it not possible to use the built-in RN animation library instead of reanimated?

As `react-native-drawer-layout` uses [`react-native-reanimated`](https://github.com/react-navigation/react-navigation/blob/main/packages/react-native-drawer-layout/src/views/modern/Drawer.tsx#L19) directly, this doesn't seem to be the case.

Note that using a version of https://github.com/laurent22/joplin/pull/7953 [with recent changes merged](https://github.com/personalizedrefrigerator/joplin/tree/pr/unrevert-7953-drawer-layout), I am able to build both debug and release builds of Joplin for Android. (I also ran [`git clean -dXi`](https://git-scm.com/docs/git-clean/en) to remove `.gitignore`d files before building.)
