### ISSUE TITLE
"Network request failed" on iOS with WebDAV sync

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [laurent22/joplin#792]
WebDAV Synchronisation does not work on iOS11. 
Same settings are working on MacOS and Windows 10.

Error is "Network request failed"

### Operating system

- iOS

### Application

- Mobile

**Comment by laurent22** [comment]
What WebDAV server do you use? And is it possible to get a test user to try to replicate the issue?

**Comment by mariomurrent-softwaresolutions** [comment]
Yes on the iPhone I am having the same issue ... On MacOS the Software works as expected

**Comment by mariomurrent-softwaresolutions** [comment]
Any updates on this?

**Comment by laurent22** [comment]
This issue will be used to track the mysterious "Network request failed" error on iOS and to try to find a common root cause to the bug.

Other ones:

- https://github.com/laurent22/joplin/issues/397
- https://help.nextcloud.com/t/mobile-note-taking-with-your-private-cloud-announcing-joplin-nextcloud-integration/29239/43?u=laurent

If someone can provide a test user on their server and send it [here](https://raw.githubusercontent.com/laurent22/joplin/master/Assets/Adresse.png), it could help fix the issue.

**Comment by mariomurrent-softwaresolutions** [comment]
Any updates on this? I sent you the test account

**Comment by laurent22** [comment]
Should be fixed in latest version - https://github.com/laurent22/joplin/commit/4e3896c10824d8d4a55ccb19892574f4cfdaf19a

**Comment by cmsimike** [comment]
Been released to the app store?

**Comment by mariomurrent-softwaresolutions** [comment]
Not fixed in version 10.0.28 which is the latest one

**Comment by mariomurrent-softwaresolutions** [comment]
Not even fixed with 10.0.29 - sync has no errors, but no notes are displayed

**Comment by laurent22** [comment]
@mariomurrent-softwaresolutions, what is you try uninstalling and reinstalling the app?

**Comment by mariomurrent-softwaresolutions** [comment]
@laurent22 i tried it but it did not help

**Comment by cmsimike** [comment]
Worked for me though it still seemed broken at first but finally went through. Thanks!

**Comment by mariomurrent-softwaresolutions** [comment]
@laurent22 Sync does not work. There is a new Error on my iOS Device.

PUT ./resource/ Exception Forbidden - but the credentials are correct, also if I test them on the settings page.

**Comment by laurent22** [comment]
@mariomurrent-softwaresolutions , could you post a screenshot of the error log?

**Comment by mariomurrent-softwaresolutions** [comment]
![DE05D2D9-B2B8-4C3D-B7D6-6F1A03806CDD](https://user-images.githubusercontent.com/5072806/56949478-52e8bf80-6b33-11e9-930a-a7171ef96dcb.png)

**Comment by mariomurrent-softwaresolutions** [comment]
![0EE78BE5-6DF6-460A-9C15-6B2A62D5E0D2](https://user-images.githubusercontent.com/5072806/56949578-98a58800-6b33-11e9-8bb2-6c4995d2e56b.png)

**Comment by laurent22** [comment]
It seems it doesn't work on macOS either (0/3 means you have three resources but none has been uploaded) because for some reason your are not allowed to write to the .resource directory.

I don't know why it would do this, but you might want to ask on Nextcloud forum as there are more users there who might be able to help.

**Comment by mariomurrent-softwaresolutions** [comment]
Yep, my MacOS cannt sync either: Last error: Error: Got metadata for path but could not fetch content: a598137175e24427a57ac3cb0083f216.md
