### ISSUE TITLE
Changing the path to notes.

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#8018]
Hello!
I asked this question on Discourse, but it's still not there because they automatically block all newbies. And I still can't ask my questions there.
So I will ask this very important question here.

Why don't users have the option to select a drive and folder for notes?
We just can't use Joplin.

**Comment by Daeraxa** [comment]
GH issues is for bugs only. Discourse does not blanket ban and any blocked comments are flagged to the moderation team. In your case it appears the block was sustained, if you want to bring this up then you should elaborate on what the actual issue is rather than just saying "we just can't use Joplin".
