### ISSUE TITLE
Rich Text Editor: The "Stop" and "Bold text" buttons overlap with each other when toggling external editing.

### ISSUE THREAD

**Issue by Sinacs** [laurent22/joplin#8084]
![Screenshot 2023-04-26 121251](https://user-images.githubusercontent.com/110529913/234469196-f60eb963-7de8-4a9e-aeed-2212232bc56e.png)

## Environment

Joplin version: 2.9.17
Platform: Win11 Home
OS specifics: 22621.1555

## Steps to reproduce

1. Open a note
2. Switch to the rich text editor
3. Go to `Note` > `Toggle external editing`

## Describe what you expected to happen

They should not be overlapping with each other.

**Comment by ScriptInfra** [comment]
Would it be possible for an admin to add a label to this bug so that it doesn't autoclose (I think that is how they remain open till resolved?). I can concur I am seeing this issue as well on v2.11.4:

![image](https://github.com/laurent22/joplin/assets/63025323/f9b76066-b8ac-4c4f-af02-c2b11368b373)

**Comment by CaptWeiss** [comment]
This issue also exists on

Joplin version: 2.10.19
Platform: macOS Ventura 13.4

![image](https://github.com/laurent22/joplin/assets/25622676/83de047d-d3ef-4483-b0d0-5e59775f594f)
