### ISSUE TITLE
Screen drawing and UI flickers and dances about when moving the mouse (Linux, Ubuntu 22.04)

### ISSUE THREAD

**Issue by FrankRay78** [laurent22/joplin#8088]
The visual drawing of the application flickers about incorrectly when moving the mouse and generally interacting with it.  All functionality seems to be working correctly, as long as you click in the right place etc.

## Environment

Joplin version: 2.10.13
Platform: Linux
OS specifics: Ubuntu 22.04, Kernel 5.19.0-41-generic, VMWare workstation 16

![2023-04-27_11-54](https://user-images.githubusercontent.com/52075808/234841951-79ae5b06-0cbe-4b35-8527-999ee7f93b4c.png)

![2023-04-27_12-24](https://user-images.githubusercontent.com/52075808/234848099-00997260-687f-4833-a750-de2a47a014d4.png)

## Steps to reproduce

1. Open the app, the screen starts to draw incorrectly

![2023-04-27_11-51](https://user-images.githubusercontent.com/52075808/234842194-cef57fbf-ac53-4ba3-981c-21dcbd5ee723.png)

2. Move your mouse about, the redrawing is all over the place randomly

![2023-04-27_11-58](https://user-images.githubusercontent.com/52075808/234842910-f5b2de94-09fb-44a1-8738-0188c93edfbf.png)

## Describe what you expected to happen

The app to work as it did 2 days ago

## Logfile

Starting in safe mode didn't fix the issue

**Comment by JGCarroll** [comment]
I'm assuming you might be using the snap since I updated it to 2.10.13 recently and alongside updating it to the Ubuntu 22.04 graphics stack. Could you confirm this by running `snap list | grep joplin`

If so, could you try running with `joplin-desktop --disable-gpu` and seeing if the error goes away.

It'd also be worth seeing if you had the same problem with the AppImage, seeing as in theory you'd have the same drivers so could expect similar results, but if you didn't it'd be interesting.

Finally it might be worth trying the Wayland backend directly, `joplin-desktop --enable-features=WaylandWindowDecorations`, presuming you're running Wayland already; although I'm unsure if VMWare would default to this.

Fundamentally it's a difficult issue as the Ubuntu graphics stack is already highly tested and rolling back to an Ubuntu 20.04 base isn't ideal since there's big performance and stability gains generally speaking from the upgrade, but with how complex drivers/Electron is these days I'm thinking there could also be hope in resolving this if the Electron version was bumped up in a future release.

**Comment by FrankRay78** [comment]
Hello @MrCarroll, thanks for replying so quickly. Before I saw your reply, I continued to tinker around with various things last night and I ultimately fixed it by turning off HW acceleration:  

![image](https://user-images.githubusercontent.com/52075808/235129172-781cae38-0452-4814-af4c-887cb905b2b6.png)

I'm aware this was mentioned on a support page somewhere, however the reason why I didn't think it was an issue is that I have always run the VM with HW acceleration turn on.  ie. > 6 months of flawless Joplin operation.  

Something in the last two days has thrown that out of balance, ie. a background driver update, perhaps a new kernel (although I did try with a couple of different versions). I couldn't say what exactly, unfortunately.

Anyhow, it's fixed for me now.  If it would still help you to do any of the above, please let me know.
