### ISSUE TITLE
consider using .joplin or .jsync instead of .sync ?

### ISSUE THREAD

**Issue by luckman212** [laurent22/joplin#814]
Would you consider switching the name of Joplin's internal `.sync` folder to something like `.joplin` or `.jsync` instead? 

[Resilio Sync](https://www.resilio.com/individuals/) (formerly btsync) already uses .sync as it's special metadata folder name, and I think this is quite a common app. Instead of public clouds (Dropbox, Box, Google Drive etc) I prefer to use Resilio Sync to sync my Joplin data as I feel it's more secure. But I am trying to avoid potential conflicts.

**Comment by foxmask** [comment]
`.sync` folder is inside `joplin` folder - how could you have conflicts with others tools ?

**Comment by luckman212** [comment]
I think any folder named `.sync` may still be treated as a special folder by Resilio Sync. I have to confirm this.

**Comment by laurent22** [comment]
> In general though, it's nice when a tool's configuration files give some indication of who they belong to. E.g. .gitconfig vs just .config.

The root folder should indeed tell what it is (i.e. ".git") to avoid conflicts with other apps, but the folders within it don't need to have such requirements. For instance, within the .git folder there's an info, logs, hooks folders, which are pretty generic.

In Joplin it's the same, the root folder in this case is named by the user so should be unique, but within it folders and files can be named anything. Tools that deal with folders at a global level shouldn't have special rules for certain names, especially for common names like "sync" since, as it happened, other apps can use these names too.

So as far as I can tell the app is not doing anything incorrect, however the Resilio Sync tool perhaps can be customised to better deal with certain folders?
