### ISSUE TITLE
Not possible to update to 2.10.17 under WIN10

### ISSUE THREAD

**Issue by sodinoel** [laurent22/joplin#8149]
## Environment

Joplin version: 2.10.17
Platform: Windows
OS specifics: WIN10

## Steps to reproduce

1. Restart PC
2. Start installation process
3. Window 'Installation von Joplin' appears
Error message (in German): 'Joplin kann nicht geschlossen werden. Schließ es bitte manuell und klicke auf Wiederholen um fortzufahren'
4. But no Joplin process is running 

Restarted PC to prevent a hidden joplin process
taskmanager is clean, no joplin process is running
Joplin will not be autostarted!

## Describe what you expected to happen

expected correct detection of running joplin in background.

## Logfile

don't have a log file from installation process, only screenshot

**Comment by kacnje** [comment]
I'm in the same boat. Can't upgrade to 2.10.17 with "Joplin cannot be closed" message. 

Windows 10

**Comment by laurent22** [comment]
Upstream issue: https://github.com/electron-userland/electron-builder/issues/6865

**Comment by laurent22** [comment]
If you're having this issue please could you try the latest version?

https://github.com/laurent22/joplin/releases/tag/v2.10.18

**Comment by kacnje** [comment]
Tnx. 
2.10.18 works on my computer (Windows 10).

**Comment by sodinoel** [comment]
Now (2.10.18) installation process **does not consider running joplin** and gives the appearance that the process has been finished correctly. But the running joplin shows the old version, even after a restart.

Stopping joplin and restarting the update **with no running joplin** helps to finaly update joplin.

**Comment by ValiumBear** [comment]
Version 2.12.18 and I still have this issue under Windows 10. The previous installer also had this issue. Nothing helps except restarting the PC (or waiting about 5 minutes after fully killing the process). I'm surprised nobody talks about it anymore?
![H7FzvTErCT](https://github.com/laurent22/joplin/assets/56096164/e445d4ca-93b1-4049-b2d5-af699045fb73)
![yC0T3ECuYn](https://github.com/laurent22/joplin/assets/56096164/90edfd68-965d-47cc-91b8-b19fb161f3f6)

The problem is caused by NSIS installer. There's more info here: https://github.com/electron-userland/electron-builder/issues/6865
Apparently it was fixed, but not fully: https://github.com/laurent22/joplin/pull/8451#issuecomment-1631403579

Edit: Still the same as of 2.13.8.

**Comment by ValiumBear** [comment]
Bug still not resolved as of 2.14.22
![olwjl9AwfO](https://github.com/laurent22/joplin/assets/56096164/9d0b5e68-3623-4448-b1e1-91713eda7dfc)
