### ISSUE TITLE
Error message "KaTeX parse error: Expected group as argument" in preview 

### ISSUE THREAD

**Issue by beatrixwillius** [laurent22/joplin#8199]
I let ChatGPT let me write some AppleScript code for embedding into a Filemaker script. I made a note with the code but Joplin find that offensive.

Here is the beginning of the code:

```
# Step 1: Get a list of files in a folder using AppleScript
Set Variable [ $folderPath ; Value: "/path/to/folder/" ]
Set Variable [ $files ; Value: AppleScript [ 
    "tell application \"Finder\"
        set fileList to every file of folder POSIX file \"$folderPath\"
        set filePathList to {}
        repeat with fileRef in fileList
            set end of filePathList to POSIX path of fileRef
        end repeat
        filePathList
    end tell"
] ]
```

Because I'm not sure what the editor here at Github does with the code I've also added a screenshot:
<img width="795" alt="Screenshot 2023-05-17 at 10 34 35" src="https://github.com/laurent22/joplin/assets/1361928/5d52d41d-ea41-4641-8993-7eec9ec65caa">

**Comment by Daeraxa** [comment]
The `$` is making Joplin think it is Katex. 

My recommendation would put everything into a code block which will make sure there aren't any rendering errors at all (as remember this is a markdown document so code in general, particularly things with `[ ]` in it often doesn't play nice, you can see that Joplin thinks those sections are weird broken links on the editor side).

Otherwise if it is just the Katex thing you want to fix then you need to turn off the Maths expression markdown extension in your settings.

**Comment by laurent22** [comment]
Maybe you can also tweak your prompt so that ChatGPT generates text that's compatible with Markdown. Like "And wrap it in a Markdown code block"

**Comment by beatrixwillius** [comment]
@Daeraxa : thanks. After deactivating Maths  expressions everything now looks fine. I do code and not maths.
