### ISSUE TITLE
Pressing enter after an image in WYSIWYG editor causes data loss

### ISSUE THREAD

**Issue by esd-o** [laurent22/joplin#8248]
Environment
Joplin version: 2.10.19
Platform: Windows 10 home single language
OS specifics: 1909

Steps:

1. Create a note
2. Paste an image
3. press enter
4. Type something
5. Make it a header
6. Leave the note.
7. Come back to the note
8. Click to the note's right side.
9. Press enter
10. Your header is gone! or might be gone

It doesnt happen 100% of the time. Its kind of hard to recreate. BUT i have a gif as proof!

![joplinbugimage](https://github.com/laurent22/joplin/assets/77168571/a35e5f61-9555-46f8-824c-a66c09aa3ed5)

This issue is at least 2 years old. It has been present ever since ive started using joplin but never have been able to capture it on a gif... now here it is!

UPDATE ---- I HAVE FOUND A CONSISTENT SETUP!
Using this exact text on my computer i can have this deletion phenomenom occur consistently EVERY TIME i press enter after the first image ( i tried using the code thing up there at <> but that doenst work so heres an image):
![image](https://github.com/laurent22/joplin/assets/77168571/97de3bb4-d8f5-48ec-9d30-a8de2642e090)

See my new GIF for clarification!
All I did there was click after the image and press ENTER.
![joplling buggerson](https://github.com/laurent22/joplin/assets/77168571/55f6acae-11a1-48e5-93f4-209daa87f77b)

**Comment by esd-o** [comment]
bump - now with a consistent method

**Comment by esd-o** [comment]
oops i closed it mb

**Comment by djsudduth** [comment]
I was able to recreate it if I pasted html images into the editor vs a direct image. Part of the issue here is that the image pasted is an HTML fragment. It seems Joplin is trying to convert that fragment into markdown and is including the next line in the conversion thereby deleting it.

Temporary fix is to not paste HTML images - but just copy and paste only the image file (jpg or png).

Probably in this code ->/packages/renderer/htmlUtils.ts
