### ISSUE TITLE
Crash when switching profile (no plugins)

### ISSUE THREAD

**Issue by eduardobehr** [laurent22/joplin#8289]
## Environment

Client information:
```
Joplin 2.10.19 (prod, linux)

Client ID: ae0e4a15f3514dd58e2f6bec922506a1
Sync Version: 3
Profile Version: 42
Keychain Supported: No

Revision: 1100ab0
```

Platform details:
```
Operating System: Fedora Linux 37
KDE Plasma Version: 5.27.0
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.9
Kernel Version: 6.1.13-200.fc37.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 2700X Eight-Core Processor
Memory: 15,5 GiB of RAM
Graphics Processor: AMD Radeon RX 570 Series
```

## Steps to reproduce

* File -> Switch profile -> Click on any not selected
* Also happens when creating a profile (I assume it creates and then switches to it)

Unfortunately, nothing printed on stderr, nor anything suspicious on GDB.

**Comment by dpoulton-github** [comment]
I do not believe that it is a crash. On Linux Joplin has to be manually restarted after a profile switch, just like when adding or removing a plugin. However with a plugin change the user is presented with a dialog saying the app will close and asking for the app to be restarted, with the profile switch they are not. That's why you are not seeing any errors in the logs, Joplin is doing what it is told to do. It has just not been asked to let the user know what is going on.

Mentioned on the forum and a user has found a possible explanation for this behaviour in the code.

https://discourse.joplinapp.org/t/linux-profile-switch-warning/28580
