### ISSUE TITLE
Searching for user should be case insensitive

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8307]
In the admin page

**Comment by FellipeMTX** [comment]
How can I reproduce this?

**Comment by hubertfilho** [comment]
I believe that the problem is when using PostgreSQL in the production enviroment.
Maybe in the SQLite the LIKE operator is case-insentive, but in the PostgreSQL doesn't. In PostgreSQL the case-insentive operator for LIKE searches is ILIKE (as far as I remember). Well, I'll just search for the lowercase version of the string, and it should solve the problem.
