### ISSUE TITLE
Rich Text editor paste as text not working as expected

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8317]
- Copy some text that includes bold text, for example "Line with **bold** text"
- Select "Paste as text"

=> It pastes `Line with **bold** text`. But it should paste `Line with bold text`

**Comment by pedr** [comment]
From what I understand this seems to be a problem with our `onCopy` function inside the TinyMCE since the Markdown content is pasted even out of Joplin Desktop App.

 `onCopy`, at some point, calls `htmlToClipboardData` that returns a object with a object with a text and html property, but the text property is not really plain text since it tries to convert HTML to Markdown. 

I'm not really sure what we should do in this, should we try to parse the text content to remove anything that resembles markdown? Maybe we could make `htmlToClipboardData` to return another property called `markdownText` that we could check if it exists when pasting the content in the Markdown Editor before just pasting the `plain/text` content?

https://github.com/laurent22/joplin/blob/753a25a5e19f0fd460f6b55e60711e8afea2a378/packages/app-desktop/gui/NoteEditor/utils/clipboardUtils.ts#L65-L85

**Comment by laurent22** [comment]
Yes, but in this particular case, we are copying HTML then pasting HTML, so that Markdown conversion should not happen. In `htmlToClipboardData` it returns both plain text (HTML converted to Markdown) and pure HTML. And this is this pure HTML, I expect, that should be pasted in the rich text editor. So I'm wondering why it's not happening?

**Comment by pedr** [comment]
> Yes, but in this particular case, we are copying HTML then pasting HTML, so that Markdown conversion should not happen. In `htmlToClipboardData` it returns both plain text (HTML converted to Markdown) and pure HTML. And this is this pure HTML, I expect, that should be pasted in the rich text editor. So I'm wondering why it's not happening?

When you try to "Paste as text" the application gets the content from the `plain/text` instead of `plain/html`, because if we paste the HTML content when using "Paste as text" then it is going to work the same way the "Paste" functionality works, right?

I'm not sure if I understand what you mean, maybe I'm just missing your point.

**Comment by laurent22** [comment]
No you're right, I got confused as I was looking at another paste issue earlier. I think as you suggested one solution would be to strip off Markdown code when pasting, if that can be done
