### ISSUE TITLE
(Android) Can't synchronize after a profile change

### ISSUE THREAD

**Issue by gabidanpremier** [laurent22/joplin#8340]
After an app restart following a profile change, a synchronization can't complete successfully, leading to this:

> Last error: Error: MKCOL locks/: Parent node does not exist (Exception Sabre\DAV\Exception\Conflict) (409)!

After ~15 minutes without any profile change, a sync will complete successfully and quickly without any other action than waiting.

## Environment

Joplin version: 2.10.8
Platform: Android
OS specifics: 13 (Samsung)

## Steps to reproduce

1. Change profile, the app closes automatically
2. Start the app  
3. Try to Sync using the synchronize button: a sync would be expect to complete sucessfully.
4. Wait ~15 minutes
5. If not in the app, start it then use the synchronize button: a sync will complete quickly.

## Describe what you expected to happen
A sync should be allowed to complete right after a profile change.

## Logfile
![Screenshot_20230619_075042_Joplin](https://github.com/laurent22/joplin/assets/47070419/ed4cbe4e-533c-49c0-b71e-9195c80f9a71)

**Comment by dsouzadrian** [comment]
Have seen this same error for some time now on the Android app. It's sporadic. The issue somehow resolves on its own with no changes to the config whatsoever.

**Comment by 6a864c7177** [comment]
This issue is described pretty well here:  https://discourse.joplinapp.org/t/unreliable-sync-nextcloud-android-parent-node-does-not-exist/31263   (gabidanpremier is not me).

In _this_ current bug post, the encryption key error _may_ be related, but I suspect that's a separate bug.  Moreover, if you can get the sync to work, the key error may be resolved by disabling and then re-enabling encryption (and, obviously, re-entering the passphrase).  

I can reproduce the sync issue on-demand on both a Galaxy Tab S8 and Galaxy S21 Ultra (both on the latest available Samsung One UI 5.1 / Android 13 patch set), although it's the 3rd profile that consistently fails.  Subjectively (I have not counted result sets), I'd guess the 2nd profile configuration and sync fail about 80% of the time.

Unlike others, I am seeing the issue persist rather than resolve itself over time.  More accurately, **what I see is that I can't even configure the sync on the secondary (and beyond) profiles**; see attached screenshot for "WebDAV directory not found" error.  If I save the config in spite of the error, I get "parent node does not exist" (see other attached screenshot). 

To very clear, 

- the sync target at the NextCloud server _absolutely_ exists
- as noted above, for the 2nd profile configuration, the "not found" error manifests on only about 80% of attempts
- this same secondary and tertiary profile configs work on Windows, Mac, and iPadOS; this issue manifests only on Android
- this does _not_ appear to be a server-side issue

I am working around the issue with Joplin file sync and FolderSync Pro, but that brings its own challenges (not the least of which is that I'm using double-storage on my phone).

I have generated a bug report, but I don't know how to sanitize it, so I'm not attaching it here for the world to see.  With guidance, I could provide it under separate cover.

(And yes, if you browse to my server's top level, that's my hairless Sphynx; her name is Fea.  😀)

![signal-2023-07-22-083443_002](https://github.com/laurent22/joplin/assets/19285249/d65f6572-9f01-457e-903c-eebce20e45e0)

![signal-2023-07-22-090249_002](https://github.com/laurent22/joplin/assets/19285249/ed6770fa-7531-4a1c-9728-88e8cde2b087)

**Comment by goldroom** [comment]
I've got the same issue on my third profile in Joplin Android (Android 14). Although after two days of trying it hasn't successfully synced once. Working without problems with same settings on Debian Bookworm and Windows 10.

**Comment by firolino** [comment]
Got the same issue with my second profile on Android 14. No issues so far on the first profile on Arch Linux and Android.

**Comment by mikeperalta1** [comment]
+1 happening here

**Comment by changemewtf** [comment]
Also getting this issue on a Samsung Galaxy Note 20 Ultra, the same sync profile is working just fine on Windows and Linux.
