### ISSUE TITLE
Joplin 2.10.19 (prod, darwin) shortcuts not working in macOS Ventura Version 13.3.1

### ISSUE THREAD

**Issue by PacoH** [laurent22/joplin#8344]
I posted this on the forum on May 24 but never go a reply.

I upgraded from Joplin 2.10.18, in which the shortcuts were working, but they no longer work in version 2.10.19. When I type  'CMD + Shift + S' or 'CMD + Shift + B', nothing happens. 'CMD + Shift + L', or 'CMD + Shift + N' result in 'Go' menu item briefly flashing gray (this sometimes happens when trying to add 'App Shortcuts', that don't work, in 'System Settings', but I didn't add any shortcuts for Joplin). I tried quitting and reopening Joplin and rebooting the iMac but that did not work.

In the 'Go->Focus' menu, where all these shortcuts are located, 'Sidebar ⇧⌘S' is completely greyed out, in 'Note list', ⇧⌘L is greyed out, in 'Note title', ⇧⌘N is greyed out, and in 'Note body', ⇧⌘B is greyed out.

![Screenshot 2023-06-19 at 9 05 13 AM](https://github.com/laurent22/joplin/assets/6173647/f944260a-0dc9-44e8-a383-1341d9ac426d)

**Comment by personalizedrefrigerator** [comment]
Sorry for taking a while to reply!

I'm not experiencing this issue with the latest build of Joplin (2.11.11) on MacOS 13.4.1 (I'll try with Joplin 2.10.19 after this). (**Edit**: Keyboard shortcuts work for me with Joplin 2.10.19).

Try launching Joplin in safe mode (help > toggle safe mode)
![screenshot: help, launch in safe mode](https://github.com/laurent22/joplin/assets/46334387/8ce3fcc0-5fe0-4c8d-8b5c-185cef01ece2)
Among other things, safe mode disables plugins. Thus, if the issue is being caused by a plugin, enabling safe mode may fix the issue.
