### ISSUE TITLE
[Feature]: use package.json for version instead of manifest.json

### ISSUE THREAD

**Issue by danielb2** [laurent22/joplin#8374]
Having two versions is unintuitive if package.json version is honored, we can use the semantic versioning that comes with the `npm version` command, i.e `npm version minor` to easily bump when adding new features.

When I first started developing the plugin this was a source of confusion

**Comment by laurent22** [comment]
Well, I agree we could improve the tooling over this. But since the beginning I consider npmjs to be a mean of distribution and the npm package number to be irrelevant (for the Joplin applications).

What matters is the version in manifest.json, because that's what we use everywhere. We don't want to rely on anything npm-related so that we are not dependent on them for distribution. Currently someone could setup their own repository and get this working without having to use npm at all.

So we will continue to ignore the package.json version, by design, but maybe we could somehow automatically update it when running `npm run dist` or `npm publish`.

**Comment by danielb2** [comment]
At what point would it be beneficial for the version in package.json to be different from manifest.json ? And I'm curious what your thinking is for not wanting to keep it divorced from npm. yarn also uses package.json and afaik all tooling for node uses it.

Could an option be to use package.json as a fall-back if no version is defined in manifest.json ?

Since the plugin system is scraping npm packages to discover new plugins, it seems they're already married. How could someone currently set up their own repo without using npm? It seems incongruent to me and I think it's reasonable we consider going the opposite route and going all in with package.json instead

**Comment by laurent22** [comment]
As I mentioned it's done the way it's done for a reason, and no it's not married at all to npm, we could switch to a different distribution method without any issues.

What you suggest would require a lot of work, with risks of breaking existing plugins if not done properly and for very little gains.
