### ISSUE TITLE
"Insert row before" missing since 2.11.11

### ISSUE THREAD

**Issue by DeirdreYoung** [laurent22/joplin#8382]
"Insert row before" button is simply not there since 2.11.11

## Environment

Joplin version: 2.11.11
Platform: Windows
OS specifics: 10

## Steps to reproduce

1. click in a table, row of buttons appears below
2. "Insert row before" button is not there

**Comment by laurent22** [comment]
The actions have been moved to the context menu now: https://github.com/laurent22/joplin/pull/8163#issuecomment-1551561012

However it's true that I'm not seeing any "Insert row before" button. @marph91, was it just forgotten or is there any reason it's missing?

**Comment by DeirdreYoung** [comment]
I do "Insert row before" fairly frequently in my note-taking workflow - would it be possible to assign keyboard shortcuts to that and "Insert row after" ?

**Comment by marph91** [comment]
> However it's true that I'm not seeing any "Insert row before" button. @marph91, was it just forgotten or is there any reason it's missing?

I forgot to migrate this action, since I don't use it in my workflow. It should be trivial to add. I can prepare a PR in the next days. Sorry for the inconvenience.

> I do "Insert row before" fairly frequently in my note-taking workflow - would it be possible to assign keyboard shortcuts to that and "Insert row after" ?

I guess that's a separate feature request. Currently it's not possible to assign custom shortcuts for the rich text editor and I'm not aware of built-in table shortcuts either.
