### ISSUE TITLE
SVG no longer rendering

### ISSUE THREAD

**Issue by danielb2** [laurent22/joplin#8396]
it used to be that svg images were actually rendered in the layout preview and in PDF files. This no longer appears to be the case.

## Environment

    Joplin 2.11.11 (prod, darwin)

    Client ID: 59825d61142446b1992338b2a16a878a
    Sync Version: 3
    Profile Version: 43
    Keychain Supported: Yes

    Revision: 6886f6f

    platform: macos

## Steps to reproduce

1.  paste \<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 150 170">
  \<path d="M70 22V0h80v22h-6c-14 0-14 0-14 10v88c0 30-26 50-66 50S0 140 0 118c0-16 8-26 24-26 14 0 20 10 20 20v6c0 18 8 24 24 24s22-12 22-25V32c0-10 0-10-14-10z"/>
\</svg> into a note

## Describe what you expected to happen

SVG to render in the preview and in exports

**Comment by personalizedrefrigerator** [comment]
I can reproduce this on Linux.

Note that SVGs as data URIs still work:
```html
<!-- %23 is the URI-encoded  "#" -->
<img src='data:image/svg+xml;utf8,<svg viewBox="53 -.2 322 362.3" width="322" height="362.3" version="1.1" baseProfile="full" xmlns="http://www.w3.org/2000/svg">
  <path d="M375,362.1L375,-.2L53,-.2L53,362.1L375,362.1" fill="%231f1f1f"/>
  <text style="transform: matrix(1.6271, 0, 0, 1.6271, 91.425, 188.675); font-family: monospace; font-size: 32px; fill: rgb(94, 38, 94);">Testing!</text>
  <text style="transform: matrix(1.6271, 0, 0, 1.6271, 95.025, 190.875); font-family: monospace; font-size: 32px; fill: rgb(255, 255, 255);">Testing!</text>
  <path d="M356.5,180.9q-1.7-81.3 -71.2-123.4q-71.3-39.2 -142.6,0q-69.5,42.1 -71.2,123.4q1.7,81.4 71.2,123.5q71.3,39.2 142.6,0q69.5-42.1 71.2-123.4l0-.1" fill="none" stroke="%2380338066" stroke-width="37"/>
</svg>'/>
```

**Comment by taqahirom** [comment]
I am experiencing the same phenomenon here on MacOS Monterey 12.6.7. I have not tested this on Linux because I am afraid of this happening there too....

When I exported a note with above example into a HTML file, the SVG tag and its contents seemed to be totally absent in the result. On the other hand, when I removed the newlines within the example, I got this:

 `<p><path d="M70 22V0h80v22h-6c-14 0-14 0-14 10v88c0 30-26 50-66 50S0 140 0 118c0-16 8-26 24-26 14 0 20 10 20 20v6c0 18 8 24 24 24s22-12 22-25V32c0-10 0-10-14-10z" class="jop-noMdConv"></path></p>
`

So in this case only the SVG tags seem to be dropped.

**Comment by personalizedrefrigerator** [comment]
It looks like direct rendering of SVGs was disabled (perhaps temporarily) to fix a security vulnerability: https://github.com/laurent22/joplin/commit/caf66068bfc474bbfd505013076ed173cd90ca83

**Comment by taqahirom** [comment]
Thank you, this is why! It is a security issue with SVG.
Data URI worked here on MacOS. For now, this can be a workaround for me.

**Comment by TuTAH1** [comment]
Is it fixable? using img instead of svg is not variant for me, since I want to apply css to tags inside svg
