### ISSUE TITLE
Rich text editor block formatting doesn't format by block

### ISSUE THREAD

**Issue by runrunrirun** [laurent22/joplin#8435]
Block-selecting multiline text with leading or trailing spaces and formatting using the rich text editor appears to format correctly, but when the note is redisplayed (by selecting another note and then returning the first note) these lines display with embedded MD.

[https://files.catbox.moe/w52rg4.png](https://files.catbox.moe/w52rg4.png)

This is a sentence with no trailing space.
 This is a sentence with a leading space.
This a sentence with a trailing space. 
This is another sentence with no trailing space.

*This is a sentence with no trailing space.*
* This is a sentence with a leading space.*
*This a sentence with a trailing space. *
*This is another sentence with no trailing space.*

**This is a sentence with no trailing space.**
** This is a sentence with a leading space.**
**This a sentence with a trailing space. **
**This is another sentence with no trailing space.**

## Environment

Joplin version: 2.11.11
Platform: macOS 12.6.7
OS specifics: 

## Steps to reproduce

1. Paste the text block above into Joplin in the RTE. 
2. Block select the 4 lines.
3. Select formatting (Bold for example)
4. Switch to the MD editor, formatting includes leading or trailing whitespace.

## Describe what you expected to happen
All lines formatted as selected in the rich text editor. I was expecting the Rich Text Editor to behave like  

**Test with 
multiple lines in
Github editor.**

and place the MD around the entire text block, not each individual line, which is what causes the lines with leading or trailing spaces to not format correctly.

**Comment by dpoulton-github** [comment]
The below reported GitHub issues appear to refer to the trailing spaces problem. Unfortunately all have been closed by stalebot / github-actions.

https://github.com/laurent22/joplin/issues/3627, https://github.com/laurent22/joplin/issues/5238, https://github.com/laurent22/joplin/issues/5413, https://github.com/laurent22/joplin/issues/6927

**Comment by personalizedrefrigerator** [comment]
One solution here would be to use, for example, HTML `<b></b>` tags instead of markdown formatting. For example, the following HTML/markdown preserves leading space:
```html
<b style="white-space: pre-wrap;">   This is a sentence with a leading space.</b>
```

With Joplin's current markdown rendering, this also seems to allow markdown within the `<b>` tag:
```html
<b style="white-space: pre-wrap;">   This is a sentence with a *leading* space.</b>
```
The above, for example, renders as
![indented: This is a sentence with a ITALIC BEGIN leading ITALIC END space](https://github.com/laurent22/joplin/assets/46334387/d65e0e7e-e002-4732-b6ad-be9e96e0fd5f)

I dislike how much less readable this makes the markdown, however.

**Edit**: A better solution might be to move the leading spaces outside of the `**`s and replace every other space with a nonbreaking space so that the spaces are rendered. For example
```markdown
&nbsp; &nbsp; **test**
```

**Edit**: The difficulty here is that `turndown` (the library we use for HTML->Markdown conversion) seems to collapse repeated spaces and convert `&nbsp;`s into spaces.

<details><summary>Implementation details</summary>

The rich text editor currently outputs as HTML.
It looks like this is the code responsible for converting HTML bolded content to markdown is
https://github.com/laurent22/joplin/blob/d2b64f9af0b22873d450abfbfaacb7405ec1a41a/packages/turndown/src/commonmark-rules.js#L390-L401

Thus, at least in this case, the above rule could be modified to check whether a bolded item's content has leading or trailing space, and if so, use an appropriate HTML delimiter, instead of a markdown delimiter.

**Edit**: This might require changing how `turndown` handles spaces...

</details>

**Comment by runrunrirun** [comment]
Again, my issue is with the fact that the Rich Text Editor formats a block selection line by line. This may be a limitation of TinyMCE, but if the Markdown or HTML tagging is applied around the entire block then internal whitespacing around sentences is irrelevant. It seems odd to me since you have the beginning and end of the selection that you would spend extra effort to insert multiple formatting tags around each sentence instead of just surrounding the block the user told you they wanted formatted. If I go into the Markdown editor and do what I just said manually, it formats as expected.

**Comment by personalizedrefrigerator** [comment]
My guess is that this is a limitation of TinyMCE — selecting multiple lines and clicking "bold" produces one one `<strong>` tag for each line:
![screenshot: TinyMCE shows one strong tag for each line.](https://github.com/laurent22/joplin/assets/46334387/0b8fd27f-9567-43de-8031-d35fbf2474a4)
