### ISSUE TITLE
Handle relative paths in Markdown export

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#846]
https://discourse.joplin.cozic.net/t/display-images-correctly-with-markdown-export/706/7

**Comment by GIT-STATA** [comment]
Hi laurent22,

thanks so much for your great work! I really appreciate all of it!

**Right now I do not find any way for using a absolute or relative path, that is portable between Mac, Linux or Windows.** It would be great to even implement that possibility in Joplin! 

It would be great to enhance this feature that way, that you could use a relative path in the first place to write md files in Joplin as well! In editors like ATOM or SUBLIME TEXT you already can use a **relative path** for pictures or file attachments. That way you could keep your directory infrastructure as well as your 'naming conventions'. 

For example, we use 
`![Picture-Definition-Year-Month](../relative_path/Illustrations/YEAR/MONTH/some_pic.jpg)`

Many thanks again!

**Comment by forcewake** [comment]
Yep, @laurent22 thanks a lot!

Regarding the relative paths in the export. 
In the current implementation there is only one issue - find the way to determine the level of `_resources` folder, due to notebooks hierarchy
![image](https://user-images.githubusercontent.com/1325702/48781835-e351e700-eced-11e8-912c-52035f3adf32.png)
or change the way how the images (or resources in general) are stored.

Second option can break some compatibility for users which are already rely on specific folder structure.

**Comment by GIT-STATA** [comment]
@laurent22
Thanks a lot! I really appreciate all of your efforts! 

Still if I do use the **file:/// protocol** I can't use a local path 
like that one:

**` C:\Program Files\YEAR\M.01\DAY.jpg`**

A fix for [#906](https://github.com/laurent22/joplin/pull/935) was merged! 
I guess, that should solve those problems? 

Thanks again!
