### ISSUE TITLE
Clarify error message when master password cannot be found in keychain

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8493]
The message asks for a "new password" but in this case it's the current one that we need.

Ref: https://github.com/laurent22/joplin/issues/6052#issuecomment-1637150766

We should make the message clearer so that it applies to all cases, maybe just "Your master password is needed please click here to enter it..."

Related to: https://github.com/laurent22/joplin/issues/8466

**Comment by personalizedrefrigerator** [comment]
This is the error message I get after deleting the master password from the keychain app:
<img width="1116" alt="One or more master keys needs a password. Set the password." src="https://github.com/laurent22/joplin/assets/46334387/6bd30a01-5c45-4141-ae00-a6f5a39b8f15">
<img width="883" alt="Screenshot; Master password: Not set. Please click on manage master password to proceed or set the passwords in the Encryption keys list below" src="https://github.com/laurent22/joplin/assets/46334387/430c0f15-3300-4296-bc1c-304bf594e509">

It doesn't look like it's asking for a new password, but maybe it can still be improved.


@amandamcg Is this the same error message Joplin displayed after upgrading?

**Comment by amandamcg** [comment]
Yes, I am 90% sure that is the screens I saw. :-) 

I am not sure all the use cases this can appear, but if it is really a missing password issue, I'd suggest: 

Banner
`Encryption Issue: Add your Master password to decrypt all messages [Manage Settings]`

- FWIW, I would not have the action be "Set the password" since I assumed that would prompt me right there and I might mess something up. I went looking for the settings page from more info, even though it probably was a link

Settings
I am not totally sure how to word this because I don't remember the difference between master passwords and encryption keys. 
Thoughts: 
- Where I got confused was at first I didnt notice the blank "password" field in Encryption Keys. If that box was outlined in red or something I might have. The "valid" red looked like a delete.  
- I don't remember if clicking "Manage master password" would have helped me in the flow? I didn't try it, but if it would I'd recommend pointing the user there. 

Hope that helps a bit, sorry if it adds more confusion!

**Comment by personalizedrefrigerator** [comment]
#8493 was only a partial solution. I'm re-opening this issue.

What still needs to be done:
- [ ] On MacOS: Link to documentation explaining why the decryption password may be empty.
- [ ] (Possibly) Change "One or more master keys needs a password. [Set the password]" to "Some items cannot be decrypted because of a missing password. [Set the password]" or something similar.
    - This has the tradeoff of breaking translation strings, however.
