### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by zhzzy** [laurent22/joplin#8506]
I try to search the note with name `Optimal phase estimation with arbitrary a priori knowledg`(mind that I loss an e after knowledge), and I found nothing as the following image shows. 
![image](https://github.com/laurent22/joplin/assets/26019724/9bdb2dcf-64ff-4c1c-be40-b7e2a7692333)
However, when I search the key words `Optimal phase estimation with arbitrary a priori knowledge`(Mind that I have filled an e this time), I find my note now as the following image shows.
![image](https://github.com/laurent22/joplin/assets/26019724/a6f38946-67d9-41f1-a421-247e6d136a01)
I believe this is a bug for search as the first keyword should also show the corresponding note.

## Environment

Joplin 2.11.11 (prod, win32)

Sync Version: 3
Profile Version: 43
Keychain Supported: No

Revision: 6886f6f

Outline: 1.5.9

## Steps to reproduce

1.  Input a keyword but not fully filled. Then you can already see you didn't see the notes you want.

**Comment by Daeraxa** [comment]
I don't *think* this is a bug because partial word matches aren't supported on the default, you would need to use a wildcard or swap to basic search.

**Comment by dpoulton-github** [comment]
According to the help page on searching, this outcome is not actually a bug as it appears to be following the search rules.

https://joplinapp.org/help/#searching

> | Search type | Description | Example |
> | --- | --- | --- |
> | Multiple word  | Returns all the notes that contain **all** these words, but not necessarily next to each other. | `dog cat` - will return any notes that contain the words "dog" and "cat" anywhere in the note, not necessarily in that order nor next to each other. It will **not** return results that contain "dog" or "cat" only. |

So the lack of an "e" causes the search to fail as it is an **AND** search so all terms must be present. Adding the "e" (or "*") should find the note.

Alternatively, searching `any:1 Optimal phase estimation with arbitrary a priori knowledg` looks for notes containing **ANY** of the included words. As the note being searched for contains many of the words listed in the search it should be at or near the top of the results. Not that useful here as the search appears to fail because of a typo . Useful if your search contains many words but you are not sure how to spell one of them, or you are not sure if one of them is actually in the note being searched for.

> | Operator | Description | Example |
> | --- | --- | --- |
> | **any:**  | Return notes that satisfy any/all of the required conditions. `any:0` is the default, which means all conditions must be satisfied.  | `any:1 cat dog` will return notes that have the word `cat` or `dog`.</br>`any:0 cat dog` will return notes with both the words `cat` and `dog`. |
