### ISSUE TITLE
Latest terminal app requires profile version 42, desktop profile is 43.

### ISSUE THREAD

**Issue by ambrt** [laurent22/joplin#8515]
Latest terminal app is not compatible with latest desktop profile.
## Environment
Joplin version Desktop 2.11.11
Joplin version Terminal: 2.11.1 
Platform: Linux - terminal
OS specifics:  Ubunut 20.04

## Steps to reproduce
1. npm i -g joplin
2. joplin --profile ~/.config/joplin-desktop 

## Error
```Fatal error:
Error: Unknown profile version. Most likely this is an old version of Joplin, while the profile was created by a newer version. Please upgrade Joplin at https://joplinapp.org and try again.
Joplin version: 2.11.1
Profile version: 43
Expected version: 42
```
## Describe what you expected to happen
Not sure if it's in a backlog or is it an omission, but newest terminal app should be able to use newest desktop profile.

**Comment by laurent22** [comment]
Unfortunately this is working as expected since the app correctly refuses to load a profile it did not create. The fact that sharing profiles between desktop and CLI sometimes work is just by chance, it may break at any time or corrupt your data, and we don't recommend doing it.

Sharing between apps, even on the same computer, should be done via the supported sync mechanism.
