### ISSUE TITLE
Sharing an image with the app does not work

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8533]
An empty note is created but no image is attached, and it shows an error:

![image](https://github.com/laurent22/joplin/assets/1285584/f307f6e7-2fbb-4c51-8277-80ef4abfe069)

**Comment by isdnfan** [comment]
Thank you @laurent22 for creating the issue. Let me know if I can provide additional details. My phone is Pixel 6a with Android 13 and Joplin 2.9.2

from: https://discourse.joplinapp.org/t/android-share-screenshot-on-mobile-doesnt-work/31840

**Comment by ardianp** [comment]
I am using Joplin since years and I am really very happy with it.
Regarding this issue, I am facing the same problem since moths. I was hoping that after some updates it would be resolved.
For me, this bug happens only when trying to share the print screen picture with Joplin immediately after the print screen.
The problem is not happening with other apps, only with Joplin.

The app permissions are all given but sharing the print screen is not working, annoying with the above message: file does not exist. Joplin just creates a new blank note. 
If you specify the picture file from the file manager, it works well. This is so time consuming for me.

**Comment by laurent22** [comment]
Well I could replicate the issue the other day, and now I cannot for some reason. Don't know why it doesn't work, don't know why it does...

If you're still having this issue could you try this please?

- Try to share an image with the app
- Note what it does exactly (does it create a note, does it show an warning, etc.)
- In the configuration screen, scroll down to the log button, and please take a screenshot of the share-related messages (they should be at the top)

Could you also confirm if you have enabled biometrics or not?

**Comment by laurent22** [comment]
I've implemented a fix that seems to make it work on emulator, so let's see if that will work on device too

**Comment by ardianp** [comment]
Here is what happens in a short screenshot

https://github.com/laurent22/joplin/assets/605940/e320e5c8-65d5-4919-b63e-3b55cb1a7178

**Comment by ardianp** [comment]
![WhatsApp Image 2023-07-25 at 
![WhatsApp Image 2023-07-25 at 19 08 30](https://github.com/laurent22/joplin/assets/605940/ff140e54-96a3-40d4-a4f7-36515c650225)
19 07 22](https://github.com/laurent22/joplin/assets/605940/2fa8912b-263d-4671-9f5c-49a952c89480)

**Comment by ardianp** [comment]
![WhatsApp Image 2023-07-25 at 19 08 30](https://github.com/laurent22/joplin/assets/605940/40fd55fe-805d-46b9-a66c-c15f03b4a9e0)

**Comment by rhrunningrhino** [comment]
Hello,
would like to add more info so that the chance to get this bug fixed could be increased:

Device #1: Samsung Galaxy S10+
Android: Android 11 running One UI 3.1 
Joplin: 2.12.2

Device #2: Samsung Galaxy A33
Android: Android 12 running One UI 4
Joplin: 2.12.2

Joplin settings:
Resize large image: "Ask" or "Always" (but doesn't matter)

How to reproduce:
- Sharing screen capture images from Samsung Gallery App v14.1.04.2
- Share immediately from Screen capture

How to successfully share:
- Share from Whatsapp chat, open image share from WhatsApp
- Sharing photos taken by Camera, using Samsung Gallery App v14.1.04.2. Resize settings doesn't matter. Resized photo can be successfully shared.
- Sharing images on a webpage from Any browser

My Guess:
Originally i thought it is a One UI specific issue but found that there are a few bug reports. The above video is a Xiaomi device, so it should be other issue.


I checked from log, all failed attempts use content:// for filepath, while all successful attempts comes with file://

It appears to me that Joplin can take file:// smoothly but failed to handle content:// 

Hope that helps! If this bug can be fixed, I will definitely leaving Evernote!!
