### ISSUE TITLE
Joplin 2.12.7 - Display glitches

### ISSUE THREAD

**Issue by ghost** [laurent22/joplin#8535]
Windows 11 Pro 22H2

Joplin 2.12.7 : 
Right click menus for plugins have disappeared 

In **Joplin 2.12.5** (prod, win32)

![Joplin 2 12 5](https://github.com/laurent22/joplin/assets/87569999/380c1c31-42a7-4617-830f-5bc0ad320f8f)

In **Joplin 2.12.7** (prod, win32)

Client ID: 5b723f0bee17477db971add186a7fcf6
Sync Version: 3
Profile Version: 43
Keychain Supported: No
Revision: 04f8e96

![Joplin 2 12 7_a](https://github.com/laurent22/joplin/assets/87569999/0cb5fb20-b80c-4373-9f8d-fd33ee1ca4c3)

And also :
Submenus are overlapping the top menus

![Joplin 2 12 7_b](https://github.com/laurent22/joplin/assets/87569999/000c4223-37c0-46bf-9f33-af835e2e1935)

Plugins installed

Admonition markdown extension: 1.1.0
Bidirectional Links: 0.1.2
Combine notes: 1.0.1
Convert Text To New Note: 1.5.1
Cursor Sync: 2.1.0
Embed Search: 2.0.0
Enhancement: 1.2.1
Markdown Prettier: 0.1.0
Menu items, Shortcuts, Toolbar icons: 1.1.0
Note Tabs: 1.4.0
Simple Backup: 1.3.3
Victor: 1.0.0

**Comment by laurent22** [comment]
@personalizedrefrigerator, it seems to be due to the Electron upgrade. Somehow it doesn't happen when the app is packaged on macOS, but it does when running from the repo (`yarn start`) and I assume on Windows too (and maybe Linux).

The commit just before the Electron upgrade definitely works: c0fe29ec823a450b864b038062c2758b7407df1c

A few things I've noticed: in CodeMirror.tsx::pointerInsideEditor, the value of `inputFieldType` now  appears to be `plainText` but was previously `none`. But even after fixing this, the customised context menu still doesn't appear. We call `menu.popup` but it displays a default context menu anyway.

A simple way to test is to install the Rich Markdown plugin, then create a note with a checkbox and right-click on it. Normally it should display an option "Toggle checkbox" but it no longer does this.

I didn't go further than this but please take a look and see if you can fix this.

**Comment by personalizedrefrigerator** [comment]
[From the changelog, it looks like upgrading to Electron 25.3.1](https://github.com/electron/electron/releases/tag/v25.3.1) should fix the overlap issue. See also https://github.com/electron/electron/issues/38991.
