### ISSUE TITLE
External edit from Rich text editor no longer works

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8541]
Pressing Cmd+E for instance doesn't work from the Rich Text editor but does from CodeMirror

**Comment by personalizedrefrigerator** [comment]
I think this was caused by https://github.com/laurent22/joplin/commit/77482a0c956987434a4e1f7d645aeec8d51292eb.

Before that commit, the enabled condition for `toggleExternalEditing` was `oneNoteSelected`. After, it seems to be `(!modalDialogVisible || gotoAnythingVisible) && markdownEditorPaneVisible && oneNoteSelected && noteIsMarkdown && !noteIsReadOnly`, which includes `markdownEditorPaneVisible`.

See
https://github.com/laurent22/joplin/commit/77482a0c956987434a4e1f7d645aeec8d51292eb#diff-aeb755d2e6ae33ed8fb5feea87c8a56fe6243339c949422e99cf0ad4f1f2152aL25-L26
