### ISSUE TITLE
Joplin Desktop does not start on Windows 10 after update to 2.11.11

### ISSUE THREAD

**Issue by mu88** [laurent22/joplin#8542]
After upgrading Joplin Desktop from `v2.8` to `v2.11.11` on a Windows 10 device, the app crashes on startup and does not log anything into `%USERPROFILE%\.config\joplin-desktop\log.txt`.

## Environment

Joplin version: 2.11.11
Platform: Windows
OS specifics: Windows 10, Version 22H2 (Build 19045)

## Steps to reproduce

1. Install Joplin
2. Start Joplin

I can see the Joplin executable popping up in the task manager for one or two seconds and then it disappears (probably due to an app crash).

## Describe what you expected to happen

Joplin starts and the main UI becomes visible.

## Logfile

Nothing is written into the log file.

**Comment by mu88** [comment]
Dear @laurent22

Is there any workaround that I can apply? Is it worth trying to install an older release from the 2.11.x batch? Or is migrating from 2.8 to 2.11 simply a too big jump and I should better install all minor versions step by step (2.9 then 2.10 then 2.11)?

You help would be really appreciated because at the moment, I cannot use Joplin at all 😢

**Comment by personalizedrefrigerator** [comment]
Sorry for the late reply!

Here are a few things to try. Before trying any of them, please make sure you have a recent backup of your notes. If you don't, try re-installing [v2.8.8](https://github.com/laurent22/joplin/releases/tag/v2.8.8) and creating one (e.g. File > Export All > JEX).

Note that `File > Export All > JEX` does not back up note history or settings.

## 0. Uninstall/disable all plugins, then re-upgrade

It's possible that the issue is a plugin that isn't compatible with v2.11. Try downgrading to v2.8, disabling or uninstalling all plugins, then upgrading again. 

## 1. Try the portable version

First, I suggest trying to launch the portable version. [This can be found under the "Assets" dropdown for the latest GitHub release](https://github.com/laurent22/joplin/releases/tag/v2.11.11). The portable version stores profile information in the same directory as the executable, so I suggest launching the portable application from a more-trusted location than the `Downloads` folder.

This isn't a permanent solution -- the portable version can be slow to start and may have other issues.

## 2. Try first upgrading to version 2.9

As you suggested, upgrading first to version 2.9, *then* attempting to upgrade to version 2.11 could fix the issue. [The 2.9 release can be found in the list of GitHub releases](https://github.com/laurent22/joplin/releases/tag/v2.9.17).

## 3. Try uninstalling Joplin, then installing the new version

Make sure you have a backup before doing this!!! To uninstall, click start then search for "Joplin". Right-click on it and select "uninstall".

## 4. Delete/move the profile directory

Another thing that could help is renaming the profile directory (e.g. from `%USERPROFILE%\.config\joplin-desktop` to `%USERPROFILE%\.config\joplin-desktop--old`) so that Joplin can't find it. This will prevent Joplin from launching with the notes/settings used by the previous version, which could be causing the issue.

**Comment by mu88** [comment]
Thank you very much for your help! Indeed, a sequential update 2.8 → 2.9 → 2.10 → 2.11 did the trick - now it is working again 🥳
