### ISSUE TITLE
First use of Joplin Cloud's "Email to Note" feature creates a second Inbox folder

### ISSUE THREAD

**Issue by dhwalker** [laurent22/joplin#8577]
I really appreciate the "Email to Note" feature in Joplin Cloud; I just discovered it. Unfortunately, I ran into an issue. I've long had an Inbox folder and expected it to be used for the notes created from email messages, but instead a second Inbox folder was created. Could there be a check to determine if an Inbox folder already exists before creating a new one? Thanks!

## Environment"

Joplin version: 2.11.11
Platform: Linux
OS specifics: openSUSE Tumbleweed 20230724 (installed with Flatpak Flatpak 1.14.4)

## Steps to reproduce

1. Create an Inbox folder.
2. Send mail to your Joplin Cloud.
3. A second Inbox folder will be created for the emailed note.

## Describe what you expected to happen

The emailed note would be in the existing Inbox folder.

## Logfile

(The interesting log file would be from Joplin Cloud. I didn't use Joplin software to send the mail.)

**Comment by laurent22** [comment]
Unfortunately it is not possible. In particular if your data is encrypted we do not have access to it, so we can't know if you have an inbox folder or not, which is why the server creates it and manages it.

What I could suggest is to add the notes from the previous inbox notebook to the new one, and delete the old one.

Thanks for trying the feature by the way, we didn't have time to announce it or mention that it is still in beta phase! So far it appears to work well though

**Comment by dhwalker** [comment]
Thanks. I'll do that.
