### ISSUE TITLE
Weird "Empty Note" bug on Android

### ISSUE THREAD

**Issue by filwi** [laurent22/joplin#8583]
## Environment

Joplin version: 2.11.32, DB v42, FTS=1, Hermes=1
Platform: Android
OS specifics: Android 13

About a month ago, my Joplin client on my phone suddenly synched several thousand items. I'd say about 10% or so of my total number of items (not notes, but items i.e. tags etc.)

I found this annoying, but it went relatively quickly (less than an hour) so I wasn't much bothered. Then a few weeks later, I went back to look at an old (>2 years old) note, and found it empty. And going back to other old notes, I found more and more of them empty.

The note is there. The dates are correct, the tags are correct, the notebook placement is correct, but there's no content. And it's not consistent either, so there are some very old notes that have content, and others that don't. Also, there are notes with attachmnts that don't have the attachments, and notes that do.

This, of course, worried me, so I checked my notes on my computer, which is my primary platform for using Joplin. Here, all the notes are OK - everything is fine.

I haven't dared do anything with the android version of Joplin since in case I'd truly erase notes.

I've checked the android error log, but apart from a few network errors and a synch lock error, there's nothing there to indicate any problems.

Any ideas what to do? 

TIA!

**Comment by personalizedrefrigerator** [comment]
Thank you for reporting this!

Some additional information that might be helpful: What sync target are you using (e.g. Joplin Cloud, OneDrive, Dropbox, etc.)? Is encryption enabled? If you open settings and click "sync status" are there any encryption/sync errors?

**Comment by filwi** [comment]
Hi,

I'm using Dropbox as sync target. Attachment behavior is auto. No proxy. Fail safe is on. Encryption is disabled.

I've had a different weird bug, too, one where, when I share content into Joplin, then, when I next open Joplin, that same content is shared again as a new note.

Maybe it's a corruption of some kind? Thinking about wiping the Android install and reinstalling from scratch (including re-syncing everything, but it takes hours to do that - I've got over 11k notes).

**Comment by samarutuk** [comment]
It seems that this is not an isolated case. I have the same problem with the empty notes in Joplin’s Android App (2.11.32). However, the list with all the notes is there. I also use Dropbox to synchronize my data. Again, after an initial shock, all notes are on the computer and not deleted (no idea what would have happened if I had gone to edit on an "empty" note in the Android app).
**Workaround for me:** after _restarting my smartphone_, the notes were back. Maybe it is enough to clear the cache of the Joplin app on Android, I will try that as soon as it occurs again. Since this problem did not exist before the last update, a bug must have crept in somewhere.

**Comment by samarutuk** [comment]
It did not occur after restarting my smartphone (Android) (possibly clearing the cache would have done it, I could not try that). The problem seems to have magically disappeared with one of the latest updates. But I can only speak for myself, of course.
