### ISSUE TITLE
Recent logs appear to be deleted

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8598]
When I installed the version with rotating log on 16 July, it cleared the log file, which is expected. However does not seem to have moved the old one to a new file `log-xxxxxx.txt`. Or it moved it there, but deleted it soon after. It's been less than 90 days and there's no such file in the config folder.

See also here: https://github.com/laurent22/joplin/issues/8592

**Comment by hubertfilho** [comment]
The log-timestamp.txt is being delete because the function is just renaming log.txt to log-timestamp.txt, therefore the log-timestamp.txt has the birthdate of log.txt and not the birthdate since when this was renamed. I think I just need to change it to use the modification date to check if the file should be delete or not, instead of using the birth date.
