### ISSUE TITLE
Capitalization of Tag names

### ISSUE THREAD

**Issue by Jakethethird** [laurent22/joplin#864]
### Operating system

- Windows
- macOS
- Linux
- Android
- iOS

### Application

- Desktop
- Mobile
- Terminal

When I import notes from Evernote into the desktop client, the tags are imported with the original capitalisation. I can use these in Joplin e.g. SPR, Laptop, BBC. They are presented in the tag list as such, and available when I add tags to notes.

However, when I create new tags, they will not accept capitalisation e.g. type in ABC and the tag name is abc. The tag LaptopX gives laptopx etc.

In the list of tags on the left, the new tags lacking the capitalisation are presented added to the end with alphabetical ordering restarting e.g. 

- Apple
- Xylophone
- Zebra
- bbc
- candy

Is it deliberate that the new tags generated in Joplin are not capitalised and not ordered in the imported list?

A workaround might be to rename my Evernote tags e.g. BBC > bbc, Laptop > laptop.

**Comment by ksl1989** [comment]
I would say this is a bug, and relatively serious, because it is making Joplin duplicate tags. Say I was using the tag *BBC* on the notes I imported from Evernote, and as I kept using Joplin, I added the *BBC* also to new notes. Not I have two different tags on Joplin: *BBC* on the notes I imported from Evernote, and *bbc* on the notes I created in Joplin.

Either Joplin doesn't allow capitalization in tags, and, as such, needs to convert tags in Enex files to lowercase, or it does and needs to not convert tags to lowercase when adding them.

**Comment by ksl1989** [comment]
Update: I just realised this issue is more serious -- even when manually renaming the tags, they are not merged. E.g.: in my previous example, renaming *BBC* to *bbc* will create two identical *bbc* tags, not merge them.

**Comment by archont00** [comment]
I eventually renamed the tags (culture => Culture) in both locally cached database.sqlite (linux desktop app) and in md files stored on server (nextcloud). The tag names in the android app got updated fine after sync.

Since I do use a pretty stable list of tags, this "approach" is okay for me.
