### ISSUE TITLE
Error: Cannot find share associated with item 29ovR33NN94hDQ3Wt93Yad

### ISSUE THREAD

**Issue by adminapc262** [laurent22/joplin#8659]
Error: Cannot find share associated with item 29ovR33NN94hDQ3Wt93Yad

Deleted Shared Notebook
{"user_data":"","icon":"","master_key_id":"","is_shared":0,"encryption_cipher_text":"","user_updated_time":1691644238606,"user_created_time":1691644201934,"created_time":1691644201934,"title":"WAMN News"}

Sync error 

Deleted remote items: 1.
Completed: 13/08/2023 3:07 AM (30s)
Last error: Error: Cannot find share associated with item 29ovR33NN94hDQ3Wt93Yad

 Environment

Joplin version: Joplin Server -v2.12.1 
Platform: Linux
OS specifics: Windows 10 Android

Steps to reproduce

1. Create Shared NoteBook
2. Delete Shared Notebook
3. Synchronise

Describe what you expected to happen
No error

**Comment by adminapc262** [comment]
Notebook deletion issue resolved, I removed the orphaned item (jE8vMXpNBoBvREiFKaYSA3) from the database.

PostgreSQL » postgres » p19178 » public » Select: shares.

**Comment by mu88** [comment]
In my case, I had to remove an item from the `items` table:
```
psql -d myJoplinDatabase --username myJoplinUser
myJoplinDatabase=# SELECT COUNT(*) FROM items WHERE id = '<the ID>';
COUNT
----------
        1
(1 row)
myJoplinDatabase=# DELETE FROM items WHERE id = '<the ID>';
DELETE 1
```

After doing so, the sync worked again. Thx @adminapc262 for guiding me in the right direction 🤜🏻🤛🏻

**Comment by 0wn2886** [comment]
Hello in my case I had to remove on the `useritem ` table because i knew it was one of my notes which had a problem.
I had to rummage through the various tables to find the note.

``
joplindb=# SELECT * FROM user_items WHERE user_id = 'user_id' AND item_id = 'problematic item_id';
  id     |        user_id       |        item_id                   | updated_time    | created_time  
------+-----------------+--------------------------+-----------------+---------------
 9227 | user_id         | problematic item_id | 1732192951092 | 1732192951092
(1 row)

joplindb=# DELETE FROM user_items WHERE item_id = 'CGdRP08To3HE0XazdLCFzt';
DELETE 1
``

Thank you for @adminapc262 and @mu88 for the help
