### ISSUE TITLE
Apple: Upgrade from 2.12.10 arm64 results in 2.12.12 x86 

### ISSUE THREAD

**Issue by xxyxxyxyx1** [laurent22/joplin#8697]
I was using joplin 2.12.10 arm64 on an apple M1 computer. Today I was prompted to upgrade to 2.12.12. The new version that downloaded was compiled x86 instead of arm64. This results in a significant performance regression. 

I checked the releases page (https://github.com/laurent22/joplin/releases/) and I do not see any "-arm64.dmg" file in the 2.12.12 release like there is for the 2.12.10. 

I verified the program architectures were "apple" and "intel" in the Activity Monitor. 

## Environment

Joplin version: 2.12.10 and 2.12.12
Platform: macOS
OS specifics: macOS 12.6.8, arm64 M1 chip

## Steps to reproduce

1. click the "Download" button in the update popup window

## Describe what you expected to happen
I expect to continue using arm64 when upgrading from an arm64 release.

**Comment by laurent22** [comment]
We no longer release the ARM-64 version, because the old non-ARM64 apps would upgrade to it and stop working. We need to wait for some time for most apps to be upgraded so that they know which version to pick when upgrading

**Comment by xxyxxyxyx1** [comment]
> We no longer release the ARM-64 version, because the old non-ARM64 apps would upgrade to it and stop working. We need to wait for some time for most apps to be upgraded so that they know which version to pick when upgrading

Is version 2.12.12 arm64 available somewhere that I can install it manually? 

On macOS, the joplin automatic update is just a prompt to download install Joplin manually, like when it was installed for the first time: you download a dmg, mount it, and drag the .app to the /Applications folder manually. Providing the arm64 installer in some special location would not be much inconvenience. 

The performance of the x86 version is not good, especially the seconds of lag when switching notebooks and random graphical issues. I would be very nice to continue receiving bugfixes, such as the editor refreshing after sync that was repaired in 2.12.12.

**Comment by laurent22** [comment]
The latest ARM64 version is here: https://objects.joplinusercontent.com/v2.12.10/Joplin-2.12.10-arm64.dmg Once we start releasing them again, they'll get bug fixes too like the other versions

**Comment by laurent22** [comment]
To give a full picture, the problem is that when the ARM64 version is built, it adds a .dmg file to the release. Then when old apps (pre-2.12) try to update, then pick one of the .dmg, possibly a random one (probably depends in which order GitHub returns the releases), and it means they may download the ARM64 version. And if the user doesn't have an Apple M1 the app no longer starts at all.

I've been thinking about it, and the obvious solution would be to release the next 2.12 (which can update the .dmg properly) and wait x months to make sure everybody has the latest version. At this point, we can start releasing the ARM64 version again. The problem is to know how long we should wait? Maybe 3 months? But from experience some users update 6 months or even a year or two later, and then they'll still end up with a broken app.

As an alternative, I'm thinking we could release the ARM64 with a different extension. Perhaps as a ".DMG" (instead of .dmg)? But we need to check that the old code will not pick that version. Or we compress the app and release a .zip?

@personalizedrefrigerator, would you mind doing some tests to see what would work? Or if you have other suggestions let me know. It would be good to fix this properly without having to wait x months, since that wouldn't even completely solve the issue.

For info the app is built using `.github/workflows/build-macos-m1.yml`. That workflow is currently disabled on CI

**Comment by personalizedrefrigerator** [comment]
Looking at the original code, I think that using a `.DMG` extension will work.

Older versions of Joplin return the first asset from the GitHub release (as ordered by the API) where the file extension matches `dmg`:
https://github.com/laurent22/joplin/blob/c89edd7b224217f6646d8fe042d3a77c6618a180/packages/app-desktop/checkForUpdates.ts#L93-L94

The file extension is retrieved with [`@joplin/lib/path-utils:fileExtension`](https://github.com/laurent22/joplin/blob/808e175f7f4d92247b44a9d64b74a11dd38af355/packages/lib/path-utils.ts#L28) which doesn't seem to convert extensions to lowercase before returning.


I plan to verify the above in the morning!

**Edit**:
- I haven't managed to get `electron-builder` to generate MacOS artifiacts that have uppercase file extensions &mdash; even if `artifactName` is set to "${productName}-${version}-${arch}.DMG", `electron-builder` generates an artifact with a lowercase extension.
- A possible alternative is to have the ARM64 artifacts appear in the artifact list *after* the x86_64 artifacts. Artifacts are sorted alphabetically in the web GitHub release. I'm hopeful that the GitHub API also sorts these artifacts alphabetically.
    - I'm creating a [test release](https://github.com/personalizedrefrigerator/joplin/releases/tag/untagged-8f288c57a942a4d43f47) on my fork of the repository that should have artifacts named such that the x86_64 artifact is before the ARM64 artifact.
