### ISSUE TITLE
Joplin freezes due to blok code

### ISSUE THREAD

**Issue by mberend** [laurent22/joplin#8768]
## Environment

Joplin version: 2.12.15
Platform: desktop
OS specifics: windows 10 home

## Steps to reproduce

I just installed the new update for desktop. When I try to edit a page, Joplin freezes. I click on other notes, but I can't open any of them. It stays on the last opened note.

Update: This problem seems to me to come from a long note where I used Blok code, among other things. The blok code has been converted to plain text by Joplin. Some html codes in blok code have been rendered. Causes freezing.

**Comment by personalizedrefrigerator** [comment]
Version 2.12 made some changes related to saving code blocks in the rich text editor (one of the goals was to prevent block code from ending early and turning into HTML in some cases :) ).

To fix the note, launch Joplin in safe mode. This can either be done through the UI (Help > Toggle safe mode) or from the command line.

On my Windows 11 computer, this can be done with
```
C:\Users\MyUserName\AppData\Local\Programs\Joplin\Joplin.exe --safe-mode
```
from PowerShell.

NOTE: Be sure not to edit notes in the **rich text editor** while in safe mode -- switch to the markdown editor first <img alt="" width="80" src="https://github.com/laurent22/joplin/assets/46334387/c6a44e71-b72a-4e32-9c4f-46499ba6344b"/> (this issue should be fixed by #8750)! 


A copy/detailed description of the markdown that caused this issue would help us fix this issue.

**Comment by mberend** [comment]
I created a new note with 2 blok of codes. I closed Joplin and opened it again. The note no longer displays the blok codes normally. I used a checklist, as shown in the picture.

I then started Joplin in safe mode and clicked markdown editor as prompted and copied the result.

Result in safe mode screenshot added.
![Screenshot_joplin-safe-mode](https://github.com/laurent22/joplin/assets/21576414/2d7c5699-8021-4ebc-bd47-05f350f88c73)

The messed up block of codes in normal mode:
![Screenshot_joplin-blok-code](https://github.com/laurent22/joplin/assets/21576414/efa77ab5-26d6-4eb9-91db-368575c0b54e)

**Comment by personalizedrefrigerator** [comment]
I'm able to reproduce this with version 2.11.11 with the following markdown
```md
- This works
    - ```html
        <div>
              This is a test
        </div>
                
        Testing.
        ```
        
    - Test 2
        

- [ ] ```html
    <div>
        This <i>does <b>not</b></i> work.
    </div>
    ```

Tested by entering this markdown into the markdown editor, switching to the rich text editor, making a change, then switching back to the markdown editor.
```

What was the last working version of Joplin?

**Comment by mberend** [comment]
If you ask if there is a version that works well with blok code? Not as far as I know. I've had this problem in previous versions as well. But because Joplin froze, I reported this. I thought it was because of the latest update. But it was an old bug.
