### ISSUE TITLE
Add PDF viewer

### ISSUE THREAD

**Issue by chrootlogin** [laurent22/joplin#877]
It would be nice to have an included PDF viewer.

### Operating system

- macOS
- iOS

### Application

- Desktop
- Mobile

**Comment by laurent22** [comment]
Isn't it just as easy to open it in an external viewer (as it does now)?

**Comment by markwdickson** [comment]
Adding features like this is what leads down the slippery slope of bloated and broken apps like Evernote.  I personally like Joplin due to being mostly text-based with Markdown formatting without being overloaded with PDFs, Images, Sounds, Attachments, Drawings, etc.  Better to do a few things well than a lot of things poorly IMO.

**Comment by nr458h** [comment]
Probably it could be handled similar the way standard note does it:
Providing plug ins for features like that

**Comment by dereitz** [comment]
I'm in agreement on the preview of PDFs in Joplin (though I'm glad that it does allow you to open the document(.  I am coming from Evernote, and was a heavy user of this feature as I scan old magazine articles, account statements, manuals, vet papers, recipes, and many other documents and stored them in Evernote.  Of course, I could store these in Nextcloud and view them there, but it was nice having these stored in a single location and being able to search all documents.

**Comment by Stele77** [comment]
I agree that at least showing a preview of pdf docs (or docs in general) is not some fancy niche nice to have feature, but a core feature for many people. 

Most people seem to use Joplin as an EVERNOTE/ONENOTE alternative, especially as there is currently no full Evernote like FOSS App.
NOT as a bare bones markdown editor. And there are so many of those already out there.

All the current FOSS note Apps can not replace the propretiary tools that most people out there use today. For the last 5+ years, so many FOSS projects tried to build a true FOSS alternative to Evernote+MSFT, but failed (also for the lack of features that users expect and need). 

Joplin now actually HAS a chance to change that, and IMHO the major part of its support and publicity comes from that fact.

Now making the 100th bare bones markdown app wont solve anything, and will only invalidate all the work done on Jolpin when it fades into being irrelevant like dozens projects before it.

KISS is good and well, but Joplin is not trying to become an Email client or DVD Ripper. 
Feature requests like this aim on the core goals of Joplin, as a true FOSS Note Taking app.

What could be done to keep it substanible? Restructure the features into plugins like Standard Notes + Inkdrop does maybe, but i guess this already been proposed before, and Laurent would now the best way forward on this anyway himself..

**Comment by laurent22** [comment]
I would argue that Joplin is not just "bare bone" :-D but regardless this feature as you can see has 6 thumbs up while for example Google Drive has 14 and spell checking 62, so while PDF preview might be very important for some users, there are many other features that are even more important. As we have limited resources here, few developers and little time, we work in order of priority.

Rendering a preview of a PDF is easy, but the missing part in Joplin is that there's no concept of thumbnails (whether it's for image, PDF or any document), so implementing this will be relatively tricky.

**Comment by Stele77** [comment]
Thanks for your fast answer Laurent! My comment was not meant to priotize this feature over others, but to speak up against implemeting a bare bones approach, where no features above the bare minimum of a markdown editor will ever be implemented, like i understood markwdickson.

I actually think you managed a great balance, and actually listen to users, like you said with the vote count. Thats what i like about this project, opposed to many other FOSS markdown editors.

So i and i guess nearly all other users appreciate your style of leadership, centered on the users whishes, and would prefer it if a feature that i personally want is not implemented first, if a more popular feature then makes it. Thats democracy, and IMHO thats how FOSS projects should be.

Because you WILL listen and implement what is popular, so we understand and appreciate your work, no matter how fast or slow a specific feature is implemented. 
As opposed to other projects that dont listen to feedback and defend this with the KISS ideology.

So my post stemmed from my fear when i read markwdickson's post, that Joplin could loose the user-centric approach where feedback matters, not about when this or other features will get implemented.

On a side note: Every 2-3 months nearly since the start i check out the state of this project, and now it seems ready enough to migrate totally to it! Also you now got enough momentum that i have great confidence in the future of it. And i have used EVERY FOSS note taking app in the last decade there is.

Joplin is the best for me now, and i am sure it will have the chance to also be a true alternative for all those millions of "normal" users stuck on their Evernote or OneNote closed source apps! 
Which would be a major win for FOSS in general.
Will push the monthly money i send to Inkdrop+MSFT to your patreon starting next 1-2 months when i fully made the switch!
All the best!

**Comment by dereitz** [comment]
I'd love to have this feature in Joplin.  Can we please keep this issue open?

**Comment by laurent22** [comment]
I don't know if it will ever be done but it's a sensible request so let's leave it open.

**Comment by gerroon** [comment]
@ markwdickson 

>Adding features like this is what leads down the slippery slope of bloated and broken apps like Evernote. I personally like Joplin due to being mostly text-based with Markdown formatting without being overloaded with PDFs, Images, Sounds, Attachments, Drawings, etc.

which leads to fragmented note taking, and our notes are spread over many apps. I feel like Joplin can handle stuff like this no problem.

**Comment by 1983shake** [comment]
预览功能很重要，也很吸引人。有道云笔记就是可以预览PDF，也可以打开word、excel、ppt。有时只想加入一个pdf文件，并能选中就可以阅读，而不是调用第三方应用。
我试用了不少笔记应用，都没有该功能。
所以，非常希望能将该功能加入进去，这样人气应该会暴涨。请慎重考虑一下。谢谢。

**Comment by adamj-codethink** [comment]
+1

**Comment by laurent22** [comment]
PDF viewer was added in v1.5
