### ISSUE TITLE
All news are published 8 may 23

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8812]
All news items have this date - instead it should take the timestamp from the Markdown filename.

**Comment by imshivam-gupta** [comment]
@laurent22 Can u please elaborate more about which news items you are talking about

**Comment by imshivam-gupta** [comment]
After reading the code i can see that the whole code written is perfectly fine. The code looks for metadata like below



---
created: 2018-06-21T17:21:12.000+00:00
source_url: https://www.patreon.com/posts/web-clipper-now-19589638
---

if this is not found then it takes the timestamp form filename since filename timestamp is same for last 3 news article hence it shows 8 May. If you want to update you can either change the filename or add metadata like shown

![image](https://github.com/laurent22/joplin/assets/93479496/98799cd7-aaab-4678-8c24-573a125e2c58)

**Comment by imshivam-gupta** [comment]
You can tell me the dates of last 3 joplin release articles i will update them and create a pr for that
