### ISSUE TITLE
Import of Evernote 

### ISSUE THREAD

**Issue by caseyheeg** [laurent22/joplin#8843]
I am trying to import an Evernote enex file containing about 6000 notes, but the import stops when it gets to 2964.  I have run the import twice, and each time had the same problem.  

## Environment

Joplin version: 2.12.15 (prod, darwin)
Platform: Macbook Pro (macOS)
OS specifics: Ventura 13.5.1

## Steps to reproduce

1. Open Joplin
2. Click File/ Import/ ENEX - Evernote Export File (as Markdown)
3. Select .enex file of cheeg notebook that was exported from Evernote on 8/5/23.
4. Import begins, import screen says: Importing from "users/cheeg/Library/CloudStorage/OneDrive-JPL/Desktop/Evernotes Backup, 8:5:23/cheeg's notebook, 8:5:23 export, EN XML format.enex" as "enex format. Please wait...
5. Import screen shows values labeled loaded, created, updated, skipped, resourcesCreated and notesTagged, that increment as the import proceeds. When the "loaded" and "created" values get to 2964, I get the circling icon that indicates it's still working on the import, but nothing happens.  Eventually (after 10 minutes or more), I try to close Joplin, but it won't close until I do a "Force Quit" operation.  

'

## Describe what you expected to happen
I expected the import operation to continue until it said loaded: 5738, and then the import operation should end. I was able to successfully import a smaller notebook with 268 notes, and that's what happened when the import was finished.   

## Logfile

[Joplin Console after import operation hung.txt](https://github.com/laurent22/joplin/files/12580726/Joplin.Console.after.import.operation.hung.txt)

**Comment by laurent22** [comment]
I think this is fixed in 2.13 so please give it a try.

Recently Evernote has been generating invalid ENEX files that even them cannot import back. We can't do much about these since they are really broken but fortunately it's not so common.

You can see the titles of these notes in the log though if you search for "import-enex.ts" and then you can evaluate whether this particular note is important or not. If it is, you can always get it back from Evernote by copying and pasting its content into Joplin.

In any case, 2.13 handles these notes better by skipping them so that the rest of it can be imported.
