### ISSUE TITLE
HTML note gets converted to markdown with loss of features

### ISSUE THREAD

**Issue by bovergaauw** [laurent22/joplin#8879]
Problem:
HTML notes get converted to markdown which causes a loss of features, among others in tables

Steps to reproduce:
- Created a note with HTML for a table without a header row
- Switched view to formatted text view and edited the table contents
- Switched back to "source view" and noticed that the edited note had been converted to markdown with an empty header row (which looks like a markdown "feature")
- Switched back to formatted text view, which effectively showed an empty header row
- From the moment the note had been converted to markdown, could not revert to a table without a header row

Expected behavior:
A HTML should not be converted to markdown, or at least not in the event the conversion causes loss of formatting or formatting features

Platform:
Windows 7 with latest Windows 7 compatible version of Joplin
Not yet tested on Windows 10 with the latest version of Joplin (but expect the dame behavior)

**Comment by Daeraxa** [comment]
> Not yet tested on Windows 10 with the latest version of Joplin (but expect the dame behavior)

There is some additional behaviour around this:

https://github.com/laurent22/joplin/releases/tag/v2.11.11

> Improved: Configure Rich Text editor to handle the first table row as header (https://github.com/laurent22/joplin/pull/8163) (https://github.com/laurent22/joplin/issues/3535 by [@Marph](https://github.com/Marph))

The problem is that a headerless table simply isn't allowed in Markdown so outside of storing the entire thing as HTML (which is often in itself undesirable) there isn't much more than can be done.

As the conversion from the HTML generated in the rich-text editor is a pretty important part of Joplin, there isn't really a blanket way that we can, or should, provide your expected behaviour of:

> A HTML should not be converted to markdown, or at least not in the event the conversion causes loss of formatting or formatting features

Where necessary (for example with the table headers and a more recent change to prevent code blocks from within tables changing) these features *are* being added to Joplin but they need to be taken on a case-by-case basis and should ideally be discussed on the forum.

If you want to preserve a note entirely as HTML and not allow any markdown conversion at all then I have a (WIP and unpublished) [plugin](https://github.com/Daeraxa/joplin-plugin-toggle-markup) to manually set the note's markup type (see [forum topic](https://discourse.joplinapp.org/t/how-to-set-the-default-markup-language-to-html-instead-of-markdown-for-new-notes/27171/17?u=daeraxa))

**Comment by bovergaauw** [comment]
Installed @Daeraxa 's plugin v0.2 and finally found out through the forum topic how to toggle, this workaround solves my problem. It would be great if the toggle command could be accessed more easily.

**Comment by Daeraxa** [comment]
I'll see if I can do some work on that then and get it published, it needs some menus added and/or a toolbar button. The commands are exposed so it should be easy enough to bind an accelerator to it.
