### ISSUE TITLE
Spell checker right-click menu not working

### ISSUE THREAD

**Issue by nunesgh** [laurent22/joplin#8881]
The spell checker feature is enabled for two languages and it is correctly detecting misspellings for both. But since v2.12.15, the right-click menu with suggestions for fixes is not working anymore.

## Environment

Joplin version: Joplin 2.12.17 (prod, linux)
Platform: Linux 5.15.0-83-generic x86_64
OS specifics: Linux Mint 21.2 Victoria 64-bit with MATE 1.26.0

## Steps to reproduce

1. Enable the spell checker.
2. Misspell a word.
3. Right-click the word.

## Describe what you expected to happen

A context menu with suggestions for fixes should appear.

## Logfile

No error or warning related to this issue on the console log.

**Comment by laurent22** [comment]
So no context menu appears?

**Comment by nunesgh** [comment]
> So no context menu appears?

Thank you for your reply, @laurent22. Exactly! No context menu.

**Comment by CptMeetKat** [comment]
This issue appears to be introduced by https://github.com/laurent22/joplin/pull/8543

When right clicking to open the context menu, if the context menu takes longer than 100ms (0.1 seconds) to open then it simply will choose to not open the context menu ([code](https://github.com/laurent22/joplin/blob/d43482a9624b2a8a5fe4fef8bb70051f67d00497/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx#L816C2-L816C2)).

This could be triggered by a number of time related issues:
- You add to many languages to the spellchecker
- The device used is slow or the Joplin instance is running slow
- Using the spellchecker with "slower" languages
   - e.g. When using just Catalan spellcheck, I've noticed rare instances where the spellchecker processes slow enough that the context menu won't open for just the single language
   
### Environment:
Joplin 2.12.15 (dev, linux)

Client ID: 12101998bd644ad9a79b606a575e5236
Sync Version: 3
Profile Version: 43
Keychain Supported: No

Revision: 2d2633277

**Comment by laurent22** [comment]
Thanks for investigating this @CptMeetKat. @personalizedrefrigerator, do you know what fix would work for this? I guess just increasing the timeout would work, but maybe would introduce other issues

**Comment by kkyucon** [comment]
Same issue here:
- Ubuntu 20.04.6 LTS
- Joplin 2.12.18

**Comment by personalizedrefrigerator** [comment]
> Same issue here:
> 
>     * Ubuntu 20.04.6 LTS
> 
>     * Joplin 2.12.18

Thank you for bumping this! I'm working on a fix.

I think that the issue was caused by aebfa6e96d3efd29892dd20b6104bf1aa5453fd4. This commit attempts to use the HTML5 `contextmenu` in addition to Electron's `context-menu`. One event contains information about *what* was clicked (through `event.target`) the other contains information about misspelled words (and an x/y position for the event).

The commit attempts to link these two events through a timestamp (in addition to some other checks). It makes two potentially-faulty assumptions:
1. The `contextmenu` event occurs **before** the `context-menu` event
2. The events, if caused by the same user action, will occur within 100ms of one another

Because `context-menu` **does** contain the x/y position of the event (but not what actually caused the event), one possible fix is to [use `document.elementFromPoint`](https://developer.mozilla.org/en-US/docs/Web/API/Document/elementFromPoint) rather than listening for the `contextmenu` event.

I've created a patch that makes this change and am currently writing tests for it. **Edit**: [jsdom doesn't support document.elementFromPoint](https://github.com/jsdom/jsdom/issues/1435).

**Comment by kkyucon** [comment]
Seems to be happening when misspelled words are more then 11 characters.

Edit: Issue does not happen when toggle to plain text editor.

**Comment by nunesgh** [comment]
The issue seems to be solved after updating to v2.13.8, including words longer than 11 characters.

Edit:
I have just updated to v2.13.9 and no issue there either.

Thank you all for the quick fix! :)
Also thank you for the great app you have been developing!
