### ISSUE TITLE
Check enex file

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#8887]
https://github.com/laurent22/joplin/issues/8699#issuecomment-1688893084

## Environment

Joplin version: 
Platform: 
OS specifics: 

## Steps to reproduce

1. 
2. 
3.

**Comment by bgoodmansf** [comment]
There are two files in that issue. Here is the one that demonstrates the problem:
[ImportFail.zip](https://github.com/laurent22/joplin/files/12623487/ImportFail.zip)

**Comment by laurent22** [comment]
@bgoodmansf, are you able to import your ENEX files with the latest version of Joplin? Either pre-release [v2.13.1](https://github.com/laurent22/joplin/releases/tag/v2.13.1) or release [v2.12.17](https://github.com/laurent22/joplin/releases/tag/v2.12.17) (where I've backported the fix)

**Comment by bgoodmansf** [comment]
Using 2.13.1, I imported the ENEX file with the invalid CDATA attribute. Joplin displays an error dialog. The note is not imported, but Joplin does not hang. So this is OK.

FYI there is a note in import-enex.ts:preProcessFile which seems to indicate this problem with the CDATA encoding was encountered [previously](https://discourse.joplinapp.org/t/20470/4).

I tried to import a large ENEX file I have been working with. It caused Joplin to hang after importing 12760 notes. The last note imported is OK. The note that failed has 7 resources. The 7 resource files were created in the resources directory, but the note was not added to the database. Perhaps this gives a clue about where the hang occurs.

I created an ENEX with the last good imported note and the note that fails. Joplin imports both notes correctly from this file. So I don't think either of the notes is corrupted. Here are those two notes in case it is helpful: [Debug-LastFirst.zip](https://github.com/laurent22/joplin/files/12651502/Debug-LastFirst.zip)

I have been able to import all the notes from the file by splitting the ENEX file whenever a hang occurs. The hangs occurred after note counts of 12760, 4934, 2969, 2752, 4822, 3251, 4753, 3063, 6049, 2652, 28355. The fails usually occur between 2000 and 5000 notes, but the last group had 28355 notes without a fail.

If you have any steps you would like  me to take to help debug this, let me know. Unfortunately, I can't provide the file to you because it contains confidential information.

**Comment by laurent22** [comment]
Thanks for the feedback, if anything it's good to know you managed to import such a huge collection of notes!

If the example you provided can be imported fine on its own, I assume it wasn't an issue specific to these notes but the context in which they are imported. Maybe the app somehow runs out of memory (although it's normally memory efficient when importing enex files) or some strange issue that only happens when importing a large number of notes.

If somehow you managed to isolate an example that freezes the app, feel free post it here and I'll look into it.

**Comment by laurent22** [comment]
Closing for now, but feel free to post here if you manage to replicate it with a specific enex file
