### ISSUE TITLE
Sync broken in Joplin iOS app 12.12.3

### ISSUE THREAD

**Issue by luigicarrini** [laurent22/joplin#8947]
## Environment

Joplin version: 12.12.13
Platform: iOS
OS specifics: iOS 16.6.1
Synchronisation Target: WebDAV

## Steps to reproduce

1. Open Joplin app on mobile phone (iOS 16.6.1). 
2. Sync starts. 
3. Spinning wheel doesn't stop spinning, it only says "Created remote items: 1" and doesn't show report (decrypted items etc.)
4. When you press cancel, it says "Cancelling..." but nothing happens. Wheel keeps spinning. Sync lock remains. nothing is synced.
5. if I open the Joplin app (12.12.3) on my iPad (iOS 15.7.9) sync works perfectly fine, also upload of notes possible.

## Logfile

not possible to select/copy/export log text from Joplin iOS app!

**Comment by laurent22** [comment]
Could you take a screenshot of any errors or warnings?

**Comment by luigicarrini** [comment]
this is my current Joplin iOS log (last time failed sync started was 24.09.2023 at about 15:32)

![IMG_A42D412CE446-1](https://github.com/laurent22/joplin/assets/135375708/c15f96b5-e573-4220-84f5-de1e702a48a3)

![IMG_2978](https://github.com/laurent22/joplin/assets/135375708/65b0494c-bb86-4894-9efb-80b69438aaab)
![IMG_2979](https://github.com/laurent22/joplin/assets/135375708/a2644926-f87c-4718-85fc-e0dbd109698c)

**Comment by Loqova** [comment]
First of all I love Joplin and all it's features. But sync has become a pain for me recently. I also had many sync issues with Dropbox recently, mainly on the Android app, the Windows desktop app would usually sync (but it is my main app, mobile is my second use). Data wouldn't sync on Android and also I couldn't cancel a sync. It would either show an endless "syncing" or endless "cancelling" without doing anything and with the same errors as shown above, in the logs. I am using end-to-end encryption (E2EE).

Also I'm shocked by how many issues are about sync on this repo.

![image](https://github.com/laurent22/joplin/assets/91497828/87193b36-05e7-4bc2-83ed-215d15726f7d)

I didn't check all issues and the logging clearly indicates a lockfile issue. I hope this fixes it once and for all.

The problem is basically that the lock remains. I suspect due to unexpected closing of one of the apps or due to connection issues (bad wifi or other networking issues on user of dropbox side). I have both the latest Android and Windows app of Joplin. 

**Temporary solution**: _I don't recommend this to anyone without knowing what you're doing and without having a back up of your data first_: I fixed it by logging into Dropbox and directly removing the (in my case two) lock files from the Dropbox folder `/Apps/Joplin/locks`. _I also force closed the Android app and cleared its cache, but I don't think that contributed to it._ Sync starts working again after that, without a full reinstall or resync.

**Additional info**: _On Android I use max concurrent connections 20, sync interval 5 min, sync over wifi only off, no proxy, fail safe on._

I noticed something odd in the Dropbox data (or at least it's a very big coincidence). I deleted the files today (september 25).

![image](https://github.com/laurent22/joplin/assets/91497828/859051d6-c6eb-4725-abfa-88db8bc6b29b)

- Both lock files are from 24th of the month, in August and in September. It's possible that my Android App didn't work since 24 August. 
- Both are modified the 9th minute (2:09pm) and (7:09pm).
- Both JSON files included type/clientType/clientId. Type 2 and clientType 2 (like the filename prefix) but other clientIds. _I don't know if this makes sense but if the clientId represents a profile that would explain the different clientId, as I had two profiles on Android (one basically a resync when the first sync stopped working). Or they simply represent Windows and Android._

I didn't dive into code, but maybe this makes sense to people who work on the sync code of the Joplin clients.

**Proposed solutions:** 
1. Let the Windows/Android clients track the sync state locally vs remotely. Or prepare a sync by making a diff of remote and local first before actually syncing. That way the exact last succesful sync step is known when a sync failed. Check locally if a sync has fully completed, anytime the app or connection restarts (for example after a crash, dead battery, whatever): if not completed, and it detects a lock file of that client while knowing that the sync did not complete, simply delete the lock file. Or resume from the "sync plan" from the last known sync.
2. Please oh please, introduce a **"force sync" option in the GUI** of both Windows and especially the Android client. With a big fat warning for potential data loss, but let that button simply removing all lock remote files. If you're like me, you have regular backups anyway and you know when it stopped syncing. Also, you have the Fail-safe option and Conflicts folder, so you should usually be fine. Just let "Force Sync" delete the remote lock files, and that's that. This would make Joplin entirely and perfectly usable on mobile again for me.

Lastly, I like the suggestion in the question about being able to select and copy text from the log file or export the mobile log file easily. And also, I have some suspicion that aggressive battery optimization or background running task on the mobile platforms might cause this broken syncs. And Android and Windows should be totally able to be open and usable at the same time without breaking sync or locking sync on one another.

Edit: I somehow managed to get a ghost lock file again from Android and can confirm that simply force deleting the lock file from Dropbox while keeping Android app open, will successfully resume and complete the sync, seconds after deleting the lock file in Dropbox.

**Comment by luigicarrini** [comment]
Thanks for you detailed insights.
I tried the  _/Apps/Joplin/locks_ fix. Unfortunately, didn't solve the problem

**Comment by Loqova** [comment]
I don't think it's possible on iOS to clear a specific app cache. But if you have a backup, make sure the locks folder in Dropbox is empty, Joplin clients on other devices are closed entirely and then try force closing and reopening the Joplin app on iOS, or perhaps restarting your whole phone. Then give it a minute. And be sure you're on WiFi if "wifi only sync" is enabled.

**Comment by JaneX8** [comment]
For reference, emptying the locks folder worked for me. Same errors in my Android app.

![Screenshot_2023-09-25-20-28-46-53_97a2b898327add53e982bbebadc3de52.jpg](https://github.com/laurent22/joplin/assets/5116641/db592731-7e25-4313-9ae6-0f524578760a)

![Screenshot_2023-09-25-20-29-39-59_97a2b898327add53e982bbebadc3de52.jpg](https://github.com/laurent22/joplin/assets/5116641/668a7797-76dd-4d84-901d-324814a12d7a)

**Comment by luigicarrini** [comment]
Still not working

**Comment by Loqova** [comment]
Do the logfiles show anything else? When you scroll all the way down?

By the way on the Joplin Android I have a "Export Debug Report" option in settings. Sharing that might help.

**Comment by luigicarrini** [comment]
Export of the log is not possible on iOS. Finally decided to deinstall the app on my phone and reinstalled it - very tedious and takes a lot of time to resync/decrypt everything again. But now it works again.

**Comment by seanieb** [comment]
It's broken for me. I've a new iPhone, and can't export the logs. Tried uninstalling and syncing, but it just spins, syncs,fetching, decrypting, but says it's completed, so I manually hit sync again and it syncs but never creates any notes or notebooks.

**Comment by seanieb** [comment]
I disabled downloading attachments and this seemed to fix the issue. If I had to guess there's some sort of issue decrypting attachments, perhaps large attachments. My phone is an iPhone 15 pro so it shouldn't have any issues processor-wise.

**Comment by seanieb** [comment]
Actually after hours of syncing, with downloading attachments set to manual, where my notes and notebooks partially appeared and decrypted in the first 15 minutes, there's been several more hours of what seem like further progress but no notes appearing, even though the app says it's creating 2000+ local items. 

![image](https://github.com/laurent22/joplin/assets/191516/6a171951-2a5c-46d3-a15d-5a185afa952d)

![image](https://github.com/laurent22/joplin/assets/191516/ed851869-8520-4eee-8f0f-8372dfe86ab7)

![image](https://github.com/laurent22/joplin/assets/191516/779f3420-4507-4c08-bf75-d068ed1a78a8)
