### ISSUE TITLE
Windows Synchronization After Folder Change

### ISSUE THREAD

**Issue by weddi-eddy** [laurent22/joplin#903]
### Operating system

- Windows
- Android

### Application

- Desktop
- Mobile

Hello.

I'm having problems with synchronization in the Windows client (v1.0.111).  My Android Client works fine.  **Here are the steps that I did to get to this point:**

1. I installed Joplin on Windows.
2. I connected Joplin on Windows to my Nextcloud environment.
3. I created some notebooks and some notes.
4. I installed an Android client on my phone.
5. I connected Joplin on Android to my Nextcloud environment.
6. Everything was synchronizing fine.
7. I noticed that it was dumping everything to the root directory because I didn't RTFM, so I read up some more and created a Joplin folder in Nextcloud.  I manually moved all Joplin related content in Nextcloud to the Joplin folder.
8. I performed a synchronization on the Windows client and everything disappeared.
9. I changed the Nextcloud WebDAV URL to include the new Joplin folder on both Android and Windows.
10. I performed another Synchronization on both clients.  Android found the files and synchronized everything no problem.  If I make edits on Android, the changes are updated.
11. When I perform a Synchronization on Windows, it does not synchronize anything.
12. If I add a new notebook on Windows and/or a new note, they both show up in the /Joplin directory on Nextcloud and I can read them on Android.  They also appear in Windows, but the other existing content does not.

**Things I have tried:**

- I have tried to uninstall and reinstall Joplin on Windows.
- I have tried to run debug but when I perform the sync on Windows, nothing shows up in the console.
- Looking at log.txt, I do not see anything with a warning or error.  It looks normal.
- I tried to export a syncReport and there is nothing shown in the is_conflict column.

I will try this on another computer from home later, but I can't figure out why it isn't performing a synchronization on the Windows Client at work.

**Comment by MarcDriver** [comment]
Bonjour, 
C'est difficile de poser une question en anglais quand ce n'est pas votre langue maternelle et que vous n'êtes pas un as en iformatique !
Je viens d'installer JOPLIN sous Windows 10 et sous Anfroid ensuite.
J'ai exporté un certain nombre de notes depuis EVERNOTE et ça a fonctionné correctement depuis Windows :)
Cependant la synchronisation [sur DROPBOX] ne fonctionne pas et je ne retrouve rien sous ANDROID.
Le rapport de synchronisation indique 0/Total avec 0 erreurs !!!
Je ne vois même pas comment effectuer une synchronation manuelle !

**_Pouvez-vous m'aider ?_**

---------

Hello, 
It's difficult to ask a question in English when it's not your mother tongue and you're not a computer expert!
I just installed JOPLIN on Windows 10 and then on Android.
I exported a number of notes from EVERNOTE and it worked correctly from Windows:)
However, the synchronization [on DROPBOX] doesn't work and I can't find anything under ANDROID.
The synchronization ratio indicates 0/Total with 0 errors!!!!!
I don't even see how to perform manual synchronization!

_**Can you help me?**_

**Comment by laurent22** [comment]
Have a look in Apps/Joplin on your Dropbox account. Are there any .md files and a .resource folder in there? By the way, this kind of question is better suited for the forum (where you can also use your GitHub ID)

**Comment by weddi-eddy** [comment]
I actually just discovered the forums the other day after posting this.  I think the only reason my issue *may* deserve to remain here is a question on caching with the Windows Client.  Something was not happy with the change and it took me to remove everything associated with Joplin from Windows and a re installation of the Joplin client in order to get it working again.  Not sure if that could be labeled as a bug or feature request or what.

**Comment by MarcDriver** [comment]
Where is the forum ?

**Comment by MarcDriver** [comment]
@subi54 Thanks a lot ! :)

**Comment by taikedz** [comment]
I've been testing a couple of things, of which, moving the Joplin folder around, or pointing to a different folder. This affects Linux desktop app too.

## Issue

Pointing the client's sync location to another folder and syncing removes all notebooks. Pointing back to a correct Joplin sync folder does not restore the notebooks and notes.

## Steps to reproduce

1. Open Joplin desktop, set a sync location as "filesystem"
2. Create notebook, add note, sync
3. Move the sync folder to a different path, sync (simulate an automatic sync during the move operation)
4. Re-configure the desktop application to point to the new folder path, sync

Note that a similar situation could arise if the user wants to change sync type.

## Observed behaviour

In (3) the notebooks disappear

In (4) the notebooks are not brought back.

## Expected behaviour

In (3) an alert to say the location does not exist anymore, and not attempt to sync

or

In (4) the notes to be brought back

## Workaround

After (4), close the app, delete `~/.config/joplin-desktop/database.sqlite`, re-open Joplin and configure the location again (all settings have been lost) ; *then* sync.

This restores the notebooks.

## Suggestion

As in `Expected behaviour` section - either prevent syncing an empty or non-existent folder (similar to the suggestion in issue #961) ; or automatically do a full-sync if a currently-empty set of notebooks should reconcile against existing files.

Alternatively, if the above are not possible/desirable, it may be sufficient to add a "Force full-reload" button in the Settings area or in a "Troubleshooting" area -- specifically, not adding it to the general interface, as this might be a resource-intensive operation for large note repositories - which I expect is why Joplin currently does not just restore notes in the interface after being re-pointed to the correct location (no file change = no state change).

## Notes

Is this a bug? Messing around with a configuration post-setup is generally not great so perhaps not.

It remains a problem however - insomuch as, it is not unheard of to want to move a store folder from one location to another. If whilst doing so, the auto-sync kicks in while the user is re-configuring the new location, all items will be "lost."

The only remedy is then as detailed in `Workaround`. Settings are lost in this case, and you can get a duplicate `Welcome` notebook. This is not great, but hardly breaking. At least the data is still there and restored. It is not something that an average user would be expected to know to do.

I'd settle for a solution being called an `enhancement` though. Let's not quibble on semantics :-)

**Comment by MarcDriver** [comment]
Résolu pour moi / Solved for me.
Merci ! Thanks !

Marc

Le 22/09/2019 à 04:07, stale[bot] a écrit :
