### ISSUE TITLE
Can't launch in Windows 8.1

### ISSUE THREAD

**Issue by amenekowo** [laurent22/joplin#9185]
## Environment

Joplin version: 2.12.19
Platform: Windows
OS specifics: Windows 8.1 Pro, NT version 6.3.9600

## Steps to reproduce

1. Download latest (2.12.19) Joplin 
2. Install
3. Open Joplin
4. Showed error: Can't locate DiscardVirtualMemory in Joplin.exe

![Screenshot](https://github.com/laurent22/joplin/assets/91962831/fcebddbc-2da0-4f77-90bf-ff9dfac64c1c)

## Describe what you expected to happen
Program to launch

## Logfile
Will attach later

**Comment by JackGruber** [comment]
From Joplin `2.12.7` is Windows 7, 8 and 8.1 no longer supported as Electron 23 no longer supports these outdated operating systems.

[Joplin Git Changelog 2.12.7](https://github.com/laurent22/joplin/releases/tag/v2.12.7 )

[Joplin Changelog 2.12.7](https://joplinapp.org/help/about/changelog/desktop/#v2127-pre-release---2023-07-13t125531z)

[Electron will end support of Windows 7, Windows 8 and Windows 8.1 beginning in Electron 23. ](https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice)

[Microsoft support ended on January 10, 2023 for Windows 8.1](https://support.microsoft.com/en-us/windows/windows-8-1-support-ended-on-january-10-2023-3cfd4cde-f611-496a-8057-923fba401e93)

**Comment by amenekowo** [comment]
Thank you for the information! I will try v2.12.7.

**Comment by amenekowo** [comment]
Use v2.10.19, worked well :)

**Comment by jlpoolen** [comment]
Just to register the fact that there is someone here who did not buy into the you-must-always-upgrade mindset of Microsoft, I still run Windows 7 ... carefully (because I have Adobe products which I have an eternal license for).  I'll try an earlier version and hope I have some of the functionality I want.  I would have abandoned Windows altogether, but the Adobe products have been just too good.
![csrss_2024-09-30_10-05-44](https://github.com/user-attachments/assets/994bf0c1-a246-4c14-aade-ecca7cf5c381)

**Comment by jlpoolen** [comment]
I successfully downloaded from https://github.com/laurent22/joplin/releases/tag/v2.12.5 and installed same and successfully launched the application in Windows 7:
![Joplin_2024-09-30_10-28-23](https://github.com/user-attachments/assets/f3a0986f-c5ad-4fc6-bd46-a258ab71cb72)


Be aware that Joplin consumes about 1 GB of space.
Now to see if the functionality I desire, to wit: integrating graphics into my notes, works in this older version.
