### ISSUE TITLE
Mobile (iOS/Android) implement external-links/x-callback-url

### ISSUE THREAD

**Issue by fatflyingpigs** [laurent22/joplin#9204]
Making an issue for the mobile part of #5168. To my knowledge this has not yet been implemented on any mobile platform. It seems there are a number of other bug reports that mention this, without a successful fix. https://github.com/laurent22/joplin/issues?q=is%3Aissue+x-callback & https://discourse.joplinapp.org/search?q=x-callback

Implementing this feature allows for NFC tags to be used on mobile devices with Joplin.

## Environment

Joplin version: Latest (iOS 12.12.3)
Platforms:  iOS 17.0.3 and iOS 15.7.1 (and Android from what I've read, but I haven't tested).

## Steps to reproduce (iOS)
1. In app, copy the markdown link for the note. eg: `[My Test Note](:/1586e8e9da1e495eb08c7b4cdf1a6f50)`
2. Modify it to a proper external link and copy. eg: `joplin://x-callback-url/openNote?id=1586e8e9da1e495eb08c7b4cdf1a6f50`
3. Switch to a different note
4. [Optional] Close the app
5. Paste the external link into safari or other browser
6. Joplin launches, but not to the correct note

## Describe what you expected to happen
Step 6 above should launch to the correct note.
Extra: UI entry to copy the external link, similar to the markdown link in the app. Currently desktop app has this

## Logfile
No relevant entries in the logfile

#### Relevant
https://reactnative.dev/docs/linking?syntax=ios

**Comment by personalizedrefrigerator** [comment]
Still an issue.

Note: This feature has also been requested on Discord and the Joplin Forum.

**Comment by fatflyingpigs** [comment]
Still an issue.

**Comment by brandondasilva** [comment]
It would be great if this was a feature on mobile. I use the external links all the time but not being able to open to a note directly on my Android phone and iPad slows me down a lot.

**Comment by GonzRon** [comment]
hi @laurent22 and @tiberiusteng I am the developer of [NoteNFC](https://github.com/GonzRon/noteNFC), I just finished updating the app to make deep links to notes via NFC tags.  Unfortunately, I ran into this issue, if joplin is running, scanning the NFC tag launches the joplin x-callback URL and opens the correct note.  If joplin is not running, or is not in the background, the joplin app opens, but does not open the deep link to the correct joplin note.  It seems like the callback URL in the intent is lost when the app is not running, but works if the app is running even in the background.

**Comment by tiberiusteng** [comment]
@GonzRon I've reproduced the issue, will create a new PR if I figure out how to fix it.

**Comment by GonzRon** [comment]
> @GonzRon I've reproduced the issue, will create a new PR if I figure out how to fix it.
@tiberiusteng -> I suspect (but could 100% be wrong), that it has to do with the Android lifecycle management of the process, here's another issue that seemingly could also stem from the same root cause:

https://github.com/laurent22/joplin/issues/11264
and 
https://github.com/laurent22/joplin/issues/11197
> It does it without biometric lock too. When I switch the phone back on, the note is displayed for a short time then it disappear and this blank screen + header is displayed instead. It's just a massive [sic] issue though, since it's possible to go back to the note by pressing the back arrow and selecting the note again

/// The following is my pure speculation, so not verified or vetted, but maybe you are already starting to suspect similar issue?

it would appear that perhaps upon cold start, the app lifecycle management is maybe starting twice (or some such similar behavior)?  The first "startup" the data is present, but the second time (or suspected reload), the data goes missing and therefore you end up with a missing x-callback-url as is the case for this issue.  Or as is the case for the other issues, you simply just end up on a blank screen, as the inner react UI framework was unable to figure out where to go (data lost or not received).  So there must be some interaction between the android wrapper (in terms of app lifecycle management and passing state data), and the inner react framework.

**Comment by tiberiusteng** [comment]
@GonzRon I think it's a different issue. [React-Native have two different code path to handle incoming URLs when app is already open or causing app launch](https://reactnative.dev/docs/linking#handling-deep-links), and previously I only handled it when app is already open. I've created a PR handling app starting case (#11280).

**Comment by GonzRon** [comment]
@tiberiusteng I'm almost 100% you are correct and I was wrong!  Similar symptoms but different root cause.  You nailed it sir!  TY!!!!

**Comment by GonzRon** [comment]
@tiberiusteng I can confirm 3.2.1 android issue is fixed :) 👍
