### ISSUE TITLE
Indentation is lost when pasting in the RTE

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9264]
When pasting the text below in the RTE, the indentation is lost:

```plaintext
Some text with indented by a tab:
	Indented
```

```plaintext
Some text with indented by four spaces:
    Indented
```

**Comment by personalizedrefrigerator** [comment]
When I copy from GitHub with formatting, it seems to work (and code blocks are created).

When copying without formatting (e.g. using the "copy" button to the right of the code block), I can confirm that indentation is lost.

**Comment by pedr** [comment]
The difference between the behavior from when you "select everything and copy" and using the copy button is that in the first action you are also copying HTML to the clipboard. When we have HTML in the clipboard, the `plain/text` source is ignored.

It is in the "format plain text to HTML" where the bug happens.

---

One fix would be to:

Change `line.trim()` to `line.trimEnd()`

https://github.com/laurent22/joplin/blob/07ee20a0ff13fff779617beb39a79d5ba19fbc3c/packages/lib/htmlUtils.ts#L177-L205

And since HTML doesn't know spaces we would need to change espapeHTML to something like this:

```javascript
function escapeHtml(s) {
	return s
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;')
		.replace(/'/g, '&#039;')
		.replace(/ /g, '&nbsp;')
		.replace(/\t/g, '&nbsp;&nbsp;&nbsp;&nbsp;');
}
```

https://github.com/laurent22/joplin/blob/07ee20a0ff13fff779617beb39a79d5ba19fbc3c/packages/lib/string-utils.js#L213

This would fix the problem, but I'm not sure if this is the correct approach.
