### ISSUE TITLE
E2EE URL in mobile app is broken (Page Not Found)

### ISSUE THREAD

**Issue by taw00** [laurent22/joplin#9347]
### Operating system

Android

### Joplin version

2.12.3

### Current behaviour

Configuration > Encryption Config

At the time is a message: "For information about End-to-End Encryptions (E2EE) and advice ... https://joplinapp.org/e2ee/"

That URL is a broken link. On the desktop, that link will fail and kick you to https://joplinapp.org On the mobile device, it will send you to a "Page Not Found" page.

### Expected behaviour

Include the right URL in the UI, which I believe is: https://joplinapp.org/help/apps/sync/e2ee/

Or ... redirect direct https://joplinapp.org/e2ee/ to https://joplinapp.org/help/apps/sync/e2ee/

**Comment by personalizedrefrigerator** [comment]
It seems to be fixed in the prerelease (iOS v12.13.7):

![screenshot: Encryption config screen shows https://joplinapp.org/help/apps/sync/e2ee/ as help URL](https://github.com/laurent22/joplin/assets/46334387/bad8d058-7491-43b8-9582-6796c8bccd4e)

The prerelease should be released as stable in [a few weeks](https://joplinapp.org/help/about/release_cycle).
