### ISSUE TITLE
CI: Tests don't run for Renovate pull requests

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#9353]
### Current behaviour

Currently, Renovate pull requests don't seem to run tests. For example, [the `@codemirror/autocomplete` pull request](https://github.com/laurent22/joplin/actions/runs/6929153495/job/18846323525?pr=9352#step:13:23) doesn't include test output in its logs.

Here is the set of environment variables for the [`@codemirror/autocomplete` update](https://github.com/laurent22/joplin/pull/9352) pull request (MacOS):
```
GITHUB_WORKFLOW=Joplin Continuous Integration
GITHUB_EVENT_NAME=push
GITHUB_REF=refs/heads/renovate/codemirror
RUNNER_OS=macOS
GIT_TAG_NAME=
BUILD_SEQUENCIAL=1
SERVER_REPOSITORY=joplin/server
SERVER_TAG_PREFIX=server
IS_CONTINUOUS_INTEGRATION=1
IS_PULL_REQUEST=0
IS_DEV_BRANCH=0
IS_LINUX=0
IS_MACOS=1
```

Observe that `GITHUB_EVENT_NAME` is `push` and `IS_DEV_BRANCH` is `0`.

Currently, we only run tests if

https://github.com/laurent22/joplin/blob/c5e15e93f495b29b44c1b0c6eb12e9f0d5a5d7de/.github/scripts/run_ci.sh#L71

which does not seem to be the case for Renovate pull requests.

### Expected behavior

Tests should run for Renovate pull requests.

**Comment by laurent22** [comment]
Thanks for checking this, that's a good find.

I think it has something to do with the fact that we don't run CI for both pr and push events because that's the same code (that's all the cancelled checks in the list)

So in this particular case it's cancelling the pr event and processing the pull event, which won't run the tests. I think it simply means we should always run the tests because the optimization on what should run or not happens earlier in pre_job

**Comment by laurent22** [comment]
I'm on the move at the moment, would you mind checking this and if it's all good creating a pr for it?

**Comment by personalizedrefrigerator** [comment]
> I'm on the move at the moment, would you mind checking this and if it's all good creating a pr for it?

Expect a pull request soon!
