### ISSUE TITLE
Tooltip doesn't disappear

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9374]
### Operating system

Android

### Joplin version

2.13.7

### Current behaviour

- In Js-Draw, long press a toolbar button
- The tooltip shows up

=> It never disappears afterwards

**Comment by personalizedrefrigerator** [comment]
Thank you for letting me know!

This is likely because the tooltips are being shown with CSS `:hover` on devices that aren't reported as touch-only (js-draw currently [takes this approach](https://css-tricks.com/solving-sticky-hover-states-with-media-hover-hover/) to showing tooltips). (Tooltips disappear on my iOS and Android devices, but don't seem to disappear on one of my Android emulators).

Possible fix: Rather than showing/hiding them with CSS, show/hide with JavaScript.

**Comment by personalizedrefrigerator** [comment]
Should be fixed by https://github.com/personalizedrefrigerator/js-draw/commit/ca3e8d6e4bf84c1ccb6c86a8c8974d94e69c585e

**Comment by nikkuAg** [comment]
Is this issue still open? I would like to work on this.

**Comment by personalizedrefrigerator** [comment]
I plan to release a new version of `js-draw` with the fix in a day or two. (I need to do some tests on different devices to make sure I didn't break anything first).
