### ISSUE TITLE
Joplin (Android) inline code block in table breaks formatting

### ISSUE THREAD

**Issue by erichiller** [laurent22/joplin#9477]
### Operating system

Android

### Joplin version

2.13.0 (Android)

### Current behaviour

In a note (using new editor) have a table with inline code: eg

```
Some text with an `inline code block`.

x     | y
------|-----
`foo` | bar
```

![Screenshot_20231209-102017_Joplin (1)](https://github.com/laurent22/joplin/assets/5379325/9179d258-6008-43c3-8d2e-4b2dfecc280e)
![Screenshot_20231209-101953_Joplin_2](https://github.com/laurent22/joplin/assets/5379325/9e73595f-d3bf-48a9-96c9-c85356d30efd)

### Expected behaviour

Both code items to have the code styling.

**Comment by personalizedrefrigerator** [comment]
Thank you for reporting this!

<details><summary>Issue Explanation</summary>

CodeMirror 6 (the mobile and beta editor) requires decorations to be sorted in a specific order. Including a code block at the beginning of the line in a table causes decorations to be added in an incorrect order (a bug in Joplin).

This breaks Joplin's additional CodeMirror formatting. 

</details>

Note that it seems to work if there's a space before the code block. (So that's a potential workaround for now).
