### ISSUE TITLE
App should ask user to login again when sync session is gone

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#9513]
### Operating system

macOS

### Joplin version

2.13.8

### Current behaviour

Tested with Joplin Server:

- Login to Joplin Server from the app and sync
- While syncing, delete the session from the database

=> The app displays auth errors in the console, but those are not displayed in the UI, so the user may not know they need to login again.

### Expected behaviour

Display the error in the UI so that the user knows they have to login again.

Also make sure they can indeed login again, that the app doesn't get in a state where they can't login.

**Comment by pedr** [comment]
I'm not sure if I understand the bug. Does it happen in the desktop app, right?

When running the synchronization and a session expires/gets deleted the API is going to return an error, but `JoplinCloudApi` will try to get a new session after the error, receiving a valid session (since the credentials are still valid).

I made some tests and never found a way to fail.
