### ISSUE TITLE
Improving management of E2EE master keys

### ISSUE THREAD

**Issue by laurent22** [laurent22/joplin#956]
Add a "status" field that can be:

- "Compromised" - in which case it will no longer be used for encryption (but it is kept to allow decrypting any existing items)
- "Preferred" - in which case it will be used for encryption, instead of using the existing default one.

Also allow manually creating master key without having to disable/enable encryption.

**Comment by WingofaGriffin** [comment]
I would love to see the ability to "cleanup" master keys as well. I have a few leftover from having to enable and disable encryption, and it would be nice to clear up the unused ones.

**Comment by ardevd** [comment]
I would also very much prefer a cleanup option in order to remove older keys.

**Comment by rclilly** [comment]
Any progress on being able to remove old keys, or at least disable the orange prompt for a password for them?

**Comment by Zer0CoolX** [comment]
Deletion of old keys would be great.

**Comment by QuantumGhost** [comment]
Export master keys.

Since everything is encrypted with master, and master key is not fully derived from password, it would be impossible to access encrypted data if the master key is corrupted or deleted. For data safety, there should be method to export master key. (maybe in encrypted format)

https://github.com/laurent22/joplin/issues/389#issuecomment-380572593  has mentioned exporting master, but it seems this feature is not implemented yet?

**Comment by KYLN24** [comment]
+1. An "Edit" button needed.

**Comment by kowalskidev** [comment]
I would like to work on it. 
@laurent22  it would be great if you can provide a detailed specs for the implementation so I can work accordingly.

**Comment by rayrrr** [comment]
@kowalskidev @laurent22 I would very much like to contribute to implementing this as well, and have access to XCode on a Mac (as well as Linux boxes) if that would be helpful in any way.

**Comment by scrumit** [comment]
> I would like to work on it.
> @laurent22 it would be great if you can provide a detailed specs for the implementation so I can work accordingly.

We can start by building the code and write some tests.

**Comment by rayrrr** [comment]
@scrumit clear game plan. What I (and most likely @kowalskidev) could use to jumpstart the plan are some links to lines of code where the handling for E2EE keys currently occurs. Any pointers?

**Comment by scrumit** [comment]
Initially, I'm ignoring the test folders.

From a cursory look, Master key handling is dealt with in only two files: 
* MasterKey.js
* EncryptionService.js

I did a search for MasterKey and found it is handled in only three places in EncryptionService.js; where it is saved (line 60), loaded (97) or checked for validity(226).

When I say found in only three places it means that I need to look more carefully because the MasterKey is assigned to something else, like masterKey or newMasterKey and so becomes hidden from a simple search.


 
These probably need further investigation 
> masterKeysThatNeedUpgrading

in EncryptionService.js:

and 

> shared.upgradeMasterKey

in encryption-config-shared.js

**Comment by J4gQBqqR** [comment]
Even if I have old keys that does not have a password, please allow me to dismiss the Android persistent warning banner of "input password". This is so intrusive...

**Comment by J4gQBqqR** [comment]
https://discourse.joplinapp.org/t/understanding-the-encryption-feature/18758

Can we at least update the documentation to give user enough warning on the downside?
