### ISSUE TITLE
Desktop entry created in linux install script and has different path than downloaded app image

### ISSUE THREAD

**Issue by zenzora** [laurent22/joplin#957]
After running the script I needed to modify the path manually. Would recommend replacing one or the other of the below. 

https://github.com/laurent22/joplin/blob/3a9948e5281d432ac46684c95e0efa0a213cf865/Joplin_install_and_update.sh#L32

https://github.com/laurent22/joplin/blob/3a9948e5281d432ac46684c95e0efa0a213cf865/Joplin_install_and_update.sh#L56

**Comment by AmrEldib** [comment]
I run into the same issue on Fedora 29 Gnome 3.30  
The `Joplin_install_and_update.sh` script creates a desktop entry that points to the wrong file name. 
The problem is caused by [this line](https://github.com/laurent22/joplin/blob/57225a36b9e4dfe1fa9a371ab16753b4f4e8146c/Joplin_install_and_update.sh#L63) in the script which points to a file name that includes the version number while it should just include `Joplin.AppImage`

**Comment by virtadpt** [comment]
Same.  I've been editing my ~/Desktop/appimagekit-joplin.desktop file to point at the right file and version for a couple of updates now.

**Comment by laurent22** [comment]
It seems it was introduced by [this pull request](https://github.com/laurent22/joplin/pull/905). @tanrax, any idea what might be the issue?

**Comment by tanrax** [comment]
That's right, it's a bug. Like @AmrEldib say.
