### ISSUE TITLE
ICON missing

### ISSUE THREAD

**Issue by pjsgsy** [laurent22/joplin#9689]
### Operating system

Windows

### Joplin version

2.13.11

### Desktop version info

Joplin 2.13.11 (prod, win32)

Client ID: 00c9fd9435fb4ae6a79ef6b390ea069c
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: 6670f9a

Email Plugin: 1.0.0
Favorites: 1.3.0
Hotfolder: 1.1.0

### Current behaviour

This has been happening for as long as I have been a Joplin User, across my Windows 10 laptop, and my Windows 11 desktop, and for the last, say, 6 months of releases. I do download the test versions on my desktop. So, it is cross platform (windows) and been around through multiple versions and on very different hardware.

When minimised to the icon tray, the Joplin icon is empty. This makes it hard to tell if the program is loaded or not. It all works - You just have to remember you cannot see it!  Screenshot below

![image](https://github.com/laurent22/joplin/assets/439341/9f53c66d-3075-4198-ad1c-9c6990dd1d2e)

### Expected behaviour

I expect to see the Joplin icon

**Comment by dpoulton-github** [comment]
This may not be Joplin at fault.

When I used to use Windows this would happen to me on a semi-regular basis. Not just for Joplin but also for other apps and could include desktop icons as well as system tray icons. It was a problem Windows was having with the Windows Icon cache. I searched online for "clear windows icon cache" and after clearing the cache the icons reappeared until Windows broke it again. It's a while since I did this and with Win11 the exact method _may_ have changed so it is probably best to search for something current.

**Comment by pjsgsy** [comment]
Hi - I still have the issue. I researched the Windows issues and tried the fixes and it made no difference to me. The thing is, it is only Joplin that is affected, so if it were a Windows issue, I think it's more of an incompatibility with Joplin, rather than an issue that affects apps widely.
![image](https://github.com/laurent22/joplin/assets/439341/8c4ee971-d60f-4ad5-8f5e-7ed82ed7a8ad)
