### ISSUE TITLE
Multilpe profiles

### ISSUE THREAD

**Issue by rrangelo** [laurent22/joplin#9969]
### Operating system

Windows

### Joplin version

2.13.15

### Desktop version info

Joplin 2.13.15 (prod, win32)

ID del Cliente: fe4bcfae68b040b8a88293b12db33de4
Versión de la Sincronización: 3
Versión del Perfil: 44
Llavero Soportado: Sí

Revisión: 7d2c1c0

Automatic Backlinks to note: 3.0.3
Code-Clipboard: 1.0.0
Cursor Sync: 2.1.0
Favorites: 1.3.2
Inline tags: 1.2.1
Kanban: 1.0.7
LanguageTool integration: 0.1.0
Link Graph UI: 1.5.0
Markdown Prettier: 0.1.0
Markdown table calculations: 1.0.5
Markdown Table: Colorize: 1.1.4
Markdown Table: Sortable: 1.2.2
Markmap: 1.6.0
MultiMarkdown Table Tools: 1.1.0
PlantUML2: 1.11.0
Quick Links: 1.3.0
Rich Markdown: 0.13.4
Search & Replace: 2.2.0
Templates: 2.4.0

### Current behaviour

1. Create new profile
2. Restart app
3. ![image](https://github.com/laurent22/joplin/assets/68767628/1990a450-4c46-4305-92bf-4e1e22503969)

This happens only if you have 4 profiles configured.

### Expected behaviour

1. Create new profile
2. Restart app (I prefer just change profile without restart)
3. Load new profile

**Comment by laurent22** [comment]
Hello, would you mind trying with v2.14 (pre-release)? https://github.com/laurent22/joplin/releases

That version generates a crash report as described here so that might help finding out what the issue is: https://joplinapp.org/debugging

By the way, you might want to try in Safe Mode in case it's a plugin that's using too much memory
